* one

**** chapter summary 
This dissertation looks at /new ways of reading queer bodies/ and
experience within technological contexts. How do digital tools and
platforms change the way we interact with affect (associated with
queer experience and embodiment) within texts? What about the digital
allows us to create /sensational/ reading experiences? In other words,
how do media touch queerness, and how might queerness touch the
reader?

This chapter proposes a reading methodology that leverages the
critic's relationship to the text to open possibilities for
interpretation and connections to the textual material. It explores
the ways that reading practices across two different fields (digital
humanities and queer theory) intertwine, and how this creates a new
method for reading queer narratives in digital contexts.

First, queerness is established as something that can only be touched
at a distance. It is defined as a desire for touch (digital touch), a
desire that cannot be satisfied, redeemed, or recovered. This impulse
to satisfy, redeem, or recover queerness is observed in “paranoid” or
“suspicious” reading practices, which seek to answer or discover the
“hidden” meaning within text. These practices attempt to answer
questions, but do so in a way that constrains inquiry, because
paranoia only delivers the results that are /imaginable/ within
current the knowledge structures. To avoid reproducing these knowledge
structures, we must look to strategies that do not assume full
connections, like /feeling backward/ and /queer form/. We value
abstraction, which is necessary for bringing things into relation, and
opacity, which keeps the unknowable nature of queer experience and
identity somewhat in tact. We look at /Confessions of the Fox/, /These
Waves of Girls/, /Borderlands/. 

Second, we examine a similar impulse in DH---and a parallel across the
status of queerness and data, which cannot be captured in their raw
forms. The history of computing and media shows how tools were built
in ways that are not neutral, and we find DH practitioners doing work
that is critical of digital methods. Looking at the example of DH from
the position of queerness we see more clearly the necessity of
opacity, formalization, and abstraction as reading methods, and the
real danger of reproducibility and totalization, a byproduct of
paranoia. We find parallels between queer critics and feminist DHers,
who are doing something similar; we interweave Saidiya Hartman and
Lauren Klein.

Third, we propose three values for queer DH, which is: novelty (the
performative), vantages (the visual), and provisionality (the
ontological). We see these examples in /voyant-tools/, /these waves
of girls/, and /the orlando project/(?). 


** Touch: a way of reading: Rosenberg, Fischer, Munoz, Anzaldua

**** touch as the intersection between queer and digital
If digital humanists and queer theorists are going to find some common
ground, they might start with /touch/. The root of the word digital,
"digitus," comes from the Latin word for finger or toe. Within the
context of electronic media, "digital" refers to a counting system
based on ten digits. Digital computation runs on data in the form of
these numerical digits, even though computer language, at the most
rudimentary level, is based on a binary counting system, on ones and
zeroes. With present technology, the associations between touch and
the digital have expanded from numerical computation to include the
haptic connections we make with media in the form of mice, keyboards,
and touch screens. 

**** queerness and the frustration of touch: confessions
To touch something, the digits extend, the furtherest appendage still
part of the coherent body, and establish contact. Touch is related to
queerness through desire---the desire for touching---which is often
frustrated by normative expectations. For queer subjects, the desire
to touch has always been a frought experience. In /The Confessions of
the Fox/ by Jordy Rosenberg, the main character displays this troubled
relationship to touch. Based in eighteenth century London, this story
follows Jack Sheppard, a young transgender male making his way as a
wily thief through corrupt and dirty London. In the time before the
pathologization of nonnormative sexual and gender identities, Sheppard
struggles to articulate his difference, what he calls his
"/Something/," from the rest of London society: "This something that
set him apart from other coves [men]. Something that had caus'd him to
dress his own chest in taut bandages... pinching at his ribs,
throttling his every Breath to a forced shallow bird-sipping of the
air" (33). The difficulty with self-identification and categorization
extends from the main character to the narrative's genre, which
unfolds as historical fiction overlaid with contemporary
memoir. Sheppard's story is discovered in the present day by Dr. Voth,
a rueful academic, also transgender, who immediately realizes the
significance of Sheppard's manuscript for the historical record. Voth
proceeds to annotate the document with relevant references and
increasingly, his own anecdotes tangential to the narrative. In one
scene, Sheppard is having a romantic moment with his lover, Bess Khan,
a bi-racial prostitute who initiates Jack into the London underground
society of rogues, when Voth relates his own story about his former
lover from the early days of their relationship:

#+BEGIN_QUOTE
She opened her legs a bit, twitched them open, really. I caught my
breath, audibly.

"Oh my god," she said, "you're such a lesbian."

She didn't mean it cruelly. And she didn't mean that I wasn't passing
as a cis-man, either. Although, since according to her we'd fucked the
night before, she knew exactly how un-cis I was. 

She meant that she saw something about the quality of my desire: that
/I could feel her even before I touched her/ [my emphasis]. And that
this was part of what it meant to be---or to have been, before my tits
became property of the California Municipal Waste Department---a
lesbian. That a woman moving in your line of sight could have an
effect that was total, atmospheric. /That you could be hesitant,
incapable, and not particularly interested in establishing a line
between touching and seeing./ That you would indulge a dead love, dead
in the eyes of the world, and valueless. A love that choked and
burdened the mind, that might even be the very foundation of
melancholy and despair. But, oh Reader, looking at a woman you really
get a feel for the way that fire is a phenomenon of touch. And my
point is, if you have every been a lesbian, you will not even have to
touch a woman to know that. (169)
#+END_QUOTE

Here, desire is characterised not by the search for satisfaction, or
the success of establishing connection, but by the sensual fullness of
a lack. The experience of desire, of craving, wanting, needing to
touch the desired object, stimulates the imagination and amplifies
sensations that would otherwise be replaced with more "direct" modes
of contact. Demonstrating this distinction between imaginary and the
real contact, Dr. Voth's lover refers to him as a "lesbian," despite
his having already transitioned to a male gender identity. The term
fits because it signals not a gender identity but a /mode of being/
that is more concerned with the visible, which portends the potential
of connection, rather than verifiable contact. With regard to desire,
the difference hinges on the role of the imagination in activating
certain sensors and receptors that cannot be accessed in the "real,"
actualized world. Here, fancy takes on the connotations of the
fanciful; desire grows in the realm of the imagination. But this does
not mean the sensations resulting from this desire are any less
palpable and sensual; on the contrary, such a desire heightens and
indeed maximizes physical experience. This mode of desiring is what
characterizes queerness in the text: a desire for something that,
because it cannot or will not be fulfilled, amplifies the fullness of
that desire. Touch, or the lack of touch, defines a peculiarly queer
experience in the novel. 

Queerness is concerned with contact and desire, and more precisely
with /the desire for contact/. A desire that opposes or offends
expectations, queerness manifests as an affective relation between the
subject and desired object. Kadji Amin defines queer as "fundamentally
affective... a matter of sensing a resonance between one's object of
study and the inchoate cluster of feelings that inhabit and animate
the term queer" (173).

 It is to the side of the acceptable, breaking the
confines of the normative. Both queer and digital are out there, our
frames for engaging with the outside world. Both queer and digital are
alternative ways of engaging with the environment

**** touch severs, divides subj/obj: waves
This leads us to the main problem with touch: it goes both ways. What
I touch also touches me; one body impressed by or in collision with
another. Eve Kosofsjy Sedgwick explains that "the sense of touch makes
nonsense out of any dualistic understanding of agency and passivity;
to touch is always already to reach out, to fondle, to heft, to tap,
or to enfold" (13). Touch engages a range of relations where power is
not always reduced to opposition. The sensation of touch often
obscures this dual effect. Some bodies appear to desire touching
rather than being touched; sometimes, the desire for touch does not
seek contact, but the fullness of desiring.  it is bidirectional,
reveals a subject/object divide.


Another text, wildly different in form, carries a similar message
about frustrated desire constituting queerness.... 
.

**** Touch reconciles -- anzaldua, sedgwick, munoz
Touch reconciles the inherent connection between bodies, something
that heteronormativity tries to suppress. For things to not touch, to
be severed or "objectified," moves them into a relation of
violence. Gloria Anzaldua explains that separation is brutal: "In
trying to become 'objective,' Western culture made 'objects' of things
and people when it distanced itself from them, thereby losing 'touch'
with them. This dichotomy is the root of all violence" (37). Losing
touch is a prerequisite for exploitation. The sundering of "objects"
from our touch primes us to take advantage of them. Colonial history
is a case study in losing touch: "White America has only attended to
the body of the earth in order to exploit it, never to succor it or to
be nurtured in it" (68). Anzaldua's /mestiza/, birthed in the open
wound of the border, "where the Third World grates against the first
and bleeds," is an attempt to bring together what has been separated
(3). Those who live on the border know better than anyone--divisions
between bodies puts those bodies into conflict.

Touch offers myriad ways of relation. Eve Kosofsky Sedgwick offers
touch as a way of connecting to objects that evades "dualistic
thought," that is, in "binary" thought, where things are presumed to
be discrete and opposed. 

*** TODO /Cruising Utopia/: queerness is desire for the not here

Muñoz re-articulates queerness as something "not yet here” (/Cruising
Utopia/ 1) It is not only as projection into the future but also as
projection of a certain futurity into and onto the present and the
past.

"Queerness is a structuring and educated mode of desiring that allows
us to see and feel beyond the quagmire of the present... Queerness is
a longing that propels us onward, beyond romances of the negative and
toiling in the present. Queerness is that thing that lets us feel that
this world is not enough, that indeed something is missing"
(/Cruising Utopia/ 1).


Queerness, Muñoz argues, is a “horizon of being” (Husserl 1991) that can be glimpsed in utopian bonds, affiliations, designs, and gestures that exist within the present, “a type of affective excess that presents the enabling force of a forward-dawning futurity” (23).
The crucial dialectical articulation of the “no longer conscious” with the “not yet”: Muñoz archives what has been lost, and what we are continuing to lose, in the long, sad shift from the sexually revolutionary energies of the fifties and sixties to their neoliberal neutralization.

*** TODO /Confessions/: desire being about hesitating touch:

 
*** TODO /Waves/: queerness (story) is frustrating closure... 


** queerness as untouchable 
But there is a problem with touch as it applies to queer bodies. Some
bodies do not want to be touched (feinberg), and other bodies, even
through touch, do not get through to us (hartman?). Experience and
subjectivity of minoritarian subjects are incommensurable: vestiges of
meaning are lost in translation[fn:6]; or experiences struggle to be
captured or expressed in form [fn:7]. In short, for queer bodies,
there is a dual impulse, a desire to touch and be touched that
coexists with the inability for touch to satisfy, provide redemption,
or avoid violation.

Respecting the right not to be touched, some queer theorists pursue
critical methods that prevent overidentification or overanalysis. They
resist reading practices, which have been called "suspicious reading"
or "paranoid reading"[fn:2], that seek to expose the effects of
homophobic prohibition and repression with the goal of affirming queer
subjects or recuperating their losses. Paranoid or suspicious reading
is oriented around finding and exposing the pain and shame of the
closet in order to turn them into sites of political resistance,
liberation, or pride.

*** Sedgwick's paranoid/suspicious reading

Such reading practices determine and constrain the ways that readers
engage with texts. To illustrate this effect, Sedgwick relates a
conversation between herself and a friend during few years of the AIDS
crisis, when speculation about the government's complicity in
spreading the virus is rampant. At the time, Sedgwick wonders whether
"the lives of African Americans are worthless in the eyes of the
United States; that gay men and drug users are held cheap where they
aren't actively hated" (123). Her friend counters this suspicion,
pointing out that knowledge of conspiracy doesn't achieve anything on
its own: "Supposing we were ever sure of all those things---what would
we know then that we don't already know?" (123). Merely knowing that
something is true, revealing the presence of systematic oppression,
injustice, discrimination, does nothing. As Sedgwick explains,
knowledge of a problem is not enough to "enjoin that person to any
specific train of epistemological or narrative consequences"
(123). Moreover, a paranoid or suspicious stance blocks out other
possibilities for relation to the text. Paranoia often only affirms
itself; reflecting and replicating itself in every surface, giving too
much power to the act of exposure. The work of paranoia is never done,
"for all its vaunted suspicion, [paranoia] acts as though its work
would be accomplished if only it could finally, this time, somehow get
its story truly known" (141). Like many other theorists, Sedgwick
wonders what is the point of continually trying to reveal, unravel,
deconstruct the injustices of the past. She searches for "some ways of
understanding human desire that might be quite to the side of
prohibition and repression, that might hence be structured quite
differently from the heroic, 'liberatory,' inescapably dualistic
righteousness of hunting down and attacking prohibition/repression in
all its chameleonic guises" (10).

*** paranoia and replication (the sciences)

In order to understand the ways that the paranoid impulse harm and
constrain inquiry, it is useful to view it at work in scientific
disciplines and for the purpose of historiography.

Some strains of scientific inquiry, in particular, shows us how
paranoia enacts a self-replicating mechanic. Though it appears in much
of literary studies, the impulse that drives paranoid reading is
borrowed from a critical viewpoint in scientific inquiry that assumes
a detached observer. Critiques of this position, particularly in Donna
Haraway's work on primatology, attempt to articulate a new mode of
feminist science that de-naturalizes the "natural." Haraway's research
on primates reveals the ways in which assumptions and preconceptions
from the (white, male) subject inflect the object of study. She
examines how scientists bring their own investments to bear even in
the seemingly benign questions they might ask, or qualities they
isolate, as areas of interest. For example, primatologists working
with the goal of studying social structures in the field often impose
their own social structures by turning their assumptions of male
dominance into "observations." Feminist scientists attempt to revise
such narratives by emphasizing organization and cooperation among
primate communities: "revisionists have stressed matrifocal groups,
long-term social cooperation rather than short-term spectacular
aggression, flexible process rather than strict structure”
(19). Pointing out that, “Women know very well that knowledge from the
natural sciences has been used in the interests of our domination and
not our liberation," Harwaway asserts that such revision is about
empowering the subjugated, reconceiving “female receptivity” as
"female choice" (8). The creation of a subject/object split
/reproduces/ and legitimizes hierarchies of domination.

Oftentimes, new tools can obscure the ways that we replicate our own
assumptions. The advent of photography in the mid-nineteenth century
allowed subjects to codify their prejudices as science, for example,
in the pictures of American slaves taken by Louis Agassiz
in 1850. These daguerrotypes, a pioneering practice in photography
that uses light-sensitive chemicals on silver plates, show how the
impulse for scientific classification impacts the quality and kind of
knowledge that results. Agassiz, a Swiss anthropologist, came to the
United States to study the physical differences between European
whites and African blacks, by examining the shape and character of
their heads and torsos, similar to contemporary studies in physionomy
and phrenology that analyzed the exterior form of the human
body. Agassiz's goal was to amass evidence to support his theory, that
mankind had been separately created and whites and blacks were in fact
different species (Wallis 40). Using photography for anthropoligical
purposes, and organizing photographs to support a classification
system, Agassiz's work demonstrates how the apparent "objectivity" of
the photograph can mask the highly subjective motives for
classification. Writing about the photographs, which were exhibited by
the Amon Carter Museum in 1992, Brian Wallis explains that such images
were organized to suggest divisions between "self and other, healthy
and diseased, normal and pathological," with the insidious effect of
"mask[ing] its subjective distortions in the guise of logic and
organization" (Wallis 47, 54-55). The problem, Wallis points out, is
the realism of the photographic tool obscures the ways that subjects
harness it to solidify their preconceptions---"Strengthened by the
seeming transparency of photographic realism, these categories and the
divisions between them soon took on the authority of natural 'facts.'
Supplying either too much or too little information, photographs soon
muddied the easy distinctions between subjective knowledge and what
was called "objective." (47-48). The more seeminly transparent the
tool, the easier it is to wrangle it toward proving "self-evident"
truths.

In this case, the apparent fidelity of the photographic tool to record
"nature" in fact obscures the ways that using the tool only reinforces
a preconceived notion of "nature." Wallis explains that, "Supplying
either too much or too little information, photographs soon muddied
the easy distinctions between subjective knowledge and what was called
'objective' (48). The photographs reinforce the ways that scientific
tools, which appear to capture "reality," can be harnessed and
manipulated toward the observer's purpose. 

*** paranoia and recovery (historiography)

Not only does paranoid inquiry tend to replicate the assumptions of
the observer, but it blocks out other forms of knowledge. This is
especially evident in the work of historical recovery, in the impulse
to find "hidden" or "forgotten" meaning in textual and archival
material. Recovery works by a self-legitimizing and perpetuating logic
that attempts to render what has been left out, disregarded, or
misunderstood within the logic of dominance. It is Jacques Derrida's
/archive fever/, or the desire for legibility, under the auspices of
the ruler, which animates the endless search for origins. It is, in
Haraway's words, a search for the "one code that translates all
meaning perfectly, the central dogma of phallogocentrism" (/Simians,
Cyborgs, and Women/ 176).

The stakes of recovery work are uniquely stark in the history of the
Black Atlantic, where researchers must work to square the growth of an
inhuman practice within a historical narrative of progress and
liberalization. A tradition that rationalizes slavery with the right
to property, that justifies war through the social contract. Black
Atlantic scholars Lisa Lowe and Saidiya Hartman point out that the
central paradox of studying the archive of slavery is the structuring
condition of recovery. In her essay "History Hesitant," Lowe explains
that because recovery work necessarily occurs within the limits of the
authorizing power, it always subjects itself to that power. Rather
that work under these conditions, historians of enslaved experience
ought to examine this confining structure, "the archeology of
knowledge through which the archive subjects and governs precisely by
means of instruments that absent the humanity of the enslaved”
(87). Researchers might examine, for example, how "the slave trader’s
desire to record, measure, list, and account" weigh up against
"rationalist claims to produce truth or meaning about the terrors of
captivity, enslavement, or torture" (88). Saidiya Hartman similarly
turns to the question of epistemology as the crux of the recovery
work: “If it is no longer sufficient to expose the scandal, then how
might it be possible to generate a different set of descriptions from
this archive?" (7).

Hartman's central problem is what to do with an absent archive. She
leaves us the paradox of recovery work: "How does one revisit the
scene of subjection without replicating the grammar of violence?"
(4). Hartman writes caustically about the impossibility of telling
stories that have been left out of the record. Not only that we can
never recover these stories (they are lost to time) but we can not
approximate them with our current tools, with language. In "Venus in
Two Acts," Hartman tells the story of Black Venus, the unnamed slave
woman who appears variously throughout the "offical" record:

#+BEGIN_QUOTE
we could have as easily encountered her in a ship’s ledger in the
tally of debits; or in an overseer’s journal—--“last night I laid with
Dido on the ground”; or as an amorous bed-fellow with a purse so
elastic “that it will contain the largest thing any gentleman can
present her with” in Harris’s List of Covent- Garden Ladies; or as the
paramour in the narrative of a mercenary soldier in Surinam; or as a
brothel owner in a traveler’s account of the prostitutes of Barbados;
or as a minor character in a nineteenth-century pornographic novel. 1
#+END_QUOTE

What draws all these iterations of Venus together is their silence,
"no one remembered her name or recorded the things she said, or
observed that she refused to say anything at all" (2). The fact of
silence cuts deeper than the failure of history but is part of the
condition known as the "violence of the archive," which denotes not
only absence as a form of evidence, in that the physical records are
missing, but also in the tools of expression, in language that cannot
approximate the reality of experience, and in the audible discourse
that dictates silence.

*** affective strategies, hestitation, restraint

Within the dominant culture, recovery means authorizing the structures
of knowledge that give rise to injustice in the first place. So what
do we do now? There are affects associated with this kind of
impasse. We hold ourselves back, restraint, avoidance. Lowe explains
that

#+BEGIN_QUOTE
Hesitation, rather than rushing to recover what has been
lost, need not be understood as inaction or postponement, or as a
thwarting of the wish to provide for a future world. Rather, it halts
the desire for recognition by the present social order and staves off
the compulsion to make visible within current epistemological
orthodoxy. 98
#+END_QUOTE

Feelings of hesitation, doubt, dissapointment are ways of protecting
the archive of slavery from further exploitation.

To sum up: one solution to paranoid impulses involves is critical
awareness, the ability to access the affects that come between you and
the object of study. 

*** estrangement as central to queerness
“Editor’s Introduction”: Queering Archives, Intimate Tracings, 2015:
The estrangement that continually happens with dealing with
queerness. Estrangement from yourself, the materials, and others.

“Estrangement” --- the torment of queer literature -- the pain of not
identification but of not identifying. Of reading the text and finding
and not finding yourself in the pages.

*** Heather Love's /Feeling Backward/
Heather Love offers a reading strategy that acknowledges queer
experience, particularly suffering, as unconsoleable. In resisting the
temptations to redeem psychic suffering by queer subjects, Heather
Love offers a strategy called "feeling-backward." This strategy opens
a space for bad feelings without trying to recuscitate, justify, or
transform them. She focuses on feelings such as "nostalgia, regret,
shame, despair, /ressentiment/, passivity escapism, self-hatred,
withdrawal, bitterness, defeatism, and loneliness," which, according
to Love, are tied to "the historical impossibility of same-sex desire"
(4, emphasis original). She examines the burdened protagonists from
famous modernist texts like Walter Pater's /The Renaissance: Studies
in Art and Poetry/ (1873), Radclyffe Hall's /The Well of Loneliness/
(1928), Willa Cather's /My Ántonia/ (1918), and Sylvia Townsend
Warner's /Summer Will Show/ (1936). Love argues that the shame and
stigma experienced by these characters ought to be recognized rather
than resolved. Instead of turning negative histories into sites of
resistance or affirmation, these hurting characters might have full
reign over their own darkness. And this darkness must be where the
critic will meet them.

*** identification is risky; Caldwell
As readers, identifying with literary subjects is both dangerous and
seducticve. Identities within texts are not stable across time and
place, and acts of identification might collapse or overlook the
complexity of experience. For queer readers in particular,
identification often emerges from a desire to recognize within the
past something that affirms queer experience in the present. Love
describes queer critics, "Like demanding lovers [who] promise to
rescue the past when in fact they dream of being rescued themselves"
(33). Reading in this sense is a search for reflection, community, or
similitude, a link between past and present. When identification is
possible, however, it can be shattering. In "The Torment of Queer
Literature," Kelly Caldwell explains the quandry of reading James
Baldwin's /Giovanni's Room/ as a transgender woman: "what if the only
available act of identification is one of stigma and shame? Embracing
queerness is often embracing abjection. Sometimes identification is
loss and despair" (par. 4). Identification tends to center around
these "bad feelings" which offer less fodder for political
resistence. However, identification with more positive aspects of
queer experience is hardly an alternative. For many readers, the more
redemptive or celebratory narratives offer no consolation. The reader
is stuck between recognizing their own pain or feeling guilty for not
recognizing pleasure: "Either read a book like /Giovanni’s Room/ at
the risk of recognizing David’s denial and repression as my own, or
read a book that celebrates queer lives and sex boldly and end up
despising my own cowardice" (par. 17).

*** queerness is a failed project, which is why it's so tempting.
The more hopeless and resistant queer subjects make for more tempting
identifications. Love explains how these subjects remain beyond the
reader's grasp: "As queer readers we tend to see ourselves as reaching
back toward isolated figures in the queer past in order to rescue or
save them. It is hard to know what to do with texts that resist our
advances" (8). The reason that these subjects remain so unreachable
has to do with the nature of queerness itself, which represents
absence, loss, and failure. Love illustrates this quality by evoking a
Greek myth, Orpheus and Eurydice, in which the lover botches his
beloved's rescue by looking back at her as they exit the
underworld. Love quotes from Maurice Blanchot's account of the story
in "The Gaze of Orpheus," to describe what Orpheus searches for in the
prohibited and doomed glance backward:

#+BEGIN_QUOTE 
Not to look would be infidelity to the measureless, imprudent force
of his movement, which does not want Eurydice in her daytime truth and
in her everyday appeal, but wants her in her nocturnal obscurity, in
her distance, with her closed body and sealed face---wants to see her
not when she is visible, but when she is invisible, and not as the
intimacy of familiar life, but as the foreignness of what excludes all
intimacy, and wants, not to make her live, but to have living in her
the plenditude of death. 50
#+END_QUOTE 

Orpheus's downfall is his desire for a glimpse at what cannot be
grapsed, at what remains beyond the light. This desire is not for
"daytime truth" but for "noctural obscurity," which is always receding
at the moment of pursuit. Like Eurydice, queerness emerges only to
slip away, turning its face from the parched gaze. Can we be blamed
for looking for that which cannot be grasped? No, because queerness
has always been structured by that which is not, by what Love calls
"impossible love" (24). Not only is queerness projected to fail, it is
a project of failure. Love reminds us that "Queer history has been an
education in absence" (50). In learning failure and loss, queer
readers can only identify with what they have been taught to recognize
as untouchable. Full identification, like Eurydice in the daylight, is
prevented by design.

*** identifying, but not fully.
Love proposes a method in which the goal is not to redeem queer
subjects or resolve queer failure. Rather, the problem of
identification is turned to a reading strategy: "I want to suggest a
mode of historiography that recognizes the inevitability of a 'play of
recogniztions,' but that also sees these recognitions not as consoling
but as shattering" (45). Reading, for Love, can enact a "play of
recognitions," which is a way of making fleeting connections that do
not presume complete understanding. It is a way of identifying, but
not fully. Full identification would attempt to wrench the subject
from its suffering, and effectively transform it into something
else. Rather that attempt to rescusitate it, Love looks to the ways
that identity unsettles and dissolves subjectivity. She gives the
example of Stephen Gordon from Radclyffe Hall's /The Well of
Loneliness/. Once considered too depressing as a model of lesbianism,
recent critics have cast Stephen Gordon as a transgender figure. Love
resists this label, maintaining that Stephen is “beyond the reach of
such redemptive narratives” (119). The question, for Love, is not
whether Stephen is a pre-op FTM (Female-to-Male), but how Stephen’s
existential negativity can be read as an embodied phenonmenon, as “a
social experience insistently internalized and corporeal” (108).

*** ofelia schutte and the incommensurable

The archivist must work within the discrepancy between reality and the
historical record. Hartman's goal is "to expose and exploit the
incommensurability between the experience of the enslaved and the
fictions of history... the requirements of narrative, the stuff of
subjects and plots and ends" (10).

*** Critique of affirmation: Cvetkovitch 

Attempts to affirm negative queer experience can be harmful. Ann
Cvetkovitch's work on trauma studies provides an example of how this
tendency can create further misunderstanding about suffering. In her
book, /Archive of Feelings/, Cvetkovitch explores expressions of
trauma within the public sphere. She asks how individuals might
reclaim some of the most negative and traumatic feelings into
something positive and theraputic: "I want to place moments of extreme
trauma alongside moments of everyday emotional distress that are often
the only sign that trauma's effects are still being felt” (3). She
wrests trauma studies out of medical discourse and into public
culture---turning something that is traditionally private and
pathologized into something communitarian, an open, everyday "archive
of feelings."

Importantly, Cvetkovitch marshalls this reconfiguration of trauma to
expand what we consider the 'archive'. She also makes some incisive
points about the inability to fully portray suffering: "Because trauma
can be unspeakable and unrepresentable and because it is marked by
forgetting and dissociation, it often seems to leave behind no records
at all" (7). Cvetkovitch explores alternative methods of figuring
trauma, which are transformed when they enter the public sphere. She
cites examples from public performances like rock shows or
documentaries, in which the artists enact "moments of intense affect
that are transformative or revealing” (26). 

Although her focus on the affective and ephemeral dimension of
performance opens up conceptions of the archive, Cvetkovitch perhaps
goes too far when she suggests that these performances are redemptive
or in some way compensate for traumatic experience. She indicates that
such performances go so far as to alleviate psychological damage and
suffering: “Imaginative work that may bear an oblique relation to the
actual event of sexual abuse can ultimately be more ‘healing’ than an
explicit rendering of the event” (94). Trauma is a real medical
condition, with real consequences (death) for those who do not seek
treatment or downplay its life-threatening effects. Critics should be
careful in extending a definition of trauma that will end up hurting
those who are affected by it. We do not need to move trauma strictly
from the medical discourse in order to have a more communitarian,
open, and public relationship to it. There are other ways to confront
stigma which doesn’t attempt to redeem it, as Love explores with her
notion of “Feeling Backward.”

The step that Cvetkovitch takes with regard to trauma is interesting,
however, for what it suggests about the role of the critic in
analysis. The point isn't to find evidence of overcoming queer
suffering, but to examine the ways that queerness is figured in
abstraction. What does queerness look like, what can it do? 


** abstraction, formalization, opacity: Queer 

*** reparative reading is active

We might explore, with Sedgwick, "forms of thought that would not be
structured by the question of prohibition" (11). Sedgwick points that
that critical inquiry might work within a /reparative/ methodology,
which opens room for interpretive possibilities and attention to
positive affects like love, gratitude, and affection. This method
welcomes surprise of discovery over affirmation. It prioritizes "local
theories and nonce taxonomies" over totalizing perspectives (145). We
might approach criticism as having to do with /movement/ rather than
/knowledge/:

#+BEGIN_QUOTE
[M]oving from the rather fixated question Is a particular piece of
knowledge true, and how can we know? to further questions: What does
knowledge /do/---the pursuit of it, the having and exposing of it, the
receiving again of knowledge of what one already knows? How, in short,
is knowledge /performative/, and how best does one move among its
causes and effects?" (my italics, 124)
#+END_QUOTE

This reorienation of knowledge as /active/, as performative, opens up
the critical process to one that is mobile and and speculative rather
than suspicious. Moreover, it draws attention to the ways that
knowledge is embodied, with all the surprises and discoveries that
embodiment entails. 

*** Scott's evidence of experience:
Scott, Joan. “The Evidence of Experience”:
- Using experience for evidence rather than thinking about how experience is shaped. Scott talks about representation, about looking at experience, at the vision, the optical effects, for what they suggest. The beautiful reading of Samuel Delany’s vision of the “millions of gay men” the fantastical projection (rather than real identity) that suggests a political consciousness. Historiography is about modes of seeing. 
- Scott’s proposed project is difficult to carry out. How many times do we need to go back to the archive? To what extent can you constantly start again at origins (genealogy). 
- She’s right in the critique that there’s no universal class consciousness. 
- Experience is always mediated for literary critics. We never take a text as referential---there is rhetoric and form. 

*** Munoz's queerness as emergent
The not-yet-here ness of queerness. 

*** hartman, lowe, arondekar on recuperating absence

"The critical challenge is to imagine a practice of archival reading
that incites relationships between the seductions of recovery and the
occlusions such retrieval mandates. By this I mean to say: What if the
recuperative gesture return us to a space of absence? How then does
one restore absence to itself? Put simply, can an empty archive also
be full?" (1). 

Hartmen's "critical fabulation"

The archivist must work within the discrepancy between reality and the
historical record. Hartman's goal is "to expose and exploit the
incommensurability between the experience of the enslaved and the
fictions of history... the requirements of narrative, the stuff of
subjects and plots and ends" ("Venus" 10).
- "This double gesture can be described as straining against the
  limits of the archive to write a cultural history of the captive,
  and, at the same time, enacting the impossibility of representing
  the lives of the captives precisely through the process of
  narration" ("Venus" 11).

*** QOC critique and aesthetics
Amber Musser's surface aesthetics
*** Toward a Queer Form
Writing the self is connected to form. Always. The form is
multiple. The form makes subjectivity opaque, but in the act of
abstraction, making it opaque, we can touch it and play around with
it. 

Opacity as value (Amin, Musser)Opacity as a value (Amin, Musser)


** in DH: data is cooked
As a mode of relationality, "Feeling Backward" not presume a full
connection between the critic and subject, keeping the subject at arms
length. It approaches queerness as something receding, even when the
critic is perpetually in pursuit. This relationship between critic and
textual subject evokes some of the attitudes that digital humaninists
take toward their data. In some queer theory and digital humanities
runs a similar hesistation not to overdetermine or overinterpret the
content of what we read. Critics such as Johanna Drucker and Ted
Underwood are careful to qualify the nature of data as constructed,
wrenched from the reality of lived experience, and necessarily reduced
to fit whatever environs required by analysis. Even if they are
careful about approaching data as constructed, however, they take
vastly different routes in handling the results of their analysis.

*** Drucker's skewing the graphs

Johanna Drucker argues that quantification techniques (such as
visualizations in graphs and charts) actually misrepresent the data
they are meant to convey. Drucker explains that, in order to place
this data on a graph or chart, it undergoes a
transformation. Complexity is reduced to whatever quality the
visualization apparently requires. To illustrate this reduction,
Drucker presents a chart displaying the amount of books published over
several years. The chart appears to convey production during this
specific time period[fn:3], but Drucker explains that publication date
is an arbitrary metric for capturing production. She brings to the
surface all the assumptions made in such a metric, for example, the
limitations of "novel" as a genre and the connotations behind
"published," which suggests date of appearance, but has no indication
of composition, editing, review, distribution. Drucker reminds us that
each piece of data carries with it the result of many interpretive
decisions, which carry with them varying degrees of opacity. These
interpretations ("reductions") are necessary in order to present
complex concepts like book production as a bar on a chart. Drucker
explains: "the graphical presentation of supposedly self-evident
information (again, formulated in this example as “the number of
novels published in a year”) conceals these complexities, and the
interpretative factors that bring the numerics into being, under a
guise of graphical legibility" (Drucker par. 23).

To resist the reductions of "data," a term that connotes that which is
"given," Drucker proposes "capta," to suggest the act of being taken
and transformed. Drucker's "capta" is deliberately creative, turning
graphical expressions into expressive metrics: components used for
measurement, like lines or bars on a graph, break or are fuzzy and
permeable. Objects are not discrete entities, but interact with the
other objects in the visualization. For example, in a bar graph of
book publications/year, she warps the bars on the graph, making some
of them fuzzy, wider, shorter, in an attempt to show that publication
as a metric elides other information such as composition, editing,
purchasing, etc.

This activity is a way of figuring elements that have been reduced,
resolved, or ignored in traditional quantitative analysis. It evokes
what Love says about queer subjectivity and experience being beyond
the reaches of the critic. Drucker makes evident what is overlooked or
assumed when dealing with complex subjects. She places those elements
there, for all to see, in a way that muddles (rather than
simplifies[fn:4]) the relationship between them. She does try to
figure these elements, but not in a way that attempts to clarify or
resolve their complexity. Rather, like Love, she works on the “image
of exile, of refusal, even of failure” (Love 71).

*** Ted Underwood's models as object of study

Ted Underwood and other literary critics doing Computational Literary
Studies (CLS) approach their data with vastly different
commitments. Underwood harnesses computational power and
sophistication to glimpse the big picture of literary history, what he
calls the "distant horizon" of literary trends across centuries. His
argument convincingly begins with the observation that human
capacities---sight, attention, and memory---preclude them from
grasping the larger patterns of literary history over time
periods. Distant reading, whereby "distance" implies abstraction, or
the simplification of textual data into computable objects such as
publication dates and genres, allows critics to make connections in
apparent chaos, to draw a steady line of historical development
through the swarm of overflowing information. According to Underwood,
distant reading opens new scopes to literary analysis, which would
otherwise be invisible to readers: "a single pair of eyes at ground
level can't grasp the curve of the horizon" (x).

Though to a much lesser degree than Drucker, Underwood similarly turns
his computational method into an object of study. His research deploys
machine learning, that is, computer programs "trained" by certain data
sets to make predictions about other datasets. Underwood studies how
"models," or calculations based on multiple variables, created by
sample data can then be used to measure further data. One of his
models measures the probability that computers can guess the sex of
a fictional character based on the words associated with that
character. Underwood explains how the test is configured:

#+BEGIN_QUOTE 
We represent each character by the adjectives that modify them, verbs
they govern and so on---excluding only words that explicitly name a
gendered role like /boyhood/ or /wife/. Then, we present characters,
labeled with grammatical gender, to a learning algorithm. The
algorithm will learn what it means to be 'masculine' or 'feminine'
purely by observing what men and women actually do in stories. The model produced by the algorithm can make predictions about other
characters, previously unseen. 115
#+END_QUOTE

The computer takes in information about some (the more the better)
books and studies that information in order to make predictions about
other books. The resulting model, therefore, is always guided by its
previous experience. Underwood rightly points out that such
calculations cannot be taken as fact. Like humans, "machine learning
tends to absorb assumptions latent in the evidence it is trained on"
(xv). To Underwood, machine learning is no more "objective" than
regualar analysis. This is why Underwood calls his work "perspectival
modeling," where he studies how datasets reveal, not the truth of
literary histroy, but the /approaches/ of those who study it: "By
training models on evidence selected by different people, we can
crystallize different social perspectives and compare them rigorously
to each other" (xv).

The results of the analysis is baked into the process, something that
Underwood understands and accepts as part of the obstacles toward his
distant horizon. In looking at the way gender is characterized, or
rather how perspectival models characterize gender, in novels from the
18th century to the 21st, he finds that the results reproduce some of
the structuring assumptions from the outset. His examination of gender
characterization finds that "while gender roles were becoming more
flexible, the attention actually devoted to women was declining"
(114). The analysis points to a steady overapping of words used to
describe men and women over time, shown as a convergence on the graph
between words previously associated with women, such as "heart," which
begin to intersect with words typically assoicated with men, like
"passion," toward the middle of the 20th century. However, while the
categories of "masculine" and "feminine" words are progressively
blurred over time, the actual number of female /characters/
declines. Underwood explains this drop could be due to several
reasons, one of which is the simple fact that the practice of writing
"gentrified" through the 20th century, when writing became
acknowledged and pursued as a male occupation (137). His analysis
shows that men tend to write more about men, while women write equally
about men and women. With less women writing, the amount of female
characters therefore declines. This explains how Underwood's seemingly
paradoxical conclusion, that gender roles become more flexible while
the actual prevalence of women dissapates from fiction, might be
possible. But Underwood also admits that another factor---the
assumption of gender as a binary category---might very well be guiding
his results: "One possible conclusion would be that the structural
positions of masculine and feminine identity, vis-'a-vis each other,
have remained very stable---while the actual content of masculinity
and femninity has been entirely mutable" (140). Viewing gender as a
binary construction perpetuates the structural categories of
male/female in a way that is at odds with the actual content of such
categorie. In other words, if gender is binary, then it stands to
reason that the relation between male and female will be one of
opposition. Underwood proposes that one way around this confining
structure of binary gender would be to refigure gender "as a spectrum
or as a /multiplication/ of gender identities that made the binary
opposition between masculine and feminine increasingly irrelevant to
characters' plural roles" (140).


** Critique of reproducibility
The criterion of reproducibility is deployed as a benchmark for
reviewing and assessing the efficacy of digital quantitative
methods. Despite their vastly different committments and methods,
scholars like Underwood can be compared to Nan Z. Da, Sari Altschuler
and David Weimer for the ways they place value on reproducibility.

*** nan Z da on reproducibility
In a controversial peice about text analysis, Nan Z. Da critiques
Computational Literary Studies (CLS) for its irrelevance to literary
criticism. Da explains that results from quantification do one of two
things: they either affirm what is already obvious or they present
conclusions that are inaccurate. Of her many gripes with quantitative
methods, which include "technical problems, logical fallacies, and
conceptual flaws," her central concern is the fundamental "mismatch"
of scientific methods to humanistic inquiry, both of which have
opposing "natures" (601). Meant for reading in abundance, tradign
"speed for accuracy, and coverage for nuance," Quantitativ methods are
inappropriately applied to literary interpretation (620). According to
Da, "we must use them in accordance with their true functions” (620).

One point in Da's essay crystallizes her ultimately conservative
investment that aligns her with theorists who have vastly different
methods and perspectives. Here she establishes the criterion of
reproducibility, which suggests an objective at odds with humanistic
endeavor. To verify the results of a Topic Modelling experiment, Da
attempts to replicate the model on her own machine. Because the
reproduction fails, she denigrates the whole process: "if the method
were effective, someone with comparable training should be able to use
the same parameters to get basically the same results"
(628-629). However, "topic modeling is like a kaleidoscope that turns
out something entirely different with the slightest tweaking”
(629). Her emphasis on the “reproducible” in CLS extends one of
distant reading early champion's originating call for a “falsifiable
criticism”: both advocate for a methodology that is as reliable and
verifiable as the social sciences[fn:5]. The interesting detail in her
critique is the insinuation in /reproducible/ that somehow analysis is
something that can exist outside of human performance/activity/error.

The reproducible indicates a slippery slope. By characterizing
literary criticism as something that can be verified, that can be
copied and reproduced ad infinitum, it assumes that interpretive
conditions can be universalized, that subjects bring with them the
same experiences and investments. Moreover, it suggests that there is
a /correct/ answer to literary critical questions, as if literature is
a problem that needs to be solved.

*** Altschuler and Weimar

This notion extends to digital humanist practitioners. 

they call to overturn the "unproblematic translatability of
information between the senses" while maintaining that reproduction is
the highest value. They argue to "texture the humanities", pointing
out that much of DH prioritizes the visual over other senses --
"privilege sight as the sense through which knowledge is accessible"
(74). Rightly so, they argue, “The textured DH we call for here
acknowledges that we cannot study knowledge only abstractly, apart
from the senses, and that we cannot study literature, art, and history
without including the history of embodied experiences” (74-75).
- “Touch This Page! uses 3-D printed facsimiles of raised-letter text to inspire reflection on the assumptions most people make about which senses are involved in reading” (82).

But they stray too far when they place reproduction over
remediation/deformance. They state their aims: “to expand the sensory
accessibility of archives for all users and to do so through the
digital reproduction---rather than the translation---of tactile
knowledge” (76). Case example of the perfect reproduction:
- A scenario where “users... can download a visual copy with
descriptive data, engage with the text in virtual reality, and create
their own textured facsimile. This technology once more makes possible
the tactile reading experiences for which this volume was designed and
promises library patrons a richer engagement with touch than most
archives can currently provide---even in person (85-86). 

The use case scenario makes the assumption that a reproduction is the
ideal form of textuality, despite their asserted aims for "diversity
of embodied experiences":
- “we must avoid tilting after the fiction of some ideal digital surrogate---like a virtual reality system that would flawlessly mimic original objects---lest we become digital Pierre Menards, expending extensive energy to improve our reproductions to discover, at last, that only the original perfects represents itself… Instead, we envision in our tactile futures multiple strategies that could not only open up access to varied experiences---past and present---but also diversity the ways embodied experiences structure our digital worlds” (86).
- in order to open up “multiple strategies” and diversity embodied experiences, we need a theory of text that is capacious enough to accept variation and transmediation. 
- This argument overlooks deformance is a
solution: the ways that creating new texts, paratexts, creates new
objects of knowledge. It overlooks the performative, ala McGann,
Clement.

In this view, digital becomes a means of optimization, efficiency,
total knowledge and understanding.



** For alternative readings: queer theory
*** Felski's post critical reading: the illusion of emotional detachment 
The reality is that we are stuck in these bodies of our thinking. Rita
Felski describes how seemingly neutral and detatched critical stance
belies an emotional disposition:

#+BEGIN_QUOTE
Scholars like to think that their claims stand or fall on the merits
of their reasoning and the irresistible weight of their evidence, yet
they also adopt a low-key affective tone that can bolster or
drastically diminish their allure. Critical detachment, in this light,
is not an absence of mood but one manifestation of it---a certain
orientation toward one's subject, a way of making one's argument
matter. 6
#+END_QUOTE

The "low-key affective tone" of scholarly discourse suggests that
affect, and the feeling subject associated with it, has been left out
of the critical process. However, appealing to the apparently
unemotional does not succeed in removing emotion from argument---this
is impossible---but it does reinforce the illusion that emotions don't
belong in rational thought. Actually they do---though the emotions of
critical discourse are of a quality and degree that mask their own
presence. Felski explains that, “Rather than an ascetic exercise in
demystification, suspicious reading turns out to be a style of thought
infused with a range of passions and pleasures, intense engagements
and eager commitments” (9). One follows the exposition of the framing
paradigms, the twists and turns of the driving question, the climax of
of discovery followed by the of denouement of the conclusion, one
immediately senses the full dramatic repertoire of critical
inquiry. 

And the illusion of reason as being devoid of emotion is not limited
to verbal discourse. It also pervades--perhaps even more
insidiously---the apparently objective reprsentations data
visualization. Graphs, charts, and maps all contain persuasive
elements that succeed through their invisibility, in the trust, for
example, that the souces are truthfully represented in the
visualization or the implied preference of some metrics over
others. Lauren Klein and Catherine D'Ignazio point out that "so-called
'neutral' visualizations that do not appear to have an editorial
hand... might even be the most perniciously persuasive visualizations
of all!" (/Data Feminism/, chapter 2). Not dots on a graph can be said
to be removed from the predelictions of the creator and the generosity
of the viewer.

*** Felski & Sedgwick affective approaches

Critics like Rita Felski and Eve Sedgwick adopt an alternative
approach toward reading that exposes knowledge as derived from
embodied experience. Felski talks about reading as an affective
orientation, where readers position themselves and their desires
around texts. Felski critiques the popular orientation in literary
criticism centered on what Paul Riceour has called the “hermeneutics
of suspicion”---the desire to unmask and demystify the secrets of
literary works. According to Felski, critics generally behave as if
language is always withholding some truth, that the critic’s task is
to reveal the unsaid or repressed. She identifies the affective modes
of suspicion to include disenchantment, vigilance, paranoia. 

Sedgwick makes a similar assertion about tendencies of "paranoid
reading," though she bases her critique on Michele Foucault's
repressive hypothesis from his /History of Sexuality, Vol. 1/, which
approaches discussions on sex and sexuality through the lense of
repression or prohibition. Rather than excavating the workings of the
repressive hypothesis, Foucault is interested in the ways that
discourse on sex has proliferated, in its multiplications that avoid
censure while satisfying the desire for sexual discourse. Left with no
place to go, discussion on sex simply continued to spread by
transforming itself into palatable discourses such as Marxism,
pyschoanalytic, libertarian, etc. By looking for the specter of
sex/power dynamics in these discourses, Foucault seems to work outside
the logic of the repressive hypothesis. But this is not the
case. Sedgwick explains that, "the almost delirious promise of the
book" is "the suggestion that there might be ways of thinking around
[the repressive hypothesis]" (9). In fact, Sedgwick explains that
Foucault's inquiry has been, from the start, structured by repression
and prohibition. She finds that the "critical analysis of repression
is itself inseparable from repression" (10). 

Felski and Sedgwick see a dead end in militant reading practices. 

Felski's nightmare: 
Sedgwick's wish: 

"How do we step outside the repressive hypothesis "to forms of thought
that would not be structured by the question of prohibition in the
first place?" (/Touching Feeling/ 11).

Speaking on Foucault's repressive hypothesis: "I knew what I wanted
from it: some ways of understanding human desire that might be quite
to the side of prohibition and repression, that might hence be
structured quite differently from the heroic, 'liberatory',
inescapably dualistic righteousness of hunting down and attacking
prohibition/repression in all its chameleonic guises" (/Touching
Feeling/ 10).

Felski shows how this suspicion toward texts forecloses other possible
readings while providing no guarantee of rigorous or radical
thought. Rather than adopt a suspicious attitude, Felski suggests that
literary scholars try “postcritical reading," which looks to what the
text suggests or makes possible. Felski wonders what if we allowed
ourselves to be marked or struck by what we read. Then, rather than
just be a cognitive activity, reading can become an “embodied mode of
attentiveness that involves us in acts of sensing, perceiving,
feeling, registering, and engaging” (176).

Reading is about movement 


Postcritical Reading --- "Reading, in this light, is a matter of
attaching, collating, negotiating, assembling—of forging links between
things that were previously unconnected”… “Reading, in this sense, is
not just a cognitive activity but an embodied mode of attentiveness
that involves us in acts of sensing, perceiving, feeling, registering,
and engaging” (176).

*** Sedgwick on generative shame
What if we read Henry James mobilizing shame as a creative resource?
  For many queer people, shame is a structuring force in their
  identity. But this doesn’t mean we need to be negative, we can look
  to the ways that shame unlocks creativity and productivity---to the
  ways that metaphors are made possible through shame. James’
  “blushing”, “flushing” is linked to a fantasy of the skin being
  entered, or touched by a hand. GLOVE, GAGE, GAGEURE…  We can reclaim
  a negative affect of shame and approach it as a generative force.
- "Shame interests me politically, then, because it generates and
  legitimates the place of identity--the question of identity--at the
  origin of the impulse to the performative, but does so without
  giving that identity space the standing of an essence. It
  constitutes the as-to-be-constituted, which is also to say, as
  already there for the (necessary, productive) misconstrual and
  misrecognition. Shame--living, as it does, on and in the face--seems
  to be uniquely contagious from one person to another. And the
  contagiousness of shame is only facilitated by its anamorphic,
  protean susceptibility to new expressive grammars" (63).







** Paralleling Queer & DHers looking for alternative readings
*** Case in point: klein's figuring the absence
Draw Klein and Hartman together---this is what I want to do for Queer
texts. 


** Performativity
Digital formats and interfaces facilitate queer encounters methods, an
intimate process of engaging with literature on a computer, where
users can manipulate and transform text.
*** Bode's materiality, critque of Underwood

Katherine Bode's critique of Underwood points out that QLS methods
incorporate hidden assumptions about the data, about what is
findable. She offers a method that builds off the humanistic
approaches in textual scholarship and bibliography, where the model is
prior to computation. 

*** Tanya Clement: discovery

*** Against reproduction, for remediation/deformance 

*** McGann's "prosthetic extension" 
These tools work alongside the reader’s intuition, in what Jerome
McGann calls a “prosthetic extension of that demand for critical
reflection,” by which the reader is able to feel her way through the
text (18).

*** Critique of Underwood's "sensitivity"

Underwood overlooks the ways that distant reading can be a
prosthesis. Claims that Quantitative are not as "sensitive" or
"exacting" as close reading, and are mostly useful for long views. How
can we approach distant reading as multiplying alternative readings?
Rightly points out that human attention guides the scale of
analysis. So we have to be very careful at the question we are posing,
and the way that we interact with the computer.
    - "Critics who want to sensitively describe the merits of a single
      work usually have no need for statistics... Computational
      analysis of a text is more flexible than it used to be, but it
      is still quite crude compared to human reading; it helps mainly
      with questions where evidence is simple too big to fit in a
      single reader's memory" (xxi).
- Repeatedly stresses that the point of quantitative methods is to
  discover new scales of analysis, but he seems to be looking for an
  overarching theory that will encapsulate literary
  history. Quantitative methods seek to overcome a problem of
  attention, of memory, in order to gain a large view. Here, human
  memory is a hindrance, rather than a drive. The goal is rather to
  multiply alternative readings. 
    - Attention determines analysis, analysis determines knowledge,
      knowledge determines disciplines, periodization (8).
    - "The challenge is to find a perspective that makes the descriptions
      preferred by eighteenth-, nineteenth-, and twentieth-century
      scholars all congruent with each other" (32). 


** Vantanges

*** Klein, Mandell, Caughie, Gaboury
*** Against totalization
*** The visible and the invisible, opting out 


** Provisionality 

*** Susan Brown's provisionality
*** Julia Flander's work on Orlando
*** Against stability 


** Digital projects based on text manipulation: 
I find that the haptic and exploratory activity of working with these
tools enlivens the reading process by allowing the reader to play,
experiment, and imagine new connections to the textual object.

*** /Voyant-Tools/
Jerome McGann "prosthetic extensions"
Potential texts: Woolf's /Orlando/. 

- Interweave a narrative about touch. Taking new materialist ideas but
placing them within context of QPOC critiqe. Anzaldua and Bennet on
touch and severing. Sarah Ahmed too. 

*** /These Waves of Girls/
Following narrative desire. The click of the mouse allows readers to
move with the text, based on their own paths. 

*** what are some print texts that enact these principles of movement?
- Alison Bechdel's "Are You My Mother": where every page is vibrating
with reference. 


** MISC 



*** within our bodies
This point bears repeating---we are always stuck within the bodies of
our thinking. As such, we might as well turn to ourselves, to explore
(rather than how things are in the world) how things are /to
us/. Sedgwick points out that the problem is not one of knowledge, but
one of movement. We can try to in-/corporate/, as much as possible,
alternative reading methods that get at the unique experience of being
a thinking/feeling human that is fiddling with these tools. We can, in
other words, examine the possibilities of /touching/ what we read. And
we can do so with digital tools for text analysis and machine
learning.  However, there still exists a view that distant reading
lacks the sensitivity of close reading. "Critics who want to
sensitively describe the merits of a single work usually have no need
for statistics" (xxi).

***  data reduction / queer assimilation 
For those that would argue that negative feelings are no longer
relevant in today's world, Heather Love responds that the advent of
assimilation, of popular acceptance, only creates more problems for a
group that has come into being as abject. /(the corrolary for digital
studies is the proliferation of data, of information, digitization)/
Queer assimilation and apparent rise in acceptance across popular
culture and mass media contradicts the reality of shame and stigma
that everyday queers experience, a contradiction that breeds ever more
shame: "Of course, same-sex desire is not as impossible as it used to
be; as a result, the survival of feelings such as shame, isolation,
and self-hatred into the post-Stonewall era is often the occasion for
further feelings of shame. The embarrassment of owning such feelings,
out of place as they are in a movement that takes pride as its
watchword, is acute" (4). What do we do with these residual feelings
of shame?

How should queer criticism orient itself? Love shows that critics face
a contradiction, brought on by the reality of negative feelings and
psychic costs of being queer in a homophobic society. The narrative
trajectory of queer progress runs counter to the residual pain of
being queer. Criticism is stuck in the middle of this ambivalence,
between affirming its pride and bemoaning its suffering: "We are not
sure if we should explore the link between homosexuality and loss, or
set about proving that it does not exist" (Love 3).

*** Misc Quotes
"how might activating emotion – leveraging it, rather than resisting
emotion in data visualization – help us learn, remember, and
communicate with data?" (Klein and D'Ignazio, /Data Feminism/,
chapter 2)


* Works Cited
Caldwell, Kelly. "The Torment of Queer Literature," /The Rumpus/. 2018.
Love, Heather. /Feeling Backward: Loss and the Politics of Queer
History/. 2009.

Wallis, Brian. “Black Bodies, White Science: Louis Agassiz's Slave
Daguerreotypes.” /American Art/, vol. 9, no. 2, 1995, pp. 39–61. JSTOR,
www.jstor.org/stable/3109184.


* commands
c-c c-x f => create a new footnote
c-u c-c c-x f then select s => sort footnotes

block quotes: #+BEGIN_QUOTE & #+END_QUOTE


* Footnotes

[fn:7] Amin, Kadji, Amber Jamilla Musser, and Roy Pérez “Queer Form:
Aesthetics, Race, and the Violences of the Social” ASAP/Journal,
Volume 2, Number 2, May 2017, pp. 227-239: “Form informs queerness,
and queerness is best understood as a series of relations to form,
relations not limited to binary and adversarial models of resistance
and opposition” (228). 

[fn:6] Schutte, Ofelia. “Cultural Alterity: Cross-Cultural
Communication and Feminist Theory in North-South Contexts.” Hypatia,
vol. 13, no. 2, 1998, pp. 53–72. www.jstor.org/stable/3810637.

[fn:1] Amin, Kadji. "Haunted by the 1990s:
Queer theory's affective histories." WSQ: Women's Studies
Quarterly:44.3 (2016): 173-189.

[fn:2] Rita Felski? and Eve Kosofsky Sedgwick.

[fn:3] Drucker implicitly refers to the first chapter from Franco
Moretti's /Graphs, Maps, Trees/ (2007), throughout which Moretti
graphs novels by their publication date between 1700 and 2000 and
draws conclusions about the relationship between genre and generations
of readers.

[fn:4] Moretti: "'Distant reading'... where distance is however not an
obstacle but /a specific form of knowledge" (1).

[fn:5] According to Franco Moretti: “Testing” literary interpretations
be the same process as in scientific disciplines -- demanding that
interpretations are “coherent, univocal, and complete,” and are tested
against “data” that appears to contradict it (/Signs/ 21). “The day
criticism gives up its battle cry ‘it is possible to interpret this
element in the following way,’ to replace it with the much more
prosaic, ‘the following interpretation is impossible for such and such
a reason,’ it will have taken a huge step forward on the road of
methodological solidity” (/Signs/ 22).


