* Chapter One Sketch

Revising the first draft. 

** the fantasy of the falsifiable 
Paranoid reading methods encourage a reproducible kind of criticism
that doesn't teach us anything novel about gender. How do we get out
of the cycle of reproducibility?

*** reading methods
Introduces paranoid, militant, suspicious reading, which is unified by
the belief that something hidden will allow us to understand the
text's meaning. 

*** DR's roots in the falsifiable toward automation
goes into Moretti's early thinking on a falsifiable criticism, which
was intended to reduce ambiguity and disagreement, and make literary
criticism more like a science.

goes into Da's usage/critique of DR, which extends Moretti's valuation
of falsifiable.

*** ramsay's algorithmic criticism, drucker's speculative computing
these approaches purposefully employ the computer toward less
reproducible, and more speculative, results. Ramsay uses the
objectivity of the machine as an aid in subjective work; Drucker takes
the more radical approach and uses methods to critique objectivity.

*** reading for social categories SoRoland
Moretti, Da, Drucker, and Ramsay are actually all engaging in a kind
of speculative kind of criticism. The difference is their orientation
toward their data. Moretti is suspicious, the others are open to being
struck. 

This is important when we are studying data about marginalized
subjectivities. See So and Roland on reading race, for example. White
authorship only coheres against the variance of black authorship. This
shows how categories are constructed. Using the computer to explore
the ways that humans encode meaning into social constructs. Finds a
relationship between sexuality and race.

I want to take aspects from Ramsay's speculation, Drucker's
distortion/deconstruction, and SoRoland's orientation to study
marginalized aspects of gender.

*** Underwood v Mandell's on deconstructing gender
Underwood shows how studying gender can fall into an oppositional
structure that Sedgwick describes as paranoia. 

Mandell's study of gender according to performance is exactly
necessary, but her understanding of gender as something to be mimicked
overlooks the habitual constitutive nature of it.

*** using the digital to work with gender
How do we take what SoRoland, Ramsay, Drucker, Mandell are teaching us
and apply it to studying gender? We need a method that attends to the
particularity of gender construction, according to queer theory. Like
So and Roland found blackness defines only against whiteness, we need
to look at how the female defines against the male.

we have to be careful about the kind of knowledge we are trying to
create. Not adopting a suspicious attitude, but a speculative one. 

*** orlando close reading
In close reading the text, we see a relationship between gender and
the imagination. Let's explore. 

--> add criticism on gender in the novel


** deformance and preformance
textual scholarship methods which pay attention to materiality of the
textual transformations (deformance) engage well with queer theory
about performance of gender (performance).

*** harnessing human attention
Distant reading not to expand coverage, but to engage with working
memory, human attention.

*** textual scholarship perspective
critics like mcgann, clement, and bode resist conservative motives for
textual scholarship and explore discovery, speculation.

*** TODO textual scholarship: from restorative to distorting
history of textual scholarship begins with a conservative trend in
which the editor takes more control/authority over the text, but
according to some external belief in what that text is supposed to be

--> add that THIS IS FUCKIN PARANOID. Spinning the thread from section
one.

Then, we have people like McGann and Samuels who adopt more
speculative approaches, aiming for a "quantum poetics" which attends
to the volatility of meaning contained within textual elements. They
propose a deformative criticism which distorts textual material
(rather than "restore" them) in order to spark inquiry. 

*** the tool creates cuts in data
Bode: our tools/apparati create "cuts" in data. 

*** TODO abstraction and human attention 
Clement: multiple levels of abstraction in the digital text allows for
numberable interventions that harness human attention spans

--> more directly engage this point in response to Underwood's comment
on human attention and paranoid reading. 

*** queer performance & citationality
performative citationality draws from a domain of abjection, the
outside, to resignify meaning within a regulatory system.

language is productive, not representative

*** example of performative citation: Irigaray
we work what's not there into what is there.

*** TODO preserving the unintelligible
the key to disrupting without doing violence (making
representationalist claims) is to never try to keep the unintelligible
outside, preserve it for continual resignification. 

--> conclusion: this is the antithesis to the paranoid position!!! 


** queer distant reading
An iterative method of distant reading attends to gender as an
iterative practice. We find ever expanding ways that gender is
characterized in /Orlando/. 

*** bode and butler parallel on language productivity
There is something fundamentally productive about language

*** reproducibility reduces data
Reproducibility reduces data into abstractable, "simple picture"
forms which perpetuate themselves.

*** shifting to the speculative
But we might use deformance and performance to harness reduction
toward speculative ends.

*** TODO Man and Woman in Orlando
Qe are resignifying man and woman to mean differently in Orland by
creating a model of their significations.

*** TODO modeling gender distinctiveness
make a model of the way that the genders distinguish themselves in the
novel---imaginative elaborations of gender. 

*** TODO iterating over the code resignifies it
running the computation over and over again with new inputs is a way
of resignifying. Like a game of telephone.

*** TODO findings: new configurations of gender
what do we find out about gender here? how does this change the way we
approach this text?

*** TODO the power of the imagination
this process reveals the hidden "enabling structure" of the imagination

*** TODO conclusion: performative citation queers distant reading
insubordination through subservience, displacement through repetition

