* Chapter One Brainstorm

** Rough outline for chapter:
- touch as a reading method: making & opening connections
  - anzaldua and sedgwick on touch as connective and multiplying
- queerness as untouchable: something we cannot fully grasp
  - love and cvetkovitch on queer negativity
- data as unknowable: something we cannot fully grasp
  - drucker and underwood on studying cooked data
- against reproducibility
  - Da, Underwood and Altschuler and Weimer
- For alternative readings: queer theory offers
  - awareness of critical detatchment opens up our engagement with capta
  - felski's affective method
  - sedgwick on reparative reading
  - sedgwick on generative shame: 
  - abstraction as necessary in order to bring things into relation
- Feminst/Queer DHers doing something similar
  - klein on figuring what is absent
- Performance as a reading method
  - bode and clement: materiality and discovery
  - against reproduction, for remediation/deformance
  - debt to mcgann, ramsay on deformance, piper on cl
- Vantages, the view
  - Klein, Mandell, Caughie, Gaboury
  - against totalization
  - the visible and the invisible, opting out
- Provisionality / Ephemerality
  - Susan Brown, Julia Flanders
  - against stability
- example of queer theorist who is guided by
    touching/feeling... affect theories? Munoz, Anzaldua, Ahmed... 
- my reading of /voyant-tools/ & /waves/

*** Pros Description: The first chapter, "Reading: 'Touching without
Touching,'" lays out what Digital Humanities methodologies might learn
from Queer Theory. This chapter looks at specific reading practices by
Eve Kosofsky Sedgwick and Heather Love, which question the proper
relationship of the critic to the object of study. Sedgwick's ideas
about "touching/feeling" and Love's notion of "touching without
touching" pose queer modes of relationality that do not presume full
connections as prerequisite for analysis. This chapter engages these
techniques with various critical methods from the Digital Humanities,
including distant, surface, and post-critical reading, and
deformative, algorithmic, and speculative criticism. I pay particular
attention to how digital formats and interfaces might facilitate queer
critical methods, and I speculate on the intimate process of engaging
with literature on a computer, where users can manipulate and
transform text in virtually infinite and unique ways. Comparing three
very different kinds of digital projects based on text manipulation,
including the text analysis web application /Voyant-Tools/, the text
encoding archive, /Women Writers Online/, and a hypertext novella by
Caitlin Fischer, /These Waves of Girls/, I explain how these tools
work alongside the reader’s intuition, in what Jerome McGann calls a
“prosthetic extension of that demand for critical reflection,” by
which the reader is able to feel her way through the text (18). In
particular, I find that the haptic and exploratory activity of working
with these tools enlivens the reading process by allowing the reader
to play, experiment, and imagine new connections to the textual
object.


** A new way of reading--guided by touch
*** touch, reading: Anzaldua and Sedgwick

Touch is the first site of connection between the queer and the
digital. 

Anzaldua shows how touch is a way of preventing conflict.

Sedgwick shows that touch is a way of multiplying connection. 


** Queerness as untouchable: Resisting overreading
This section explores how reading practices grapple with histories of
queer pain and exclusion to open up new possibilities for
interpretation based on feeling rather than redemption or closure. 

*** Heather Love's queerness as failure, impossible
Love offers a model of "feeling backward" which is a way for critics
to connect with queer subjects in a way that keeps objects out of the
critic's reach. For Love, identification is about finding the moment
when the subject turns away: "Queer history has been an education in
absence" (50.) This moment of turning away characterizes queerness as
something raw, which cannot be captured.

*** Ann Cvetkovitch's trauma is public, archives are affective. 

Cvetkovitch shows how affirming queer negativity, in trying to
recusitate bad feelings, can actually create more harm. She is good at
recognizing that some things cannot be figured, while expanding the
archive

Critique: the critic goes too far in making assumptions about the
healing potential of public acts of queer trauma. The critic is not a
psychologist, trauma still kills people, those traumatized need to
seek treatment. The point isn't heal or recuperate queer suffering,
this can never be done through abstraction, not by the critic. The
point is to examine the ways that queerness is figured through
abstraction--I think? We do not say whether these things are
healing. All we can deal with is the data that we are given.


** The problem: Data as always cooked
*** Johanna Drucker's capta

Shows the reductions of data that are necessary for most graphical
visualizations. Counters these with the concept of "capta" and
graphical expressions that can gesture toward the messiness of
experience. 

*** Case in point: Ted Underwood

Ted Underwood is a case in point of how the critic's entanglement
bakes results into analysis. 


** Critique of Reproducibility: Nan Z Da, Underwood, Altschuler and Weimer
Scholars like Da, Underwood and Altschuler and Weimer who want something
reproducible (this overlooks the performativity of engaging with texts
online).
 
*** Nan Z Da on Reproducibility 
*** Ted Underwood on studying models

Underwood from PMLA example. He only reproduces the gender
binary. Interweave with what Sedgwick says about binaries.

Ted Underwood puts forth a good understanding on quantification being
no more more objective than words. Rather than using "distant reading"
to ascertain "facts" about literary history, he's examining what
models are doing when used by humans. His focus on "perspectival
modeling" reveals how the computer process reproduces human
assumptions.

However, the results of the analysis are always baked into the start,
ask Underwood's conclusions about gender reveal gender to be a binary
and oppositional force.


** For alternative readings: queer theory
The question then becomes, how might we pursue criticism that does not
reproduce our own assumptions?

*** Felski's and Sedgwick
Eve Kosofsky Sedgwick has explained how /reading/ can be either
liberatory or relational. Which is to say it can be a tool for closing
or opening further readings. Sedgwick critiques Michel Foucault for
contributing to a model of "suspicious reading:" an approach that
mines a text for what is hidden, latent, or just beneath the
surface. Foucault's "repressive hypothesis" posits that discourse on
sexuality has been 

"I have tried in this project to explore some of the ways around the
topos of depth or hiddenness, typically followed by a drama of
exposure, that has been such a staple of critical work of the past
four decades" (/Touching Feeling/, 8). 

*** Sedgwick on generative shame
*** Saidiya Hartman on Speculation in the face of absence
*** Alternative readings, speculation is necessary


** Paralleling Queer & DHers looking for alternative readings
*** Case in point: klein's figuring the absence
Draw Klein and Hartman together---this is what I want to do for Queer
texts. 


** Performativity
Digital formats and interfaces facilitate queer encounters methods, an
intimate process of engaging with literature on a computer, where
users can manipulate and transform text.
*** Bode's materiality, critque of Underwood

Katherine Bode's critique of Underwood points out that QLS methods
incorporate hidden assumptions about the data, about what is
findable. She offers a method that builds off the humanistic
approaches in textual scholarship and bibliography, where the model is
prior to computation. 

*** Tanya Clement: discovery

*** Against reproduction, for remediation/deformance 

*** McGann's "prosthetic extension" 
These tools work alongside the reader’s intuition, in what Jerome
McGann calls a “prosthetic extension of that demand for critical
reflection,” by which the reader is able to feel her way through the
text (18).
*** Critique of Underwood's "sensitivity"

Underwood overlooks the ways that distant reading can be a
prosthesis. Claims that Quantitative are not as "sensitive" or
"exacting" as close reading, and are mostly useful for long views. How
can we approach distant reading as multiplying alternative readings?
Rightly points out that human attention guides the scale of
analysis. So we have to be very careful at the question we are posing,
and the way that we interact with the computer.
    - "Critics who want to sensitively describe the merits of a single
      work usually have no need for statistics... Computational
      analysis of a text is more flexible than it used to be, but it
      is still quite crude compared to human reading; it helps mainly
      with questions where evidence is simple too big to fit in a
      single reader's memory" (xxi).
- Repeatedly stresses that the point of quantitative methods is to
  discover new scales of analysis, but he seems to be looking for an
  overarching theory that will encapsulate literary
  history. Quantitative methods seek to overcome a problem of
  attention, of memory, in order to gain a large view. Here, human
  memory is a hindrance, rather than a drive. The goal is rather to
  multiply alternative readings. 
    - Attention determines analysis, analysis determines knowledge,
      knowledge determines disciplines, periodization (8).
    - "The challenge is to find a perspective that makes the descriptions
      preferred by eighteenth-, nineteenth-, and twentieth-century
      scholars all congruent with each other" (32). 


** Vantanges

*** Klein, Mandell, Caughie, Gaboury
*** Against totalization
*** The visible and the invisible, opting out 


** Provisionality 

*** Susan Brown's provisionality
*** Julia Flander's work on Orlando
*** Against stability 


** Digital projects based on text manipulation: 
I find that the haptic and exploratory activity of working with these
tools enlivens the reading process by allowing the reader to play,
experiment, and imagine new connections to the textual object.

*** /Voyant-Tools/
Jerome McGann "prosthetic extensions"
Potential texts: Woolf's /Orlando/. 

- Interweave a narrative about touch. Taking new materialist ideas but
placing them within context of QPOC critiqe. Anzaldua and Bennet on
touch and severing. Sarah Ahmed too. 

*** /These Waves of Girls/
Following narrative desire. The click of the mouse allows readers to
move with the text, based on their own paths. 

*** what are some print texts that enact these principles of movement?
- Alison Bechdel's "Are You My Mother": where every page is vibrating
with reference. 


** MISC
*** incommensurability, numbers are just as ambiguous
    - "The imprecision of the human world is part of the reason why
      numbers are so useful in social science: they allow researchers to
      describe continua instead of sorting everything into discrete
      categories" (Underwood 20).
