* Chapter One Sketch

Revising the first draft. 

** The fantasy of the falsifiable 

*** reading methods
Introduces paranoid, militant, suspicious reading, which is unified by
the belief that something hidden will allow us to understand the
text's meaning. 

*** DR's roots in the falsifiable toward automation
goes into Moretti's early thinking on a falsifiable criticism, which
was intended to reduce ambiguity and disagreement, and make literary
criticism more like a science.

goes into Da's usage/critique of DR, which extends Moretti's valuation
of falsifiable.

*** ramsay's algorithmic criticism, drucker's speculative computing
these approaches purposefully employ the computer toward less
reproducible, and more speculative, results. Ramsay uses the
objectivity of the machine as an aid in subjective work; Drucker takes
the more radical approach and uses methods to critique objectivity.

*** reading for social categories SoRoland
Moretti, Da, Drucker, and Ramsay are actually all engaging in a kind
of speculative kind of criticism. The difference is their orientation
toward their data. Moretti is suspicious, the others are open to being
struck. 

This is important when we are studying data about marginalized
subjectivities. See So and Roland on reading race, for example. White
authorship only coheres against the variance of black authorship. This
shows how categories are constructed. Using the computer to explore
the ways that humans encode meaning into social constructs. Finds a
relationship between sexuality and race.

I want to take aspects from Ramsay's speculation, Drucker's
distortion/deconstruction, and SoRoland's orientation to study
marginalized aspects of gender.

*** Underwood v Mandell's on deconstructing gender
Underwood shows how studying gender can fall into an oppositional
structure that Sedgwick describes as paranoia. 

Mandell's study of gender according to performance is exactly
necessary, but her understanding of gender as something to be mimicked
overlooks the habitual constitutive nature of it.

*** using the digital to work with gender
How do we take what SoRoland, Ramsay, Drucker, Mandell are teaching us
and apply it to studying gender? We need a method that attends to the
particularity of gender construction, according to queer theory. Like
So and Roland found blackness defines only against whiteness, we need
to look at how the female defines against the male.

we have to be careful about the kind of knowledge we are trying to
create. Not adopting a suspicious attitude, but a speculative one. 

*** orlando close reading
In close reading the text, we see a relationship between gender and
the imagination. Let's explore. 

--> add criticism on gender in the novel
