* Chapter One Brainstorm

*** Nan Z Da on Reproducibility 
Reproducibility as a benchmark for quantitative methods enacts some of
the same harms as paranoid reading. Da's point on "reproducibility"
reveals an ultimately conservative investment in interpretive work as
something objectively, factually, effectively true.

*** Altschuler and Weimar
They call to overturn the "unproblematic translatability of
information between the senses," valuing reproduction
over remediation/deformance. In this view, digital becomes a means of
optimization, efficiency, total knowledge and understanding.

*** Drucker's skewing the metrics
Drucker warps graphical metrics to suggest indeterminacy. 

*** the intersection btw queer & digit
The "desire for touching," without being able to fully touch, as the
definition of queerness, is also where the digital and queer
intersect. Digital media creates the illusion that we have access to
data, to information, but all we have access to is a *formalized*
relationship to that data. We encounter the digital object through
mediation, through an interface, mice, GUIs, keyboards, etc.


** TODO draft Value: Performativity
--> Digital formats and interfaces facilitate an intimate process of
engaging with literature on a computer, where users can unlock the
dynamicity of texts. This performative elements allows unique and
alternative reading paths. 

*Distant reading tools are tools for thought, rather than
disambiguation machines.*
- this is about seeing data as performative, prompting play,
speculation...

*** the value of alterneity over reproduction: performance
We move away from the reproducible to the performative, exploring
active elements of analysis, the sensible engagement between critic
and text

*** Bode's materiality, critque of Underwood
Bode emphasizes attention to the apparatus. 

*** Critique of Underwood's "sensitivity"
Distant reading can be sensitive, harnessing the attention span of
the reader to present new pathways through text. 

*** Tanya Clement: discovery
                


** Digital projects based on text manipulation: 
I find that the haptic and exploratory activity of working with these
tools enlivens the reading process by allowing the reader to play,
experiment, and imagine new connections to the textual object.

*** /Voyant-Tools/
Jerome McGann "prosthetic extensions"
Potential texts: Woolf's /Orlando/. 

- Interweave a narrative about touch. Taking new materialist ideas but
placing them within context of QPOC critiqe. Anzaldua and Bennet on
touch and severing. Sarah Ahmed too. 

*** /These Waves of Girls/
Following narrative desire. The click of the mouse allows readers to
move with the text, based on their own paths. 

*** what are some print texts that enact these principles of movement?
- Alison Bechdel's "Are You My Mother": where every page is vibrating
with reference. 


** MISC
*** incommensurability, numbers are just as ambiguous
    - "The imprecision of the human world is part of the reason why
      numbers are so useful in social science: they allow researchers to
      describe continua instead of sorting everything into discrete
      categories" (Underwood 20).

*** race and technology
- Lisa Nakamura, “Race In/For Cyberspace: Identity Tourism and Racial
      Passing on the Internet” in Works and Days, Volume 13, Nos. 1 &
      2, 181-193, 1995. [Available as a .pdf on course Group site.]


