* Chapter One Sketch

Revising the first draft. 

** the fantasy of the falsifiable 
Paranoid reading methods encourage a reproducible kind of criticism
that doesn't teach us anything novel about gender. How do we get out
of the cycle of reproducibility?

*** intro - computing queerness
The question: how do we deform a text to bring out new forms of
gender?

*** reading methods
Paranoid reading is about expressing something something hidden. This
reading style encourages reproducibility in criticism, turning 
reading into a mechanical practice that searches for what is hidden
rather than what is on the surface ofthe text.

*** DR begins in the falsifiable, toward reproducibility
Distant reading furthers this reproductive impulse in paranoid
reading. The paranoia to analyze vast swaths of literary history. 

Franco Moretti's scholarship has been invested in riding the critic of
subjectivity, in creating a reproducible (to the point of automating)
analysis. 

Reproducibility is so paranoid that even those who disagree with
quantification think of it as a benchmark (Da).

*** Ramsay and Drucker's speculative methods
There are critics doing speculative work--using computers as an
opportunity for critical analysis (Ramsay) and using them to engage
with data that is reduced or flattened (Drucker).

*** orientation makes the difference: falsifiable v speculative
The difference between the falsifiable and the speculative--the
falsifiable creates a reproducible critique.

*** reading for social categories SoRoland
Reproducibility blocks out other relation to text, especially aspects
that are slippery or marginalized, such as gender. There are attempts
to use DR for this kind of social analysis. SoRoland uses machine
learning to explore the constructedness of social
categories--whiteness as a category depends on blackness. They also
find material speculation in the form of an error, something
unexpected that yields a new reading. They conclude that machine is an
apt tool for studying race because it similarly uses highly
constructed and reductive methodologies.

*** Underwood: reproducing gender
Underwood uses statistical modeling to study how words associated with
gender change over time. The way that Underwood studies gender is by
associating adjectives with male/female and then making
predictions. Input leads to output. Underwood's method and approach
reify the structure of gender as a binary. He approaches gender as
something to be settled, reproduced and verified. 

*** Mandell: deconstructing/multiplying gender
Mandell criticizes the reduction of gender into the M/F binary, and
instead explores new taxonomies of gender by seeing how "genre" cuts
across gender and is part of its constitution. She is deconstructing
gender by analyzing genre. She argues that computers are ideal
for "breaking down the strength of the signal", and "computation
enables complexity". There is a potential for animation of data.

However, gender is actually more constrained than Mandell allows. It
constitutes subjectivity, not "highly imitable." We ought to look to
the ways that gender constitutes subjectivity.

*** computation & gender mutually enlightening
The computer enables complexity, but only under certain
constraints. As it turns out, computation, like gender, is also
constrained. Gender and computation can be mutually enlightening,
seeing constraint in form. Like SoRoland says, computation is good for
deconstructing, but we can also do this within a speculative mode,
like Ramsay/Drucker, starting with the error, and moving out. 


** deformance and preformance
This section poses text analysis, where textual data is cleaned,
structured, and normalized for computation, against the process of
performativity. Here, I am looking at how these two phenomena--gender
performance and text analysis--might coincide. I also review some DH
practices that engage elements of performativity, to highlight some
critical approaches that use this concept.

if gender is a series of acts, of repetitions, so is the process of
text analysis. 

*** NLTK
Look at the constrained nature of regularization -- briefly!

*** constraints of computational lit crit
McGann, Bode, Clement: how critics in English studies have approached
the constraints of computation into their work --- by harnessing
attention, abstraction, speculation.

*** queer performance
Now, look at gender as a constraint. In performative acts, the
repudiated terms (like 'queer') is what has the power to disrupt
existing significatory schemas. 

*** example of performative citation: Irigaray
Repetition displaces the logic of the signifying structure. 

*** preserving the unintelligible
the key to disrupting without doing violence (making
representationalist claims) is to never try to keep the unintelligible
outside, preserve it for continual resignification. 


** queer distant reading
An iterative method of distant reading attends to gender as an
iterative practice. We find ever expanding ways that gender is
characterized in /Orlando/. 

*** bode and butler parallel on language productivity
There is something fundamentally productive about language

*** reproducibility reduces data
Reproducibility reduces data into abstractable, "simple picture"
forms which perpetuate themselves.

*** shifting to the speculative
But we might use deformance and performance to harness reduction
toward speculative ends.

*** orlando close reading - gender as enabling constraint
For example, in Orlando, how does gender constrain other elements of
the text? Not in a way that hides/makes elements latent, but explores
what is on the surface? Close reading of gender in the novel finds
that it is related to language and the significatory power of
language. As Orlando settles into her gender, she is also able to find
the ability to mean, and the narrator can use experimental strategies
for telling the story.

*** TODO Man and Woman in Orlando
Qe are resignifying man and woman to mean differently in Orland by
creating a model of their significations.

*** TODO modeling gender distinctiveness
make a model of the way that the genders distinguish themselves in the
novel---imaginative elaborations of gender. 

*** TODO iterating over the code resignifies it
running the computation over and over again with new inputs is a way
of resignifying. Like a game of telephone.

*** TODO findings: new configurations of gender
what do we find out about gender here? how does this change the way we
approach this text?

*** TODO the power of the imagination
this process reveals the hidden "enabling structure" of the imagination

*** TODO conclusion: performative citation queers distant reading
insubordination through subservience, displacement through repetition

