* Chapter One Sketch

Revising the first draft. 

** the fantasy of the falsifiable 
Paranoid reading methods encourage a reproducible kind of criticism
that doesn't teach us anything novel about gender. How do we get out
of the cycle of reproducibility?

*** intro - computing queerness
The question: how do we deform a text to bring out new forms of
gender?

*** reading methods
Paranoid reading is about expressing something something hidden. This
reading style encourages reproducibility in criticism, turning 
reading into a mechanical practice that searches for what is hidden
rather than what is on the surface ofthe text.

*** DR begins in the falsifiable, toward reproducibility
Distant reading furthers this reproductive impulse in paranoid
reading. The paranoia to analyze vast swaths of literary history. 

Franco Moretti's scholarship has been invested in riding the critic of
subjectivity, in creating a reproducible (to the point of automating)
analysis. 

Reproducibility is so paranoid that even those who disagree with
quantification think of it as a benchmark (Da).

*** Ramsay and Drucker's speculative methods
There are critics doing speculative work--using computers as an
opportunity for critical analysis (Ramsay) and using them to engage
with data that is reduced or flattened (Drucker).

*** orientation makes the difference: falsifiable v speculative
The difference between the falsifiable and the speculative--the
falsifiable creates a reproducible critique.

*** reading for social categories SoRoland
Reproducibility blocks out other relation to text, especially aspects
that are slippery or marginalized, such as gender. There are attempts
to use DR for this kind of social analysis. SoRoland uses machine
learning to explore the constructedness of social
categories--whiteness as a category depends on blackness. They also
find material speculation in the form of an error, something
unexpected that yields a new reading. They conclude that machine is an
apt tool for studying race because it similarly uses highly
constructed and reductive methodologies.

*** Underwood: reproducing gender
Underwood uses statistical modeling to study how words associated with
gender change over time. The way that Underwood studies gender is by
associating adjectives with male/female and then making
predictions. Input leads to output. Underwood's method and approach
reify the structure of gender as a binary. He approaches gender as
something to be settled, reproduced and verified. 

*** Mandell: deconstructing/multiplying gender
Mandell criticizes the reduction of gender into the M/F binary, and
instead explores new taxonomies of gender by seeing how "genre" cuts
across gender and is part of its constitution. She is deconstructing
gender by analyzing genre. She argues that computers are ideal
for "breaking down the strength of the signal", and "computation
enables complexity". There is a potential for animation of data.

However, gender is actually more constrained than Mandell allows. It
constitutes subjectivity, not "highly imitable." We ought to look to
the ways that gender constitutes subjectivity.

*** computation & gender mutually enlightening
The computer enables complexity, but only under certain
constraints. As it turns out, computation, like gender, is also
constrained. Gender and computation can be mutually enlightening,
seeing constraint in form. Like SoRoland says, computation is good for
deconstructing, but we can also do this within a speculative mode,
like Ramsay/Drucker, starting with the error, and moving out. 


** deformance and preformance
This section poses text analysis, where textual data is cleaned,
structured, and normalized for computation, against the process of
performativity. Here, I am looking at how these two phenomena--gender
performance and text analysis--might coincide. I also review some DH
practices that engage elements of performativity, to highlight some
critical approaches that use this concept.

if gender is a series of acts, of repetitions, so is the process of
text analysis. 

*** NLTK
Look at the constrained nature of regularization -- briefly!

*** constraints of computational lit crit
McGann, Bode, Clement: how critics in English studies have approached
the constraints of computation into their work --- by harnessing
attention, abstraction, speculation.

*** queer performance
Now, look at gender as a constraint. In performative acts, the
repudiated terms (like 'queer') is what has the power to disrupt
existing significatory schemas. 

*** example of performative citation: Irigaray
Repetition displaces the logic of the signifying structure. 

*** preserving the unintelligible
the key to disrupting without doing violence (making
representationalist claims) is to never try to keep the unintelligible
outside, preserve it for continual resignification. 


** queer distant reading
An iterative method of distant reading attends to gender as an
iterative practice. We find ever expanding ways that gender is
characterized in /Orlando/. 

*** bode and butler parallel on language productivity
There is something fundamentally productive about language

*** reproducibility reduces data
Reproducibility reduces data into abstractable, "simple picture"
forms which perpetuate themselves.

*** shifting to the speculative
But we might use deformance and performance to harness reduction
toward speculative ends.

*** orlando close reading - gender as enabling constraint
For example, in Orlando, how does gender constrain other elements of
the text? Not in a way that hides/makes elements latent, but explores
what is on the surface? Close reading of gender in the novel finds
that it is related to language and the significatory power of
language. As Orlando settles into her gender, she is also able to find
the ability to mean, and the narrator can use experimental strategies
for telling the story.

*** TODO Man and Woman in Orlando
Qe are resignifying man and woman to mean differently in Orland by
creating a model of their significations.

*** TODO modeling gender distinctiveness
make a model of the way that the genders distinguish themselves in the
novel---imaginative elaborations of gender. 

*** TODO iterating over the code resignifies it
running the computation over and over again with new inputs is a way
of resignifying. Like a game of telephone.

*** TODO findings: new configurations of gender
what do we find out about gender here? how does this change the way we
approach this text?

*** TODO the power of the imagination
this process reveals the hidden "enabling structure" of the imagination

*** TODO conclusion: performative citation queers distant reading
insubordination through subservience, displacement through repetition


** networkx visualization

Using networkx to make a network graph of terms related to "woman" and
"man" in Orlando. 

The nodes are the terms, and the edges connect terms that have been
computed as ~similar_words()~. 

For the first level, create a list of words that are similar to
woman. Then, create a nested list of words that are similar to the
first level of similar words. Finally, add the nodes and edges for the
first level of similar words.

For the second level, create a dict which will take key:list of values
relationships as node & edge pairs.
- First, create a list of second level similar words, filtering out the
  term 'woman' (and any duplicates?  maybe later). 
- Second, create a dict that with the key 'woman' and a list of values
  that are first level similar words. Then, create more keys of each
  of the first level similar words. To those keys, add lists of words
  computed to be similar to them.

This worked. Now I'm going to 




** reading notes

*** orlando close reading & scholarship

**** Benzel, Kathryn N. 
"Reading readers in Virginia Woolf's Orlando: A Biography." Style,
Summer 1994, p. 169+.

Emphasizes the role of the reader in creating meaning in the
text. Woolf writes in a way that creates multiple levels of meaning,
inviting the reader's interpretation. 

The space break exemplifies this--creating literal space--an absence
of evidence--for the reader to speculate. An absence which the reader
has to fill in. 

**** Berman, Jessica. 
“Is the Trans in Transnational the Trans in Transgender?"
Modernism/modernity, vol. 24 no. 2, 2017, pp. 217-244. Project MUSE,
doi:10.1353/mod.2017.0019

The novel is a "trans text" (218) that interrogates the structures and
boundaries of nationality by challenging the concept of embodied
identity. "The transnational situation as also intrinsically
transgender" (218). Shows us the ways that bodies are marked and
categorized (221). 

**** Burns, Christy L.
“Re-Dressing Feminist Identities: Tensions between Essential and
Constructed Selves in Virginia Woolf's Orlando.” Twentieth Century
Literature, vol. 40, no. 3, 1994, pp. 342–364. JSTOR,
www.jstor.org/stable/441560.

The novel challenges "essentialized" concepts of femininity. Notions
of stable identity and biography are parodied. 

**** Caughie, Pamela. "Virginia Woolf's Double Discourse," 1989. 
 
Orlando is feminist for the way it precludes or obsures or refuses any
straightforward understanding of identity, sex, language. (41) 

"This sexual and textual indeterminacy links language and identity. As
the androgynous Orlando brings the question of sexual identity to the
fore, the obtrustive narrator brings the textual language to the fore
by intruding to discuss how own art" (42). 

"Double discourse" - "what appears to be an opposition between
positions is tolerated as difference without belligerance, as
different options on a spectrum of possibilities, not a /choice/ of
position but a /doubling/ of vision" (50). 

"for sex cannot be separated from text, the grammatical from the
gendered" (51). 
**** Cervetti, "In the Breeches, Petticoats, and Pleasures of Orlando"
(1996). 

Take orlando out of the details of Woolf's life, not a biography or a
love letter, but a feminist statement on gender, identity, and the
body (165). 

The criniline and its effect on her personality/behavior (the body):
"clothing alters the physical body" (169). 

**** Channing, Jill.
"Magical realism and gender variability in Orlando." Virginia Woolf
Miscellany, no. 67, 2005, p. 11+.

Orlando's narrative disruptions of realism and challenges against
normativity place its genre as magical realist. The sex change is the
key "irreducible element" where "there is no explanation" (11-12). 

**** de Gay, Jane. 
"Virginia Woolf's feminist historiography in Orlando." Critical
Survey, vol. 19, no. 1, 2007, p. 62+.

Novel enacts a "feminist historiography" which rejects victorian
patriarchal ideologies and metanarratives, instead making history
"live in the present" ... "for Woolf, the imagination provided the
only satisfactory medium for embracing the past" (71). 

**** Hovey, Jaime. 
“‘Kissing a Negress in the Dark’: Englishness as a Masquerade in
Woolf's Orlando.” /PMLA/, vol. 112, no. 3, 1997, pp. 393–404. JSTOR,
www.jstor.org/stable/462948.

Examines racial and gendered strictures of nationalism from a
privileged position of british white femininity.

Orlando is "an ambivalent articulation of English nationalism," how
that nationalism intersects with (and depents on) gender and race
(394). "Orlando critiques whiteness and heterosexuality ambivalently
and unevenly," using radialized and sexually transgresive subjects in
a way that "allows the protagonist to pass as respectible and
heterosexual" (398). Although Orlando challenges compulsory
heterosexuality of national identity, she does so by appropriating
otherness; uses femininity to hint at this playfully, taking advantage
of white femininity.

**** Knopp, Sherron E. 
“‘If I Saw You Would You Kiss Me?": Sapphism and the Subversiveness of
Virginia Woolf's Orlando.” /PMLA/, vol. 103, no. 1, 1988,
pp. 24–34. JSTOR, www.jstor.org/stable/462459.

Orlando is an extention of Woolf's love for Vita; representing Vita's
life, her loves and choices. Not sexually explicit but still sexual;
It is a coded love letter, but "the central relationship is between
Orlando and the biographer" (29). 

**** Micir, Melanie. 
"The queer timing of Orlando: a biography." Virginia Woolf Miscellany,
no. 82, 2012, p. 11+.

Reading Orlando as a love letter diminishes the other feminist and
queer readings, of queer time, the way that the novel disrupts
reproductive futurism. Critiques understanding of time as naturalized,
of the social scripts that govern timelines: "For Woolf, rupturing the
generic conventions of biography is a means of unseating(?) the
keystone of normativity, itself" ().

**** Sadjadi and Hojabli, "Gender, Performance, and Agency in Woolf's
/Orlando/," 2019.

Gender performativity emerges in "repeated rituals" with clothing and
social mores, "and the non-identity between sex and gender has been
emphasized" (21). 

**** Shaffer, Talia. "Posing Orlando," 1994.

Orlando working through performativity. Reading the photos.

"Orlando shows that the categories by which we locate ourselves are
perpetual performances, proliferating self reproductions" (26).

"The act of imitation [in the photos] does important ideological work,
for it constructs the present as an endless performance of a past that
it constructs as essentially empty of meaning" (26). Like Butler's
"masquerade" in /Gender Trouble/.
**** Smith, Victoria L. 
""Ransacking the Language": Finding the Missing Goods in Virginia
Woolf's Orlando."/.Journal of Modern Literature/, vol. 29 no. 4, 2006,
pp. 57-75. Project MUSE, doi:10.1353/jml.2006.0050

Orlando explores the limits of representation in narrative, reality,
identity, gender. "The fantastic content in the novel is directly
linked to the undecidability/impossibility of the form of the novel
and of the protagonist" (58). 

The novel "thematizes within the text how representation or, rather
more particularly, how literary language finds itself at a loss"
(68). "The text offers a recuperation of the object while bemoaning
the inadequacy of language" (68). Thus, the Sasha episode, the
description of nature, the indescribable love for Shel. 

The "doubleness of language... laments inadequacies while effectively
and fantastically achieving her ends" (69). 

**** Rado, Lisa. "Would the Real Virginia Woolf Please Stand
Up?" 1997. 

"Woolf appropriated the figure of the androgyne to generate the create
inspiration and artistic authority she felt she lacked" (150). One
result is a repression of her body, the female body. Orlando is
overlooked, not seen as serious, by scholarship (150-151).

"Attempting to employ an androgynous movel of the imagination involves
the painful and continuous repression of the body that ultimate
indicator of sexual difference" (157-8). The trances, sasha, shel
demonstrate this.

**** Rongstad, "The Representation of Gender in Woolf's
/Orlando/," 2012.

Gender performance in clothing and costumes, shows gender is
constructed (54). Personality is satble while gender shifts with
clothing. 


















*** Critiques of Butler

**** Geoff Boucher, "The Politics of Performativity":

Butler locates the "potential for subversion" "in a disembodied
intentionality that appears to stand outside of the
culturally-scripted subject positions that the individual occupies"
(115). 

"Gender performances... are subjectless procedures of a discursive
formation" (116). 

"Who (or what) decides 'how to repeat'? On what basis is the ecision
to subvert power made?" (119). 

"free-floating intentionality" (119).

In other writing on Althusser, however, Butler relies on a
pre-discursive desire for recognition, a "primary narcissism" (121)
which explains "where the intentionality that drives gender parody is
located" (121). 

**** Prosser, Jay. /Second Skins: The Body Narratives of
Trannsexuality/, Columbia U Press, 1998. 

Prosser's main argument is that queer theory, and gender
performativity in particular, has relied on transgender
identification in ways that elide the specificity of the trans body. 

"The question of how to represent the narratives of
transsexuality... to put into narrative its remarkable bodily
trajectories" (4). 

Goal is to read the materiality of transsexual body into narratives:
"To bring into view the mateirality of the body" (12).  

Critique of Butler and queer theory generally: Butler considers
"transitions as discursive but not explored in the bodiliness of
gendered crossings" (6). 

Butler's work considers gender, not sex, crossings, sex is "what was
beneath the favored terrain of performativity" (6). Transsexuality is
about embodiment. 
- "deliteralization of sex" - displaced from materiality to fantacized
  surface.
- on "Gender is Burning" in BTM: "According to Butler, transgressive
crossings can simultaneously reinscribe symbolic norms" (45). There is
a "metaphorization of the transsexual body" (55). If Venus got her sex
change, she would cease to be subversive" (49). This is a "critical
perversity" (49). 

Queer studies has depended on the transgender, has relied on
transgender desires (21).

Critique of Sedgwick: Theorizing about homosexuality relies on
cross-gendered identifications. In /Between Men/, normative sexuality
depends on male identification, and the avowal of such, with women as
objects of desire (22). 



Criticism:

"transsexuality's somatic transitions are spurred and enabled by the
formal transitions of narrative... Sex change is a plot... [Prosser's
book suggests transsexuality, with its extraordinary conjunctions of
body and narrative, as an identity story that transitions across the
body/language divide that currently stalls poststucturalist thought."

From Judith Halberstam's review: 

  Second Skins: The Body Narratives of Transsexuality. Jay Prosser
  Trans Liberation: Beyond Pink or Blue. Leslie Feinberg FTM:
  Female-to-Male Transsexuals in Society. Holly Devor Judith Halberstam
  /Signs: Journal of Women in Culture and Society/ 2000 26:1, 313-317

  "Jay Prosser delineates three major areas for discussion: first,
  the (mis)representation of the transgender body within queer theory
  as a privileged example of gender performativity" (313).

   "In a discussion of poststructuralist treatments of the transsexual
   body, Prosser vigorously contests the notion that the body is
   simply an inscribed surface or a discursive effect; such a reading
   of the body becomes particularly problematic for the transsexual
   whose desire for a sex change suggests a return to the literal, the
   real, the intractable flesh" (314).

   "In a dense and complex chapter on the work of Judith Butler,
   Prosser argues that her texts, central as they are to queer theory,
   simultaneously invoke and repudiate the transsexual body as a
   figure for gender crossing.  In Gender Trouble, Prosser argues, the
   transgender figures of the drag queen and the butch lesbian "come
   to appear the empirical subjects of gender performativity, their
   crossing illustrating both the inessentiality of sex and the
   nonoriginality of heterosexuality that was the book's thesis"
   (26). And yet, when Butler shifts her gaze from the transgender
   figure to the transsexual in /Bodies That Matter/, the transsexual
   represents a limit to performativity. Prosser claims that, while
   transgender and queer may be allied in Butler's work, transsexual
   and queer are most certainly in opposition.  Prosser's reading of
   Butler is crucial to the political stakes of his book.  In true
   deconstructive fashion, he aims his critical attention at Butler's
   mis- reading of a footnote in Freud about the relationship between
   body and ego. When she misreads /ego/ as /body/, Prosser claims,
   Butler dematerializes the body as a fantasy/fiction of the ego
   while Freud wanted to make the body the materialization of the
   psyche. This misreading sets up a series of priorities for queer
   performativity that are all at odds with transsexuality.
   Accordingly, Prosser understands queer theory to validate surface
   over depth, gender over sex, fiction over the real, the visual over
   the felt, the queer over the heterosexual. "In its representation
   of sex as a figurative effect of straight gender's constative
   performance," he claims, "/Gender Trouble/ cannot account for the
   transsexual desire for sexed embodiment S I G N S Autumn 2000 1 315
   /telos/" (33). I think Prosser's reading of Butler is compelling,
   and it is partic- ularly persuasive when Prosser tackles the most
   problematic chapter in /Bodies That Matter/, a close reading of the
   limits of performativity in relation to the transsexual drag queens
   in Jennie Livingston's film /Paris is Burning/." (314-315)
  
