**** chapter summary 
This dissertation looks at new ways of reading /queer bodies/ and
/queer experience/ within technological contexts. How do digital tools
and platforms change the way we interact with affect (associated with
queer experience and embodiment) within texts? What about the digital
allows us to activate /sensational/ reading experiences? In other
words, how does digital media interface with queerness?

This chapter proposes a reading methodology that leverages the
critic's relationship to the text to open possibilities for
interpretation and connections to the textual material. It explores
the ways that reading practices across two different fields (digital
humanities and queer theory) intertwine, and how this creates a new
method for reading queer narratives in digital contexts.

First, queerness is established as something that can only be touched
"at a distance." It is defined as a /desire for touch/ (digital
touch), a desire /that cannot be satisfied, redeemed, or
recovered/. This impulse to satisfy, redeem, or recover queerness is
observed in “paranoid” or “suspicious” reading practices, which seek
to answer or discover the “hidden” meaning within text. These
practices attempt to answer questions, but do so in a way that
constrains inquiry, because paranoia only delivers the results that
are /imaginable/ within current the knowledge structures. To avoid
reproducing these knowledge structures, we must look to strategies
that do not assume full connections, like /feeling backward/ and
/queer form/. We value abstraction, which is necessary for bringing
things into relation, and opacity, which keeps the unknowable nature
of queer experience and identity somewhat in tact. We look at
/Confessions of the Fox/, /These Waves of Girls/, /Borderlands/.

Second, we examine a similar impulse in DH---and a parallel across the
status of queerness and data, which cannot be captured in their raw
forms. The history of computing and media shows how tools were built
in ways that are not neutral, and we find DH practitioners doing work
that is critical of digital methods. Looking at the example of DH from
the position of queerness we see more clearly the necessity of
opacity, formalization, and abstraction as reading methods, and the
real danger of reproducibility and totalization, byproducts of
paranoia. We find parallels between queer critics and feminist DHers,
who are doing something similar; we interweave Saidiya Hartman and
Lauren Klein.

Third, we propose three values for queer DH, which is: novelty (the
performative), vantages (the visual), and provisionality (the
ontological). We see these examples in /voyant-tools/, /these waves
of girls/, and /the orlando project/(?). 

**** note to diss workshop:
My concerns: 
- the first paragraph are pretty dense, and the first one is a
whopper. I'm not sure how I can get into my subject without covering
all of this theoretical ground at the outset. I'm wondering most of
all if you're able to follow this argument, does it make sense to you,
and second of all, do you buy it? This work is striking out into a new
area, so I'm a little insecure about the plausibility of my project. 
- where are the terms/concepts that I need to explain further? This is
only a little into to the paragraph, so major concepts like "queer
subjectivity" and "data" will be elaborated at length later. But I
still want to know where you feel like I'm not giving enough
information. 
- are the close readings compelling? Do they make you want to read
more?


** Queerness, the Digital & Touch
No sooner have I written this than it strikes me as an avowal of the
imaginary; I should have uttered it as a dreamy speech which seeks to
know why I resist or I desire; unfortunately I am condemned to
assertion: we lack in French [and perhaps in every language] a
grammatical mode which would speak lightly [our conditional is much
too heavy], not intellectual doubt, but the value which strives to
convert itself into theory.
- Roland Barthes, /Roland Barthes by Roland Barthes/, 55.

*** touch intersects queer and digital, abstracting sense

If digital humanists and queer theorists are going to find some common
ground, they might start with /touch/. Touch is a means of interfacing
with the world, an encounter between subject and object, which signals
a problem of access[fn:1] that applies to both electronic media and
queer subjectivity. Associations between the digital[fn:2] and touch
expand from numerical computation (the ten "digits" of the hand) to
signify the haptic connections made through the intermediaries of
mice, keyboards, and touch screens. Crucially, these intermediaries
demonstrate that humans engage with electronic data at a remove,
through layers of computation, abstraction, formalization[fn:3]. Matt
Kirschenbaum explains that “[d]igital inscription is a form of
displacement. Its fundamental characteristic is to remove digital
objects from the channels of direct human intervention” (/Mechanisms:
New Media and the Forensic Imagination/ 86). Moving to the context of
queerness, touch similarly points to a problem of access. Like digital
media, queer subjectivity has been theorized as legible by and through
the framework of formalization--specifically, through a
heteronormative power structure that delineates the queer subject for
the purpose of reconsolidation. As queer theorists like Judith Butler
have shown, subjectivity is constructed through discursive and
performative processes:[fn:4] "Where there is an 'I' who utters or
speaks and thereby produces an effect in discourse, there is first a
discourse which precedes and enables that 'I' and forms in language
the constraining trajectory of its will" ("Critically Queer" 18). At
the intersection of the digital and queerness, then, the phenomenon of
touch indexes our grasp of the subject as a construct, a
formalization.

This examination harnesses the formal qualities of both queer
subjectivity and digital media. It supposes that the parallels between
data and queer subjectivity might coalesce into an approach toward
reading, which engages queer subject matter and digital media through
the matrix of touch. Touch is an approach toward reading that provides
alternative possibilities and pathways for sensation. My reading will
demonstrate how touch offers a means of knowing based on feeling,
which works by abstracting sensation beyond the readily sensible. This
process of abstraction compensates for the constructed nature of queer
subjectivity by exploring queerness as emergent[fn:5] within digital
media. My readings will surface new forms, /queer forms/, that evoke
digital materialities and aesthetics as formalizations of the
immaterial.[fn:6]

*** /Waves/: queerness frustrates closure, eludes touch

Two close-readings will serve to demonstrate that queerness is
concerned with touch, and more precisely, with /a desire for touch/
that is continually frustrated. Though one is from a digital source
and the other from print, both examples demonstrate a self-conscious
and critical stance about its own form, a key component of what I will
later elaborate as /queer form/.

The first text, entitled /These Waves of Girls/ by Caitlin Fisher,
figures touching as desire quite literally, with touch being the means
of pursuing desire. This "hypertext," an electronic text format that
links "nodes" or pages within an associative structure, enacts desire
by tempting the reader to click through the various episodes of the
story in order to achieve narrative closure. /Waves/ is an
autobiographical account of the author's sexual coming-of-age, which
unfolds in a series of interconnected vignettes that recount Fisher's
adolescent experiences with men and women. Despite winning the 2001
Electronic Literature Organization Award, this "hypertext novella"
draws criticism for a formal structure that complicates a
straightforward reading experience. Through the profusion of
hyperlinks, which connect one node to the next in ways that disrupt
temporal and causal relations, this hypertext frustrates the reader’s
desire for narrative coherence. One critic argues that the
use of hyperlinks “present[s] a baffling range of choices for movement
which actually led to a stifling of movement altogether” (Pope,
“Significance”).

!["DARE" > "I liked girls..." > "the lover" > "Only one of us is
15..." > "Jerk off…"](../qt_writings/one/videos/erotic.gif)

The disorienting feeling of reading this text is an effect of its
form.  The conventional reading practice of turning the pages in a
codex dissolves in the distracting and technical complexity of a
narrative that requires effort to traverse. Episodes do not have a
discernible chronology or progression, and clicking on the links
between nodes disrupts any sense of coherence. While the desire for
narrative closure is continually frustrated by the work's form, in
another sense, this fragmentary structure exactly constitutes its
appeal, for it compels the reader to chase an elusive understanding of
sexuality, as the text continually defies the reader’s expectations
about the narrator's motives. In one repeatedly linked node, aptly
titled “erotic,” the words “and it was the most erotic year of my
life” march across the screen like ticker tape (“And it was...”). This
node is accessed through two different sources, both featuring sexual
episodes between the narrator and men. In a novella that largely
consists of stories about the narrator’s sexual history and fantasies
with other women, these nodes are unusual, checking the reader’s
expectations about the narrator’s identity and desire. The
accumulation of seemingly capricious sexual episodes disrupts the
relationship between cause and effect, scrambling the reader's sense
of direction across the text. Other moments in the text create a
similar dissonance from the associations the narrator's motives. One
occurs in the last node of the “beam routine” episode, when the
narrator is about to perform gymnastics to placate a man that she
brought home. The link reads “I don’t want to have sex,” and it leads
the reader back to a familiar episode about "Jennie Winchester":

#+BEGIN_QUOTE
I’m in bed with Jennie Winchester and I realize she wants me to undo
her pants. She needs to be home by 11:00 and needs to leave my place
by 10:45. I’m kissing her but opening my eyes at intervals to catch
the clock. At exactly 10:43 I unbutton her Levis and shove my hand
inside, barely undoing the zipper. “I’m in bed...”
#+END_QUOTE

As the reader familiarizes herself with the events of the story, she
is always losing context. Now the reader experiences this familiar
node in a new way that casts its former meaning into doubt. What is
the connection between this episode and the phrase, "I don't want to
have sex"? Why is the narrator watching the clock? Because the
character's desires have been muddled by the unpredictable connections
between episodes, what at first seems straightforward now appears to
support alternate readings. The reader’s confusion in navigating
through /Waves/, in re-interpreting fragments that had been previously
integrated, reinforces queer identity as something elusive, a
condition that is not fully intelligible. Clicking (/touching/) her
way through the narrative, the reader is repeatedly reminded of her
removal from the distance from the narrator.

*** /Confessions/: queerness and the denial of touch
For queer subjects, touch and the desire for touching has always been
a frought experience, which can in turn activates a sensorium of
affects. In my second example, /The Confessions of the Fox/ by Jordy
Rosenberg, the main character exhibits a troubled relationship to
touch which partly constitutes his subjectivity. Beginning in
eighteenth century London, this story follows Jack Sheppard, a young
transgender male as a wily thief amid a group of "rogues."  Before the
official pathologization of nonnormative desires and identities,
Sheppard struggles to articulate his difference, what he calls his
"/Something/:" "This something that set him apart from other coves
[men]. Something that had caus'd him to dress his own chest in taut
bandages... pinching at his ribs, throttling his every Breath to a
forced shallow bird-sipping of the air" (33). The hesitance toward
self-identification extends from the main character to the narrative's
genre, which unfolds as historical fiction overlaid with contemporary
fictional memoir. Sheppard's story is discovered in the present day
United States by Dr. Voth, a rueful academic who is also
transgender. Voth, who immediately recognizes the historical
significance of Sheppard's manuscript, proceeds to annotate the
document with relevant references and increasingly, his own tangential
anecdotes. In one scene of the manuscript, Sheppard is having a
romantic moment when Voth relates his own episode about a former
lover:

#+BEGIN_QUOTE
She opened her legs a bit, twitched them open, really. I caught my
breath, audibly.

"Oh my god," she said, "you're such a lesbian."

She didn't mean it cruelly. And she didn't mean that I wasn't passing
as a cis-man, either. Although, since according to her we'd fucked the
night before, she knew exactly how un-cis I was. 

She meant that she saw something about the quality of my desire: that
I could feel her even before I touched her. And that this was part of
what it meant to be---or to have been, before my tits became property
of the California Municipal Waste Department---a lesbian. That a woman
moving in your line of sight could have an effect that was total,
atmospheric. That you could be hesitant, incapable, and not
particularly interested in establishing a line between touching and
seeing. That you would indulge a dead love, dead in the eyes of the
world, and valueless. A love that choked and burdened the mind, that
might even be the very foundation of melancholy and despair. But, oh
Reader, looking at a woman you really get a feel for the way that fire
is a phenomenon of touch. And my point is, if you have every been a
lesbian, you will not even have to touch a woman to know that. 169
#+END_QUOTE

Here, desire is characterised not by the search for satisfaction, or
the success of establishing contact, but by the sensual fullness of a
lack. The experience of desire, of craving, wanting, needing to touch
the desired object stimulates the imagination and amplifies sensations
that would otherwise be replaced with more "direct" modes of
contact. The lover's reference to Dr. Voth as "such a lesbian" brings
this distinction about physical and imaginary contact to the realm of
identity, reinforcing the interplay between imaginary and real when it
comes to touch. Though Dr. Voth is not a lesbian, the term fits
because it signals not a gender or sexual identity but a sensuality
that is more concerned with the potential of connection rather than
verifiable contact. The appellation hinges on the role of the
imagination in activating certain sensations--"total,"
"atmospheric"---that supercede those in the actualized
world. Therefore, Dr. Voth's visual fancy takes on connotations of the
fanciful. But this does not mean the sensations resulting from this
desire are any less palpable. On the contrary, such a desire maximizes
physical experience: it is a desire for something that, because it
cannot or will not be fulfilled, amplifies the fullness of that
desire. This mode of desiring is what characterizes queerness in the
text. Here, touch, or the lack of touch, defines a peculiarly queer
subjectivity.

In both /Waves/ and /Confessions/, queerness is constituted by a
troubled relationship to touch, reinforcing queerness as something
that cannot be grasped or is beyond grasp. In /Waves/, touch is the
continually frustrated means for traversing the narrative: clicking
her way though the nodes, the reader fails to grasp the arc of the
story or the intentions of the narrator. In /Confessions/, denying
touch casts queer identity as something beyond
categorization. Maintaining the gap between sight and touch stimulates
the senses beyond what's possible within normative expectations of
sexual desire. This condition of inaccessibility gestures at an affect
of suspension or displacement that is central to the experience of
queerness, an affect that I call the "untouchable," which we now
explore in depth.

*  Footnotes

[fn:1] By "access" I mean knowledge, the notion that we can
exhaustively know the subject (queer subjects & technology) beyond a
cultural construction.

[fn:2] The root of the word digital, "digitus," originally comes from
the Latin word for finger or toe, and in electronic media, it refers
to a counting system based on ten digits. Digital computation runs on
numerical data called "bytes" which can take a value between 0 and
255, although computer language, at the most rudimentary level, is
based on "bits," a binary counting system that represents the polarity
(North or South, translated into 0 or 1) of magnetic traces on a hard
drive. (and include quote from Sadie Plant's /Zeroes and Ones/)

[fn:3] [to be expanded in depth later in the chapter] My approach
toward data emphasizes the different levels of digital materiality,
what Matt Kirschenbaum calls "formal" and "forensic" levels of
materiality. The formal level is what can be seen and interacted with
on a computer screen, such as the interface, icons, and windows. The
forensic is the level of the nanoscale, what cannot be seen, which is
the hard encoding and electronic activity in drives, circuits, and
chips (Kirschenbaum, /Mechanisms: New Media and the Forensic
Imagination/ 11).

[fn:4] [to be expanded in depth later in the chapter] My understanding
of Queer Subjectivity draws from Michel Foucault's theorizations of
the constructedness of sexuality and Judith Butler's points about the
incompleteness of subject formation. According to Foucault, "Sexuality
must not be thought of as a kind of natural given which power tries to
hold in check, or an an obscure domain which knowledge tries to
gradually uncover. It is the name that can be given to a historical
construct: not a furtive reality that is difficult to grasp, but a
great surface network in which the stimulation of bodies, the
intensification of pleasures, the incitement to discourse, the
formation of special knowledges, the strengthening of controls and
resistances, are linked to one another" (/History of Sexuality,
Vol. 1/ 105-106). Butler asserts that "the impossibility of a full
recognition, that is, of ever fully inhabiting the name by which one's
social identity is inaugurated and mobilized, implies the instability
and incompleteness of subject-formation" ("Critically Queer,"
18). [this note needs to work harder to link Foucault & Butler]

[fn:5] [this footnote needs to be integrated to the main text?] José
Esteban Muñoz defines queerness as "a structuring and educated mode of
desiring that allows us to see and feel beyond the quagmire of the
present... Queerness is a longing that propels us onward, beyond
romances of the negative and toiling in the present. Queerness is that
thing that lets us feel that this world is not enough, that indeed
something is missing" (/Cruising Utopia/ 1). Muñoz here indicates an
imminant quality about queerness, which is situated within the
present. Because queerness is "not yet here," it calls for something
else, for something that "allows us to see and feel beyond the
quagmire of the present," opening a space for emergent affects. In
other words, queerness expands a sensibility of feeling to include
sensations beyond the immediate, the readily sensible.

[fn:6] Data, at the fundamental level, is a series of optically
invisible (but very physical) traces on a magnetized surface, which
assume virtual form on the screen. Kirschenbaum explains that "a
digital environment is an abstract projection supported and sustained
by its capacity to propagate the illusion (or call it a working model)
of immaterial behavior: identification without ambiguity, transmission
without loss, repetition without originality" (/Mechanisms: New Media
and the Forensic Imagination/, 11).
