* Propectus: Queer Tools
Filipa Calado

** The Rise of Queer DH
Since the popularization of "distant reading," there has been much
debate about what digital tools can do for the humanities, and
literary studies in particular.[fn:1] Although many DH practitioners
have been careful to situate their methodologies within the context of
humanistic study, there persists an idea that digital methods ought to
verify, correct, or establish facts about literature and literary
history, similarly to the social sciences.[fn:2] However, within the
broad field of "Digital Humanities," an emerging /Queer/ DH is
upending this assumption. This recent work interrogates some of the
ways that “queerness” might address DH research practices, and tend to
center around speculative or critical making projects that emphasize
the constructed nature of technical objects and promote play. For
example, Zach Blas and micha cárdenas’s /transCoder/, a “queer
programming anti-language,” features programming functions inspired by
Judith Butler like the “destabilizationLoop()” that “breaks apart any
process that acts as a continuously iterating power” (“Queer
Technologies / transCoder”). Another project that probes the
possibilities of queerness and DH is “Queer OS: A User’s Manual,”
which reimagines how various components of an operating system, such
as interfaces, applications, and memory function unexpectedly within
an ethos of queerness.

** Experimentation, Exploration, Error

Although the speculative nature of such projects troubles the
positivist tendencies of mainstream DH, allowing critics to imagine
the emergence of queered technological contexts where functionality
and productivity are not taken for granted, it overlooks the ways in
which current technological systems and tools already contain elements
of queerness. To this end, my project explores how current digital
tools for editing, reading, and archiving resist the impulse for
fixity, certainty, and verification. Instead, I emphasize how these
tools promote experimentation and exploration, and revel in the
inconsistencies, errors, and idiosyncrasies of close reading. My
analysis looks to the ways that both human minds and computers are
prone to making mistakes and misreadings, and takes these ironies as
points of inspiration for re-imagining human-computer interactions. In
reviewing various digital methods that engage reading and interpretive
processes, such as electronic editing, social reading tools, and
archival practices, I’m interested in how the logics and limitations
of technology reflect the complexities of identity and engage
questions about queer embodied experience and subjectivity. Here, I
focus on life writing and compositional forms, particularly memoirs,
journals, and manuscripts by queer authors, to highlight the
construction and legibility of queer embodiment and subjecthood. How
do digital tools allow us to “encode” or “decode” queerness in texts
that trouble the stability of a writing self?
 
** Touching without Touching
At stake throughout my project is the critic's relation to the object
of study. Some DH practitioners have already proposed useful models
for reading that emphasize the critic's role in analysis, such as
"algorithmic criticism," "deformative criticism," and "speculative
computing."[fn:3] These approaches are careful to temper the common
reductions and rhetoric of "distant reading" by being explicit about
the constructed nature of data and the implicatedness of the literary
critic in analysis. In parallel to these developments, Queer Theory
has also been exploring new relations to textual objects, resisting
"suspicious" or "paranoid" reading practices which attempt to uncover
hidden or latent "truths" about queer experience in favor of affective
orientations.[fn:4] Bringing this attitude in Queer Theory to bear on
digital methodologies, my project experiments with notions of "touch"
and more playful and experimental modes of reading that resist the
temptations to fix knowledge about queer subjects.[fn:5] The mode of
"touch" combines lightness with depth---although "touch" is soft, it
can leave a mark or impression between critic and object of
study. Toward a reading practice that prevents the overidentification
of queer subjects, "touch" demonstrates what DH what might learn from
queer models of relationality while also animating the haptic and
physical experience of engaging with texts in electronic formats where
users must swipe, drag, and click their way. This reading method aims
to expose what happens when we use digital media to engage with queer
subjects.

** Life Writing by Queer Authors
I mobilize the term "queer" as both method and matter, denoting not
only a reading practice but also a textual corpus that features queer
authors and subjects. This textual corpus in particular adds
compositional forms to the larger category of what Sidonie Smith and
Julia Watson call "life writing."[fn:6] Smith and Watson's capacious
term, "life writing," which centers on a writing self, leaves out
drafting and other more raw and experimental modes of writing that
interrogate selfhood by posing it as an iterative practice. Therefore,
to various examples of life writing, such as autobiography, memoir,
fictionalized autobiography and autofiction, I include compositional
forms of writing like journals, diaries, and manuscripts. Here, I
focus on the way that these texts demonstrate a writing self or an
experimental style that reflects the fragmentary and accumulative
nature of subjecthood and provides a key into reading affective,
embodied experience. For example, my interest in the manuscripts and
journals of Oscar Wilde, Virginia Woolf, and Katherine Mansfield
highlights how compositional writing continually calls into question
the construction of embodiment and subjectivity. These concerns with
subjectivity extend into fictional works, such as Woolf's /Orlando/
and Djuna Barnes's /Nightwood/, whose formal experiments create a
fulcrum around which the false distinctions between fantasy and
reality revolve.[fn:7] These moves culminate in 21st-century
"autofiction" by Alison Bechdel, Jordy Rosenberg, Yiyun Li, and
Carment Maria Machado, which trouble the line between fiction and
biography while posing problems for keeping subjectivity both legible
and dynamic. An recurring concern throughout this analysis is the
difficulty of using digital tools to "decode" or "encode" queer
embodied experience.

** Cyborgs

My project adopts the cyborg as a figure for queer embodiment that is
assembled yet unseamed. Since Judith Butler's seminal troubling of
gender in the early 90s, incoherences between sex, gender, and
sexuality have constituted queer subjectivity. My project explores how
these incoherences reverberate across neuroscientific and new media
technical contexts in order to inform human-computer computer
interactions. First, I embark on studies of embodied cognition,
examining how neuroscientific discourses situate perceptual processes
(such as reading) in the body. Within these discourses, I focus on
feminist accounts that center bodily difference in understanding
cognition. Second, I delve into new media studies, particularly media
archaeology, to examine the unexpected idiosyncracies of digital
media. Here, I explore how the physical processes of inscription,
processing, and storage disrupt our assumptions about digital
immateriality, what Matt Kirschenbaum calls "screen essentialism."
Situating consciousness and computation as /material/ allows me to
re-imagine Donna Haraway's cyborg as operating across
biological-mechanical registers, opening up the illuminating parallels
between the body and computer, for example, between neurons and
transistors, memory and RAM. Interrogating the ways that certain
perceptual and computational processes work across biological and
mechanical levels sparks my thinking about human-machine
interactions. Here, I speculate on how language marks us, triggers our
emotions and memories to create aesthetic, affective reading
experiences.

** Toward Disability

My emphasis on queer relationality as a critical method for working
with digital media naturally leads me to theorizing about the
unexpected interactions humans have with their world. Here, I'm
interested in the potential for queer digital tools to facilitate
aesthetic encounters between reader and object. By opening up the way
we use the digital tools to considertations about our embodied
experience with them, we expand our understanding about human-compuer
interactions beyond traditional knowledge structures and discipline
boundaries. To fully explore models of knowing based on feeling, I
turn to new media, new materialism, and disability studies. I find
that thinkers as ranged as Steven Shaviro, Jane Bennett, John Durham
Peters, and Mark Hansen, offer models that prioritize aesthetic
experience over epistemology. For example, Steven Shaviro, who draws
from Alfred N. Whitehead's concept of "prehension," emphasizes what he
calls "non-correlational sentience" about objects over our actual
knowledge about them. Moving to disability studies, Victoria
Pitts-Taylor draws the concept of "mis/fitting" into models of
embodied cognition in order to present disability as a temporally and
spatially specific attempt at connection (or "fitting") between human
body and its surrounding world. These models concretize the
interactions between man and machine as an aesthetic and sensory
encounter, which inflects the way that I approach the "efficacy" of
digital tools. For example, how can electronic editing schemas
facilitate the encoding of data about embodied experience? How might
digital annotation tools visualize social reading as affective? And,
finally, how do archival digitization efforts animate the past?

** Chapter Descriptions
*** How do these chapters fit together? --- overview of ideas
Each chapter of this project takes up a different aspect of digital
media to explore a facet of this central question: How do our current
digital tools facilitate queer encounters with literature? This
examination addresses various digital tools across reading, editing,
teaching, and archiving, to push against the idea that these methods
are somehow more objective, rational, or verifiable than traditional
practices. My first chapter asks what digital methods have to learn
from Queer Theory, and lays out a model of relationality that guides
the rest of my project. My second chapter turns to a popular editing
standard for text encoding, and posits how this method might mark
elusive subjectivities and embodiments. My third chapter describes a
classroom experiment with social annotation, particularly with a
digital tool that I developed specifically for teaching, and explains
how this tool prioritizes affective and immediate responses to reading
in order to elude attempts to track and quantify student
performance. My final chapter explores how archival practices subvert
existing structures of knowledge and access, and point to the ways
that digital media engages theories of queer temporality. Though these
chapters range over a variety of tools and areas of study, they are
constrained by a investment to seek out queerness with our existing
digital methodologies.

*** Reading: How might we read by touching?
The first chapter, "Reading: 'Touching without Touching,'" lays out
what Digital Humanities methodologies might learn from queer
theory. This chapter looks at specific reading practices by Eve
Kosofsky Sedgwick and Heather Love, which question the proper
relationship of the critic to the object of study. Sedgwick's ideas
about "touching/feeling" and Love's notion of "touching without
touching" pose queer modes of relationality that do not presume full
connections as prerequisite for analysis. This chapter engages these
techniques with various critical methods from the Digital Humanities,
including distant, surface, and post-critical reading, and
deformative, algorithmic, and speculative criticism. I pay particular
attention to how digital formats and interfaces might facilitate queer
critical methods, and I speculate on the intimate process of engaging
with literature on a computer, where users can manipulate and
transform text in virtually infinite and unique ways. Comparing three
very different kinds of digital projects based on text manipulation,
including the text analysis web application /Voyant-Tools/, the text
encoding archive, /Women Writers Online/, and a hypertext novella by
Caitlin Fischer, /These Waves of Girls/, I explain how these tools
work alongside the reader’s intuition, in what Jerome McGann calls a
“prosthetic extension of that demand for critical reflection,” by
which the reader is able to feel her way through the text (18). In
particular, I find that the haptic and exploratory activity of working
with these tools enlivens the reading process by allowing the reader
to play, experiment, and imagine new connections to the textual
object.

*** Editing: How might we encode embodiment?
The second chapter, "Editing: Encoding Embodiment," examines the
instability of queer identity and subjecthood against the limitations
and fixities of computational methods. How do the abstractions and
structures of digital formats register the complexities of embodied
experience and identity? To answer this question, I examine how one
might edit, or "encodoe" manuscripts, diaries, and autofiction that
display queer struggles with subjecthood. First, I explore TEI (the
Text Encoding Initiative), an encoding standard or "markup language"
for electronic editing, and its method for handling complex textual
data. Here, I demonstrate how TEI might be used to mark up Oscar
Wilde's manuscript of /The Picture of Dorian Gray/, which was
repeatedly edited by Wilde to minimize homoerotic content. How might
editors approach the rigidity of encoding standards in order to
address embodied experience present in tonal shifts, elisions, and
revisions over time?  Throughout my conversation about /Dorian Gray/,
I bring up examples of modernist diaries by Virginia Woolf and
Katherine Mansfield to proliferate the alternative figurations of
queer selfhood. Here, I also touch on similar figurations in an
example of 21st-century autofiction by Yiyun Li, /Dear Friend, from my
Life I Write to you in your Life/, to show how this problem endures
over time and subject identities. This examination finds that queer
experience is never fully legible, despite our tools.

*** Teaching: How might we teach with emotions?
The third chapter, "Teaching: Social Annotation," questions how
digital annotation tools might facilitate embodied interactions with
text. To begin to answer this question, I examine biological processes
of perception and analogies between man and machine, taking up the
figure of the cyborg. This figure of human-computer engagement allows
me to address the unexpected affinities that emerge in the interface
between reader and text. Taking social annotation as a test case, I
examine a particular digital annotation tool that I've modified for
purposes of marking prediscursive responses to reading, by which I
mean the reactions and sensations that occur prior to articulated
response. I created this annotation tool to resist the tendency of
other annotation tools (and educational technology solutions more
generally) to track, quantify, and assess student performance. Instead
of having users type their comments, this tool offers a red, blue, and
yellow highlighter (primary colors). Due to their very low opacities,
colors can be layered, one over another, to create secondary and
tertiary color combinations. When used with a social reading context,
I imagine that the color layerings will create a "heatmap" of the
text. This pedagogical experiment hypothesizes that alternative
reactions to reading will materialize in the color mixtures, in the
alchemy of dissonances that layering creates. I run experiments in
reading Virginia Woolf's /Orlando/, Djuna Barnes’s /Nightwood/, and
Roland Barthes's /Roland Barthes by Roland Barthes/. I examine how
annotation might harness cognition, affect, and embodiment as formal
strategies in these texts.

*** Archiving: How might we animate the past?
The fourth chapter, "Archiving: Feeling Backward / Feed Forward,"
explores queer temporality's connection to new media in order to
disrupt typical notions of the archive. How do displacements across
our understanding of media, perception, and time affect our experience
with literary objects in the archive? How might new media animate the
past? Here, various displacements between our encounter with digitized
literary and cultural objects and their functionality offer a model
for thinking about our interaction with these objects. I embark on a
deep reading of digital media, exploring the central displacement
between what we see on the screen and what is inscribed in the
computer’s hardware—--what Matt Kirschenbaum calls the levels of
formal and forensic materiality. I consider these levels of digital
materiality alongside theories of temporality and perception from
queer theory and new media studies. What does queerness as
anticipatory (Jose Munoz's "not here yet") or backward looking
(Heather Love's "feeling backward") have in common with ideas about
new media changing our perceptual experience of the world (Mark
Hansen's "feed forward")?[fn:8] My deep reading of computer hardware
and software evokes the temporal and sensory displacements from queer
theory to offer possibilities for animating the archive. This chapter
considers a community archive, the /Lesbian Herstory Archive/ in
Brooklyn, New York, alongside 21st-century autofiction with archival
themes by Alison Bechdel, Carmen Maria Machado, and Jordy
Rosenberg. How do community archival practices and digitization
efforts change our assumptions about what counts as "archival"? My
examination of 21st-century autofiction refigures the ideas of
archival preservation and animation in print, demonstrating how these
authors write through enduring (im)possibilities of writing the self.


*** TODO Read Sharpe, Kazanjian, Venus in Two Acts

* Footnotes

[fn:1] These theorists take different stances on whether DH tools
facilitate a more objective, or what Franco Moretti calls
“falsifiable," method of criticism, where graphs and other
visualizations might answer questions about literary history and form,
or a more “speculative” mode, championed by Johanna Drucker, who
purposefully skews graphical metrics in order to reflect the ambiguity
and partiality of the data they represent. In between these two
extremes, there are theorists like Andrew Piper and Ted Underwood, who
temper the reductions and rhetoric of "distant reading" by
incorporating close readings and explanations, or Catherine D'Ignazio
and Lauren Klein, whose attempts to recover emotion and emobodiment
are a direct indictment on data science as an exclusionary discipline.

[fn:2] Recently, Nan Z. Da deems Computational Literary Studies (CLS)
ineffective when her own experiments fail to reproduce or verify the
results of her colleagues. Her emphasis on the “reproducible” in CLS
extends Moretti’s call from 1983 for a “falsifiable criticism”: both
advocate for a methodology that is as reliable and verifiable as the
social sciences.

[fn:3] See Stephen Ramsay, /Reading Machines: Toward an Algorithmic
Criticism/, 2011, Jerome McGann and Lisa Samuels, "Deformance and
Interpretation," in /Radiant Textuality: Literary Studies after the
World Wide Web/, 2001, Johanna Drucker, /SpecLab: Digital Aesthetics
and Projects in Speculative Computing/, 2009.

[fn:4] According to critics like Eve Sedgwick, Heather Love, and Rita
Felski, the logic of exposure closes off alternative possibilities for
responding to texts.

[fn:5] Both Eve Sedgwick and Heather Love explicitly discuss "touch"
as an affective orientation for critical analysis: Sedgwick for the
purpose of promoting spatial over teleological relations ("beside"
rather than "beneath") and Love..... prefers to dwell in the painful
past, giving inconsolable characters full reign over their own
darkness.

[fn:6] Sidonie Smith and Julia Watson define "life writing" as "a
general term for writing that takes a life, one’s own or another’s, as
its subject. Such writing can be biographical, novelistic, historical,
or explicitly self-referential and therefore autobiographical" (4).

[fn:7] Barnes's /Nightwood/ is not traditionally considered to be a
fictionalized biography, though it is widely accepted as a roman à
clef in which Barnes herself takes the character of Nora Flood and her
former lover, Themla Ellen Wood, is Robin Vote.

[fn:8] Mark Hansen's concept of "feed-forward" considers how new media
expands perceptual reaches across new environments while
marginalizing the direct apprehension of objects. 
