* three

** chapter overview
This paper juxtaposes two unlikely texts--an early hypertext work from
1999, and a science fiction novel from 1987--to unpack the role of
“media” across physiological and technological systems. The early
hypertext work, /skinonskinonskin/, written collectively by the
artist-couple known as Entropy8Zuper!, explores
electronically-mediated desire through a series of digital love poems
that combine hypertext, audio, and Flash media technology. Moving from
digital to embodied desire, the science fiction novel, Dawn by Octavia
Butler, poses a post-apocalyptic scenario where humans find themselves
coerced into sex and procreation with extraterrestrial colonizers. In
these couplings, sexual contact is routed through an alien
intermediary, whose ability to plug directly into the human brain’s
pleasure centers intensifies their sexual instincts into all but
irresistible compulsions. Though Butler’s novel and skinonskinonskin
present vastly different narrative worlds and physical formats, I’m
interested in how both texts trouble the boundary between materiality
and abstraction, in one case technological, through computer hardware
and software, and in another physiological, through nervous systems
and brain chemistry.

My analysis reads for sensuality across medial environments in each
text. In Butler’s novel, I examine how human flesh--the traditional
site for sexual contact between two partners--is bypassed for direct
neural stimulation facilitated by an alien intermediary. Because this
direct neural connection scrambles traditional distinctions between
the body and mind, during the sex act, the humans have trouble
differentiating their embodied feelings from their cognitive
interpretations. The alien colonizers, who describe themselves as
“gene traders,” exploit this human susceptibility to sexual pleasure
in order to interbreed with them. By bypassing the flesh, this method
of intercourse dissolves the binary between self and other--the
foundation for possessive individualism--as well as sense and
thought. Drawing from thinkers in Chicanx Studies and Black Feminist
Studies, I argue that this method creates an ethics based on pleasure
rather than choice or consent.

To better understand the compulsions of pleasure and the flesh, I
engage Black Feminist Studies’ theorizing on the flesh. According to
critics like Hortense Spillers, C. Riley Snorton, and Amber Jamilla
Musser, the systematic reduction of the Black body to the physical
flesh, a process that began during the violences and atrocities of the
Middle Passage, creates an opportunity for rethinking the political
potential of pleasure and eroticism. In my analysis, this concept of
the flesh becomes a ground for understanding how physical registers
interact with symbolic ones. Here, I examine how the concept of the
Pornotrope, that is the reduction of body to flesh, of the conceptual
(body) to the material (flesh), creates a ground for new theorizations
of meaning and materiality. Specifically, this reduction of Body to
Flesh offers a model of resistance to racial exploitation that
reinforces sensuality and pleasure.

Turning to /skinonskinonskin/, I examine the hardware and software
formats that facilitate the display and preservation of this work,
tracing the complicated stack of technologies, which include internet
networks, web tools, Flash media, and more recently, a computer system
Emulator. Borrowing from Media Archaeology and Network Studies, I take
a close look at what Matt Kirschenbaum describes as the “formal” level
of materiality, or the effects on the screen, moving down the layers
of abstraction, through the compiled code of Flash media, into the
level of hardware, what he calls the “forensic materiality,” of the
internet network. My goal is to examine the material qualities of the
medium--be it technical or physiological--for the ways it offers a
kind of capacious mode for theorizing new forms of ethical relations.


** sex
*** section overview
These sections examine human vs Oankali social structures to read the
priortization of sensuality and feeling as a basis for more ethical
relationship. While human nature struggles within the "contradition"
of hierarchy and intelligence, the Oankali harness thier physiological
ability to bypass flesh for direct neural connections that enable
collectivityñ. The Oankali offer a model of ethics based on mutual
feeling, rather than choice or consent. Interestingly (and a point I
will pick up in my "skins" section), in the process of having "neural"
sex with each other through the aliens, the humans begin to blend
cognitive processes with their sensual experiences. The blending of
thought and feeling shows a collision of registers, which will be
useful for my media archaeological reading of the stack of
technologies in the hypertext peice, /skinonskinonskin/.

The crucial point of this section occurs in my close-reading of the
scene when Lilith first meets the aliens, and her experience of
xenophobia, which is crytallized in her use of the comparison to
"Medusa". I draw from Chicana Studies to explain how the comparison to
Medusa expresses a fear of the unknown through the frame of the
known. Furthermore, it shows the "human contradiction" at work--the
intersection of a hierarchical impulse and a capacity for
intelligence--a contradiction which the novel demonstrates can be
resisted overcome by bypassing the flesh, which is the topic of my
next section.

*** 1. /Dawn/ overview
Octavia Butler's novel, /Dawn/, published in 1987, is the first book
of a trilogy, initially titled /Xenogenesis/ and more recently,
/Lilith's Brood/, about humans who are coerced into interbreeding with
extra terrestrial beings. The story begins with Lilith Iyapo waking up
in a prison cell on the Oankali spaceship, where she soon finds out
that the humanity has been all but extinguished, and that the Oankali
intend to reproduce with the remaining survivors. Over the next
several chapters, it becomes clear what the Oankali want Lilith to do:
to shepherd a group of humans to accept what they call the "gene
trade." The gene trade is a form of genetic manipulation where Oankali
and human genes are combined to yield a new, hybrid race. As the
"Judas goat" who leads the sheep to slaughter, Lilith must convince
the humans to accept a fate which she herself cannot bear: that
humanity will become something profoundly different from what it is;
that their children will look far from human, what she describes as
"Medusa children" (Butler 87).

*** 2. the human contradiction
One reason that humans cannot accept the gene trade can be attributed
to their own genetics which contain, in the words of the Oankali
themselves, the "human contradiction." As explained by Jhdaya, the
first Oankali that Lilith meets, humans have two characteristics that
enabled humanitity to survive and evolve but now threaten the future
of the species:
#+BEGIN_QUOTE
"You are intelligent," he said. "That's the newer of the two
characteristics, and the one you might have put to work to save
yourselves. You are potentially one of the most intelligent species
we've found, though your focus is different from ours. Still, you had
a good start in the life sciences, and even in genetics."

"What's the second characteristic?  

"You are hierarchical. That's the older and more entrenched
characteristic. We saw it in your closest animal relatives and in your
most distant ones. It's a terrestrial characteristic. When human
intelligence served it instead of guiding it, when human intelligence
did not even acknowledge it as a problem, but took pride in it or did
not notice it at all. . ." [...] "That was like ignoring cancer. I
think your people did not realize what a dangerous thing they were
doing."
#+END_QUOTE
The tendency toward hierarchy, as a "terrestrial" characteristic, is
ingrained in all humans. The impulse to stratify people, to create
social groupings, even to colonize and oppress, descends from an
ancient instinct that once served to sustain, protect, and organize
early human tribes. But when the hierarchical instinct grows unchecked
into the modern world, Jdhaya explains, it becomes dangerous, like a
cancer. Stratifications between gender, race, nationality, and class,
for example, descend from this very foundational tendency to mark and
divide what is different, what is other, from what is familiar. This
novel explores how such a tendency, deeply ingrained in human nature,
comes to the fore even as it is threatened by aliens who intend to
"fix" the human contradiction through gene manipulation in
interbreeding. The tendency to self-organize appears early on, when
the humans are being woken up from suspended animation in order to
prepare and train for survival. For example, the pressure to couple
brings a remnant of human society into the strange, alien spaceship
which offers some form of social stability for the survivors. When one
woman hesitates to choose a mate, another woman remonstrates: "What
the hell is she saving herself for?... It's her duty to get together
with someone. There aren't that many of us left" (335). Throughout the
novel, the social stratifications intensify as the humans become more
desperate in their resistance against the Oankali
colonization. Growing more and more agitated in their captivity,
certain men like Peter and Curt eventually attack Lilith and her
followers, who they regard as responsible, with deadly force.

*** 3. fear of the unknown
One of the implications of the human contradiction is how the
hierarchical tendency works in tandem with the propensity for
intelligence to create a fear of the other. Early in the story, this
fear is established as a stubborn and innate human trait. To wade
through this fear, familiar categories and concepts are often imposed
onto foreign phenomena. This is why, when she first sees her captives,
Lilith processes the alien body in human terms:
#+BEGIN_QUOTE
The lights brightened as she had supposed they would, and what had
seemed to be a tall, slender man was still humanoid, but it had no
nose--no bulge, no nostrils--just flat, gray skin. It was gray all
over--pale gray skin, darker gray hair on its head that grew down
around its eyes and ears and at its throat. There was so much hair
across the eyes that she wondered how the creature could see. The
long, profuse ear hair seemed to grow out of the ears as well as
around them. Above, it joined the eye hair, and below and behind, it
joined the head hair. The island of throat hair seemed to move
slightly, and it occurred to her that that might be where the creature
breathed--a kind of natural tracheostomy.

Lilith glanced at the humanoid body, wondering how humanlike it really
was. "I don't mean any offense," she said, "but are you male or
female?"

"It's wrong to assume that I must be a sex you're familiar with," it
said, "but as it happens, I'm male."

Good. It could become 'he' again. Less awkward. 29
#+END_QUOTE
Lilith initially describes the alien's features by cataloging a
"nose," "hair," "eyes," "ears," and "throat," though he has no such
organs, and the first question she asks is to inquire him of his
sex. These responses illustrate the strength of the instict to
interpret bodily appearances according to pre-existing anatomical
categories. Although Jdhaya points out Lilith's mistake in making
assumptions about gender, she nonetheless takes some comfort from
being able to call Jdhaya a "he."

When, however, the strangeness of the alien's appearance proceeds the
terms available to her, she immediatley turns to what would likely be
read as a fear of the other:
#+BEGIN_QUOTE 
She did not want to be any closer to him. She had not known what held
her back before. Now she was certain it was his alienness, his
difference, his literal unearthliness. She found herself still unable
to take even one more step toward him.

"Oh god," she whispered. And the hair--the
whatever--it-was--moved. Some of it seemed to blow toward her as
though in a wind, though there was no stirring of air in the room.

She frowned, strained to see, to understand. Then, abruptly, she did
understand. She backed away, scrambled around the bed and to the far
wall. When she could go no farther, she stood against the wall,
staring at him.

Medusa. 30
#+END_QUOTE 
The narration in this passage suggests a process as Lilith attempts to
place the alien into pre-existing categories. First, when the truth of
his total alienness begins to register, it occurs in a pre-linguistic,
embodied level. It begins with an intense aversion toward physical
proximity--"She found herself unable to take even one more step toward
him" (29-30). Then, when she examines his "features," she still
struggles to process his physical composition until she finally,
"abruptly... understand[s]," and her impulse is to move away. Her
encounter with Jhdaya's unknown alien form demonstrates an aversion
through terms of body language. Then, the narration moves from
depicting body language to description through figuration, an
evocation of the mythical figure "Medusa." Here, Lilith's subscribes
the unknown in terms of something that is, ableit in the context of
myth and fantasy, familiar to the human imaginary. The narration in
this passage, which builds from instinctual body movement to
imagination, reinforces the processes that humans undergo when
encountering the unknown. The tendency toward hierarchy demands that
she place this being on a scale of familiarity, comparing him to what
she already knows about other living beings, for example, that Jhadaya
is male. However, the hierarchy fails to subsume his other qualities,
the sensory organs, intelligence steps in to create an analogy, and
her mind makes the leap between what she sees and what she already
knows. The two sides of the contradiction, hierarchy and intelligence,
work together here to engender a sense of all-consuming fear of the
other.

*** 4. fear of the known
The comparison to Medusa, however, demonstrates that the fear of the
other is based not on the unknown, but on the known. Lilith's use of
similitude evokes a point that Cherrie Moraga, Chicana feminist
activist and writer, argues that the cause of racial fear is not the
totally foreign, but a similarity that the subject percieves in the
other, despite their difference. In her influential essay, "La Guera"
[The White Girl], Moraga explains:
#+BEGIN_QUOTE
it is not really difference the oppressor fears so much as
similarity. He fears he will discover in himself the same aches, the
same longings as those of the people he has shitted on. He fears the
immobilization threatened by his own incipient guilt. He fears he will
have to change his life once he has seen himself in the bodies of the
people he has called different. He fears the hatred, anger, and
vengeance of those he has hurt. 32
#+END_QUOTE
Describing how her lesbianism unlocked the workings racial and class
oppression, Moraga explains that "[her] lesbianism is the avenue
through which I have learned the most about silence and oppression,
and it continues to be the most tactile reminder to me that we are not
free human beings" (28-29). For Moraga, similarity is the foundation
on which fear of the other is built. This similarity is apparent in
Lilith's use of the "Medusa" comparison, and marks the moment when the
subject, which can find no expression beyond body language, finally
settles on a familiar designation, relating the unknown to a form
within the human imaginary. Despite his alienness, at that point,
Jhadaya becomes incorporated into an anthropocentric worldview. This
process is about finding similarity in difference as it is being felt,
in the form of "aches" and "longings." Who has lighter skin and more
education than most in her Latino, working-class background,

*** TODO 5. sensuality in communication [add Anzaldua]
For Chicana theorists like Moraga and Gloria Anzaldua, the body is
both the central obstacle and the solution for achieving interpersonal
connection with the other. To overcome the fear of the other, it is
necessary to come to terms with similarity in the body coded
different--by race, gender, class, disability. This occurs in a
process by which one opens one's body, particularly sensastions,
oneself to full accounting of oppression. Moraga explains that:
#+BEGIN_QUOTE
The danger lies in ranking the oppressions. /The danger lies in
failing to acknowledge the specificity of the oppression/. The danger
lies in attempting to deal with oppression purely from a theoretical
base. Without an emotional, heartfelt grappling with the source of our
own oppression, without naming the enemy within ourselves and outside
of us, no authentic, non-hierarchical connection among oppressed
groups can take place. Emphasis original, 29
#+END_QUOTE
As Moraga explains, one must not only acknowledge the existence of
others' oppression, but come to terms with the oppression's
specificity, a process which involves looking within the self to
experience its physical, sensual components, what she calls "an
emotional, heartfelt grappling" of one's own oppression. Moraga's
argument, which is an intersectional Feminist response to the identity
politics of second-wave feminism, offers a model for interpersonal
understanding while keeping the specificity of oppression local and
situated, which is to say in some way unknowable or
un-essentializable. The power of this kind of connection comes from
its incompletion, its partiality, its lack of fulfillment. 

Chicana and Latin American theorists like Ofelia Schutte and Norma
Alarcon emphasize the danger in achieving perfect communication.
Schutte, for example, explores the problem of "cross-cultural
communication," specifically, the question of "how to speak to the
'other' who is different from oneself" (Schutte 53). Schutte's
strategy is to emphasize attention to what she calls
"incommensurability," that is, the "residue of meaning that will not
be reached in cross-cultural endeavors" (56). Incommensurability
refers to the quality that is lost in translation, so to speak, when
members from two cultures interact. In order to tap into
incommensurability, Schutte explains, interlocutors might attend to
moments when the other's speech "resonates in [one] as a kind of
strangeness, a kind of dsiplacement of the usual expectation" (Schutte
56). The point here is to not subsume that quality of strangeness in
the other into familiar structures of knowledge, like the way that
Lilith subsumes Jhadaya's strangeness into the similitude of the
terrifying Medusa. Rather, the point is to sustain the feelings of
difference without trying to incorporate them into pre-existing
(dominant) modes of thought. Norma Alarcon makes a similar point in
her argument about the dangers of "ontologiz[ing] difference," that
is, of subsuming specific difference into a universal identity
politics. She explains that,
#+BEGIN_QUOTE
The desire to translate as totalizing metphorical substitution without
acknowledging the "identity-in-difference," so that one's own system
of signification is not disrupted through a historical concept whose
site of emergence is implicated in our own history, may be viewed as
a desire to dominate, constrain, and contain. 133 
#+END_QUOTE
The challenge, according to Schutte and Alarcon, is to achieve
connection without totally subsuming the other into totalizing and
therefore oppressive paradigms of subjectivity. One potential
solution, as Schutte and Moraga exemplify, is to attend to the
feelings of the body, of both the "emotional, heartfelt grappling"
within the self /and/ the "incommensurability" of the other, which
seeks to feel without attempting to recodify.

*** 6. Oankali social collectivism
For most humans, who are bound and determined by their biological
impulses and social conditioning, this process is nearly
impossible. It is only through significant effort and supra-human
capabilities that Lilith herself is able to move beyond her fear of
the Oankali. Crucially, this novel refrains from offering an easy
solution to the problem of xenophobia that accompanies the innate
human characteristic of hierarchy. Rather, it explores how
hierarchical human nature might engage with an alternative, even
antithetical social paradigm, that is, social collectivism. The
novel's proposal for this new form of social organization comes down
to Oankali anatomy and their sense organs, which enable direct
connection between themselves and their human partners. Connection
between the Oankali is based the immediate sharing of feelings,
sensations, and thoughts through the neural linkage enabled by their
sensory organs, in particular, their "sensory hands" which they use
for gene manipulation and sex. By connected to each other's bodies and
minds, the Oankali have no need for deceoption or even memory, for
they are compelled to share experiences directly. This form of
collectivism enables the novel to explore new alternatives for
collectivism based on mutual sensation, in particular, through
pleasure. It offers the human-Oankali couplings allow for a
reconsideration of the role of agency in ethics.

Before moving forward, however, it is important to situate Oankali
collectivism within a larger purpose of colonization. Jhadaya explains
that the deepest drive for the Oankali is to acquire new species for
their "gene trade": "We acquire new life, seek it, investigate it,
manipulate it, sort it, use it. We carry the drive to do this in a
minuscule cell within a cell, a tiny organelle within every cell of
our bodies" (84). The Oankali compulsion to acquire may seem to have
some similarities with the human drive for hierarchy, in particular,
that it requires taking in and incorporating new beings into an
existing structure. However, there is a crucial difference between the
Oankali and the humans, which has to do with the collective nature of
the alien species. One of the Oankali children, Nikanj, explains to
Lilith that they evolved from a life form that consisted of numerous
interconnected beings: "'Six divisions ago, on a white-sun water
world, we lived in great shallow oceans,' it said. 'We were
many-bodied and spoke with body lights and color patterns among
ourself and among ourselves'" (123). From their "many-bodied"
ancestors, the current Oankali inheirited a constitution of
collective, rather than individual, consciousness, which affects their
concept of agency. As the Oankali evolved, this collective nature
affects the way they communicate, which is by sharing sensory
information directly so that the interlocutor experiences what is
being related to them, and the way they make decisions, which is by
unanimous agreement. Agency is distributed among the beings, who are
singular and plural at once, "ourself and ourselves."

Their method of acquisition, though arguably similar to human acts of
colonization in the way they expand through incorporation, presents
different priorities when it comes to ethical relations. Because
health and vitality are necessary in order to trade genes, the Oankali
do not admit any form of harm or desctruction of life. At several
points in the book, this attachment to life creates a blind spot,
preventing them from anticipating acts of violence and at one point,
even death, by humans. Toward the end of the novel, Lilith's partner,
Joseph, is killed by a group of humans who rebel and attempt to escape
the Oankali. Soon after his murder, Nikanj uses Joseph's genetic
material to impregnate Lilith without her knowledge. Nikanj explains
to Lilith that it gives her what she truly wants, though she cannot
admit it,
#+BEGIN_QUOTE
"You'll have a daughter," it said. "And you are ready to be her
mother. You could never have said so. Just as Joseph could never have
invited me into his bed--no matter how much he wanted me
there. Nothing about you but your words reject this child." 468-9.
#+END_QUOTE
Nikanj's reasoning is simple: no matter what Lilith says, it knows she
will love and accept the child. For the Oankali, pleasure, not
preference or choice, is the principal factor for
decision-making. For, unlike humans, Oankali lack the capacity to
self-delude through language. When Lilith protests that "It won't be
human," Nikanj warns that "You shouldn't begin to lie to
yourself. It's a deadly habit. The child will be yours and Joseph's"
(469). That agency depends on pleasure rather than individual choice
has significant implications for ethics, particularly for what counts
as coercion and manipulation.

*** 7. pleasure overrides choice
For, even when this sex act appears contained to the mind, it is
always portrayed as something that relies on and is guided by the
material exegencies of the body. When being seduced by the ooloi, the
humans' sex drive is so strong that it overrides the question of
consent. Jayna Brown points out that "the pleasurable experience of
sex with the Ooloi is so highly compelling it is sometimes likened to
rape in the text" (105). Lilith, however, apepars to willingingly
surrender to the Oankali when it comes to sex, even when she resists
their control at all other points of the novel. This tension emerges
when Nikanj invites Lilith to join it and Joseph in bed:
#+BEGIN_QUOTE
“Lie here with us,” it said, speaking alone. “Why should you be down
there by yourself?”

She thought there could be nothing more seductive than an ooloi
speaking in that particular tone, making that particular
suggestion. She realized she had stood up without meaning to and taken
a step toward the bed. She stopped, stared at the two of
them. Joseph’s breathing now became a gentle snore and he seemed to
sleep comfortably against Nikanj as she had awakened to find him
sleeping comfortably against her many times. She did not pretend
outwardly or to herself that she would resist Nikanj’s invitation—-or
that she wanted to resist it. Nikanj could give her an intimacy with
Joseph that was beyond ordinary human experience. And what it gave, it
also experienced. 306
#+END_QUOTE
Lilith welcomes her body's immediate, unconscious response to Nikanj's
invitation, and doesn't attempt to hide or resist this response. Where
one might expect a split between embodied instinct and free will, or
drive and determinacy, one instead encounters their collapse or
conflation. This total surrender to her sexual desire appears in stark
contrast to her other attempts to resist Oankali colonization,
summarized what can be considered her motto, "Learn and run!", that
she repeats up until the last page of the novel. Speaking of the
/Parable/ novels, which also depict the events following societal
collapse, Jayna Brown explains that, for humanity, "changing and
prevailing cannot coexist... We must adapt to survive, but species are
never stable over time if they successfully adapt" (Brown
94). Throughout the novel, Lilith toes the line of this paradox,
simultaneously encouraging the humans to obey the aliens' directions
while preparing them for escape.

In this novel, adaptation requires changes that necessarily
re-formulate what constitutes subjectivity, that is, the boundaries of
the liberal humanist subject. The novel uses sexual pleasure in the
flesh to destabilize the assumptions underpinning free will, which has
the effect of challenging the boundaries of what is traditionally
considered the individual. Brown argues that feeling, the receptivity
to feeling, can be a basis for a kind of subjectivity that moves
beyond the individual subject: "to surrender to touch, to our
sensations, is to loosen the bounds of individualism, to mingle with
other flesh and with the elements" (11). Her concept of the flesh
mends Spillers's earlier differentiation between flesh, or "captive
body," from "motive will," to offer a model of collective subjectivity
enabled by feeling. While the senses "individuate us, demarcate our
boundaries," they also "mark the ways our bodies are open. The body,
the self, is porous, receptive, impressionable" (Brown 14). This
openness recalls the immersion between Lilith and Joseph during sex:
"Now their delight in one another ignited and burned. They moved
together, sustaining an impossible intensity, both of them tireless,
perfectly matched, ablaze in sensation, lost in one another"
(309). The pleasure in the flesh appears to momentarily dissolve the
boundaries of the individual.

Basing subjectivity in the volition of the flesh dismantles one of the
core tenets of liberal subjectivity, that of agency. The notion of
choice becomes re-formulated to the sharing mutual feeling, of feeling
in the flesh. This proposes a model of ethics based on receptivity and
vulnerability, rather than agency. Crucially, however, this model of
ethics does not resolve inequalities that stem from hierarchy or
subject/object formations. Although relationships based on pleasure
admit less opportunity for exploitation, there are still hierarchical
systems without the Oankali society. While the Oankali's repeated
failure to anticipate human acts of violence reinforces the blindspots
imposed by a social structure that cannot account for the destruction
of life, they still exhibit hierarchical tendencies. For example, the
ooloi, the third-gender beings who have sensory arms that can
manipulate genes, are in charge of the gene trade and act as a
matchmakers among the males and females. They demonstrate that
individuals within collective structures require some level of
separateness and delegation in order to work cooperatively. Brown
emphasizes this point when she distinguishes her interest in "feeling"
from "sentimentality":
#+BEGIN_QUOTE
"Feeling togeher does not secure a place free of hierarchical
relationships nor affirm a universalism based on the notion of oceanic
unification. I am not invested in conciliatory politics, in some
notion of symmetrical receprocity. Rather, I want to get at something
that sentimentality attempts to but can never fully harness, for
feeling, as we explore it here, is anarchistic, a modality that cannot
be controlled or always directed" (Brown 28)
#+END_QUOTE
Some form of hierarchy and individuality are crucial components for
maintaining an environment that enables desire. Ironically, this
separateness is reinforced in the moment of seamless connection. For
example, when Lilith asks Nikanj to share its feelings of grief after
Joseph's untimely death, its response suggests that some feelings
cannot be entirely expressed: "It gave her... a new color. A totally
alien, unique, nameless thing, half seen, half felt or... tasted. A
blaze of something frightening, yet overwhelmingly, compelling"
(Butler 429). Despite their direct neural connection, the description
here derives its expressive power on the quality of unknowability,
using formations of strangeness or liminality, ("half seen, half
felt," "alien," "a new color") for its poignancy. It also puts into
relief the contrast between human and Oankali approach toward
difference: for the Oankali, who are enticed by difference, the other
is "something frightening, yet overwhelmingly, compelling." For humans
and Oankali, individuality, and the inexhastability of individual
specificity, is what drives the desire for connection. As Audre Lorde
affirms, "The erotic is a measure between the beginnings of our sense
of self and the chaos of our strongest feelings," then individuality
is central for the experience of its own dissolution (54).

*** TODO 8. the posthuman critique
This ethics based on feeling revises traditional humanist and
poshumanist elisions of the body. As N. Katherine Hayles's work
demonstrates, such elisions emerge from early conceptualizing of the
liberal humanist subject, in which the rational mind /possessed/ a
body, into the posthuman, where cognition and feeling are /collapsed/
into informational patterns. Hayles explains that the dualism of
mind/body and the attendent erasure of the body from cognitive
processes enables further suppressions: "Only because the body is not
identified with the self is it possible to claim for the liberal
subject its notorious universality, a claim that depends on erasing
markers of bodily difference, including sex, race, and ethnicity"
(4-5). The model of sex in Butler's novel revises this esssential
fiction spun in over the history of cybernetic development, mending
the rift between body and mind.

*** 9. scrambling sense and thought
One of the consequnces of the Oankali focus on pleasure as a
foundation for ethics may seem perhaps paradoxical from a human
perspective. The method that Oankali have sex dispenses with what is
for humans the source of sexual pleasure--the flesh. Flesh, which is
the means through which humans achieve sexual contact, is an obstacle
for Oankali sex. In the Oankali sexual union, the male and female do
not touch, but are rather routed through an intermediary, nonbinary
being whose "sensory arms" plug directly into into the brain. The
ooloi intermediary dispenses not only with the clumsiness of human
bodies and the flesh, but also with human modes of communication and
intimacy, to achieve direct stimulation of the brain's pleasure
centers. In the process of seducing Joseph, Nikanj explains that it
"offer[s] a oneness that your people strive for, dream of, but can't
truly attain alone" (359). The direct connection facilitated by the
ooloi offers a sensual and cognitive experience which cannot be
paralleled by physical intercourse. Once Nikanj has her "plugged in",
Lilith
#+BEGIN_QUOTE 
immediately recieved Joseph as a blanket of warmth and security, a
compelling, steadying presence. 

She never knew whether she was receiving Nikanj's approximation of
Joseph, a true transmission of what Joseph was feeling, some
combination of truth and approximation, or just a pleasant fiction. 

What was Joseph feeling from her?

It seemed to her that she had always been with him. She had no
sensation of shifting gears, no "time alone" to contrast with the
present "time together." He had always been there, part of her,
essential. 

Nikanj focused on the intensity of their attraction, their union. It
left Lilith no other sensation. It seemed, itself, to vanish. She
sensed only Joseph, felt that he was aware only of her. 

Now their delight in one another ignited and burned. They moved
together, sustaining an impossible intensity, both of them tireless,
perfectly matched, ablaze in sensation, lost in one another. 308-309
#+END_QUOTE
While Lilith's experience of sex with Joseph and Nikanj explains a lot
about the relationship between physical pleasure and mental
experience, it also instructs one crucial lesson about human
relationships. That Lilith questions whether her mental experiences
are true or not, the fact that she doubts, points to an issue with
human intimacy--that there is exists a gap for miscommunication and
misunderstanding. This gap is created and sustained by the flesh,
which can be a clumsy, cumbersome, and unreliable space through which
two sexual partners must navigate to reach sexual unity. By contrast,
the Oankali sexual experience bypasses this gap directly, plugging
into the brain's pleasure centers. By routing sensual connection to
the brain, they eliminate the space for discomfort and even repulsion
which can occur when in flesh-to-flesh contact.

The elimination of flesh in sex reveals a complex imbrication between
physical sensation and mental experience, which pushes against a
tendency in narratives that feature the "posthuman," that is, figures
who extend the bounds of the traditional human subject by
technological, biological, or spiritual modification. Because the
sexual experience occurs entirely in the brain, it is easy to assume,
as Lilith and Joseph do, that the experience is a simulation. Their
assumption perpetuates one crucial tenet of liberal human
subjectivity, according to N. Katherine Hayles, that the rational mind
/possess/ a fleshy body which functions as an extension of the
mind. Hayles explains that for the posthuman, the mind represents pure
intelligence, a set of informational patterns, while the body
functions as a sort of prosthesis, which can be substituted, updated,
or even removed from the intelligent mind. The classic example is
William Gibson's /Neuromancer/ novel, which poses a a virtual
"dataspace," known as a "matrix," where users can move and interact
without the need of a physical body. This emphasis on cognition
creates an "erasure of embodiment" which assumes that feelings and
sensations that occur in the body can be experienced in a flesh-less
environment (Hayles 4-5). In the novel, Lilith appears to make the
same assumptions as the posthuman when she questions whether the
feelings she recieves from Joseph are "true." However, as her
conversation with Nikanj develops, she brings the body back into
consideration:
#+BEGIN_QUOTE
"He... felt everything I felt?"
"On a sensory level. Intellectually, he made his interpretations and
you made yours.
"I wouldn't call them intellectual." 310-311
#+END_QUOTE
Lilith's response here indicates that sense and thought are not as
distinct as might have been assumed, in Hayles words, that "abstract
pattern can never fully capture the embodied actuality" (22).Indeed,
during the sex act, the terms that she uses to describe their sexual
union appear to blend feeling and thought. The physical "warmth" with
which she receives Joseph is immediately augmented with mental
interpretations of "security," that is, comfort and
protection. Further on, the intensity of their connection appears not
only to dissolve her sense of time, as she feels "she had always been
with him," but also to intuit what he was feeling, "that he was aware
only of her" (308). While sex with the Oankali focuses on physical
pleasure, the mind builds mental interpretations that seem to be
inextricable from physical sensation.


**** Dawn Quotes

***** Colonialist intentions, Crossbreeding vs Trade:
"'It is crossbreeding, then, no matter what you call it.' 'It's what I
said it was. A trade. The ooloi will make changes in your reproductive
cells before conception and they’ll control conception.'" (Butler
87). 

***** Irresitable sex drive
#+BEGIN_QUOTE
“Lie here with us,” it said, speaking alone. “Why should you be down
there by yourself?”

She thought there could be nothing more seductive than an ooloi
speaking in that particular tone, making that particular
suggestion. She realized she had stood up without meaning to and taken
a step toward the bed. She stopped, stared at the two of
them. Joseph’s breathing now became a gentle snore and he seemed to
sleep comfortably against Nikanj as she had awakened to find him
sleeping comfortably against her many times. She did not pretend
outwardly or to herself that she would resist Nikanj’s invitation—or
that she wanted to resist it.  Nikanj could give her an intimacy with
Joseph that was beyond ordinary human experience. And what it gave, it
also experienced. This was what had captured Paul Titus, she
thought. This, not sorrow over his losses or fear of a primitive
Earth.
#+END_QUOTE


** flesh
*** section overview
Bound by the impulses of the "human contradiction," the flesh poses a
problem for interpersonal relationships. It functions as a barrier to
more pleasurable forms of social organization. Black Feminist studies
help us to see how the Flesh can be redeployed, through their
examination of flesh as surface. Their emphasis on the surface finds
fugitivity and foreclosure as possible modes of resistance.

*** 1. the reduction of flesh
The process of racialization, which builds from the flesh not only
helps us to understand the inextricability of the material from the
mental, but also offers a possibility for developing social relations
into toward more ethically equitable forms. To help unpack this
inexctricability between registers, I turn to thinkers in Black
Feminist Studies whose theorizations of the flesh enables them to
parse various racial and gendered processes, the "symbolic order" or
"American grammar," in Hortense Spillers words, ascribed to Black
bodies over time (68). These theorizations of the flesh, which index a
liminal space where meaning is simultaneously ascribed and obscured,
will become the ground for my working through the intersections of
physical materiality and symbolic meaning in my next section,
/skin/. They will allow me to trace in more detail how the process of
reduction to flesh simultaneously creates an opportunity for resisting
certain kinds of reading(s) [definitely rephrase].

In the nearly impossible task of the history of transatlantic slavery,
thinkers in Black Feminist Studies have redeployed the systematic
reduction of the body to flesh into a tool of resistence. The idea of
black flesh as a reduction of the black body is first theorized by
Hortense Spillers in her influential essay, "Mama's Baby, Papa's
Maybe: An American Grammar Book." Here Spillers puts forth the
conception of the black body as a stack of "attentuated meanings, made
in excess over time, assigned by a particular historical order"
(65). These meanings developed from the Black body that had been
reduced to flesh, "severing of the captive body from its motive will,"
that Spillers traces to the middle passage. Spillers enumerates four
effects of this violent process (67):
#+BEGIN_QUOTE
1) the captive body becomes the source of an irresistible, destructive
   sensuality;
2) at the same time--in stunning contradiction--the captive body
   reduces to a thing, becoming being for the captor;
3) in this absence from a subject position, the captured sexualities
   provide a physical and biological expression of "otherness";
4) as a category of "otherness," the captive body translates into a
   potential for pornotroping and embodies sheer physical
   powerlessness that slides into a more general "powerlessness,"
   resonating through various centers of human and social meaning. 67
#+END_QUOTE
Imposed by the reduction of Black bodies to bare physicality, to a
material substance for labor and exchange, there is, in "stunning
contradiction," some form of meaning which aheres to the flesh. This
process of the reduction to flesh, which Spillers calls
"pornotroping," opens a space for the layering of sensuality,
objectificaiton, otherness, and powerlessness (Spillers 67).

*** 2. fungibility -> fugitivity
Following Spillers, who poses flesh as the "zero degree of social
conceptualization", thinkers in Black Feminist Studies have drawn from
the flesh as a ground for theorizing the intersection of materiality
and meaning (Spillers 67). For example, C. Riley Snorton attends to
flesh as a site of resistance against the imposition of racial
signification. Snorton explains that that the whittling down of black
subjectivity, which enabled chattel slavery, imposes a state of
interchangeability, what he calls the "fungible." This fungibility in
Black flesh creates a possibility for for "fugitivity," or escape,
from the trappings of sex and gender: "Captive and divided flesh
functions as malleable matter for mediating and remaking sex and
gender as matters of human categorization and personal definition"
(20). Snorton describes how the reduction of black female bodies to
flesh for experimental purposes enabled the emergence of field of
gynecology as a white women's science. While white femininity prevents
the inspection of white female genitalia, it is constructed out of the
"scopic availability" of black flesh (Snorton 33). Beyond facilitating
the study of white bodies, however, Black flesh also creates a
"capacitating structure" that enables "fungibility for fugitive
movement" (Snorton 53). Here, Snorton interweaves various narratives
of fugitivity, such as that of Harriet Jacobs, whose story of escape
in 1842 is documented in /Incidents in the Life of a Slave Girl/
(1861). While traditional racial "passing" assumes an ambiguity that
enables one to pass for white, the reduction to Black flesh, by
contrast, endows a "gender indefiniteness" for "cross-gendered modes
of escape" (56). In other words, it is the "blackening" of Jacobs that
allows her to obtain a level of "fungibility, thingness" that
precludes her recognition (Snorton 71). Being suceptible to multiple
mappings of meaning here, the Black flesh therefore opens a site for
potentiality that paradoxically facilitates escape from
signification. The reduction to flesh creates an almost chaotic state
where the body can slip in and out of signification.

*** 3. opacity -> foreclosure
Like Snorton, Musser builds off Spillers' theorization of the Black
flesh as a reduced state. For Musser, this means thinking alongside
the inherent violence that adheres in the concept of the pornotrope:
""to think with the flesh and to inhabit the pornotrope is to hold
violence and possibility in the same frame" (12). Drawing from
Alexander G. Weheliye's point that sexual desire cannot be severed
from domination, Musser's emphasis on fleshiness brings to the surface
other modes of relationality that exist alongside and are in tension
with the desire to dominate. One of these modes is hunger, which she
reads through a photograph of the artist Lyle Ashton Harris's
impersonation of Billie Holiday. Musser's reading of its surface
emphasizes a self that is excessive yet inaccessible. Musser notes the
details of the Harris's dress, such as the "pearls, eye shadow and
lipstick" that capture the light of the image, as the "Shine [which]
plays joyfully with the idea of the body as body while rejecting the
demand to present anything other than surface" ("Surface-Becoming"
par. 3). Musser explains that Harris's open mouth, for example: 
#+BEGIN_QUOTE
tells us nothing of Holiday or Harris, but it reveals a sensuality or
mode of being and relating that prioritizes openness, vulnerability,
and a willingness to ingest without necessarily choosing what one is
taking in. This is not the desire born of subjectivity in which
subject wishes to possess object, but an embodied hunger that takes
joy and pain in this gesture of radical openness toward otherness. 5
#+END_QUOTE
While emphasis on the surface here indexes the matter, the material
aspects, of the image, it also /forecloses/ access to that which we
cannot know. In this way, Musser explains, the surface aesthetics of
the image exist in tension with the inescapable violence of the
pornotrope: "we can understand surface as the underside of the
scientific/pornographic drive toward locating knowledge in an
'objective' image" ("Surface-Becoming" par. 2). In foreclosing access
to interiority, opacity opens relational possibilities that transcend
the boundaries of the possessive subject.

*** 4. surface -> shifting registers
In another example, Musser moves to a painting by artist Mickalene
Thomas entitled /Origin of the Universe 1/ (2012), whose depiction of
a female vulva evokes French realist painter Gustave Courbet's
/Origine du Monde/ (1866). Here, the vulva is black, and encrusted
with rhinestones, creating an effect of brilliant surface which Musser
argues is a "formal strategy of producing opacity" (/Sensual Excess/
48). While this work, like Harris's citation of Billie Holiday,
instrumentalizes opacity as a means of foreclosing access to
interiority, it does so alongside a more pronounced subtext of
objectification that results from the commodification of the black
female body. Here, Musser's analysis turns to the rhinestones, which
function simultaneously on two registers: first, their flashiness "as
a reminder of the long association between black people and the
commodity" (/Sensual Excess/ 50); and second, as a brilliance that
evokes wetness, as a result of sexual pleasure. This dual possibilities
exists simultaneously, as Musser explains:
#+BEGIN_QUOTE
Thinking the rhinestone as a trace or residue of Thomas’s wetness and
excitement allows us to hold violence, excess, and possibility in the
same frame. Even as the source is ambiguous, the idea that rhinestones
might offer a record of pleasure—-pleasure that is firmly constituted
in and of the flesh—-shows us a form of self-possession.  This self is
not outside of objectification, but its embellishment and insistence
on the trace of excitement speaks to the centrality of pleasure in
theorizations of self-love. /Sensual Excess/ 63
#+END_QUOTE
I want to emphasize the movement between these registers here. While
the significatory system that works on the image of the black vulva is
inescapable, the effect of objectification exists alongside the
projection of pleasure. The surface of the image facilitates this
shift in registers. Attention to materiality, to opacity of the
brilliant surface, enables one to apprehend this movement from one
frame to another, from "violence, [to] excess, [and to] possibility."

[connect this to the notion of "torque" in M. Kirschenbaum]


** skin
Here we see the layers of flesh as "surface effects." 
- Hayles and Kirschenbaum enable us to deconstruct how what we think
  is immaterial is actually embodied/inscripted. 
- First, to understand, as Hayles explains, that "information loses
  its body" and see how this perpetuates liberal humanist reductions
  of the subject. Hayles frames this within a discussion of the
  posthuman.
- Second, to examine K's concept of formal materiality, where
  abstraction engages manipulation and sensuality, the shifting of
  registers.
- K's torque enables us to read sensuality into Hayles's concept of
  flickering signifiers.

-> Bringing back the flesh: pattern as material in the form of opacity,
  surface, torque.
-> deep reading of different technologies in /skin/. 

*** Media Archaeology overview
New Media studies poses an understanding of digital media as
alternately undifferentiated or immaterial, or then as durable and
particular inscription. Media theorist Friedrich Kittler, who famously
conceives digital media as undifferentiated, argues that:
#+BEGIN_QUOTE
The general digitization of channels and information erases the
differences among individual media. Sound and image, voice and text
are reduced to surface effects, known to consumers as interface. Sense
and the senses turn into eyewash. Inside the computers themselves
everything becomes a number: quantity without image, sound or
voice. /Grammophone/ 1
#+END_QUOTE 
From Walter Benjamin's seminal "The Work of Art in the Age of
Mechanical Reproduction," Kittler bring media theory to consider the
effects of the digital in conversation with recent theoretical
developments, like discourse analysis and structuralist
psychoanalysis. Kittler imposes Lacan's concepts of the symbolic,
imaginary, and real to give detailed accounts of the specificities
brought about by differentiation of communication technologies in
writing, sound, and visual media. Writing, for example, as a
"symbolic" medium with letters and words operating within a
significatory system, constrasts with the phonograph, which etches
acoustic effects of the "real" into vinyl material, and with film,
whose projection evokes the imaginary. Kittler's essential proposition
is that media do not simply reflect our thought: rather, they shape
thought. It is not that the film mimics our unconscious, but that our
unconscious mimics film. Film projects the effect of light waves at
speeds fast enough to sustain an illusion of movement. For Kittler,
the digital computer is the medium to end all media: “What will soon
end in the monopoly of bits and fiber optics began with the monopoly
of writing” (/Grammophone/ 4). He presents a reintegration of all
differentiated materialities into the stream of zeros and ones:
#+BEGIN_QUOTE
Our media systems merely distribute the words, noises, and images
people can transmit and receive. But they do not compute these
data. They do not produce an output that, under computer control,
transforms any algorithm into any interface effect, to the point where
people take leave of our senses. /Grammophone/ 2
#+END_QUOTE
Kittler argues that the effect of the computerization is to flatten
the material specificity of various media, which corresponded to
various sense perceptions. By "computing these data," the digital
medium does the feeling in place of the human senses.

*** how information lost its body
Working to unflatten the zeroes and ones, scholars influenced by
literary studies, like N. Katherine Hayles and Matthew Kirschenbaum,
emphasize the /materiality/ in digital media. According to Hayles, the
disarticulation of digitality from materiality has been in production
since the emergence of computing technologies in the mid-20th
century. Hayles's influential text, /How We Became Posthuman: Virtual
Bodies in Cybernetics, Literature, and Informatics/ (2000), lays out
the "waves of cybernetic development," that is, the development of
systems theory among prominant information and communication theorists
like Norbert Wiener, John von Neumann, Claude Shannon, and Warren
McCulloch (2). Hayles traces the first of these waves, "how
information lost its body," to bring to the surface the conceptual
moves that, throughout cybernetic developement, reduced intelligence
to information processing, the calculation and manipulation of
symbols. To re-materialize the conceptual moves that evacuate
embodiment, Hayles offers a dialectic of "pattern/randomness," in
which information is as a formal organization of symbols (pattern)
against arbitrary or chaotic "noise" (randomness). This privileging of
intelligence in the human congeals an imaginary for developing
increasingly sophisticated machines that can compute streams of
seemingly weightless, massless numbers. The body and the experience of
embodiment becomes more and more displaced in favor of a conception of
humanity as primarily information processing entities.

This development, according to Hayles, extends reductive ideologies in
the liberal human into the "posthuman." Specifically, the displacement
of embodiment in favor of information processing perpetuates liberal
humanist conceptions that privilege a dominant, unmarked rationality
over embodied experience and especially, embodied difference. As
Hayles explains, "Information, like humaninity, cannot exist apart
from embodiment that brings it into being as a material entity in the
world; and embodiment is always instantiated, local, and specific"
("Virtual Bodies and Flickering Signifiers", 1993, 91). The liberal
humanist subject is characterized by classical mind/body divisions and
hierarchies that posit embodiment as separate from and subordinate to
intelligence, in which the rational mind /possesses/ a body. Extending
this framework, the postuman is characterized by an intelligence
consisting of informational patters that /inhabit/. This progression
from possession to inhabitation suggests that the next move will be to
transcend the material realm altogether, as consciousness can be
uploaded to a virtual space where life itself is infinite.

*** turing test
Hayles inaugurates the story of "how information lost its body" with a
Alan Turing's famous thought experiment, the "Turing Test." In a 1950
paper, "Computing Machinery and Intelligence," Turing outlines
criteria for evaluating whether or not machines can "think" in a way
comparable to human thinking. The resulting Turing Test, or "imitation
game," as it's also known, poses a strategically simplified definition
for computer intelligence. The question is not whether a computer can
intrinsically display intelligent or conscious thought which, Turing
points out, is difficult enough to guage in a human. Rather, the
question is whether a computer can adequately /impersonate/ a human to
feign intelligence. Turing therefore sets up the test to include one
human and two interlocutors, a human and a machine. The test consists
of the first human typing questions to the two interlocuters whose
answers will enable the human to guess which one is a human and which
a machine. Because all communication occurs is routed through a
keyboard and screen, the game relies on how well each interlocutor can
respond in verbal form to questions posed by the first human.

Hayles points out that this first step toward Artificial Intelligence
crucially /sidesteps/ the role of the body in thinking. By
distinguishing /embodied/ experience from verbal representation, the
test poses a concept of intelligence which is detachable from its
material instantiation. Hayles drives this point home with the
comparison to gender that Turing makes prior to his explanation of the
Turing Test, as a way of introducing the idea and structure of a
guessing game based on verbal questioning and responses. Here, rather
than intelligence, the person taking the test must guage which of the
two interlocutors is male and which is female. By sequestering the
body into another room, Hayle explains, the test effectively severs
gender into two components: the embodied component, and the
represented component. If the person taking the test guesses correctly
which is the man and which the woman, then gender is reconsolidated
into a single identity; However, as Hayles points out, "The very
existence of the text...  implies that you might also make the wrong
choice" (/Posthuman/ xiii). That gender can be represented
/discursively/, as a formal or symbolic phenomenon, bifurcates gender
into embodiment and representation. As Hayles explains, "the overlay
between the enacted and represented bodies is no longer a natural
inevitability but a contingent production, mediated by a technology
that has become so entwined with the production of identity that it
can no longer meaningfully be separated from the human subject"
(/Posthuman/ xiii).

My first chapter explores how gender has been characterized within
discursive frame, in terms of performativity. In that chapter, I
examined how coding structures (the for loop, for example) create
iterative forms which can be reworked toward evoking iterativity in
gender performativity. Here, I want to take a different approach. I
want to examine how Hayles' reading of information as represented on
the computer screen, which she frames as an evacuation of embodiment,
might actually be reframed as a /distinctly material/ and /sensual/
process. I want to consider the ways in which the language on the
computer's screen is only the topmost in a layer of various software
stacks that contain their own materialities.

In my view, the test's most interesting move isn't that it evacuates
embodiment, but that it speculates the terms under which embodiment
can be /performed/. Turing, who spends a significant portion of his
argument clearing the ground for what he means by "thinking" in the
context of computation, which is decidedly not thinking as humans
experience it, explains that it is necessary to elide questions of
embodiment and consciousness when it comes to assessing
intelligence. The inclusion of typing purposefully evacuates
body/feeling from the test, as Turing explains,
#+BEGIN_QUOTE
In order that tones of voice may not help the interrogator the answers
should be written, or better still, typewritten. The ideal arrangement
is to have a teleprinter communicating between the two
rooms. Alternatively the question and answers can be repeated by an
intermediary. The object of the game for the third player (B) is to
help the interrogator. The best strategy for her is probably to give
truthful answers. She can add such things as "I am the woman, don't
listen to him!" to her answers, but it will avail nothing as the man
can make similar remarks. 434
#+END_QUOTE
Turing is careful to construct the components of the test in a way
that deliberately reflects an anthropocentric frame. The question, for
Turing, is not whether a machine can "think," but whether a machine
can act indistinguishably from the way a thinker acts. Avoiding the
difficult philosophical problem of defining what it means "to think,"
Turing can instead focus on how a formal system of symbol manipulation
might generate a performance of intelligence. From this perspective,
the Turing test deliberately offers up gender and cognition as a
simulation. Another way of putting it is that cognition and gender
become features of a certain type of formal performance.

*** formal materiality
In what follows, I explore the /formal/ aspects of this kind of symbol
manipulation. Here, I draw from Hayles and Matthew Kirschenbaum to
tease out the sensual aspects of digital media. As Kirschenbaum points
out, the effects of the screen, where objects appear, disappear, and
move with apparent fluidity that seems to defy matter (have you ever
wiggled a window?), reinforce a common misconception that digital
media is "immaterial"--that it isn't based on physical objects, in
this case, the physical level of digital inscription on computer
hardware. To counter this misconception, which Kirschenbaum calls
"screen essentialism," Kirschenbaum offers a dual framework of
"formal" and "forensic" materiality. Together, these levels of
materiality produce what Kirschenbaum calls "the illusion of
immaterial behavior" on the screen (11). Forensic materiality examines
the physical level of digital inscription, that is, the magnetic
encoding at the level of computer hardware, and it how it bubbles up
the software stack through the levels of programming languages toward
specific interface effects on the screen. Kirschenbaum demonstrates
how a reading of physical materiality of digital media, such as file
formats or software specifications below the level of human senses and
awareness, might influence the “close-reading” of textual material in
electronic formats to challenge widespread theorizations about
electronic formats manifesting post-structural aesthetics like
fluidity and ephemerality. For example, his reading of an early story
authoring software called /Storyspace/ points out that the physical
realities of software create idiosyncratic reading experiences of the
same story.

If forensic materiality denotes the physical level of computer
hardware, such as the magnetic polarities inscribed on hard drives,
which are invisible to the naked eye, formal materiality consists of
visual and conceptual phenomena such as display and appearance on the
screen, as well as underlying software logics and structures, such as
programming languages and data formats. Kirschenbaum asserts that the
effects of the screen, which suggest that digital objects are easily
manipulated, is a deliberate result from a long process of
normalization as data moves up the software stack. Just as older
technologies like the telegraph employ relay systems to reinforce
signals over long stretches of transmission, so software employs
signal "reinvigoration" that refreshes data as it travels through
software environments. Contrary to the misconception that digital
processes enable "transmission without loss, repetition without
originality," electronic data is continually reproduced and refreshed
to fix errors and idiosynracies that occur during
transmission. Kirschenbaum describes this process as "allographic
reproduction" in which information systems standardize data through
/approximation/ rather than exact copying (136). As a result,
Kirschenbaum argues, formal materiality, the effect on the screen, is
a "built" and "manufactured" phenomenon, "existing as the end product
of long traditions and trajectories of engineering that werer
deliberately undertaken to achieve and implement it (137).

*** abstraction -> tangibility of data
Although formal materiality acts as a buffer between the user and the
digital inscription, there is an inverse relationship between digital
abstraction and tactile manipulation. At the most basic level,
electronic data consists of one of two possible ("binary") marks on a
magnetized surface, a north polarity signifying "1", or a south
polarity signifying "0". As data moves up the stack, this binary
digits, or "bits," abstract into informational patterns, which take
the form of shapes on the screen. More specifically, these binary
digits are compiled into low machine languages such Assembly language,
then into higher order programming languages like Java and
Python. Kirschenbaum points out that the higher that data climbs up
the levels of abstraction, the more malleable and manipulatable
digital objects become, a state which he calls "digital volitality"
(140). By manipulating the graphical user interface, for example, by
dragging and right clicking on items, users can move, duplicate, or
delete large quantities of data. Kirschenbaum explains this "dynamic
tension... between inscription and abstraction, digitality and
volitality" makes formal materiality more susceptible to movement and
change than physical inscription, which remains inaccessible. Moving
away from the inscription, is a move toward something that users can
handle and "touch," so to speak.

*** torque -> materializes the shift of software registers
The concept of formal materiality not only applies to conceptual
objects on the screen, such as windows and icons, but also to the ways
that data is transformed as it moves up the stack. Kirschenbaum
explains that formal materiality, as a term, "tries to capture
something of the procedural friction or perceived difference--the
torque--as a user shifts from one set of software logics to another"
(13). Kirschenbaum's choice of /torque/, a concept from physics and
mechanics, is significant. Torque signifies a force that results in a
rotational movement, and can be represented with the formula t = f *
d, where f denotes an external force, and d denotes distance from the
object's pivot point. This force combines energy from two directions,
first, from the external force acting upon the object, and second,
from the relation between the exact point of contact on the object and
the objects own weight. Typically, objects rotate along their "center
of mass," or pivot point, the point along the object where it can be
balanced, where its distributional weight is zero. For example, one
could balance a twelve-inch ruler by placing a finger under the sixth
inch. By applying some force to the center of mass, the object would
not pivot, but move in a linear direction, either up or down, or
sideways, depending on the direction of the force. However, if
external force was applied along either side of the center, say at the
second or ninth inch, the object would pivot. Its direction would then
be determined by its pivot point, whether that be its center of mass
or the point where the object is affixed to another object, if the
ruler were nailed to the wall, for example. In this case, the ruler
would pivot around this point of attachment, and the force and
direction of its pivot would be measured as "torque." Torque,
therefore, is a measure of a force that relies on /distance/ between
the point of contact the object's center. 

The concept of torque is useful for materializing the shift from one
code to another. The distance between the point of contact and the
center of weight, which with force determines /torque/, can be
understood as the gap between one sign and another. Or at a larger
scale, the shift from one significatory system to another as data
travels up the software stack. 

*** flickering signifiers
Hayles wonders, "Why do we talk and write incessantly about the
'text,' a term that obscures differences between technologies of
production and implicitly promotes the work as an immaterial
construct?" ("Flickering connectivities in Shelley Jackson's Patchwork
Girl: the Importance of Media-Specific Analysis," 2000,
par. 57). Hayles offers the concept of the "flickering signifer" to
tease out the cultural assumptions behind digital immateriality. The
flickering signifier consists of words and objects on the screen that
appear immaterial, "characterized by their tendency toward unexpected
metamorphoses, attenuations, and dispersions" ("Virtual Bodies and
Flickering Signifiers", 1993, 76). Due to this appearance, the
flickering signifier perpetuates a liberal humanist ideology about the
body/mind separation into the posthuman one of hardware/code. Just as
the mind rules the fleshy body, so the /code/ represents a an
insubstantial standard that drives computation. Hayles frames the
flickering signifier within a poststructuralist critique that work to
destabilize meaning and truth within classical knowledge
paradigms. Evoking Jacques Lacan's "floating signifier," the idea that
a word has no referent, but "floats" above a text, attaining whatever
meaning it can by a play of differentials within other floating
signifiers, the "flickering" refers to the ways that electrical
signals, which represent words, travel up the software stack. Hayles
explains that the floating signifier belies an immateriality:
#+BEGIN_QUOTE
As I write these words on my computer, I see the lights on the video
screen, but for the computer the relevant signifiers are magnetic
tracks on disks. Intervening between what I see and what the computer
reads are the machine code that correlates alphanumeric symbols with
binary digits, the compiler language that correlates these symbols
with higher-level instructions determining how the symbols are to be
manipulated, the processing program that mediates between these
instructions and the commands I give the computer, and so forth. A
signifier on one level becomes a signified on the next higher
level. Precisely because the relation between signifier and signified
at each of these levels is arbitrary, it can be changed with a single
global command. Virtual Bodies and Flickering Signifiers", 1993, 77
#+END_QUOTE
Hayles's description of the flickering signifier, what she calls a
"flexible chain of markers," materializes the various levels of
transformation that digitized inscription must undergo in order to
reach the level of the screen. The process begins at the level of
physical inscription, where binary markings on disks are translated to
machine code and other lower level programming languages, when are
then fed into a compiler procedure that rewrites these codes into more
readable programming languages (also known as "higher order"
languages), at which point they are composed into applications and
files that humans can engage directly via a graphical user
interface. In this movement up the stack, data shifts between
registers and becomes more tangible, a process that is belied by the
fleeting and diaphanous forms that finally emerge on the computer
screen.

*** Hayles perhaps underestimating materiality of flicking sig
Flickering signifiers bring consideration of "transformations" into
view. though I do think she is underestimating the "matter," "energy"
which goes into it. 
#+BEGIN_QUOTE
When a text presents itself as a constantly refreshed image rather
than durable inscription, transformations would occur that would be
unthinkable if matter or energy, rather than informational patterns,
formed the primary basis for the systemic exchanges. This textual
fluidity, which humans learn in their bodies as they interact with the
system, imply that signifiers flicker rather than float. 30
#+END_QUOTE

*** /skinonskinonskin/
In what follows, I read the flickering signifiers, this "flexible
chain of markers bound together by the arbitrary relations specified
by the relevant codes" ("Virtual" 77). They are productions, they are
manipulable, they are shifting.  

/skinonskinonskin/ is a work of "net art" created in collaboration
between Auriea Harvey and Michael Samyn, who go by the name
Entropy8Zuper!. /skin/ documents the inception of their love affair,
which began in an internet chat room in 1999, in the form of a digital
correspondence of web pages, or "digital love letters".
("/skinonskinonskin/" /Net Art Anthology/).

By today's technological standards, the net artwork is inaccessible to
modern browsers. The work consists of HTML (HyperText Markup Language)
pages animated by now obsolete web browser code (HTML and JavaScript)
and Flash software. Due to modernization, the browser languages HTML
and JavaScript use now depreciated elements like ~<layers>~ and
~<area>~ to add animation. Additionally, since Flash technology, a
compiled software that is not "human-readable", has been discontinued,
it is very difficult to find solutions for editing and viewing Flash
elements. Besides the difficulty with authoring languages, it was
created to run on the Netscape 4 browser which offered, for the time,
a platform agnostic solution that would render on both Harvey's Mac
and Samyn's PC. /skin/ takes part in a body electronic work called
"Electronic Literature," which is now practically
inaccessible. Electronic Literature, which spans several subgenres,
like hypertext fiction, network literature, interactive fiction, and
generative text share a common interest in exploring aesthetics that
draw from the digitality of the medium.

In what follows, I am going to discuss this work according to three
key ideas from black feminist studies: [force], foreclosure, and
fugitivity.

**** haptics -> movement engages source code's "shifts" (torque)
The hypertext work plays with haptic engagement (the hand on the
mouse) in ways that point to /shifts/ that occur in the underlying
program code. 

-> These shifts can be what? What is a "shift" -- a piece of code that
executes?  

-> What is the significance of these shifts? That they are rooted in
constraints, conditional statements, static images, to engage motion?

The pages by Samyn, in particular, deploy animation techniques that
engage the user's physical movement. One page, "air.html," challenges
the user's tactile ability, requiring precise mouse manipulations in
order to "move" elements across the page. On this page, the user
controls two small bodies in horizontal, flying position, as they
float over a field of a field of rotating lines, which evoke a
rolling, cyber-landcape. The animations operate like magnets, always
moving toward the mouse, but the strength of their attraction depends
on the mouse's speed. By slowing down the speed, the individual bodies
can touch, but they can never cross each other. Even with the most
precise movements, Samyn's body remains on the left, while Harvey's is
on the right. [SEE GIF] The illusion of freedom in floating,
therefore, has constraints. 

[include gif of air.html]

The animation is defined in the JavaScript, in the page's source code.
Observe the if/else statement for the JavaScript function,
~flyMouse()~.

#+BEGIN_SOURCE
if ( mouseX < halfW )
	{
	var mFactor = 0.1;
	var aFactor = 0.01;
	}
else
	{
	var mFactor = 0.01;
	var aFactor = 0.1;
	};
...
dMove('flyingmL','document.',mLeft + thisXDiff*mFactor,mTop + thisYDiff*mFactor);
...
dMove('flyingaL','document.',aLeft + thisXDiff*aFactor,aTop + thisYDiff*aFactor);
moveGround();
#+END_SOURCE

Though the full workings of the source code remain fuzzy (at least to
me), it is clear that the basics of the animation element relies on an
if/else statement. Here, the movement of the bodies is conditional on
their distance between the mouse and the original positioning of the
bodies on either side of the screen. Depending on this distance, the
magnetic force for each of the bodies is multiplied against a factor
of .1 or .01. This results in a stronger movement from Samyn's body
when the mouse is on the left side of the screen (Samyn's original
position), and a stronger movement from Harvey's body when the mouse
is on the right half of the screen. The binary nature of this
conditional statement--it can be true or it can be false, and will
execute the associated code--accords with an animation that is, at its
core, about dual movement. Here, the movement by the hand and the
oppsitional constraints which the user comes up against, engage the
transformations that take place in the code, "under the hood" of the
work, so to speak.

Throughout this work, the user engages with HTML and JavaScript code
via haptics on the browser. The source code endows digital "objects"
with properties and methods so that they can become manipulable at the
level of surface. These constructs, which are defined under the hood
of the browser, enable sensual experiences for the user. 

One example occurs on "obsessed.html," which contains a view of a
concentric circles, in green, that move against the cursor in a
circular motion. The motion of the circles, which are rooted in the
ummoving center circle, and whose outer layers increase in mobility,
recall a spring mechanism, flexible yet taut. If "air.html" play with
magnetic forces, this plays with the opposite, with opposing
foce. Moving the mouse across the screen pushes the circles away. If
one, however, moves the mouse to the center of the circle, they settle
back into a neutral position.

The center circle, when clicked, leads to a new page, "control.html."
While the source code for most pages include a title, author, and
date, this page only contains a title, "you:controlMe." It consists of
a monochrome green image of Harvey, whose head rolls from side to side
in the direction of the user's cursor. The effect, which is reinforced
by the cursor appearing as a pointing hand, as it does when something
becomes "clickable," is that the user manually turns Havery's head
from one side to the other by pressure of the
cursor-as-hand. Additionally, when the user moves Harvey's head from
side to side, they not only see more or less of her face, but also
peices of "alt-text" with words like "go" "believe" "ocean" and
"mind". The [SEE GIF].

[INSERT GIF]

There are two interesting things here. The first is the way the
animation engages directly the sensuality of the human user. Not only
does the cursor implicate hand movement, in that the user /moves/
Harvey's face by passing the mouse over it, but the animation itself
lends an aura of super-reality. Rather than represent a smooth
movement from side to side, Harvey's head takes little jumps from one
position to another. A look into the source code reveals that the
animation consists of 23 images that loop according to the position of
the user's mouse. The effect is a slight lag, a series of fleeting
pauses that intensify Harvey's direct gaze into the camera.

**** foreclosure - > language & code
Although the user has full access to Harvey's image, they have only
partial access to the alt-text that appears when they pan over certain
parts of the animation." Alt-text is one of several attributes tied to
each of the 23 images used to animate the movement of Harvey's head,
including coordinates for the mouse to activate the relevant image and
conditional statements that define visibility. The code for a single
image of the 23, for example, consists of the following: ~<AREA
SHAPE=RECT ALT="i" HREF="#" COORDS="0,0,8,142"
onMouseOver="strokeimage.src=stroke1.src ; window.status='i' ; return
true">~. Alt-text," short for "alternative text," triggers the
displays descriptive text meant to stand in place of the image, for
accessibility reasons and in the case that the image fails to
load. Without knowledge of the precise location of each alt-text
coordinate, accessing all of the alt-text embedded within the images
requires a peak at the source code, which lists the alt-text for each
of the 23 images one by one:
#+BEGIN_SOURCE 
<AREA SHAPE=RECT ALT="i" ..>
<AREA SHAPE=RECT ALT="believe" ...>
<AREA SHAPE=RECT ALT="in" ...>
<AREA SHAPE=RECT ALT="it" ...>
<AREA SHAPE=RECT ALT="you" ...>
<AREA SHAPE=RECT ALT="created" ...>
<AREA SHAPE=RECT ALT="it" ...>
<AREA SHAPE=RECT ALT="in" ...>
<AREA SHAPE=RECT ALT="my" ...>
<AREA SHAPE=RECT ALT="mind" ...>
<AREA SHAPE=RECT ALT="my" ...>
<AREA SHAPE=RECT ALT="mind" ...>
<AREA SHAPE=RECT ALT="cannot" ...>
<AREA SHAPE=RECT ALT="let" ...>
<AREA SHAPE=RECT ALT="it" ...>
<AREA SHAPE=RECT ALT="go" ...>
<AREA SHAPE=RECT ALT="the" ...>
<AREA SHAPE=RECT ALT="ocean" ...>
<AREA SHAPE=RECT ALT="the" ...>
<AREA SHAPE=RECT ALT="waves" ...>
<AREA SHAPE=RECT ALT="its" ...>>
<AREA SHAPE=RECT ALT="a" ...>
<AREA SHAPE=RECT ALT="vision" ...>
#+END_SOURCE
While the user may experience a number of these phrases as they pan
over the image, here the ordering creates a sense of coherence. When
viewed in this way, from the top-down, the words string together into
intelligible thoughts like "i believe in it," and "my mind cannot let
it go." What appears on the surface of the work, then, is only a
particle of the full description occuring below. 

Below the overt narrative of surface effects, lies another narrative
within the source code. Here, within the HTML and JavaScript that
define the content, presentation, and animations on the page, lie
secret messages meant for human eyes. While most of the work is visual
and haptic in nature, these hidden messages combine natural language
with code to make verbal exhortations of love. For example, on the
first page, "breath.html," an array of romantic protestations are
assigned to the value, "whispers." These "whispers," which include
phrases like "i will love you forever," "i want to breath you," among
others included below, do not manifest directly on the browser, which
only shows a moving image of a bared chest accompanied by breathing
sounds. Rather, the messages are hidden within the source code,
waiting only for the curious and experienced user to come and find
them.
#+BEGIN_SOURCE
whispers = new Array();
whispers[0] = "breath me";
whispers[1] = "i will love you forever";
whispers[2] = "skin";
whispers[3] = "skin on skin";
whispers[4] = "skin on skin on skin";
whispers[5] = "implode";
whispers[6] = "soft";
whispers[7] = "slow";
whispers[8] = "can you feel me?";
whispers[9] = "touch me";
whispers[10] = "one more cigarette";
whispers[11] = "i am so open";
whispers[12] = "i want to feel you inside of me";
whispers[13] = "smoke";
whispers[14] = "i want to breathe you";
whispers[15] = "we are smoke";
whispers[16] = "yesss";
whispers[17] = "deeper";
whispers[18] = "i am disappearing";
whispers[19] = "warm";
#+END_SOURCE

Musser describes foreclosure as an overflow of surface effects that
preclude understanding beyond them. Foreclosure is strategy of
resistance against attempts at incorporation. Something is always
withheld. Similarly, I want to suggest that computer code creates a
level of foreclosure by making elements always partially
inaccessible. The surface effects of the screen engage elements within
the code, sometimes in code from other pages, which are inaccessible
to the general user, to surface additional layers of foreclosure. For
example, the page, "close.html," takes a series of filenames from
"smoke.html" to overlay the image of the chest from "breath.html" (SEE
IMAGE). Rather than take the content of the files directly, this new
page takes the /filenames/ of the words, such as "ccy_01_Over.jpg."
The move creates a double foreclosure: first, in the original image,
which requires precise activation by the user's mouse; and second, in
the filename, which gives no indication of the image's content and
cannot be found (as far as I can tell) for further examination on the
server. In other words, the filenames on the chest stand for images
which the user cannot see directly. This effect surfaces a
displacement inherent in all significatory systems but particularly in
machine language systems, which rely on levels of abstraction in its
software stack.

[IMAGE OF CLOSE.HTML]

**** flash foreclosure
In "words.html,"
view-source:http://entropy8zuper.org/skinonskinonskin/rhizome/words.html
By Samyn on valentines day, 1999.

Samyn animates a beating heart, overlaid with words and phrases that
move in various arcs from its center. [SEE IMAGE/GIF]

The code for this page does various things: first, it defines the list
of strings, or words/phrases, which will arc over and around the
heart. Then, it includes a series of JavaScript functions that selects
words, calculates their trajectory and timing, and resets their
position to restart the loop.
#+BEGIN_SOURCE
unction startMove()
{
floatWords(0,Math.round(words.length/4));
setTimeout("floatWords(Math.round(words.length/4),Math.round(words.length/2));",5000);
setTimeout("floatWords(Math.round(words.length/2),Math.round(words.length/4*3));",10000);
setTimeout("floatWords(Math.round(words.length/4*3),Math.round(words.length));",15000);
};

function floatWords(startNumber,endNumber)
{
for ( i = startNumber ; i < endNumber ; i++ ) { floatWord(i); };
};

function rePos(thisNumber)
{
dMove('wordL'+thisNumber,'document.',halfW-rand(50),halfH-rand(50));
floatWord(thisNumber);
};

function floatWord(thisNumber)
{
var randTime = (rand(15) + 5 )*1000;
var thisRand = rand(4);
if ( thisRand == 1 ) { dMoveStraight('wordL'+thisNumber,'document.',-100-rand(100),rand(stageH),randTime,'wordVal'+thisNumber,'rePos(' + thisNumber + ');',''); }
else if ( thisRand == 2 ) { dMoveStraight('wordL'+thisNumber,'document.',rand(stageW),-20-rand(100),randTime,'wordVal'+thisNumber,'',''); }
else if ( thisRand == 3 ) { dMoveStraight('wordL'+thisNumber,'document.',stageW + rand(100),rand(stageH),randTime,'wordVal'+thisNumber,'rePos(' + thisNumber + ');',''); }
else if ( thisRand == 4 ) { dMoveStraight('wordL'+thisNumber,'document.',rand(stageW),stageH + rand(100),randTime,'wordVal'+thisNumber,'',''); }
if ( rand(4) == 1 ) { dShow('wordL'+thisNumber,'document.','visible'); };
}; "words.html"
#+END_SOURCE
I'm going to give a brief overview of each function. The first
function, ~startMove()~, sets a series of timers that initiate and
perpetuate the animation. The second function, ~floadWords()~, loops
through the list of words and phrases and passes individual selections
from this list to the next function, ~floatWord()~, which sets the
trajectory and timing for their movement. Within this function, a call
to ~rePos()~ repositions the word in a new location, to begin the
cycle anew. 

On line 98: "$we are disembodied arms and mouths "

Let us look more closely into the flash animation, which contains its
own foreclosures. Flash is a standalone application and web browser
plugin for authoring and viewing animations. It began development in
the mid-1990s and gained popularity for its ability to deliver
relatively advanced graphics (such as video and sound, primarily) at a
time when media-rich content traveled slowly over the web. However,
with the development of newer, more efficient and secure animation
technologies in the last 10 years, Flash began to fall out of
popularity and was officially discontinued on December
31st, 2020. Although the general internet user will not feel the
difference, since newer technologies like HTML5 and Javascript have
stepped up to deliver what Flash had initially offered in much more
flexible, portable, and efficient ways, this development has cast a
generation of internet games, net art, and electronic literature into
obsolesence. Today, the only way to view Flash content is through
plugins, emulators (like the one for /skin/), or "decompiler" programs
(discussed below).

The elements of foreclosure emerge most starkly with non-plain-text
content like Flash files. This is due to Flash code, unlike
plain-text, being a binary code format. If opened in a text editor,
for example, Flash files (which usually have an ".swf" or ".fla"
extention) would appear to be made of incomprehensible characters and
symbols, some of which the text editor may recognize, and others which
it would display as a question mark. For example, here is a plain text
rendition of the file that contains the sound animation of of the
heatbeat on "breath.html":

[IMAGE OF TEXT EDITOR OF OF HEARTBEAT.SWF]

Because binary code is unreadable to the human eye, it requires
specific authoring software to work with it. A "Flash decompiler"
program, for example, offers an interface for seeing the components of
a Flash file without having to deal with the machine code layer. The
file is separated into components. The above file, for example,
contains components like "sounds," "frames," and "scripts." So the
file becomes abstracted in a way that humans can make sense of
it. Below is an image of the flash decompiler interface, with all of
the components of the image on the left sidebar. Interestingly, when
examining the frames, one can distort the sound of the heartbeat.

[IMAGE OF FLASH DECOMPILER INTERFACE ON "HEARTBEAT.SWF"]

What I want to emphasize here is that this code cannot be edited
directly. 

How does an emulator work? Does emulation add another layer of
sensuality to the peice?]

The final aspect of this text I want to discuss is reduction. The love
affair is reduced to digital objects which can pass over the
wires. The couple make this point in a chat between the two of them,
discussing how constraints constitute the relationship:
#+BEGIN_QUOTE
womanonfire: the sound is a bit distorted with these things
zuper: (private) yes
womanonfire: if no one was around me here
zuper: (private) the image is distorted too
womanonfire: i would speak to you
zuper: (private) but that's ok
womanonfire: yes!
womanonfire: these are all part of our relationship
womanonfire: these limitations
womanonfire: we must
zuper: (private) 26 letters, no sound, no image
womanonfire: learn new ways
zuper: (private) make DHTMLove to me... http://entropy8zuper.org/
#+END_QUOTE

The way that digital objects play with reductions of complexity here
evokes what Snorton says about the reduction of black bodies to
flesh. Such a reduction enables flesh to harness the chaos of
significatory possibility. I want to argue that digital objects, as
distillations of real world referents, are imbued with expressive
potential.

In what follows, I'm going to examine the ways that Harvey's (black)
body has been reduced with this effect. The question of Harvey's race
emerges in a chat between Harvey and Samyn, though it is buffeted by
questions of physicality more generally. To get a sense of the
conversation, I quote the chat at some length: 
#+BEGIN_QUOTE
womanonfire: i wonder wht your voice is like
zuper: my voice?
zuper: let's try
zuper: it's weird to talk in a silent office at night
womanonfire: yes
womanonfire: i can just barely make you out
womanonfire: how fitting
womanonfire: it sounds so far away but you feel so close
zuper: yes
zuper: i am close
zuper: i don't understand myself
womanonfire: i will write you a very long letter tonight
zuper: I'm falling in love with a 160x120 pixel video...
zuper: Yes please write me a long letter
womanonfire: it is dificult for me here right now
zuper: why is it difficult?
womanonfire: i was just about to write one about this
womanonfire: because i love you
zuper: ...
womanonfire: seems so 
womanonfire: strange
womanonfire: maybe it is lust
womanonfire: i cant tell anymore
zuper: pixellust?
womanonfire: right
zuper: I my case only ASCIIlust...
womanonfire: but i want to make a home for us
womanonfire: in the network
zuper: Have you read Sterlings 'Holy Fire'?
womanonfire: no
zuper: They have places called 'Memory Palaces' on the net
zuper: where they keep all their souvenirs and where people can meet
womanonfire: i just heard you that time
womanonfire: !
zuper: in dutch!
womanonfire: yes!
zuper: (private) I realised today that I have never been in love with somebody who doesn't speak Dutch before.
womanonfire -> zuper: i have never been in love with someone in another country before
zuper: (private) I have never been in love with someone with green dreadlocks before
zuper: (private) let alone black skin
womanonfire -> zuper: yes i hope you wiwll like my skin
zuper: (private) I already do.
womanonfire -> zuper: :) http://entropy8zuper.org/ 
#+END_QUOTE
The question of race becomes one in a list of other physical
attributes, is equated to speaking a foreign language, is buffeted by
concerns about connectivity and finally, transported and made possible
by network technologies. 

The reduction of her body to certain attributes, her black skin and
green hair, for example, endows her physical being with expressive
possiblity. The dark-skinned green-haired floating woman. Here, the
less detail an element has, the more meaning the viewer can impose to
the elements.

We see this in the black hand which touches our screen. It is a simple
shape, but it is expressive.

l materiality hearkening back to black fem theory 
Sensuality in their shifts and their surface effects, particularly in
the way they foreclose /forensic/ materiality, refuse depth. Here we
draw from black feminist theorizing. 


** unstructured fragments
*** flesh becomes a queer form
Snorton explains that the materiality of a daguerreotype suggests "a
visual grammar for reading the imbrications of 'race' and 'gender'
under captivity" (40). In the daguerrotype, the surface becomes the
ground, flipping the traditional (presumptive) way of reading for what
is under the surface. This method is about /taking what has been a
method of reduction/, what has been a tool for appropriating the
complexity of real world objects for the purpose of exploitation, and
using that /to instead seek out moments of obfuscation/, a kind of
diversion from or forclosure to objectification, which does not
attempt to deny the power of objectification. These strategies are
rooted in ways of reading materiality, in the ways that Black Feminist
Studies have discovered within the violent history of the Black flesh
some kind of *subversion*, which is not quite resistence, which is not
quite empowerment. To approach material as something slippery,
shifting, which confuses rather than resolves meaning.

It leads to a *re-formulation* for understanding the interaction
between the material and the symbolic in media, and how these relate
to power dynamics. Eventually, we will look at /skinonskinonskin/ to
read these qualities of the flesh--opacity, torque, vulnerability--in
the technological stack. But first, it will be helpful to ground our
discussion in Media Archaeological debates.



*** unmappability, collision of registers
This inexctricability of physical sensation from mental interpretation
has an analogue in the collision of registers, such as the visual and
the material. C. Riley Snorton describes this collision as
"unmappability," relating this ambiguous and liminal space to the
process of racialization. As an example, Snorton does a close reading
of a the material qualities of a daguerrotype, an early method of
photography:
#+BEGIN_QUOTE
To view a daguerreotype is to look at an image that does not sit on a
surface but appears to be floating in space. Rather than an antiquated
form of modern photography, as Foucault’s characterization implies,
the daguerreotype provides a series of lessons about power, and racial
power in particular, as a form in which an image takes on myriad
perspectives because of the interplay of light and dark, both in the
composition of the shot and in the play of light on the display. That
the image does not reside on the surface but floats in an unmappable
elsewhere offers an allegory for race as a procedure that exceeds the
logics of a bodily surface, occuring by way of flesh, a racial
mattering that appears through puncture in the form of a wound or
covered by skin and screened from view. 40
#+END_QUOTE
The format of the dagguereotype evokes the method by which meaning is
stripped then reapplied to flesh that, for captive bodies, "functioned
as a disarticulation of human form from its anatomical features"
(18). The physical material of the image, that is the silvered copper
plate of the daguerreotype, at once solidifies its ground and indexes
an ambiguous space, what Snorton describes as the "unmappable
elsewhere" which swells to obscure while simultaneously containing the
evidence of racial significations. Snorton's curious use of the word
"puncture" here recalls Roland Barthes's concept of the "punctum,"
which indexes the experience of being pierced by a detail of the
photograph (/Camera Lucida/ 27). Opposed to the concept of the
/studium/, which represents the dominant historical, social, or
cultural meaning portrayed within and by the photograph, the /punctum/
is the "sting, speck, cut, little hole... that accident which pricks
me (but also buises me, is poignant to me)" (Barthes /Camera Lucida/
27-28). Barthes explains that, "However lightning-like it may be, the
/punctum/ has, more or less potentially, the power of expansion. This
power is often metonymic" (/Camera Lucida/ 45). For Barthes, the
/punctum/ is that detail of a photograph which at once pierces the
viewer and suggests an expansion, an effect which is exagerrated in
erotic photographs, where the /punctum/, "is a kind of subtle
/beyond/--as if the image launched desire beyond what it permits us to
see" (59). Barthes's theorization of the /punctum/ allows us to see
how the flesh can be at once a /mattering/, a becoming matter, and an
accumulation of meaning, which in simulteneity, has the effect peirces
the viewer. We cannot, as Snorton points out, locate the image at a
specific point on the copper-plate is essential, though we can feel
its puncture. That the image cannot be traced back to a single
location, yet is contained and signifies within that physical space,
is crucial for undersanding the way that the physical registers
interact with symbolic ones. The meeting between this liminal space of
the image's visual content and its silver-plated copper ground offers
another perspective for understanding the collision of flesh and
racialization.


* Works
Alarcon, Norma. "Conjugating Subjects in the Age of Multiculturalism"
/Mapping Multiculturalism/. Avery F. Gordon and Christopher Newfield,
editors. University of Minnesota Press. pp. 127-148.

Barthes, Roland. /Camera Lucida/.

Butler, Octavia. Dawn. Grand Central Publishing. 1987.

Chun, Wendy. Control and Freedom: Power and Paranoia in the Age of Fiber Optics. 2006.

Entropy8Zuper!. skinonskinonskin. Rhizome. https://anthology.rhizome.org/skinonskinonskin 

Galloway, Alexander and Eugene Thacker. The Exploit: A Theory of Network. Univ Of 
Minnesota Press. 2007. 

Galloway, Alexander. Protocol: How Control Exists after
Decentralization. 2004.

Hartman, Saidiya. "Venus in Two Acts." /Small Axe/, vol. 12 no. 2,
   2008, p. 1-14. Project MUSE muse.jhu.edu/article/241115.

Hayles, N. Katherine. Writing Machines. MIT Press, 2002. p. 107.

Kirschenbaum, Matthew G. Mechanisms: New Media and the Forensic Imagination. MIT Press 
2008.

Moraga, Cherrie. "La Guera", from /Loving in the War Years: Lo que
nunca paso' por sus labios/.

Musser, Amber Jamilla. /Sensual Excess: Queer Femininity and Brown
Jouissance/. NYU Press,
2018. JSTOR, http://www.jstor.org/stable/j.ctvwrm5ws. 

Musser, Amber Jamilla. "Surface-Becoming: Lyle Ashton Harris and Brown
  Jouissance." /Women & Performance/, vol. 28,. no. 1. February 26, 2018
  https://www.womenandperformance.org/bonus-articles-1/28-1-harris. 

Schutte, Ofelia. “Cultural Alterity: Cross-Cultural Communication and
Feminist Theory in North-South Contexts.” /Hypatia/, vol. 13, no. 2,
1998, pp. 53–72.

Snorton, C. Riley. Black on Both Sides: A Racial History of Trans Identity. University of 
Minnesota Press, 2017. JSTOR, https://doi.org/10.5749/j.ctt1pwt7dz;

Spillers, Hortense J. “Mama’s Baby, Papa’s Maybe: An American Grammar Book.” Diacritics, 
vol. 17, no. 2, 1987, pp. 65–81. JSTOR, https://doi.org/10.2307/464747

