* three
#+SEQ_TODO: TODO(t) WAITING(w) IN_PROGRESS(p) WAITING(w) FOLLOWUP(f) | CANCELLED(c) DONE(d)

"Sex, Flesh, Skin: A Media Archaeology of Octavia Butler's /Dawn/ and
Entropy8Zuper!'s /skinonskinonskin/"

** chapter overview
This paper juxtaposes two unlikely texts--an early hypertext work from
1999, and a science fiction novel from 1987--to unpack the role of
“media” across physiological and technological systems. The early
hypertext work, /skinonskinonskin/, written collectively by the
artist-couple known as Entropy8Zuper!, explores
electronically-mediated desire through a series of digital love poems
that combine hypertext, audio, and Flash media technology. Moving from
digital to embodied desire, the science fiction novel, Dawn by Octavia
Butler, poses a post-apocalyptic scenario where humans find themselves
coerced into sex and procreation with extraterrestrial colonizers. In
these couplings, sexual contact is routed through an alien
intermediary, whose ability to plug directly into the human brain’s
pleasure centers intensifies their sexual instincts into all but
irresistible compulsions. Though Butler’s novel and skinonskinonskin
present vastly different narrative worlds and physical formats, I’m
interested in how both texts trouble the boundary between materiality
and abstraction, in one case technological, through computer hardware
and software, and in another physiological, through nervous systems
and brain chemistry.

My analysis reads for sensuality across medial environments in each
text. In Butler’s novel, I examine how human flesh--the traditional
site for sexual contact between two partners--is bypassed for direct
neural stimulation facilitated by an alien intermediary. Because this
direct neural connection scrambles traditional distinctions between
the body and mind, during the sex act, the humans have trouble
differentiating their embodied feelings from their cognitive
interpretations. By bypassing the flesh, this method of intercourse
dissolves the binary between self and other--the foundation for
possessive individualism--as well as sense and thought. Drawing from
thinkers in Chicanx Studies and Black Feminist Studies, I argue that
this method creates an ethics based on pleasure rather than choice or
consent.

To better understand the compulsions of pleasure and the flesh, I
engage Black Feminist Studies’ theorizing on the flesh. According to
critics like Hortense Spillers, C. Riley Snorton, and Amber Jamilla
Musser, the systematic reduction of the Black body to the physical
flesh, a process that began during the violences and atrocities of the
Middle Passage, creates an opportunity for rethinking the political
potential of pleasure and eroticism. In my analysis, this concept of
the flesh becomes a ground for understanding how physical registers
interact with symbolic ones. Here, I examine how the concept of the
Pornotrope, that is the reduction of body to flesh, of the conceptual
(body) to the material (flesh), creates a ground for new theorizations
of meaning and materiality. Specifically, this reduction of Body to
Flesh offers a model of resistance to racial exploitation that
reinforces sensuality and pleasure.

Turning to /skinonskinonskin/, I examine the hardware and software
formats that facilitate the display and preservation of this work,
tracing the complicated stack of technologies, which include web tools
and Flash media. Borrowing from Media Archaeology I take a close look
at what Matt Kirschenbaum describes as the “formal” level of
materiality, or the effects on the screen, moving down the layers of
abstraction, through the compiled code of Flash media, into the level
of hardware, what he calls the “forensic materiality,” of the internet
network. My goal is to examine the material qualities of the
medium--be it technical or physiological--for the ways it offers a
kind of capacious mode for theorizing new forms of ethical relations.


** sex
*** section overview
These sections examine human vs Oankali social structures to read the
priortization of sensuality and feeling as a basis for more ethical
relationships. While human nature struggles within the "contradition"
of hierarchy and intelligence, the Oankali harness thier physiological
ability to bypass flesh for direct neural connections that enable
collectivity. The Oankali offer a model of ethics based on mutual
feeling, rather than choice or consent. In the process of having
"neural" sex with each other through the aliens, the humans begin to
blend cognitive processes with their sensual experiences. The blending
of thought and feeling shows a collision of registers, which will be
useful for my media archaeological reading of the stack of
technologies in the hypertext peice, /skinonskinonskin/.

The crucial point of this section occurs in my close-reading of the
scene when Lilith first meets the aliens, and her experience of
xenophobia, which is crytallized in her use of the comparison to
"Medusa". I draw from Chicana Studies to explain how the comparison to
Medusa expresses a fear of the unknown through the frame of the
known. Furthermore, it shows the "human contradiction" at work--the
intersection of a hierarchical impulse and a capacity for
intelligence--a contradiction which the novel demonstrates can be
resisted overcome by bypassing the flesh, which is the topic of my
next section.

*** /Xenogenesis/ to xenophobia: intro
In the novel /Dawn/, the first of the /Xenogenesis/ trilogy by Octavia
Butler, the main character, Lilith Iyapo, is seduced by an alien. The
alien, called "Nikanj," is an ooloi, or third-gendered being. Nikanj
coaxes Lilith to join it and her human partner, Joseph: "'Lie here
with us,' it says, 'Why should you be down there by yourself?'" (PAGE
NUMBER). Lilith's erotic impulse is difficult to resist:
#+BEGIN_QUOTE
She thought there could be nothing more seductive than an ooloi
speaking in that particular tone, making that particular
suggestion. She realized she had stood up without meaning to and taken
a step toward the bed. She stopped, stared at the two of
them. Joseph’s breathing now became a gentle snore and he seemed to
sleep comfortably against Nikanj as she had awakened to find him
sleeping comfortably against her many times. She did not pretend
outwardly or to herself that she would resist Nikanj’s invitation—-or
that she wanted to resist it. Nikanj could give her an intimacy with
Joseph that was beyond ordinary human experience. And what it gave, it
also experienced. PAGE NUMBER
#+END_QUOTE
The erotic draw that Lilith experiences is intense enough to make her
temporarily ignore that these aliens, called "Oankali," have descended
upon earth with one goal: to coerce humans to reproduce with them,
creating a human-alien species. As ooloi, Nikanj has a special sexual
organ that enables a neural connection between a male and female
partner, in this case, between Lilith and Joseph. It makes this
connection by inserting its sexual organ, a "sensory hand," into its
partner's spinal cord, located at the back of the neck. Then, during
the sex act, the alien collects reproductive material which it will
eventually use to engineer a viable embryo made of human and Oankali
genes.

Despite her eagerness to join Nikanj in sex, Lilith harbors a deep
resistance against the Oankali's intention to procreate with
humanity. Scenes like the one above, in which Lilith surrenders to her
sexual desire, appear in stark contrast to her determination to
escape, conveyed by her invocation to "Learn and run!" which she
repeats up until the last page of the novel. Having barely survived a
nuclear apocalypse only to be "rescued" by the aliens, Lilith, along
with the surviving humans, is being held on the Oankali spaceship in
preparation to do their part in the "gene trade"--that is, to help
re-populate the earth with the new human-Oankali species. The Oankali
have given Lilith a special job to be a shepherd, what she calls a
"Judas goat," to guide humans to accept that humanity will change
forever, that their children will look like "Medusa children" (Butler
87).

The conflict between various biological drives, such as sex drive
versus the survival drive, speaks to a larger debate among the novel's
critics about the primacy of biological impulses in determining human
behavior and characteristics. For, even when this sex act appears
contained to the mind, it is always portrayed as something that relies
on and is guided by the material exegencies of the body. Donna Haraway
and Kitty Dunkley, for example, argue that the interspecies couplings
challenge assumptions about biological essentialism that power
naturalized notions of sex, race, and the human/animal
divide. Haraway's influential reading of the novel, from her book
/Primate Visions: Gender, Race, and Nature in the World of Modern
Science/ (1989), situates the novel as a feminist, posthuman critique
of human-animal hierarchies and divisions. Reading the novel "as if it
were a report from the primate field in the allotopic space of earth
after a nuclear holocaust," Haraway sites the inter-species relations
and the way these relations reconceive notions of choice and consent
as examples to "facilitate revisionings" of "difference, reproduction,
and survival" (Haraway 376, 377). 

On the other hand, critics like Stephen Barnes, Nancy Jesser, and Erin
Ackerman argue for the primacy of biology in naturalizing aspects of
identity. Stephen Barnes, who knew Butler personally and
professionally during her life, maintains that her biological
researches influenced her beliefs about human nature, particularly as
the development of hierarchical tendencies. According to Barnes,
Butler was fascinated by what she called "emergent properties," which
begin from small impulses, like the tendency to categorize something
as either similar or different, as the seeds of complex social
behaviors and structures. Nancy Jesser brings this idea to the
portrayal of sex, arguing that "the plot relentlessly reinforces
certain sociobiological notions of essential and 'natural' male and
female through the concept of biological 'tendency'" (Jesser
41-42). 

*** TODO add connection to queer studies, critical debate on biology
This paper argues that the heterosexual paradigm is indeed disrupted,
and it is disrupted by a queer mode of relation which emerges in the
tripartite sexual union enabled by the ooloi figure. The linkage of
neural pathways between two bodies, a linking that bypasses the
obstacle of flesh to connect directly to the brain's pleasure centers,
scrambles the distinctions between thinking and feeling. This chemical
signaling surfaces a clashing of registers between cognition and
sensation that dissolves the differences between the materiality of
the flesh and the abstraction of cognitive processes. This kind of sex
also blurs the binary between self and other--the foundation for
possessive individualism.

This chapter will explore this clashing of registers across three
domains: science fiction (that of Butler's novel), Black Feminist
Studies, and Media Archaeology Studies. I will examine how each of
these domains handles the intersection of physical embodiment with
chemical, conceptual, and/or electrical signaling, reading for
sensuality across various medial environments in each domain. 

First, in Butler's novel, I seek moments of heightened sensuality,
which occurs not only in sexual contact, but interestingly, in moments
of xenophobia when the humans encounter the aliens. My close-reading
of these moments finds that desire and fear work similarly to scramble
traditional distinctions between the body and mind, which struggle to
differentiate embodied feelings from their cognitive
interpretations. The blending of physical and conceptual registers
here enables a new, human-alien ethics based on pleasure rather than
choice or consent. Then, to explore this new ethics, I engage Black
Feminist Studies’ theorizing on the flesh. According to critics like
Hortense Spillers, C. Riley Snorton, and Amber Jamilla Musser, the
systematic reduction of the Black body to the physical flesh, a
process that begins during the violences of the Middle Passage,
creates an opportunity for rethinking the political potential of
pleasure and eroticism. This concept of the then flesh becomes a
ground for understanding how physical registers interact with symbolic
ones in my final section, on electronic media. Turning to a hypermedia
narrative work, /skinonskinonskin/, I examine its hardware and
software formats, tracing the complicated stack of technologies that
include programming languages and Flash media. Borrowing from Media
Archaeology, I take a close look at what Matt Kirschenbaum describes
as the "formal" level of materiality, or the effects on the screen,
build on layers of software abstractions, against what he calls
"forensic materiality," which is the level of hardware, bits and
signals. My goal is to examine the material qualities of the
media--physiological and technical--for the ways materiality offers a
kind of capacious mode for theorizing new forms of ethical relations.

For the rest of this section on /Dawn/, I will deconstruct the erotic
as a physical, sensual phenomenon. Where do thought and feeling
intersect in moments of heightened sensuality? How does approaching
thought as physical, or feeling as conceptual, change the way we think
about ethics and social relations, especially those that concern
choice and consent? To answer these questions, I will first examine
one of these moments of heightened sensuality, that of extreme fear,
to tease a connection between xenophobia and xenogenesis.

*** fear of the unknown
We begin with a moment of fear from early in the story, when Lilith
first comes face-to-face with her captors. Jhadaya, a male Oankali,
meets Lilith in her isolation room. Initially, Lilith processes his
alien body much like human anatomy:
#+BEGIN_QUOTE
The lights brightened as she had supposed they would, and what had
seemed to be a tall, slender man was still humanoid, but it had no
nose--no bulge, no nostrils--just flat, gray skin. It was gray all
over--pale gray skin, darker gray hair on its head that grew down
around its eyes and ears and at its throat. There was so much hair
across the eyes that she wondered how the creature could see. The
long, profuse ear hair seemed to grow out of the ears as well as
around them. Above, it joined the eye hair, and below and behind, it
joined the head hair. The island of throat hair seemed to move
slightly, and it occurred to her that that might be where the creature
breathed--a kind of natural tracheostomy.

Lilith glanced at the humanoid body, wondering how humanlike it really
was. "I don't mean any offense," she said, "but are you male or
female?"

"It's wrong to assume that I must be a sex you're familiar with," it
said, "but as it happens, I'm male."

Good. It could become 'he' again. Less awkward. 29
#+END_QUOTE
Although Jdhaya points out Lilith's mistake about assuming gender, she
nonetheless takes some comfort from being able to call Jdhaya a "he."
The gender designation, along with a catalogue of mammalian anatomical
features "hair," "eyes," "ears," and "throat," display the strength of
an impulse to categorize the unknown according to human
terms. Lilith's comfort, however, is short-lived, when the strangeness
of the alien's appearance exceeds the terms available to her:
#+BEGIN_QUOTE 
She did not want to be any closer to him. She had not known what held
her back before. Now she was certain it was his alienness, his
difference, his literal unearthliness. She found herself still unable
to take even one more step toward him.

"Oh god," she whispered. And the hair--the whatever it
was--moved. Some of it seemed to blow toward her as though in a wind,
though there was no stirring of air in the room.

She frowned, strained to see, to understand. Then, abruptly, she did
understand. She backed away, scrambled around the bed and to the far
wall. When she could go no farther, she stood against the wall,
staring at him.

Medusa. 30
#+END_QUOTE 
The attempt to understand Jhadaya's difference is more instinctual
than logical. As Lilith attempts to place the alien into familiar
categories, she undergoes a complex physiological process. First, she
deploys anatomical categories to perceive Jhadaya. Then, as his
difference begins to register, she apprehends him on a pre-linguistic,
embodied level, which is expressed by an paralyzing aversion--"She
found herself unable to take even one more step toward him"
(29-30). When Lilith examines his face more closely, the interval of
immobilizing fear ends abruptly with her "understand[ing]." Her final
impulse is to express her aversion in figurative language, with an
evocation of the mythical figure "Medusa."

Medusa here is significant. It demonstrates that Lilith subscribes the
unknown in terms of something that is familiar to the human imaginary,
ableit in the context of myth and fantasy. The physio-cognitive
progression from instinctual body movement to intellection recalls a
deeper reality about humanity and how it handles the unknown. This can
be attributed to human genetics which express, according to the
Oankali, the "human contradiction." Later in this scene, Jhadaya,
explains this contradiction in terms of two characteristics: 
#+BEGIN_QUOTE
"You are intelligent," he said. "That's the newer of the two
characteristics, and the one you might have put to work to save
yourselves. You are potentially one of the most intelligent species
we've found, though your focus is different from ours. Still, you had
a good start in the life sciences, and even in genetics."

"What's the second characteristic?  

"You are hierarchical. That's the older and more entrenched
characteristic. We saw it in your closest animal relatives and in your
most distant ones. It's a terrestrial characteristic. When human
intelligence served it instead of guiding it, when human intelligence
did not even acknowledge it as a problem, but took pride in it or did
not notice it at all..." [...] "That was like ignoring cancer. I
think your people did not realize what a dangerous thing they were
doing."
#+END_QUOTE
According to Jhadaya, the tendency toward hierarchy, as a
"terrestrial" characteristic, is ingrained in all humans. The impulse
to stratify people, to create social groupings, even to colonize and
oppress, descends from an ancient instinct that once served to
sustain, protect, and organize early human tribes. But when the
hierarchical instinct grows unchecked into the modern world, Jdhaya
explains, it creates unjust divisions, such as stratifying people
along gender, race, nationality, and class, for example. 

Fear, then, descends from biological imperatives: the human
constradiction, a combination of intelligence and hierarchy. For
Lilith, then, the tendency toward hierarchy first demands that she
place this being on a scale of familiarity. She compares Jhadaya to
what she already knows about other living beings, that he fits into a
binary gender designation, for example. However, when the hierarchy
fails to subsume his other qualities, like the tentacles emerging from
all over his body, her intelligence steps in to speculate with an
analogy, "Medusa." Her mind makes the leap between what she sees and
what she can imagine.

*** fear of the known
That Lilith uses an analogy to the Medusa indicates something
important about this particular type of xenophobia--that her fear is
not just of otherness, but in the interplay between otherness and
similarity. It is this interplay between similarity and difference and
their combination in nontraditional ways causes a reaction of fear and
repulsion. What scares Lilith is an apparent familiarity of this humanoid,
bipedal, two-limbed creature, which has an audible language and
conscious intelligence and displays aspects that do not belong to any
mammal--the tentacles. Lilith's use of the "Medusa" comparison marks
the moment when she, who until then has been struggling to place a
strange being within known phenomena, finally settles onto a familiar
designation. Despite his alienness, at that point, Jhadaya becomes
incorporated into an anthropocentric worldview--specifically, into a
fearsome figure that represents monstrous and deadly femininity.

The criticism from the novel examines this interplay of similarity and
difference, much of it situating the tension within Women of Color
feminism, particularly in Chela Sandoval's theorization of
"differential consciousness." In an early and influential commentary,
Donna Haraway describes /Dawn/ as an example of the
"techno-bio-politics of difference" (Haraway, /Primate Visions/
376).[fn:3] Using terms that echo in her famous followup work, "The
Cyborg Manifesto," she describes this text (and Butler's fiction in
general) as being "about the monstrous fear and hope that the child
will not, after all, be like the parent" (Haraway /Primate Visions/
387). Catherine S. Ramirez builds from both Sandoval and Haraway to
explore the tension between essentialism and constructedness in the
novel, which she calls an example of "cyborg feminism"--a feminism
that explores a strategic tension between between "affinity and
essence, and "plurality and specificity" (Ramirez 395). Ramirez argues
that, by "critiqu[ing] fixed concepts of race, gender, sexuality and
humanity, and, subsequently, 'fictions' of identity and community"
this work displays a "strategic deployment of essence," that is, the
claiming of a subject position for the purpose of resisting
subjectification (Ramirez 375, 395).[fn:2] Ramirez explains that while
difference is necessary, essentializing is also necessary within a
feminist project. While essential understandings of identity have been
used to reduce, denigrate, and oppress identity groups, some kind of
positionality with regard to identity is necessary in order to
"forg[e] links between women from distant and disparate locations"
(Ramirez 384). It is a quality that enables connection and recognition
across differences.

Women of this movement were also careful to emphasize the danger in
overlooking differences among groups. Seeding the ideas that will
eventually become the Intersectional Feminist movement in the 21st
century, Women of Color Feminism's critique of identity politics, such
as the universalizing of terms like "woman," emphasizes a strategic
deployment of difference toward the goal of aligning across social and
cultural groups. As bell hooks explains, the rally for solidarity
across "women" has the effect of overlooking differences contained
within women, such as the ways that category intersects with race,
gender, class, ability, and so on. hooks emphasizes the need for
specific terms that make legible different lived experiences across
social groups. For example, she points out that the word "oppression"
fails to represent the situation of all women: "Being oppressed means
the absence if choices... Many women in this society do have choices
(as inadequate as they are); therefore exploitation and discrimination
are words that more accurately describe the lot of women collectively
in the United States" (/Feminist Theory: From Margin To Center/ 5). In
striving for solidarity, one must be careful not to collapse
difference. They key here is specificity. A differential consciousness
locates similarity across difference without negating the ways that
difference inflects lived experience.

While the criticism on the novel does a good job of situating the
tension between similarity and difference within WOC feminism, I am
interested in this experience of difference and
similarity-in-difference as a physiological response, and what that
can teach us about ethical relations. As Lilith exhibits with the
Medusa analogy, the interplay between similarity and difference
instigates fear. There is an encounter with the other, which triggers
xenophobia. But as Chicana feminist and writer Cherrie Moraga
explains, the feeling of fear is heightened by a perceived
similarity. Speaking within the context of social hierarchies, Moraga
explains that, "it is not really difference the oppressor fears so
much as similarity.... He fears he will have to change his life once
he has seen himself in the bodies of the people he has called
different" (32). In the her first meeting with Jhadaya, Lilith's fear
response heightens when she realizes that his anatomy is different
from the familiar human anatomy: "She had not known what held her back
before. Now she was certain it was his alienness, his difference, his
literal unearthliness" (Butler 30). Lilith, who first registers
Jhadaya in terms of similarity, describing his ears, mouth, and hair,
experiences an intense form of fear when she acknowledges the
difference in his figure.

*** TODO fear is a sensual phenomenon
As evidenced by the example of "Medusa," the two sides of the human
contradiction, hierarchy and intelligence, work together to engender a
sense of all-consuming fear of the other.

Similarity perceived across difference causes fear. However, at the
same time that it causes fear, it also offers an opportunity for
connection, according to Chicana feminists like Moraga and Gloria
Anzaldua. Moraga, who describes herself as "la guera," the
light-skinned one, among her family, draws from her sexuality to
relate across this difference. Speaking of her relationship to her
mother, Moraga explains that:
#+begin_quote
It wasn't until I acknowledged and confronted my own lesbianism in the
flesh that my heartfelt identification with and empathy for my
mother's oppression--due to being poor, uneducated, and Chicana--was
realized. My lesbianism is the avenue through which I have learned the
most about silence and oppression, and it continues to be the most
tactile reminder to me that we are not free human beings. Moraga 28-29
#+end_quote
Here, the thing that makes Moraga different, her sexuality, is what
enables her to make a connection to other kinds of difference,
specifically differences across skin tone. This confrontation occurs
"in the flesh," meaning that difference is felt, as a sensational
phenomenon. Rather than sever the relationship with her mother,
Moraga's embodied experience of her difference, her lesbianism, serves
as a "tactile reminder" that can bridge the gap between self and
other. 

When difference is a source of "silence and oppression," as it has
been for Moraga's sexuality, finding similarity requires a deeply
sensual process.

Gloria Anzaldua, a Chicana lesbian like Moraga, explores a method for
/incorporating/ difference into identity in the form of figuration and
embodied states. Anzaldua, who grew up in the remote "el Valle" region
on the Texas-Mexico border, emerges from a Aztec, Spanish, and Mexican
backgrounds with the goal of integrating her indigenous roots into a
modern Chicana identity. Anzaldua knows that surfacing this history
and heritage will require "developing a tolerance for contradictions,
a tolerance for ambiguity... learn[ing] to be an Indian [sic] in
Mexican culture, to be a Mexican from an Anglo point of view"
(Anzaldua 78-79). Anzaldua resurrects and incorporates latent and
fearful aspects of the cultural psyche in the form of the ancient
Aztec goddess, Coatlicue. Like Medusa, Coatlicue is associated with
snakes, her name translating from Nahuatl into "serpent skirt," and
she is often depicted with a skirt of serpents, as well as a necklace
of human hearts. Originally, as the "Earth Mother who conceives all
celestial beings out of her cavernous womb," Coatlicue represents a
unity of opposites, the dual forces of life and death, fertility and
destruction (Anzaldua 46). Over time, however, Anzaldua explains that
this unity has been severed into aspects such as the pure from the
impure. First, Aztec culture, influenced by a growing patriarchy,
split Coatlicue into the fertility earth goddess, "Tonantsi" (the
puta) and into "Coatlalopeuh" (the chaste) (27). Then, with the
arrival of the Spaniards, the figures were split again, this time into
the Virgin of Guadalupe, the most revered figure of Mexican
Cathololicism, with the negative aspects incorporated into the figures
La LLorona and La Chingada.

/Coatlicue/ incorporates the originary whole that holds all aspects,
positive and negative, of the self. Anzaldua's goal is to bring back
the severed aspects of Coatlicue and unifiy them into a modern
imaginary: "Coatlicue- Cihuacoatl- Tlazolteotl- Tonantzin-
Coatlalopeuh- Guadalupe--they are one" (50). Anzaldua affirms that,
"Let the wound caused by the serpent be cured by the serpent"
(50). The process by which Anzaldua accesses and integrates the
scattered aspects of Coatlicue is the "/Coatlicue/ state." Here,
Anzaldua enters into a trance, a spiritually open state, to confront
the pain, shame, and lonelienss of a severed identity. She explains
that, "We need /Coatlicue/ to slow us up so that the psyche can
assimilate previous experiences and process the changes... Our
greatest disappointments and painful experiences--if we can make
meaning out of them--can lead us toward becoming more of who we are"
(Anzaldua 46). The process is a difficult one; it requires seeing the
darkness in the other, and and incorporating that darkness into
feelings of disappointment and pain. In her encounter with
/Coatlicue/, Anzaldua describes a visual process of confrontation
between the self and other, /Coatlicue/:
#+begin_quote
Seeing and being seen. Subject and object, I and she. The eye pins
down the object of its gaze, scrutinizes it, judges it. A glance can
freeze us in place; it can "possess" us. It can erect a barrier
against the world. But in a glance also lies awareness,
knowledge. These seemingly contradictory aspects--the act of being
seen, held immobilized by a glance, and "seeing through" an
experience--are symbolized by the underground aspects of /Coatlicue/,
/Cihuacoatl/, /Tlazolteotl/ which cluster in what I call the
/Coatlicue/ state. 42
#+end_quote
Here, vision is simultaneously a tool for capture, for being "pin[ned]
down" or "immobilized," and a tool of enlightenment, in "awareness,
knowledge." Anzaldua embraces the duality of this aspect, and in what
seems to be a paradoxical effect, which is freedom in
possession. Being the object of /Coatlicue/'s gaze is both to
reliquish agency and to open a connection. This enables an intimate
relation to the other, but without total incorporation. Anzaldua's
repeatedly emphasizes the importance of containing duality, opposites,
which she also figures as "a struggle of borders," or a "choque" of
cultural collisions (Anzaldua 78-79). Rather, the power that comes
from confronting and connecting with the other stems a sense of
incompletion, partiality, and lack of fulfillment. Latin American
philospher Ofelia Schutte, describes this aspect as
"incommensurability." Writing on the problem of "cross-cultural
communication," or "how to speak to the 'other' who is different from
oneself," Schutte proposes that one attend to incommensurability, the
"residue of meaning that will not be reached in cross cultural
endeavors" (Schutte 53, 56). In conversation, for example,
interlocutors can observe moments when the other's speech "resonates
in [one] as a kind of strangeness, a kind of displacement of the usual
expectation" (Schutte 56). This process keeps the other in some way
unknowable or un-essentializable.

**** -> alarcon: sustain strangeness rather than incorporating it
Alarcon Alarcon makes a similar point in her argument about the
dangers of "ontologiz[ing] difference," that is, of subsuming specific
difference into a universal identity politics. She explains that,
  #+BEGIN_QUOTE
  The desire to translate as totalizing metphorical substitution without
  acknowledging the "identity-in-difference," so that one's own system
  of signification is not disrupted through a historical concept whose
  site of emergence is implicated in our own history, may be viewed as
  a desire to dominate, constrain, and contain. 133 
  #+END_QUOTE
  The challenge is to achieve connection without totally subsuming the
  other into totalizing and therefore oppressive paradigms of
  subjectivity 

The point here is to not subsume that quality of strangeness in the
  other into familiar structures of knowledge, like the way that
  Lilith subsumes Jhadaya's strangeness into the similitude of the
  terrifying Medusa. Rather, the point is to sustain the strangeness
  without attempting to block it out.

*** pleasure
Oankali do not have a fear of difference, they crave it.  Oankali,
unlike humans, are attracted to difference. As Jhadaya explains to
Lilith: "We acquire new life, seek it, investigate it, manipulate it,
sort it, use it. We carry the drive to do this in a minuscule cell
within a cell, a tiny organelle within every cell of our bodies"
(84). This essential drive, which powers their "gene trade," is made
possible by that which the humans find most disturbing about their
captors--the tentacle-like organs that sprout from their bodies. These
organs transmit all external sensory information such as sight,
hearing, touch, smell, and taste, provide channels for the immediate
sharing of thoughts and feelings in intra-Oankali communication, and
faciliate sex.

Unlike humans, Oankali can close the gap between self and other. This
sensory capacity puts them into direct contact with those who are
different. As a result, the Oankali do not fear difference, rather,
they crave it. They seek to blend with difference and incorporate it
into new life forms, an expanding species. This craving to absorb
difference is encoded in their genetic ancestry. Nikanj, the ooloi
child who will eventually become Lilith's mate, explains to Lilith
that "'Six divisions ago, on a white-sun water world, we lived in
great shallow oceans'[...] 'We were many-bodied and spoke with body
lights and color patterns among ourself and among ourselves"
(123). From this ancestry, the current Oankali inheirited a drive for
collectivity.

Because health and vitality are necessary in order to "trade" genes,
the Oankali do not admit any form of harm or destruction to life. At
several points in the book, this regard for life combined with the
inability to deceive make it difficult for the Oankali to understand
(and therefore anticipate) human tendencies for violence. For example,
the Oankali overlooked suspicion, paranoia, and rebellion among the
humans, which leads to violence and death toward the end of the
novel. Joseph, Lilith's partner, is killed by a group of humans who
the Oankali have let escape. Due to their biological imperative for
life, and the Oankali were unable to anticipate the violence and
couldn't not save Joseph's life in time. Not only are the Oankali
blind to motives of violence, but they also have different views on
consent. Soon after Joseph's murder, Nikanj then uses Joseph's genetic
material to impregnate Lilith without her knowledge, much less her
consent. It explains to Lilith that it only gives her what she truly
wants, which is a child:
#+BEGIN_QUOTE
"You'll have a daughter," it said. "And you are ready to be her
mother. You could never have said so. Just as Joseph could never have
invited me into his bed--no matter how much he wanted me
there. Nothing about you but your words reject this child." 468-9.
#+END_QUOTE
For the Oankali, sustaining and cultivating life is the principal
factor for decision-making. Nikanj's reasoning is simple: it knows
Lilith will love and accept the child. When Lilith protests that "It
won't be human," it warns that "You shouldn't begin to lie to
yourself. It's a deadly habit. The child will be yours and Joseph's"
(469). This quality of the instant and intimate connection is so
encompassing that it nullifies any need for deception between Oankali
who cannot avoid full disclosure and as a result, never lie.

- mental v embodied consent
This tendency for collective consciousness, distributed among the
beings, singular and plural at once, "ourself and ourselves,"
destabilize the an assumption underpinning free will, that of
consent. The sex scenes in particular portray a level of sensual
pleasure and connection that it is difficult to separate embodied
desire from conscious will. As Jayna Brown points out, "the
pleasurable experience of sex with the Ooloi is so highly compelling
it is sometimes likened to rape in the text" (105). The issue of
consent in the novel is a significant one: humans find themselves
compelled into sexual relations with the Oankali through chemical
means, either by direct drugging to pacify them or by the more subtle
release of pheramones that arouse an overwhelming sexual desire.  In
doing so, the Oankali, who are biologically engineered promoting
pleasure toward for creating and sustaining, maintain that the humans
desire this sex on a physiological level. Joshua Yu Burnett explains
that "the novel's treatment of the issue [of consent] is both
provocative and troubling" (110). On the more troubling side, Burnett
points out the acts of involuntary sterilization, forced conception,
complicity in human-on-human rape, and most seriously, Nikanj's rape
of Joseph, Lilith's partner. Yet, Burnett maintains, "none of this is
meant to suggest that the Oankali are vicious, brutal rapists"
(117). Because their sensory and communication capacities prevent the
Oankali from lying or deception, "they seem quite genuine in their
insistance that human claims of non-consent belie a deeper,
physio-psychological consent" (Burnett 117). For the Oankali, consent
gives way to consensus. 

- consensus revises/shifts contradiction power imbalances 
The issue of consent in the novel points to the ways that subjugation
and coercion is part of a framework that revises the human
contradiction. Justin Louis Mann argues that the novel evokes the
concept of "pessimistic futurism," combining the cynicism of
afro-pessimism, which associates blackness with ontological death and
the impossibility of black subjectivity, and the optimism of
afro-futurism, which speculates and potentializes liberatory black
subjectivity and futurity. Mann explains that the sexual relationship
between Lilith, Joseph, and Nikanj conveys this dynamic, a
relationship that is crystalized in the image of Nikanj's "sensory
arm" wrapped around Lilith's neck, which she describes as "an oddly
comfortable noose" (Mann 62). Drawing from history of subjugation and
death, the noose also evokes comfort, a kind of complacency with
sexuality, made possible through pleasure. According to Mann, this
seeming paradox between "pleasure and pain, history and futurity, and
abjection and subjection" has the potential to replace the injustices
of the human contradiction (Mann 62). Rather than being subjected to
the stratifications of society based on identity, race, and class,
humans are subjected to their own own physical pleasure and
well-being, regardless of their mental opposition.

For the Oankali, the emphasis is not on consent but on consensus. The
Oankali handle difference and dissent by literally /incorporating/ it
into their organism through genetics or through tenticular
connection. The sex scenes here are particularly instructive. When
Nikanj presents himself to Lilith, one might expect a split between
her embodied instinct and free will, that is, between her sexual
desire and her determination to rebel against the forced
interbreeding. One instead encounters their conflation. Lilith
welcomes her body's immediate, unconscious response to Nikanj's
invitation: "She realized she had stood up without meaning to and
taken a step toward the bed... She did not pretend outwardly or to
herself that she would resist Nikanj’s invitation—-or that she wanted
to resist it" (PAGE NUMBER). Lilith's body acts before her conscious
mind can intervene. When her conscious mind does catch up to her body,
it lacks the will, even the smallest hint of one, to refuse her
desire. Rather, her desire and her will are in harmony, both in step
to fulfill the act that she spends the rest of the book plotting to
resist.

**** the workings of pleasure
- Looking at sex, how it bypasses the flesh. Which enables us to see
how what we assume to be purely cognitive is actually fleshy,
embodied. 
- The fleshiness of mental experience changes the way we view
heterosexuality. 

The conflation between desire and will has to do with the
priortization of pleasure in the body, in the flesh. The flesh--the
central conduit for human sexual contact and its source of
pleasure--is an obstacle for Oankali. In their sexual unions, the male
and female bodies do not touch, but are rather routed through the
"ooloi," an intermediary, nonbinary being whose "sensory arms" plug
directly into into the brains of each partner. This intermediary
dispenses not only with the flesh but also with human modes of
communication and intimacy to stimulate the brain's pleasure centers
directly.

During the sex act, Lilith experiences a torrent of thought and
sensation which leads her to question the objective reality of her
experience. "Plugged" into Joseph via Nikanj, she
#+BEGIN_QUOTE 
immediately recieved Joseph as a blanket of warmth and security, a
compelling, steadying presence. 

She never knew whether she was receiving Nikanj's approximation of
Joseph, a true transmission of what Joseph was feeling, some
combination of truth and approximation, or just a pleasant fiction. 

What was Joseph feeling from her?

It seemed to her that she had always been with him. She had no
sensation of shifting gears, no "time alone" to contrast with the
present "time together." He had always been there, part of her,
essential. 308-309
#+END_QUOTE
What Lilith first feels as a physical presence, she then builds into
cognitive interpretations. Lilith senses Joseph as a "blanket of
warmth" and a "steadying presence." To these physical sensations, she
augments mental interpretations of "security" and "compelling." She
then begins to question the objective truth of her experience,
wondering what Joseph is feeling, and whether he shares in the same
sensations. This doubt, however, soon fades to reassurance as she
intuits that "He had always been there, part of her, essential." This
progression reveals that, while she initially suspects whether Joseph
is feeling the same way, the blending of sensation and thought seems
to inspire belief in their union. Physical presence transforms into a
mental certainty: "he had always been there, part of her, essential."

Meanwhile, Nikanj, who is mediating the experience, becomes
imperceptible to the two of them:
#+BEGIN_QUOTE
Nikanj focused on the intensity of their attraction, their union. It
left Lilith no other sensation. It seemed, itself, to vanish. She
sensed only Joseph, felt that he was aware only of her. 

Now their delight in one another ignited and burned. They moved
together, sustaining an impossible intensity, both of them tireless,
perfectly matched, ablaze in sensation, lost in one another. 308-309
#+END_QUOTE
The lovemaking that fuses physical and mental experience, with them
"lost in one other," dissolves Lilith's sense of time, space, and the
distance between her and Joseph, who she felt "was aware only of her."
In the midst of this intensity, the intermediary responsible for this
fusion fades. And paradoxically, this fusion between minds surfaces
the power of the flesh, engendering that which their neurological
connection bypasses---physical sensation. 

Afterward, when Lilith asks if the sex is simulated, Nikanj explains
that although sensory experience is shared between herself and Joseph,
"Intellectually, he made his interpretations and you made yours." To
this, Lilith remarks that she "wouldn't call them intellectual"
(310-311). That Lilith questions whether her mental experiences are
true or not, that she doubts her experience on the level of objective
reality, points to an important lesson about human-to-human contact:
The gap between human bodies, who are not connected by neural
infrastructure, creates the potential for miscommunication and
misunderstanding. And the flesh, the traditional route for bridging
this gap, can add to the confusion. While humans must navigate through
communication and the flesh to attain unity, the Oankali can bypass
these obstacles entirely, plugging directly into the brain's pleasure
centers. By routing sensual connection to the brain, they eliminate
the space for discomfort and even repulsion which can occur when in
flesh-to-flesh contact. This immediate connection facilitated by the
ooloi offers a sensual and cognitive experience that is beyond human
abilities. As Nikanj explains, it "offer[s] a oneness that your people
strive for, dream of, but can't truly attain alone" (359).

**** bioloigical determinism debate
Through a neurological infrastructure, cognitive and mental
experiences emerge as a physical phenomenon, with partners "ablaze in
sensation" (309). The importance of the bodily sensation speaks to one
critical debate about the influence of the body, in particular, the
influence of biology, on identity and behavior in the novel. One group
of critics generally maintain that the novel destabilizes biological
categories its associated assumptions about behavior, while a second
argue that the novel reinforces biological determinist views. This
debate on biological determinism turns on the relationship between
behavior expressed in action, will, and tendency against biological
fact. How and in what way does the body as a physical fact /matter/ in
the text?

The first group emphasizes the novel's revision of biological
determinist views, particularly when it comes to gender. Donna
Haraway's early critique of the novel fits within her larger project
exploring the deconstruction of essentialized notions of identity
across humans, animals, aliens, and machines. "Gender," she argues,
"is not the transubstantiation of biological sexual difference,"
rather, it is "kind, syntax, relation, genre" (/Primate Visions/
377). Speaking of Butler's work in particular, Haraway points out that
the revision of power dynamics and individual agency serve to
destabilize teleological stories that recreate more of the same
(378). Using language that prefigures her famous essay, "Cyborg
Manifesto," Haraway claims that Butler's fiction, "especially
Xenogenesis, is about the monstrous fear and hope that the child will
not, after all, be like the parent" (Haraway 378). Critics who build
Haraway's reading, like Catherine Ramirez and Kitty Dunkley, explore
how Butler deploys aspects of biological identity in a strategic way.
Ramirez explains that Butler strategically deploys essentialist
identity categories, as a tool for "imagining and mobilizing new
subjects and new communities" (395). Drawing from Gayatri Spivak's
"Strategic essentialism" (Spivak 1993), Ramirez explains that
essentialist identity is both a tool and and obstacle:
#+BEGIN_QUOTE
"The tension between affinity and essence, and between plurality and
specificity... highlights a contradiction of woman-of-color
subjectivity and feminism. The histories of racism, imperialism,
patriarchy, and homophobia have rendered women of color abject, yet,
via history, women of color must claim some sort of position in order
transform themselves into (speaking) subjects (without replicating the
regime[s] that silenced them). Ramirez 395-396
#+end_quote
Ramirez explains that that identity, which has been an obstacle to
attaining subjectivity, is simultaneously a tool that can be
redeployed to claim that same subjectivity. Making a similar argument,
within a frame of humanism, Kitty Dunkley emphasizes Butler's revision
the anthropocentric and patriarchial structures that necessitate
essential notions of gender. According to Dunkley, the Oankali "are
ostensibly constructed invert our Humanistic egocentrism" (96). An
example of this egocentrism is the men's fear of the sexual seduction
and penetration by the ooloi, which "threatens to usurp the men’s
position at the pinnacle of a gendered hierarchy" (Dunkley
100). Dunkley situates the novel as a radical example of a posthuman
framework, in the craving to integrate difference. The novel, she
argues, "prompts us to question how our relationships and sense of
kinship with the racialized, sexualized, and naturalized Other might
look, if, like the Oankali, we chose to 'embrace difference'" (Dunkley
113-114). For both Ramirez and Dunkley, biological "facts" of gender
are concepts to be deconstructed, rather than reinforced.

By constrast, critics like Nancy Jesser and Stephen Barnes center the
role of biological determinism within Butler's fiction. Jesser boldly
asserts that "Genetics is the science of Butler's fiction. The
translation of genotype to phenotype is the plot" (52). According to
Jesser, the novel re-works genetic tendencies of behavior by deploying
feminine traits, like maternal self-sacrifice, nurture, and
relationality, to correct tendencies of dominance, possessiveness, and
aggression typically displayed by the males (41-42). Jesser argues
that moments of male aggression, lik rape, are "both natural and
avoidable" due to the intervention of feminine traits of
relationality, cooperation, and flexibility (Jesser 43). Ultimately,
such feminine capacities will enable humanity to expand beyond its
innate, destructive tendencies. With a similar emphasis on biology,
Barnes cites Butler's interest in "emergent properties" of human
biology. According to this view, "Tiny individual tendencies
multiplied across thousands or millions of interactions over lifetimes
create the kind of dangerous, intractable sexism and racism that
Octavia saw as the building blocks of Armageddon" (Barnes 12). For
this side of the debate, biology is a physical fact that determines
behavior, but can also be re-worked or overcome through other
tendencies.

While one side reads biology in the novel as physically-based and
deterministic, and the other side reads it as an oppressive ideology
to be deconstructed, they both agree on one point: the primacy of
heterosexuality and the exclusion of non-normative sexualities in the
novel. These views are due to the gendered structure of the sex act,
which maintains a male/female coupling, despite the addition of an
ooloi participant. Haraway points out that,
#+BEGIN_QUOTE
Heterosexuality remains unquestioned, if more complexly mediated. The
different social subjects, the different genders that could emerge
from another embodiment of resistance to compulsory heterosexual
reproductive politics, do not inhabit this /Dawn/. In this critical
sense, Dawn fails in its promise to tell another story, about another
birth, a xenogenesis. 380
#+END_QUOTE
According to Haraway, Butler's deconstruction of species and sex falls
short of affecting sexuality. Several critics agree with this reading,
like Erin Ackerman, who draws from Jesser's work to say that
"heterosexuality does read as the standard, or even, only erotic
option available" (Ackerman 40).

There is one exception to this view, from Patricia Meltzer, who argues
that the trilogy, and its third installment specifically, presents a
view of non-normative sexuality which can literally transform bodies
at will. In this book, the human-Oankali constructs evolved the
ability to manipulate organic matter within their own bodies, as
shape-shifting beings who can adapt to their prospective partner's
desires. Drawing from Judith Butler, Meltzer poses a body that is
queer because it is constructed by desire:
#+BEGIN_QUOTE
"Butler's concepts here are positioned neither in a biological
essentialism that insists on gender identity (woman) as derivated of a
body's sex (female), nor in a social and/or psychological
constructivism that udnerstands the body's materiality as dominated by
(social) discourse. Instead, desire and sexuality are based in the
body's need for others... the body follows desire. Meltzer 241
#+END_QUOTE
While other critics point out the disruptions to normativity, like in
those in which the binary is destabilized, upended, where gender roles
are reimagined, here Melzter draws out alternate visions for sex,
gender, and desire altogether. Building from Butler's concept of
performativity, Meltzer defines queerness as resisting the normative
correlation of sex/gender/desire. The failure of easy alignment among
these elements opens up the possibility of imagining how desire can
construct new configurations of sexuality, that are "rooted in the
body's amorphous craving for physical pleasure" (Melzter 236).

I agree with Meltzer that the sex act is a queer one, but not because
of a desire that literally transform bodies. Rather, the sex act is
queer because of the way that it simultaneously bypasses and
invigorates the flesh. Here, I draw from Jayna Brown's emphasis on the
flesh and how it opens up possibilities for reconceiving
subjectivity. She asks, "Does the self need bounded wholeness in order
to feel, or can it thrive in the effluent?" (14). According to Brown,
while the senses "individuate us, demarcate our boundaries," they also
"mark the ways our bodies are open. The body, the self, is porous,
receptive, impressionable" (Brown 14). In the novel, this openness to
feeling is achieved by re-routing around the flesh and its senses, the
traditional channel for feeling, in a way that paradoxically
emphasizes that which it bypasses. The sensory hand that connects to
the spinal nerve at the base of the brain creating a direct neural
connection in which embodied sensation can traffic. The effect is to
transform cognitive and conceptual phenomena into physical, sensual
experiences.

Nancy Jesser claims that this novel presents "a vision of bodies that
are bad for us" (45). Clearly, flesh is an obstacle for human
communication/interaction and society. It is something that humans
cannot get past, and creates all sorts of problems for how they relate
and organize themselves, particularly as they relate between self and
other. Oankali sex demonstrates that the way of overcoming the
obstacle of flesh is by experiencing the cognitive/mental as
inextricable from the physical. This creates a relation, unity,
through feeling.

Bypassing of the flesh in order to attain fleshy sensation disrupts
the confines of the traditional human and what is considered to be
traditional sexuality. This complex imbrication between physical
sensation and mental experience, extends theorizations of the
"posthuman," that is, figures who extend the bounds of the traditional
human subject by technological, biological, or spiritual
modification. Because the sexual experience occurs entirely in the
brain, it is easy to assume, as the humans in the novel do, that the
experience is entirely a simulation. But rather, the experience
reinforces embodied sensation in a way that disrupts traditional
concepts of the human. Rather than possessing a body, the mind thrives
in the tension between connection and separateness in the flesh. Brown
explains that "Flesh… is free of the need for subjectivity...there is
freedom in the flesh, in the moments when it is excluded from being
marked, as it feels, and responds to, touch" (Brown 11).

Here, separateness is crucial for enabling connection. While
sensation, desire, and flesh momentarily dissolve the boundaries of
the individual, a distance between self and other maintains an
elusiveness that energizes feeling in the flesh. In the novel, this
distance can emerge at a moment of direct neural connection. For
example, when Lilith asks Nikanj to share its feelings of grief after
Joseph's untimely death: "It gave her... a new color. A totally alien,
unique, nameless thing, half seen, half felt or... tasted. A blaze of
something frightening, yet overwhelmingly, compelling" (Butler
429). Despite their direct neural connection, the description here
derives its expressive power on the quality of unknowability, using
formations of strangeness or liminality, ("half seen, half felt,"
"alien," "a new color"). Such a connection can only emerge in the
distance between self and other.

In SEX section, the sex act with the Oankali demonstrates two things: 
 
- first, that flesh is an obstacle for human communication/interaction
  and society. It is something that humans cannot get past, and
  creates all sorts of problems for how they relate and organize
  themselves.
- second, as Oankali sex demonstrates, the way of overcoming the
  obstacle of flesh is by experiencing the cognitive/mental as
  inextricable from the physical. This creates a relation, unity,
  through feeling.

Now, in FLESH section, we ask how this obstacle, the flesh, to human
connection can also be a solution? 


** flesh
*** revision TODOs
**** CANCELLED SEX: MOVE? critical debate on the question of consent
     CLOSED: [2023-05-29 Mon 11:54]
Burnett says that issue of consent is major, and hardly addressed. He
is disturbed by it, and brings up an association to slavery. The
lesson here is the need for affirmative consent, not to go back to the
days of atrocity. But this misses the point!

The question of consent points to a larger issue of how this book
relates to black studies. What is the relation of the novel to
problematic themes within black studies, to the remnants of slavery?
Is it pessimistic or futuristic?

Mann says it's both pessimistic and futuristic. And that the tension
between these two is what allows the novel to trouble questions of
consent

**** DONE FLESH: revise intro posing flesh as problem
     CLOSED: [2023-05-29 Mon 11:54]

**** TODO FLESH: impose new schema of flesh & abstraction
Foreclosure
Fugitivity
Shifting registers
Unmappability

Displacement
Volatility
Torque
Flickering signifiers

**** DONE FLESH: reorganize Snorton section, addin unmap
     CLOSED: [2023-06-05 Mon 10:24]
**** DONE FLESH: streamline Musser 
     CLOSED: [2023-06-13 Tue 10:38]
**** DONE FLESH: move media archaeology section here
     CLOSED: [2023-06-13 Tue 10:38]
*** section overview
Both black fem and media arch offer ways of thinking through
materiality, "flesh," that opens up the way we think about surfaces
(skin) and bodies (sex).
- Black fem: flesh that is reduced is also imbued with significatory
  potential. 
- Media arch: materiality has bearing on immaterial effects

Black Fem: 
  Foreclosure - denying interiority to offer up other messages that
  engage without resolving the violence of the pornotrope

  Fugitivity - reduction to flesh facilitates chaos of meanings.

  In a fugitive state, meaning becomes unstable and in conflict. How
  does this emerge on the surface?
  - Unmappability - where depth and surface are flipped, so meaning
  cannot be firmly located.
  - Shifting - in the movement between registers, interpretations.

Media Arch:

Forensic materiality - the level of hardware where things are
displaced away from the end user.

Flickering signifiers, the relation between levels on the software
stack. Leads to a formal materiality. 

Volatility - vulnerability of data manipulation at the top of the
stack. 

Torque - shifting between registers which affects the surface level of
formal materiality. 



*** black fem studies, media arch
Could the flesh, which poses a problem for intra-human connection,
also offer a solution to this problem? In what follows, I explore two
how two very different fields--Black Feminist Studies and Media
Archaeology--offer critical methods for deconstructing the
relationship between materiality and meaning. Black Feminist Studies
explores the concept of the flesh within the history of slavery of
racialization, while Media Archaeology explores the materiality of
electronic processing and its relationship to interface effects. Both
areas of inquiry, though vastly different in the subject of study,
share a similar investment in reading into the surface of materiality
to see how it might offer new modes of thinking and resistance. The
workings of the flesh on the one hand, and of technology on the other,
not only helps us to understand the inextricability of the material
from the mental, but also offers a possibility for developing social
relations based on embodied expereience. These theorizations of
materiality, which index a liminal space where meaning is
simultaneously ascribed and obscured, will become the ground for my
working through the intersections of hardware and software in my next
section, /skin/. They will allow me to trace in more detail how the
process of reduction to the physical surface simultaneously creates an
opportunity for new readings.

Black Feminist Studies tackles a nearly impossible task--to redeploy
the flesh, which has undergone a systematic reduction from the body
that begins with the history of transatlantic slavery, into a tool of
resistence. Critics like Hortense Spillers, C. Riley Snorton, and
Amber J. Musser offer readings of the flesh to parse various racial
and gendered processes, a "symbolic order" or "American grammar," in
Hortense Spillers words, ascribed to Black bodies over time (68). In
her influential essay, "Mama's Baby, Papa's Maybe: An American Grammar
Book," Hortense Spillers describes the black body as a stack of
"attentuated meanings, made in excess over time, assigned by a
particular historical order" (65). The "severing of the captive body
from its motive will," which can be traced to the violence of the
middle passage, creates four effects (67):
#+BEGIN_QUOTE
1) the captive body becomes the source of an irresistible, destructive
   sensuality;
2) at the same time--in stunning contradiction--the captive body
   reduces to a thing, becoming being for the captor;
3) in this absence from a subject position, the captured sexualities
   provide a physical and biological expression of "otherness";
4) as a category of "otherness," the captive body translates into a
   potential for pornotroping and embodies sheer physical
   powerlessness that slides into a more general "powerlessness,"
   resonating through various centers of human and social meaning. 67
#+END_QUOTE
The "stunning contradiction" here is the tension between reduction and
signification. First, there is a reduction of the body to its bare
physicality, into a material substance for labor and exchange. At the
same time, however, this reduction also opens a possiblity for
signification, which aspects of sensuality, objectificaiton,
otherness, and powerlessness can be layered onto the flesh.  Spillers,
and thinkers in Black Feminist Studies who build from flesh as the
"zero degree of social conceptualization," name this simultaneous
reduction and accumulation of meaning "pornotroping" (Spillers
67). This critical move is about taking what has been a method of
reduction, what has been a tool for appropriating the complexity of
real world objects for the purpose of exploitation, and using that to
instead seek out moments of obfuscation, a kind of diversion from or
forclosure to objectification without denying objectification. These
strategies are rooted in ways of reading materiality, in the ways that
Black Feminist Studies have discovered within the violent history of
the Black flesh some kind of resistance, which is not quite
empowerment, but which is also not subordination. Rather, it
approaches materiality as something slippery, shifting, which confuses
rather than resolves meaning.

With quite different political focus, thinkers in Media Archaeology
like Matthew Kirschenbaum and N. Katherine Hayles offer deep readings
of digital media and technological processes to tease out the role of
physical aspects, such as hardware and software stacks, and how they
produce seemingly immaterial surface forms. For Hayles, digital
materiality is a way of bringing the body into computation. Her
research traces "how information lost its body," that is, how
information processing, the calculation and manipulation of symbols,
reveals an imaginary of the body and the experience of embodiment that
is continually displaced. Hayles's work is situated within a
destabilization of Liberal Humanism's prioritization of
mind/rationality over body/emotions in Englightenment thinking and how
this perpetuates into the mid-20th century ideologies about
information versus instantiation, code versus hardware.[fn:1] Her work
resists the idea of digital immateriality, which has been in
production since the emergence of computing technologies in the
mid-20th century, and is famously articulated by Media Studies
theorist Friedrich Kittler:
#+BEGIN_QUOTE
The general digitization of channels and information erases the
differences among individual media. Sound and image, voice and text
are reduced to surface effects, known to consumers as interface. Sense
and the senses turn into eyewash. Inside the computers themselves
everything becomes a number: quantity without image, sound or
voice. /Grammophone/ 1
#+END_QUOTE 
Working to unflatten the stream of zeroes and ones, Hayles
disarticulates digitality from materiality which, she argues, extends
liberal humanist ideology into the "posthuman," where a dominant,
unmarked rationality is privileged over embodied experience and
especially, embodied difference. Whereas the liberal humanist subject
is characterized by classical mind/body divisions and hierarchies that
posit embodiment as separate from and subordinate to intelligence, in
which the rational mind /possesses/ a body, the postuman is
characterized by informational patterns that /inhabit/ a physical
vessel, such as a body or a machine. According to Hayles, this
progression from possession to inhabitation suggests that the next
move will be to transcend the material realm altogether, as
consciousness can be uploaded to a virtual space where life itself is
infinite. As Hayles explains, "Information, like humanity, cannot
exist apart from embodiment that brings it into being as a material
entity in the world; and embodiment is always instantiated, local, and
specific" ("Virtual Bodies and Flickering Signifiers", 1993, 91).

While both Black Feminist Studies and Media Archaeology are interested
in the surface effects of materiality, they offer distinct
perspectives on the collision between these effects and their
meaning. Drawing from Spiller's concept of the pornotrope in black
flesh, Snorton poses racialization as a conceptual, "unmappable"
phenomenon. Black Feminist thinkers following Spillers plumb the
depths of the surface to posit ways that meaning cannot be firmly
adhered to materiality. Media Archaeology theorists, by contrast,
deconstruct what appears to be immaterial by situating it as a formal
production, relying on distinctly physical processes. In what follows,
I explore how these two perspectives together might offer a radical
re-thinking for how technological contexts might mediate embodied and
conceptual experience. By revising assumptions of digital media as
insubstantial or immaterial, existing primarily as an effect on a
screen, these theorists open avenues for thinking through the effects
of physicality throughout technological systems.

*** black feminist studies: foreclosure, fugivity, unmappability
From black feminist studies, I begin with the concept of
"foreclosure," which builds from Amber J. Musser's instruction that
"to think with the flesh" involves "hold[ing] violence and possibility
in the same frame" (12). Musser's critical readings of "fleshiness" in
Spiller's pornotrope pushes against trends in Afropessimism that take
the pornotrope as a foreclosure of black subjectivity. Rather, Musser
explores how foreclosure, such as the denial of access or knowledge,
offers possibilities for new modes of relation. Drawing from Alexander
G. Weheliye's argument about the imbrication of sex and domination,
Musser's emphasis on fleshiness brings to the surface relations that
are in tension with the desire to dominate. Following Weheliye, she
affirms that "turning to the violence of the pornotrope allows us to
see the radical potential of excess without flattening the violence at
its core" (/Sensual Excess/ 9). As an example of this "excess," Musser
offers up a reading of Lyle Ashton Harris's self-portrait as Billie
Holiday. Her reading of the photograph surfaces a subject whose
inaccessibility is challenged with an excess that depicts hunger as a
mode of relation. Musser explains that Harris's open mouth, for
example,
#+BEGIN_QUOTE
tells us nothing of Holiday or Harris, but it reveals a sensuality or
mode of being and relating that prioritizes openness, vulnerability,
and a willingness to ingest without necessarily choosing what one is
taking in. This is not the desire born of subjectivity in which
subject wishes to possess object, but an embodied hunger that takes
joy and pain in this gesture of radical openness toward otherness. 5
#+END_QUOTE
Forclosing access to the subject's interiority, the shiny surface of
the photograph opens other relational possibilities. A reading of
hunger on this surface refuses what Musser describes as "the underside
of the scientific/pornographic drive toward locating knowledge in an
'objective' image" ("Surface-Becoming" par. 2). This reading engages
(without resolving) the inescapable violence of the pornotrope, the
desire for access, and its foreclosure.

Foreclosing access to interiority creates a state where meaning is
fugitive, where bodies slip in and out of signification. The concept
of fugitivity, or escape, is based on a condition of black bodies
which have been designated as a commodity have undergone a reduction
into flesh, where they become exchangable with other bodies or
commodities of equal value, a state that C. Riley Snorton calls the
"fungible." Snorton then makes the incisive argument that this
fungibility of black flesh turns bodies into "malleable matter,"
enabling a fugitivity from markers of sex and gender (20). He
illustrates this process with narratives of fugutive slaves, such as
the story of Harriet Jacobs, whose escape from slavery in 1842 is
documented in /Incidents in the Life of a Slave Girl/ (1861). Snorton
explains how Jacobs's "blackening" of her face with charcoal endowed
her with a level of "fungibility, thingness" to pass as a man, even
deceiving those who knew her well (Snorton 71). As oppposed
totraditional racial "passing" that assumes a degrees of whiteness,
the amplification of blackness in the flesh, which reduces it to a
commodity value, creates a "gender indefiniteness" that enables escape
(56). Black flesh thus, but undergoing a reduction, enables an escape
from signification that simultaneously opens the potential of
signification. This fungibility creates an almost chaotic state in
which the black body suceptible to multiple mappings of meaning, and
can therefore slip in and out of signification.

In a fugitive state, meaning that is unstable and in conflict emerges
in certain "surface effects." To illustrate one of these effects,
Snorton offers up an example of the daguerrotype, an early
photographic technology that involves using chemicals on silver
plates. Snorton explains that the dagguerotype offers "a visual
grammar for reading the imbrications of 'race' and 'gender' under
captivity" (40). It does so by flipping expectations about surface and
depth: here, rather than perpetuating the idea that depth exists below
the surface, the surface becomes a ground for the layering of
depth. Snorton describes the effect of this this flip as an
"unmappability" in which racialization takes place:
#+BEGIN_QUOTE
... the daguerreotype provides a series of lessons about power, and
racial power in particular, as a form in which an image takes on
myriad perspectives because of the interplay of light and dark, both
in the composition of the shot and in the play of light on the
display. That the image does not reside on the surface but floats in
an unmappable elsewhere offers an allegory for race as a procedure
that exceeds the logics of a bodily surface, occuring by way of flesh,
a racial mattering that appears through puncture in the form of a
wound or covered by skin and screened from view. 40
#+END_QUOTE
The physical material of the image, that is the silvered copper plate
of the daguerreotype, at once solidifies its ground and indexes an
ambiguous space, what Snorton describes as the "unmappable elsewhere."
The image of the daguerrotype, which changes according to angle and
lighting, evokes the condition of racialization as "a procedure that
exceeds the logics of a bodily surface" while nonetheless adhering to
that surface, "a racial mattering that appears through puncture."
Snorton's curious use of the word "puncture" here revises Roland
Barthes's concept of the "punctum," or being "pierced" by a detail of
the photograph (/Camera Lucida/ 27). Unlike Barthes's punctum, one
cannot locate the image at a specific point on the copper-plate. That
the image resists stability is crucial for undersanding the way that
the physical registers interact with symbolic ones. The meeting
between this liminal space of the image's visual content and its
silver-plated copper ground offers another perspective for
understanding the collision of flesh and racialization.

Another related surface effect is what Musser describes as a shifting
between registers of interpretation. Musser demonstrates this surface
effect in her reading of the painting /Origin of the Universe 1/
(2012), by artist Mickalene Thomas, whose depiction of a female vulva
evokes French painter Gustave Courbet's /Origine du Monde/ (1866). In
Thomas's piece, the vulva is black and encrusted with rhinestones,
creating a brilliant surface which Musser claims is a "formal strategy
of producing opacity" (/Sensual Excess/ 48). While this work, like
Harris's citation of Billie Holiday, instrumentalizes the opacity of
the surface as a means of foreclosing access to interiority, it also
multiplies the potentiality of readings. Here, the foreclosure of
interiority works alongside a more pronounced subtext of
objectification about the commodification of the black female
body. Musser points to the rhinestones, which function simultaneously
on two registers: first, their flashiness "as a reminder of the long
association between black people and the commodity" (/Sensual Excess/
50); and second, as a brilliance that evokes wetness, suggesting
sexual pleasure. Both possibilities exist not only side-by-side, but
are in tension with one another:
#+BEGIN_QUOTE
Thinking the rhinestone as a trace or residue of Thomas’s wetness and
excitement allows us to hold violence, excess, and possibility in the
same frame. Even as the source is ambiguous, the idea that rhinestones
might offer a record of pleasure—-pleasure that is firmly constituted
in and of the flesh—-shows us a form of self-possession. This self is
not outside of objectification, but its embellishment and insistence
on the trace of excitement speaks to the centrality of pleasure in
theorizations of self-love. /Sensual Excess/ 63
#+END_QUOTE
While the significatory system that commodifies the black vulva is
inescapable, this objectification exists alongside a production of
pleasure. This surface whose opacity seems to insist upon itself
facilitates a shift between theses registers. It is not just that
these readings exist simultaneously, or side-by-side, but that they
enable a movement, or a shift, between one and the other, like a
shifting between frames. This brilliant surface enables one to
apprehend this movement from one frame to another, from "violence", to
"excess," and finally, to "possibility."

*** media arch: volatility & torque
In what follows, I will explore some of the parallels between Black
Feminist Studies and Media Archaeology. The first parallel has to do
with the concept of displacement, which I argue is related to that of
foreclosure. In Media Archaeology, displacement refers to the
sequestering of electronic processing and computer hardware from the
end user. I take this term from Matt Kirschenbaum, who argues that
"Digital inscription is a form of displacement. Its fundamental
characteristic is to remove digital objects from the channels of
direct human intervention" (86). Kirschenbaum offers the term
"forensic materiality" to refer to this level of computer hardware. On
this level, materiality consists of the physical traces on a hard
drive, specifically, of of one of two (binary) marks on a magnetized
surface, a north polarity signifying "1", or a south polarity
signifying "0". Examining these binary digits, or "bits," through
magnetic force microscopy, Kirschenbaum notes that each one appears as
a unique trace:
#+BEGIN_QUOTE
The bits themselves prove strikingly autographic, all of them similar
but no two exactly alike, each displaying idiosyncrasies and
imperfections--in much the same way that conventional letterforms,
both typed and handwritten, assume their own individual personality
under extreme magnification. 62
#+END_QUOTE 
That electronic data is, at its root, physical, shatters the illusion
of digital immateriality, that digitized objects and data are
homogenous in quality, a stream of code all the way down. In reality,
each object on the screen exists in a physical manifestation, whose
displacement from human engagement forecloses knowledge or access to
these materialities.

To trace the transformations of these physical elements as they travel
up the software stack, N. Katherine Hayles offers the concept of
"flickering signifers." Here, she brings Jacques Lacan's "floating
signifier," the idea that a word does not refer to a stable referent,
but "floats" above a text and attains its meaning through a play of
difference against other words, to bear on the interplay between the
immateriality of the screen and the materiality of the computer
hardware. Rather than destabilize meaning and truth within a
poststructural critique of knowledge paradigms, the flickering
signifier destabilizes the illusion of immateriality by tying it
(however tenuously) to physcial signals that move through the software
stack. Hayles explains that while apparently immaterial text and
objects have a "tendency toward unexpected metamorphoses,
attenuations, and dispersions," they are grounded in a physical
reality ("Virtual Bodies and Flickering Signifiers", 1993,
76). Between 
#+BEGIN_QUOTE
As I write these words on my computer, I see the lights on the video
screen, but for the computer the relevant signifiers are magnetic
tracks on disks. Intervening between what I see and what the computer
reads are the machine code that correlates alphanumeric symbols with
binary digits, the compiler language that correlates these symbols
with higher-level instructions determining how the symbols are to be
manipulated, the processing program that mediates between these
instructions and the commands I give the computer, and so forth. A
signifier on one level becomes a signified on the next higher
level. "Virtual Bodies" 77
#+END_QUOTE
Hayles's description of the flickering signifier, what she calls a
"flexible chain of markers" materializes the various levels of
transformation that digitized inscription must undergo in order to
reach the level of the screen (/Posthuman/ 31). First, physical traces
on a magnetic surface are mapped into low-level machine languages,
which based on numeric patterns and are illegible to human
readers. Then, these patterns are translated into Assembly languages
that pertain to the computer's Central Processing Unit (CPU), the main
processor that executes instructions, arithmetic, and logic which form
the bedrock of computational processes. Finally, as data moves up the
stack, it abstracts into high level programming languages like Python
and JavaScript and their effects on the screen, which humans interact
with in the form of the Graphical User Interface (GUI). In this way,
the objects on the screen rely on the physical materialities of
underlying computational processes, which are designed to remain
inaccessible to human observation.

To counter the misconception of "screen essentialism," an assumption
that objects on the screen appear, disappear, and move without a
physical origin, Kirschenbaum offers the concept of "formal
materiality" which challenges "the illusion of immaterial behavior"
(Kirschenbaum 11). While forensic materiality consists of physical
inscriptions, such as magnetic traces on hard drives, formal
materiality describes these traces as they are computed up the
software stack, through levels of programming languages toward
specific interface effects on the screen. It describes not only the
visual and conceptual phenomena such as screen display and appearance,
but also the way that these are deliberately produced to reinforce
fluidity and ephemerality. Kirschenbaum explains that as data moves up
the stack, it is continually reproduced and refreshed to fix errors
and idiosynracies that occur during transmission. As a result, formal
materiality on the screen is a "built" and "manufactured" phenomenon,
"existing as the end product of long traditions and trajectories of
engineering that werer deliberately undertaken to achieve and
implement it (137). He likens this process of data normalization to
"allographic reproduction" and older technologies like the telegraph
that use relay systems to reinforce signals over long stretches of
transmission (136). As data moves through electronic processing,
signal "reinvigoration" refreshes and standardizes it through
approximation rather than exact copying.

Formal materiality facilitates physical effects, "screen effects."
Although these screen effects function as a buffer between the user
and the digital inscription, there is in actuality an inverse
relationship between digital abstraction and tactile manipulation. The
higher that data climbs up the levels of abstraction, the more
manipulable it becomes, a state which Kirschenbaum calls "digital
volatility" (140). By manipulating the graphical user interface, for
example, by dragging and right clicking on items, users can move,
duplicate, or delete large quantities of data. Kirschenbaum explains
this "dynamic tension... between inscription and abstraction,
digitality and volitality" makes formal materiality more susceptible
to movement and change than physical inscription, which remains
inaccessible. Moving away from the inscription, is a move toward
something that users can handle and "touch," as anybody who has
dragged a file to their Desktop's trash can confirm.

As a surface effect, volatility is also animated by another force, a
more subtle one, which operates in the shifts between code and its
abstraction.  Kirschenbaum describes this force as "torque," or a
"procedural friction or perceived difference... as a user shifts from
one set of software logics to another" (13). The concept of torque,
which Kirschenbaum borrows from physics, materializes the shift from
one coding logics to another. Typically in physics, objects rotate
along their pivot point, where its distributional weight is
zero.[fn:4] Torque, however, is characterized by an oblique movement,
such as a rotational movement. Torque combines energy from two
directions, first, from the external force acting upon the object, and
second, from the relation between the point of contact on the object
and its pivot point, or the point along the object where it can be
balanced. Torque, therefore, measures a force that relies on distance
between the point of contact the object's center. Applied to media,
this term refers to the gap between one signficatory system and
another, such as programming code and its executed state, as data
travels up the software stack.

In Black Feminist Studies, these critics find ways of reading methods
of resistance, such as unmappability and shifting registers, from the
reduction of the body into flesh. This reduction creates surface
effects in which multiple registers of meaning move to avoid
resolution. Here, the flattening into surface forecloses access to an
interiority and opens the possibility of fugitivity, where meaning
escapes into irresolvable or incongruent registers. In these
registers, meaning is layered upon meaning, clash or are in
conflict. Theses "surface effects" of the flesh relate to "screen
effects" of electronic processing as data moves up the software
stack. Each stage of data transformation instantiates a formal
materiality, a surface effect which simultaneously depends on and
obscures the levels below. This displacement is energized by a sense
of volatility, in which data at the higher levels is more manipulable
than those below, and by a sense of torque, in the shifting between
software registers and objects, between the signifier on one level and
signified on another. This chain of transformations end at the screen,
where the end user experiences them in haptic engagements. In the next
section, I will demonstrate how these concepts of foreclosure,
fugitivity, and unmappability in Black Feminist Studies engage with
those of flickering signifiers, volatility, and torque in Media
Archaeology to read the haptic effects and its relationship to
racialization in a hypermedia literary work.


** skin
*** revision TODOs
**** SKIN: impose new schema
There is a tension between control and connection playing through the
work. This tension emerges in "surface effects," like haptics. 

Reading the underlying code deepens the interpretion of surface
effects. Of conceptual objects that elude our manual control. Moving
from one register (conceptual/logical) to another register
(sensual/tactile).

***** air.html -> multiplicity of movement, intractible movement
- surface effect: challenges tactile ability, objects moving toward
  and against like magnets.
- The way the object move on the screen is influenced by the coding
  logics below the surface. if/else statement in code reflects duality
  of movement (either toward or against) and of the objects (there are
  two figures).
  - a simple if/else directive. *Conditional statement is a reduction*
    of choices, of nuance to an either/or. All movement is defined by
    a very simple yes or no condition. *Something that is binary and
    very controlled can enable all kinds of movement*. There is an
    escape here, something fugitive, in the way that *their bodies
    eludes the mouse*. They cannot be caught.
-> Racialization: 
   - But there is also a reduction here, the two bodies are reduced to
     small images, where the differences between them are visible but
     minor, in shape and color.

***** control.html -> lagging movement, uncontrollable 
- surface effect: user manually turns Harvey's head, gets bits of alt
  text.
- this piece is about control -- it plays with the control of the
  female body in the haptics that are sensual but laggy. The haptics
  indicate that full control is not possible, there is something
  intractible about it. 
- there are multiple registers here, from the surface effects to the
  code. The underlying code contains the full message. The surface
  only shows parts which are incoherent.
- the lack of control results from what's happening at the level of
  software. Torque. 
- Racialization: intractible control. Most likely by Harvey. 

***** breath.html -> limitations of medium as enabling constraint
- There are places where foreclosure of the software and hardware
  stack has a stronger effect, to reinforce physicality of medium.
- Foreclosure: love notes deliberately hidden in the code, meant to be
  displaced and to be discovered.
- compare with dialogue between them in "WHISPERING WINDOWS", which is
  limited to just text, but at two different levels (public and
  private). The limitations of the communication medium as an enabling
  constraint.
- the levels of media here enable different levels of communication. 

***** Heart.swf -> total inaccessibility of physical matter enables
connection
- Flash media is totally inaccessible, only through abstraction can we
  engage with it.
- The conversation between them: 
  - the inaccessibility of the technological stack amplifies physical
    aspects that normally would be a barrier, like geography, culture,
    race.
  - like sex in /Dawn/, makes sensual connections that blend feeling
    and thought.  

**** SKIN: conclusion

   Here we see the layers of flesh as "surface effects." 
   - Hayles and Kirschenbaum enable us to deconstruct how what we think
     is immaterial is actually embodied/inscripted. 
   - First, to understand, as Hayles explains, that "information loses
     its body" and see how this perpetuates liberal humanist reductions
     of the subject. Hayles frames this within a discussion of the
     posthuman.
   - Second, to examine K's concept of formal materiality, where
     abstraction engages manipulation and sensuality, the shifting of
     registers.
   - K's torque enables us to read sensuality into Hayles's concept of
     flickering signifiers.

   -> Bringing back the flesh: pattern as material in the form of opacity,
     surface, torque.
   -> deep reading of different technologies in /skin/. 

*** /skinonskinonskin/
**** intro
Now, I turn to /skinonskinonskin/ (1999), a work of "net art" created
by Auriea Harvey and Michaël Samyn, under their collaborative artist's
name /Entropy8Zuper!/. /skin/ documents the inception of their love
affair, which began in an internet chat room and evolved into a
digital correspondence, or "digital love letters"
("/skinonskinonskin/" /Net Art Anthology/). These letters took the
form of individual web pages, designed by Samyn and Harvey, containing
notes, images, and interative elements using early web tools and
animation software, much of which is now defunct or unsupported. The
Rhizome.org /Net Art Anthology/, where the work is preserved with
emulator software, describes it as a "complex portrait of an artistic
and romantic relationship that shows that online intimacy is as deeply
felt, embodied, and full of risk and reward as any other form"
("/skinonskinonskin/").

/skin/ takes part in a body electronic work called "Electronic
Literature," which is now practically inaccessible with modern
technology. Electronic Literature, which spans several subgenres, like
hypertext fiction, network literature, interactive fiction, and
generative text share a common interest in expressing and exploring
digitality as an aesthetic. This work, like many in Electronic
Literature, is inaccessible to modern web browsers. Though most of it
is written in HTML (HyperText Markup Language), which continues to be
the default language for the web, it is animated by depreciated
versions of JavaScript code and now obsolete Flash software. Besides
the outdated code, it also has an incompatibility with platform, the
Netscape 4 browser, which could run on both MAC and PC systems
(rendering pages on both Harvey's Mac and Samyn's PC) at the
time. Netscape's decline in the late 1990s and early 2000s brought
with it the depreciation of HTML and JavaScript elements that
characterized its associated web authoring tools and practices.

In what follows, I embark on a close reading of the work's "surface
effects," that is, the appearance and interactivity of objects and
words on the screen. I emphasize how these elements facilitate a
haptic engagement, a sense of touch and movement through the user's
mouse. Then, I turn to the underlying source code, the HTML,
JavaScript, and Flash files, to examine how the coding layer, another
level of formal materiality, might influence the reading of the work's
surface effects. Here, I explore how programming concepts and
structures might enhance the reading of visible and interactive
elements on the screen. I find that the different registers of
abstraction across surface effects and code suggest a tension
throughout the work between control and communication.

**** air.html
First, I examine "air.html" page, which depicts an animation of two
small figures floating in black space. The two figures, which
represent the Samyn and Harvey, float in a horizontal, flying position
over a field of a field of rotating green lines, which evoke a
rolling, cyber-landcape. Each figure can be moved by the cursor as it
pans across the screen, attracting them like magnets. While they slide
effortlessly in all directions, coaxing precise movements from the
figures requires precise mouse manipulations that challange the user's
tactile ability. By using slow movements, the user can bring the
individual bodies into contact, but they can never cross each other,
or cross to the other's side of the screen. Samyn's body remains
confined to the left, while Harvey's is to the right. [SEE GIF] The
initial illusion of free floating, therefore, is deceiving.

[include gif of air.html]

This animation is defined in the source code of the page, in a series
of functions written in JavaScript, the standard language for defining
interactive elements on web pages. Below is an excerpt of one
JavaScript function called ~flyMouse()~:

#+BEGIN_SOURCE
if ( mouseX < halfW )

	{

	var mFactor = 0.1;

	var aFactor = 0.01;

	}

else

	{

	var mFactor = 0.01;

	var aFactor = 0.1;

	};

...

dMove('flyingmL','document.',mLeft + thisXDiff*mFactor,mTop + 
thisYDiff*mFactor);

...

dMove('flyingaL','document.',aLeft + thisXDiff*aFactor,aTop + thisYDiff*aFactor);
#+END_SOURCE
The direction and speed of the bodies' movement hinges on the if/else
statement above. An "if/else" statement, or conditional statement, is
a core construct in programming, which exists across many programming
languages. The conditional statement determines the "control flow," or
the order of operations, in a block of code based on whether a
specific condition is true or whether it is false. Underlying the
if/else statement is the Boolean data type, which can be either ~True~
or ~False~. Checking whether a condition is ~True~ or ~False~ enables
programmers to write code that makes decisions, so to speak, to
execute the relevant block of code that matches the condition. For
example, an email inbox will display unread emails in bold formatting
depending on whether or not that email has been opened by the
user. Behind the scenes, an if/else statement checks if the email has
been opened, and if it has, the email will render with regular
formatting, and if it has not, it will render in bold formatting. In
the if/else statement on "air.html," the movement of the bodies is
conditional on their distance between the mouse and the original
positioning of the bodies on either side of the screen. Depending on
this distance, the magnetic force for each of the bodies is multiplied
against a factor of .1 or .01. This results in a stronger movement
from Samyn's body when the mouse is near Samyn's original position on
the left side of the screen, and a stronger movement from Harvey's
body when the mouse is on the right half of the screen, near Harvey's
original position. The conditional statement is thus a reduction of
possible choices to an either/or, where all movement depends on a
simple yes or no condition.

The binary nature of this conditional statement--it can be true or it
can be false, and there are two resulting actions--reflects an
animation that is, at its core, about a dual force. But this dual
force, either attraction or repulsion from the mouse, enables movement
across all directions of the screeen. The binary structure of the
if/else statement, in which bodies move toward and against each other,
thus faciliates a multiplicity of movement. In that movement, there is
something intractible, something fugitive, about the way that the
figures are drawn to but resist being controlled by the mouse. These
figures, which have been reduced to two small pixelated images of
Harvey and Samyn's naked bodies. Here, the movement by the hand and
the oppsitional constraints which the user comes up against, engage
the transformations that take place in the level of code.

**** control.html
If "air.html" plays with binary movement, another page,
"control.html," plays with lag. The page consists of a monochrome
green image of Harvey's head, which rolls from side to side in the
direction of the user's cursor as it pans over the image. As the
cursor moves, exposing Harvey's face at different angles, it also
displays peices of "alt-text," short for "alternative text," triggers
the displays descriptive text meant to stand in place of the image,
for accessibility reasons and in the case that the image fails to
load. The alt-text here contains words like "go" "believe" "ocean" and
"mind," depending on the cursor's location over the image. The tactile
qualities of this page, in which the user manually turns Havery's head
from one side ot another with the cursor-as-hand, are further
emphasized by the cursor itself, which appears as a pointing hand.

[INSERT GIF]

Looking into the source code, a couple of interesting things
emerge. 

#+BEGIN_SOURCE
<AREA SHAPE=RECT ALT="i" HREF="#" COORDS="0,0,8,142"
onMouseOver="strokeimage.src=stroke1.src ; window.status='i' ; return
true">

<AREA SHAPE=RECT ALT="believe" HREF="#" COORDS="8,0,15,142"
onMouseOver="strokeimage.src=stroke2.src ;window.status='believe' ;
return true">

<AREA SHAPE=RECT ALT="in" HREF="#" COORDS="15,0,22,142"
onMouseOver="strokeimage.src=stroke3.src ;window.status='in' ; return
true">
	
<AREA SHAPE=RECT ALT="it" HREF="#" COORDS="22,0,30,142"
onMouseOver="strokeimage.src=stroke4.src ;window.status='it' ; return
true">
	
<AREA SHAPE=RECT ALT="you" HREF="#" COORDS="30,0,38,142"
onMouseOver="strokeimage.src=stroke5.src ;window.status='you' ; return
true">
	
<AREA SHAPE=RECT ALT="created" HREF="#" COORDS="38,0,46,142"
onMouseOver="strokeimage.src=stroke6.src ;window.status='created' ;
return true">
	
<AREA SHAPE=RECT ALT="it" HREF="#" COORDS="46,0,54,142"
onMouseOver="strokeimage.src=stroke7.src ;window.status='it' ; return
true">
	
<AREA SHAPE=RECT ALT="in" HREF="#" COORDS="54,0,63,142"
onMouseOver="strokeimage.src=stroke8.src ;window.status='in' ; return
true">
	
<AREA SHAPE=RECT ALT="my" HREF="#" COORDS="62,0,69,142"
onMouseOver="strokeimage.src=stroke9.src ;window.status='my' ; return
true">
	
<AREA SHAPE=RECT ALT="mind" HREF="#" COORDS="69,0,78,142"
onMouseOver="strokeimage.src=stroke10.src ;window.status='mind' ;
return true">
	
<AREA SHAPE=RECT ALT="my" HREF="#" COORDS="79,0,88,142"
onMouseOver="strokeimage.src=stroke11.src ;window.status='my' ; return
true">
	
<AREA SHAPE=RECT ALT="mind" HREF="#" COORDS="88,0,97,142"
onMouseOver="strokeimage.src=stroke12.src ;window.status='mind' ;
return true">
	
<AREA SHAPE=RECT ALT="cannot" HREF="#" COORDS="97,0,105,142"
onMouseOver="strokeimage.src=stroke13.src ;window.status='cannot' ;
return true">
	
<AREA SHAPE=RECT ALT="let" HREF="#" COORDS="105,0,113,142"
onMouseOver="strokeimage.src=stroke14.src ;window.status='let' ;
return true">
	
<AREA SHAPE=RECT ALT="it" HREF="#" COORDS="112,0,121,142"
onMouseOver="strokeimage.src=stroke15.src ;window.status='it' ; return
true">
	
<AREA SHAPE=RECT ALT="go" HREF="#" COORDS="121,0,131,142"
onMouseOver="strokeimage.src=stroke16.src ;window.status='go' ; return
true">
	
<AREA SHAPE=RECT ALT="the" HREF="#" COORDS="131,0,140,142"
onMouseOver="strokeimage.src=stroke17.src ;window.status='the' ;
return true">
	

<AREA SHAPE=RECT ALT="ocean" HREF="#" COORDS="140,0,149,142"
onMouseOver="strokeimage.src=stroke18.src ;window.status='ocean' ;
return true">
	
<AREA SHAPE=RECT ALT="the" HREF="#" COORDS="149,0,155,142"
onMouseOver="strokeimage.src=stroke19.src ;window.status='the' ;
return true">
	
<AREA SHAPE=RECT ALT="waves" HREF="#" COORDS="155,0,160,142"
onMouseOver="strokeimage.src=stroke20.src ;window.status='waves' ;
return true">
	
<AREA SHAPE=RECT ALT="its" HREF="#" COORDS="160,0,165,142"
onMouseOver="strokeimage.src=stroke21.src ;window.status='its' ;
return true">
	
<AREA SHAPE=RECT ALT="a" HREF="#" COORDS="165,0,174,142"
onMouseOver="strokeimage.src=stroke22.src ;window.status='a' ; return
true">
	
<AREA SHAPE=RECT ALT="vision" HREF="#" COORDS="174,0,181,142"
onMouseOver="strokeimage.src=stroke23.src ;window.status='vision' ;
return true">
#+END_SOURCE

The surface of the peice only reveals part of the full message. First,
while most pages contain an author, title, and date, this one only
contains a title, "you:controlMe." It seems that the page was created
by Harvey addressing a message for Samyn to "control" her by moving
her face back and forth across the image. Second, the source code
reveals that the animation consists of 23 images, each of which is
associated with a specific alt-text and coordinate. Here, the full
message of the alt-text, which is hidden from the screen, appears in a
list like formate: "i believe in it you created it in my mind my mind
cannot let it go the ocean the waves its a vision." Each of these
images and its associated message is tied to a specific coordinate on
the screen's surface, which activates the relevant image and
alt-text. Thus the effect of Harvey's head moving across the screen is
in reality an image that has been activated by the mouse on a specific
coordinate and has been super-imposed on the screen. Rather than
represent a smooth movement from side to side, Harvey's head takes
little jumps from one position to another. The effect is a slight lag,
a series of fleeting pauses that intensify Harvey's direct gaze into
the camera.

When we examine the source code, we see that this peice is about
control, specifically, with control over the female body. It deploys
layers of foreclosure, where the source code contains the full message
and workings of the animation, to create a haptic effect that is
sensual but laggy. The haptics with the mouse indicate that full
control of Harvey's head and full access to the message is not
possible, there is something intractible about it. What's happening at
the level of code influences this screen effect. 

**** TODO breath.html
Below the overt narrative of surface effects, lies another narrative
within the source code, where hidden messages mix natural language
with computer language to make verbal exhortations of love. On one
page, "breath.html," the surface effects consists of an animated male
torso that swells slightly when the mouse pans over it accompanied by
the sound of breathing that also accelerates with each swipe of the
mouse. The effect is sensual, tactile, and auditory. In the pages
source code,, amid the HTML and JavaScript that defines the content
and animations, lie words meant only for human eyes. Here, a list of
"whispers" make romantic protestations like "i will love you forever"
and "i want to breath you." Unlike the previous example with
"control.html," these messages do not manifest directly on the
browser, but wait for the curious user to come and find them in the
source code.
#+BEGIN_SOURCE
whispers[0] = "breath me";

whispers[1] = "i will love you forever";

whispers[2] = "skin";

whispers[3] = "skin on skin";

whispers[4] = "skin on skin on skin";

whispers[5] = "implode";

whispers[6] = "soft";

whispers[7] = "slow";

whispers[8] = "can you feel me?";

whispers[9] = "touch me";

whispers[10] = "one more cigarette";

whispers[11] = "i am so open";

whispers[12] = "i want to feel you inside of me";

whispers[13] = "smoke";

whispers[14] = "i want to breathe you";

whispers[15] = "we are smoke";

whispers[16] = "yesss";

whispers[17] = "deeper";

whispers[18] = "i am disappearing";

whispers[19] = "warm";
#+END_SOURCE
Musser describes foreclosure as an overflow of surface effects that
preclude access below the surface. Similarly, this piece illustrates
how computer screens inherently contain a level of foreclosure that
masks inaccessible elements, like the line containing the work's
title, "skin on skin on skin." The hidden messages in the source code
suggest that there is always a level of displacement which creates
another channel for communication.

**** TODO
The final aspect of this text I want to discuss is reduction. The love
affair is reduced to digital objects which can pass over the
wires. The couple make this point in a chat between the two of them,
discussing how constraints constitute the relationship:
#+BEGIN_QUOTE
womanonfire: the sound is a bit distorted with these things

zuper: (private) yes

womanonfire: if no one was around me here

zuper: (private) the image is distorted too

womanonfire: i would speak to you

zuper: (private) but that's ok

womanonfire: yes!

womanonfire: these are all part of our relationship

womanonfire: these limitations

womanonfire: we must

zuper: (private) 26 letters, no sound, no image

womanonfire: learn new ways

zuper: (private) make DHTMLove to me... http://entropy8zuper.org/
#+END_QUOTE

The way that digital objects play with reductions of complexity here
evokes what Snorton says about the reduction of black bodies to
flesh. Such a reduction enables flesh to harness the chaos of
significatory possibility. I want to argue that digital objects, as
distillations of real world referents, are imbued with expressive
potential.



This screen surfaces a displacement inherent in all
significatory systems but particularly in machine language systems,
which rely on levels of abstraction in its software stack.


**** flash foreclosure
In "words.html,"
view-source:http://entropy8zuper.org/skinonskinonskin/rhizome/words.html
By Samyn on valentines day, 1999.

Samyn animates a beating heart, overlaid with words and phrases that
move in various arcs from its center. [SEE IMAGE/GIF]

The code for this page does various things: first, it defines the list
of strings, or words/phrases, which will arc over and around the
heart. Then, it includes a series of JavaScript functions that selects
words, calculates their trajectory and timing, and resets their
position to restart the loop.
#+BEGIN_SOURCE
function startMove()

{

floatWords(0,Math.round(words.length/4));

setTimeout("floatWords(Math.round(words.length/4),Math.round(words.length/2)
);",5000);

setTimeout("floatWords(Math.round(words.length/2),Math.round(words.length/4*
3));",10000);

setTimeout("floatWords(Math.round(words.length/4*3),Math.round(words.length));",15000);

};

function floatWords(startNumber,endNumber)

{

for ( i = startNumber ; i < endNumber ; i++ ) { floatWord(i); };

};

function rePos(thisNumber)

{


dMove('wordL'+thisNumber,'document.',halfW-rand(50),halfH-rand(50));
floatWord(thisNumber);

};

function floatWord(thisNumber)

{

var randTime = (rand(15) + 5 )*1000;

var thisRand = rand(4);

if ( thisRand == 1 ) { 
dMoveStraight('wordL'+thisNumber,'document.',-100-rand(100),rand(stageH),randTime,'wordVal'+thisNumber,'rePos(' +
thisNumber + ');',''); }

else if ( thisRand == 2 ) {
dMoveStraight('wordL'+thisNumber,'document.',rand(stageW),-20-rand(100),randTime,'wordVal'+thisNumber,'',''); }

else if ( thisRand == 3 ) {
dMoveStraight('wordL'+thisNumber,'document.',stageW + rand(100),rand(stageH),randTime,'wordVal'+thisNumber,'rePos(' + thisNumber + ');',''); }

else if ( thisRand == 4 ) {
dMoveStraight('wordL'+thisNumber,'document.',rand(stageW),stageH + rand(100),randTime,'wordVal'+thisNumber,'',''); }

if ( rand(4) == 1 ) { dShow('wordL'+thisNumber,'document.','visible'); };
}; "words.html"
#+END_SOURCE
I'm going to give a brief overview of each function. The first
function, ~startMove()~, sets a series of timers that initiate and
perpetuate the animation. The second function, ~floadWords()~, loops
through the list of words and phrases and passes individual selections
from this list to the next function, ~floatWord()~, which sets the
trajectory and timing for their movement. Within this function, a call
to ~rePos()~ repositions the word in a new location, to begin the
cycle anew. 

On line 98: "$we are disembodied arms and mouths "

Let us look more closely into the flash animation, which contains its
own foreclosures. Flash is a standalone application and web browser
plugin for authoring and viewing animations. It began development in
the mid-1990s and gained popularity for its ability to deliver
relatively advanced graphics (such as video and sound, primarily) at a
time when media-rich content traveled slowly over the web. However,
with the development of newer, more efficient and secure animation
technologies in the last 10 years, Flash began to fall out of
popularity and was officially discontinued on December
31st, 2020. Although the general internet user will not feel the
difference, since newer technologies like HTML5 and Javascript have
stepped up to deliver what Flash had initially offered in much more
flexible, portable, and efficient ways, this development has cast a
generation of internet games, net art, and electronic literature into
obsolesence. Today, the only way to view Flash content is through
plugins, emulators (like the one for /skin/), or "decompiler" programs
(discussed below).

The elements of foreclosure emerge most starkly with non-plain-text
content like Flash files. This is due to Flash code, unlike
plain-text, being a binary code format. If opened in a text editor,
for example, Flash files (which usually have an ".swf" or ".fla"
extention) would appear to be made of incomprehensible characters and
symbols, some of which the text editor may recognize, and others which
it would display as a question mark. For example, here is a plain text
rendition of the file that contains the sound animation of of the
heatbeat on "breath.html":

[IMAGE OF TEXT EDITOR OF OF HEARTBEAT.SWF]

Because binary code is unreadable to the human eye, it requires
specific authoring software to work with it. A "Flash decompiler"
program, for example, offers an interface for seeing the components of
a Flash file without having to deal with the machine code layer. The
file is separated into components. The above file, for example,
contains components like "sounds," "frames," and "scripts." So the
file becomes abstracted in a way that humans can make sense of
it. Below is an image of the flash decompiler interface, with all of
the components of the image on the left sidebar. Interestingly, when
examining the frames, one can distort the sound of the heartbeat.

[IMAGE OF FLASH DECOMPILER INTERFACE ON "HEARTBEAT.SWF"]

What I want to emphasize here is that this code cannot be edited
directly. 

How does an emulator work? Does emulation add another layer of
sensuality to the peice?]


In what follows, I'm going to examine the ways that Harvey's (black)
body has been reduced with this effect. The question of Harvey's race
emerges in a chat between Harvey and Samyn, though it is buffeted by
questions of physicality more generally. To get a sense of the
conversation, I quote the chat at some length: 
#+BEGIN_QUOTE
womanonfire: i wonder wht your voice is like

zuper: my voice?

zuper: let's try

zuper: it's weird to talk in a silent office at night

womanonfire: yes

womanonfire: i can just barely make you out

womanonfire: how fitting

womanonfire: it sounds so far away but you feel so close

zuper: yes

zuper: i am close

zuper: i don't understand myself

womanonfire: i will write you a very long letter tonight

zuper: I'm falling in love with a 160x120 pixel video...

zuper: Yes please write me a long letter

womanonfire: it is dificult for me here right now

zuper: why is it difficult?

womanonfire: i was just about to write one about this

womanonfire: because i love you

zuper: ...

womanonfire: seems so 

womanonfire: strange

womanonfire: maybe it is lust

womanonfire: i cant tell anymore

zuper: pixellust?

womanonfire: right

zuper: I my case only ASCIIlust...

womanonfire: but i want to make a home for us

womanonfire: in the network

zuper: Have you read Sterlings 'Holy Fire'?

womanonfire: no

zuper: They have places called 'Memory Palaces' on the net

zuper: where they keep all their souvenirs and where people can meet

womanonfire: i just heard you that time

womanonfire: !

zuper: in dutch!

womanonfire: yes!

zuper: (private) I realised today that I have never been in love with somebody who doesn't speak Dutch before.

womanonfire -> zuper: i have never been in love with someone in another country before

zuper: (private) I have never been in love with someone with green dreadlocks before

zuper: (private) let alone black skin

womanonfire -> zuper: yes i hope you wiwll like my skin

zuper: (private) I already do.

womanonfire -> zuper: :) http://entropy8zuper.org/ 
#+END_QUOTE
The question of race becomes one in a list of other physical
attributes, is equated to speaking a foreign language, is buffeted by
concerns about connectivity and finally, transported and made possible
by network technologies. 

The reduction of her body to certain attributes, her black skin and
green hair, for example, endows her physical being with expressive
possiblity. The dark-skinned green-haired floating woman. Here, the
less detail an element has, the more meaning the viewer can impose to
the elements.

We see this in the black hand which touches our screen. It is a simple
shape, but it is expressive.

l materiality hearkening back to black fem theory 
Sensuality in their shifts and their surface effects, particularly in
the way they foreclose /forensic/ materiality, refuse depth. Here we
draw from black feminist theorizing. 

**** haptics
Throughout this work, the user engages with HTML and JavaScript code
via haptics on the browser. The source code endows digital "objects"
with properties and methods so that they can become manipulable at the
level of surface. These constructs, which are defined under the hood
of the browser, enable sensual experiences for the user. 

**** foreclosure
The surface effects of the screen engage elements within the code,
which are inaccessible to the general user, to surface additional
layers of foreclosure.

**** obsolete elements
Due to modernization, the browser languages HTML and JavaScript use
now depreciated elements like ~<layers>~ and ~<area>~ to add
animation. Additionally, since Flash technology, a compiled software
that is not "human-readable", has been discontinued, it is very
difficult to find solutions for editing and viewing Flash elements.

** unstructured fragments
*** Hayles on data traveling up the stack
Hayles points out that, "Precisely because the relation between
signifier and signified at each of these levels is arbitrary, it can
be changed with a single global command" (Hayles, "Virtual Bodies"
77).

Flickering signifiers bring consideration of "transformations" into
view. though I do think she is underestimating the "matter," "energy"
which goes into it. 
#+BEGIN_QUOTE
When a text presents itself as a constantly refreshed image rather
than durable inscription, transformations would occur that would be
unthinkable if matter or energy, rather than informational patterns,
formed the primary basis for the systemic exchanges. This textual
fluidity, which humans learn in their bodies as they interact with the
system, imply that signifiers flicker rather than float. 30
#+END_QUOTE

In this movement up the stack, data shifts
between registers and becomes more tangible, a process that is belied
by the fleeting and diaphanous forms that finally emerge on the
computer screen.

Due to this appearance, the flickering signifier perpetuates a liberal
humanist ideology about the body/mind separation into the posthuman
one of hardware/code. Just as the mind rules the fleshy body, so the
/code/ represents a an insubstantial standard that drives computation.

Thinking about the illusion of digital materiality on the screen,
N. Katherine Hayles wonders, "Why do we talk and write incessantly
about the 'text,' a term that obscures differences between
technologies of production and implicitly promotes the work as an
immaterial construct?" ("Flickering Connectivities" 2000,
par. 57). 




* Works
Alarcon, Norma. "Conjugating Subjects in the Age of Multiculturalism"
/Mapping Multiculturalism/. Avery F. Gordon and Christopher Newfield,
editors. University of Minnesota Press. pp. 127-148.

Barthes, Roland. /Camera Lucida/.

Butler, Octavia. Dawn. Grand Central Publishing. 1987.

Chun, Wendy. Control and Freedom: Power and Paranoia in the Age of Fiber Optics. 2006.

Entropy8Zuper!. skinonskinonskin. Rhizome. https://anthology.rhizome.org/skinonskinonskin 

Galloway, Alexander and Eugene Thacker. The Exploit: A Theory of Network. Univ Of 
Minnesota Press. 2007. 

Galloway, Alexander. Protocol: How Control Exists after
Decentralization. 2004.

Hartman, Saidiya. "Venus in Two Acts." /Small Axe/, vol. 12 no. 2,
   2008, p. 1-14. Project MUSE muse.jhu.edu/article/241115.

Hayles, N. Katherine. "Flickering connectivities in Shelley Jackson's
Patchwork Girl: the Importance of Media-Specific Analysis," 2000.

Hayles, N. Katherine. Writing Machines. MIT Press, 2002. p. 107.

Kirschenbaum, Matthew G. Mechanisms: New Media and the Forensic Imagination. MIT Press 
2008.

Moraga, Cherrie. "La Guera", from /Loving in the War Years: Lo que
nunca paso' por sus labios/.

Musser, Amber Jamilla. /Sensual Excess: Queer Femininity and Brown
Jouissance/. NYU Press,
2018. JSTOR, http://www.jstor.org/stable/j.ctvwrm5ws. 

Musser, Amber Jamilla. "Surface-Becoming: Lyle Ashton Harris and Brown
  Jouissance." /Women & Performance/, vol. 28,. no. 1. February 26, 2018
  https://www.womenandperformance.org/bonus-articles-1/28-1-harris. 

Sandoval, Chela. "U.S. Third World Feminism: The Theory and Method of
Oppositional Consciousness in the Postmodern World."

Schutte, Ofelia. “Cultural Alterity: Cross-Cultural Communication and
Feminist Theory in North-South Contexts.” /Hypatia/, vol. 13, no. 2,
1998, pp. 53–72.

/skinonskinonskin/ (1999). Rhizome.org /Net Art Anthology/.
https://anthology.rhizome.org/skinonskinonskin

Snorton, C. Riley. Black on Both Sides: A Racial History of Trans Identity. University of 
Minnesota Press, 2017. JSTOR, https://doi.org/10.5749/j.ctt1pwt7dz;

Spillers, Hortense J. “Mama’s Baby, Papa’s Maybe: An American Grammar Book.” Diacritics, 
vol. 17, no. 2, 1987, pp. 65–81. JSTOR, https://doi.org/10.2307/464747

* Footnotes

[fn:4]  For example, one could balance a twelve-inch ruler by placing
a finger under the sixth inch. By applying some force to the center of
mass, the object would not pivot, but move in a linear direction,
either up or down, or sideways, depending on the direction of the
force. However, if external force was applied along either side of the
center, say at the second inch, the object would pivot. Its direction
would then be determined by its pivot point, whether that be its
center of mass or the point where the object is affixed to another
object, if the ruler were nailed to the wall, for example. In this
case, the ruler would pivot around this point of attachment, and the
force and direction of its pivot would be measured as "torque."

[fn:1]  Hayles's influential text, /How We Became Posthuman: Virtual
Bodies in Cybernetics, Literature, and Informatics/ (2000), lays out
the "waves of cybernetic development," that is, the development of
systems theory among prominant information and communication theorists
like Norbert Wiener, John von Neumann, Claude Shannon, and Warren
McCulloch (2).

[fn:3] Haraway draws from Chela Sandoval's concept of "differential
consciousness" that "constructs a kind of postmodern identity out of
otherness, difference, specificity" (/Simians/ 155).

[fn:2] Chela Sandoval describes "tactical subjectivity" as the process
by which identity formations constantly shift to elude and oppose the
universalizing tendendies of identity politics (Sandoval 1991, 14).

