* three

** overview

This chapter looks at the materiality of digital media by harnessing
concepts of the flesh as developed in black feminsist studies. 

First I consider how the flesh has been theorized in black feminist
studies, looking primarily at Snorton and Musser. The concept of the
pornotrope, which is the reduction of body to flesh, offers an
analytic for understanding the kind of capacious thinking required
when two registers combine---the physical/analog and the
immaterial/digital. 

Throughout this converstation, I incorporate a discussion of Octavia
Butler's /Dawn/ novel as a way of reading the intersection between the
digital and analog, particularly in the way that sexual relations
occur through direct neural stimulation between alien/human "triples,"
facilitated through the third partner, non-binary intermediary being
with the ability to connect directly to the brain's pleasure centers.

Then, I examine a hypertext fiction work, a digital series by
Entropy8Zuper! entitled /skinonskinonskin/ (1999), and efforts at its
preservation amid the obsolescence of one of its major components,
Flash technology. I trace the complicated stack of hardware and
software that facilitate the display and preservation of this work,
examining various technologies that work in tandem such as internet
networks, hypertext, and Flash. These technologies together enable me
to explore how /skinonskinonskin/'s interface engages the intersection
between the digital and analog registers undergirding its components. 


** intro: detail from Butler's /Dawn/
How can sex be more sensational if it bypasses the flesh? This is a
contradiction of registers, the analog and the digital. 

Explain a scene where they have sex, showing how it's like the analog
and the digital. (But the secret, which the chapter will reveal, is
that the digital is analog all long...)

** flipping the pornotrope
*** outline
+ examining the contradictions
+ methodology to read into details
+ race emerges in the space of image, the floating space. the concept
  of black flesh enable collision of two registers
+ reading escapability in the image, resisting the reduction to flesh (musser)
- this is queer form (are there other people I want to look at?)


what do I need in order to talk about /Dawn/? See my handwritten
notes.

*** flipping the reductions: spillers to snorton, musser
In the nearly impossible task of accounting of the egregious yet
overlooked of horrors of transatlantic slavery, black feminist
thinkers flip a concept that has been used to for the evils of
subjectification--the flesh. The idea of black flesh is a reduction of
the black body is first theorized by Hortense Spillers in her
influential essay, "Mama's Baby, Papa's Maybe: An American Grammar
Book." Here Spillers puts forth the conception of the black body as a
stack of "attentuated meanings, made in excess over time, assigned by
a particular historical order" (65). These meanings developed from the
body that had been reduced to flesh, a violent process, "severing of
the captive body from its motive will," that Spillers traces to the
middle passage and has four effects (67):
#+BEGIN_QUOTE
1) the captive body becomes the source of an irresistible, destructive
   sensuality;
2) at the same time- in stunning contradiction - the captive body
   reduces to a thing, becoming being for the captor;
3) in this absence from a subject position, the captured sexualities
   provide a physical and biological expression of "otherness";
4) as a category of "otherness," the captive body translates into a
   potential for pornotroping and embodies sheer physical
   powerlessness that slides into a more general "powerlessness,"
   resonating through various centers of human and social meaning. 67
#+END_QUOTE
Imposed by the reduction of bodies to bare physicality, to a material
substance, there is, in "stunning contradiction," some form
of meaning aheres to the flesh, a potential combination of sensuality,
objectificaiton, otherness, and powerlessness (Spillers 67).

Snorton suggests that this stripping (and imposition) of meaning
creates a possibility for resignifying black flesh, which "await[s]
whatever marvels of... inventiveness" (Spillers 65). More recently,
black feminist theorists such as C. Riley Snorton, Amber Musser, and
Jayna Brown, for example, looks at the denigration of black flesh as a
simultaneous enabling of blackness as power. Snorton, for example,
demonstrates that the whittling down of black subjects to the
interchangeable, what he calls the "fungible," in chattel slavery
creates a possibility for for "fugitivity," or escape. His theorizing
uses the properties of flesh to trace the contradictions that produce
race and gender, for "Captive and divided flesh functions as malleable
matter for mediating and remaking sex and gender as matters of human
categorization and personal definition" (20). To demonstrate the
imbrication between sex, race, and black flesh, Snorton examines how
the denial of femininity of black slaves, whose bodies were used for
experimental purposes, enabled the emergence of field of gynecology as
a /white/ women's science. Snorton explains that, white femininity,
which prevents the inspection of white female genitalia, is
constructed out of the "scopic availability" of black flesh of women
(33). Yet, Snorton crucially asserts, this genderless flesh is also a
"capacitating structure" which enables "fungibility for fugitive
movement" (53). Here, Snorton interweaves various narratives of
fugitivity, such as that of Harriet Jacobs, who escaped slavery in
1842 and subsequently wrote /Incidents in the Life of a Slave Girl/
(1861). Snorton points out that, while traditional racial "passing"
assumes white passing, it is blackness which gives one the "gender
indefiniteness" to enable "cross-gendered modes of escape" (56). The
"blackening" of Jacobs, for example, allowed her to obtain a level of
"fungibility, thingness" that precluded her recognition (Snorton 71).

For this "black and trans historiographical project," Snorton
demonstrates flesh as the physical and malleable material that enables
the construction of social categories like race and gender. Snorton's
method takes the details of the archival record as "conditions of
possibility" in his study, and reads for hints of resistance contained
within the dominant narrative that suggest the ommitted, obscured, or
elided experience of black subjects (Snorton 11). One example concerns
a slave woman, Anarcha, whose severe case of Vaginal Fistula made her
an object of medical experimentation. Because the record that hardly
mentions her by name (when it does not misname her) is silent about
her experience of what certainly were painful and prolonged surgeries
without anesthetics, Snorton turns to seemingly minor details like
smell and the presence of other enslaved women to "further imaginative
capacities" for reading resistance (14). Anarcha's reportedly
offensive smell, what Snorton calls the "discourse of disgust," for
example, indexes both her subjection to social hierarchy and her
resistance, for "the recurrent descriptors of Anarcha's body odor
provides an opening to imagine what modicums of protection might have
been afforded by smelling noxious to one's enslaver"
(27). Additionally, the banal reality of servitude implies that other
slave women such as Lucy and Betsey (among others who were unnamed),
stood as medical assitants when necessary, which opens speculation
into "modes of nourishment and care" they provided one another
(Snorton 29); In one procedure on Betsey, for example, Snorton
explains that "the opacity in the archive... leaves room to imagine
how Betsey might have somehow resisted the performance of stoic
bravery or willing subjectivity that she was compelled to produce"
(25).

This methodology uses the critical imagination to read into what
Saidiya Hartman and others call "the violence of the archive," a
violence not only in the form of evidence, that the records literally
obscure or overlook information, but also in the tools of expression,
in the language that cannot approximate experience, and in the
discourse that dictates silence (2). Like "Critical fabulation,"
Snorton's reading of archival material draws narrative from the gaps
and lacunae of the evidence, working to "expose and exploit the
incommensurability between the experience of the enslaved and the
fictions of history" (Hartman 10). One difference however, which is
crucial for my purpose, is the influence of /flesh/ following Spillers
as the "zero degree of social conceptualization" (Spillers
67). Snorton's attention to flesh as a /ground/ for theorizing enables
him to attend to the implications of format and form in the
archive. For example, Snorton explains that the materiality of a
daguerreotype suggests "a visual grammar for reading the imbrications
of 'race' and 'gender' under captivity" (40):
#+BEGIN_QUOTE
To view a daguerreotype is to look at an image that does not sit on a
surface but appears to be floating in space. Rather than an antiquated
form of modern photography, as Foucault’s characterization implies,
the daguerreotype provides a series of lessons about power, and racial
power in particular, as a form in which an image takes on myriad
perspectives because of the interplay of light and dark, both in the
composition of the shot and in the play of light on the display. That
the image does not reside on the surface but floats in an unmappable
elsewhere offers an allegory for race as a procedure that exceeds the
logics of a bodily surface, occuring by way of flesh, a racial
mattering that appears through puncture in the form of a wound or
covered by skin and screened from view. 40
#+END_QUOTE
The format of the dagguereotype evokes the method by which meaning is
stripped then reapplied to flesh that, for captive bodies, "functioned
as a disarticulation of human form from its anatomical features"
(18). The physical material of the image, that is the silvered copper
plate of the daguerreotype, at once solidifies its ground and indexes
an ambiguous space, what Snorton describes as the "unmappable
elsewhere" which swells to obscure while containing the evidence of
racial significations. Snorton's curious use of the word "puncture"
here recalls Roland Barthes's concept of the "punctum," which indexes
the experience of being pierced by a detail of the photograph (/Camera
Lucida/ 27). Opposed to the concept of the /studium/, which represents
the dominant historical, social, or cultural meaning portrayed within
and by the photograph, the /punctum/ is the "sting, speck, cut, little
hole... that accident which pricks me (but also buises me, is poignant
to me)" (Barthes /Camera Lucida/ 27-28). Barthes explains that,
"However lightning-like it may be, the /punctum/ has, more or less
potentially, the power of expansion. This power is often metonymic"
(/Camera Lucida/ 45). For Barthes, the /punctum/ is that detail of a
photograph which at once pierces the viewer and suggests an expansion,
an effect which is exagerrated in erotic photographs, where the
/punctum/, "is a kind of subtle /beyond/--as if the image launched
desire beyond what it permits us to see" (59). Barthes's theorization
of the /punctum/ allows us to see how the flesh can be at once a
/mattering/, a becoming matter, and an accumulation of meaning, which
in simulteneity, has the effect peirces the viewer. We cannot, as
Snorton points out, locate the image at a specific point on the
copper-plate is essential, though we can feel its puncture. That the
image cannot be traced back to a single location, yet is contained and
signifies within that physical space, is crucial for undersanding the
way that the physical registers interact with symbolic ones. The
meeting between this liminal space of the image's meanings and its
silver-plated copper ground offers a means for thinking through the
collision of two registers, of flesh against gender & race.

Amber Jamilla Musser runs with the notion of unmappability to theorize
surface aesthetics in her conception of /brown jouissance/. Like
Snorton, Musser develops her ideas alongside a reading of photograph
technology, in this case, from a photograph of the artist Lyle
Harris's "citation" of Billie Holiday. Musser's reading of the
photograph theorizes the way that escapability emerges from the
superfical, the surface of this image, in its "shine" revealing a self
that is excessive yet inaccessible. Musser notes the details of
Harris's dress, such as the "pearls, eye shadow and lipstick" that
capture the light of the image, as the "Shine [which] plays joyfully
with the idea of the body as body while rejecting the demand to
present anything other than surface" ("Surface-Becoming"
par. 3). Moving beyond the unmappable elsewhere, surface for Musser
not only indexes but /forecloses/ access to that which we cannot know:
She explains, "we can understand surface as the underside of the
scientific/pornographic drive toward locating knowledge in an
'objective' image" ("Surface-Becoming" par. 2). The material of the
surface, which "highlights the mutability of the flesh rather than
interiority," suggests that which escapes its own form (Musser,
"Surface-Becoming" par. 11). While foreclosing the reading of
interiority, the surface aesthetics opens up other considerations,
such as the evocation of hunger in Lyle's open mouth: "sticking with
the surface--–through the use of Polaroid and shine–--illuminates the
possibilities of imaging a self whose interiority we do not have
plumb, but who still generates creative possibilities for resisting
the mandate of sovereign subjectivity" ("Surface-Becoming"
par. 23). To locate in something physical that which eludes
physicality is a way of resisting (without attempting to recuperate)
the reduction of body to flesh.

*** TODO via the pornotrope, the flesh becomes a queer form
This method is about /taking what has been a method of reduction/,
what has been a tool for appropriating the complexity of real world
objects for the purpose of exploitation, and using that /to instead
seek out moments of illegibility/, opacity. To multiply rather than
resolve meaning.

** alien sex (is queer bc sensational, bypassing flesh?)
*** outline
- Butler establishes fear and violence as innate to humanity. 
- Alien sex in /Dawn/ bypasses flesh to amplify sensation
- What have Brown, Jackson said about Butler and /Dawn/?
- What is the general criticism of this book?
- Pose black feminist thinkers on the question of sensation against
  traditional white male accounts. Counter William James with Dereik
  Scott.

*** /Dawn/
For Spillers, Snorton, and Musser, the flesh has been a location from
which to theorize the various (racial) meanings ascribed to it over
time. The /fact of the flesh/, that is its physical materiality which
indexes a liminal space where meaning is simultaneously ascribed to
and obscured from that materiality, functions a solid ground for
theorizing.

Octavia Butler's novel, /Dawn/, published in 1987, is the first book
of a trilogy, initially titled /Xenogenesis/ and more recently,
/Lilith's Brood/, about one human family who must, as a question of
survival, interbreed with extra terrestrial beings. /Dawn/ relates the
story of this family's matriarch, Lilith Iyapo, who is "rescued" from
nuclear war by the extra terrestrials, the Oankali. The story begins
with Lilith waking up in a prison cell on the Oankali spaceship, where
she soon finds out that the humanity has been all but extinguished and
that the Oankali intend to reproduce with the remaining survivors. For
the rest of the book, Lilith attempts to convince a group of humans
whom she has been chosen to "mother" to accept the conditions for
their survival while she herself struggles to come to terms with its
implications. [INSERT BROWN pages 94-99 QUOTE ABOUT THE QUESTION BEING
OF WHAT IT MEANS TO SURVIVE... TO PERSIST OR TO CHANGE].

The importance of the book is that we need ways of conceptualizing
relationships without fixing or recuperating histories of violence and
oppression. [INSERT MUSSER QUOTE ABOUT THIS] There are things that
Butler does to establish that fear of the unknown in humanity and the
impulse to discriminate is innate. She doesn't ignore them, and she
doesn't fix them. She opens a capacious way of thinking beyond the
binaries. She inserts a third element.

**** Fear of the strange flesh is xenophobia, it is innate in humans:
#+BEGIN_QUOTE
The lights brightened as she had supposed they would, and what had
seemed to be a tall, slender man was still humanoid, but it had no
nose—no bulge, no nostrils—just flat, gray skin. It was gray all
over—-pale gray skin, darker gray hair on its head that grew down
around its eyes and ears and at its throat. There was so much hair
across the eyes that she wondered how the creature could see. The
long, profuse ear hair seemed to grow out of the ears as well as
around them. Above, it joined the eye hair, and below and behind, it
joined the head hair. The island of throat hair seemed to move
slightly, and it occurred to her that that might be where the creature
breathed—-a kind of natural tracheostomy.  

...  

She did not want to be any closer to him. She had not known what held
her back before. Now she was certain it was his alienness, his
difference, his literal unearthliness. She found herself still unable
to take even one more step toward him.  

“Oh god,” she whispered. And the hair--the
whatever--it-was--moved. Some of it seemed to blow toward her as
though in a wind—though there was no stirring of air in the room.

She frowned, strained to see, to understand. Then, abruptly, she did
understand. She backed away, scrambled around the bed and to the far
wall. When she could go no farther, she stood against the wall,
staring at him.

Medusa.
#+END_QUOTE 

**** Assumption of gender, it is human to categorize: 
#+BEGIN_QUOTE
Lilith glanced at the humanoid body, wondering how humanlike it really
was. “I don’t mean any offense,” she said, “but are you male or
female?”

“It’s wrong to assume that I must be a sex you’re familiar with,” it
said, “but as it happens, I’m male.”  

Good. “It” could become “he” again. Less awkward.
#+END_QUOTE

**** Human tendency toward hierarchy is violence
#+BEGIN_QUOTE
Jdahya made a rustling noise that could have been a sigh, but that did
not seem to come from his mouth or throat. “You are intelligent,” he
said. “That’s the newer of the two characteristics, and the one you
might have put to work to save yourselves. You are potentially one of
the most intelligent species we’ve found, though your focus is
differ-ent from ours. Still, you had a good start in the life
sciences, and even in genetics.”  

“What’s the second characteristic?  

“You are hierarchical. That’s the older and more entrenched
characteristic. We saw it in your closest animal relatives and in your
most distant ones. It’s a terrestrial characteristic. When human
intelligence served it instead of guiding it, when human intelligence
did not even acknowledge it as a problem, but took pride in it or did
not notice it at all. . .“ The rattling sounded again. “That was like
ignoring cancer. I think your people did not realize what a dangerous
thing they were doing.”
#+END_QUOTE

**** hierarchy vs acquisitive --> these are both oppressive social
forms:

For the Oankali, the nature is to acquire, which is why they do not
understand killing. (See fight scenes). 
"We’re not hierarchical, you see. We never were. But we are
powerfully acquisitive. We acquire new life—seek it, investigate it,
manipulate it, sort it, use it. We carry the drive to do this in a
minuscule cell within a cell—a tiny organelle within every cell of our
bodies."

They are colonizers. But not in a hierarchical way.  The Oankali are
actually very manipulative. They are gene colonizers, and they have
this impulse to spread and mix the genes.  A question---because they
do not acknowledge a hierarchical tendency, does this mean they are
immune to ethical questions about coercion and manipulation?

If everything is connected, like in the ship, then consent seems to
change from what we thought it was. Everything is part of the same
organism, how do you express non-consent? Everything must be working
together, there has to be a consensus there.

**** intelligence will handicap itself -> see history of male
theorizing on the sensation which overlooks what it well pleases

It’s interesting that reason will handicap itself from diagnosing its
own irrationalities. It will explain them away. Why does reason do
this?  Intelligence is largely an operation that orders, organizes,
things. Makes judgements and therefore places things in a
hierarchy. This organization or ordering is inherent to the way that
intelligence works, right? So there is the conflict. Reason can
rationalize hierarchy as a good thing, as an efficient thing.

**** Alien sex paradoxically bypasses flesh to amplify sensation
This is a paradox!

The novel examines an otherwise epistemology for the problem of flesh,
sensation, sex. The question that Bulter explores: How can the
sensational sidestep the flesh?

What does it say about pleasure and touch? About pleasure and
mediation?  This is a question that I’m also exploring in my Orals
reading, the question of locating pleasure in the interface, of
whether we can locate pleasure in the immediacy of an interface that
fades from view---from the direct “connection” between two neural
systems---or from the levels of mediation between two entities, such
as the skin, sexual organs, etc.  So which sex is more pleasurable?

The sharing of sensory experiences via the central nervous system.
This is “jacked in”. We see this in Neuromancer. The idea that a human
can directly link or connect to another system. It’s a hallucination.
This goes back to the question of sex, but here extends it to other
experiences. The ooloi have both sensory sharing and what I’ll call
reflective relation. They can use both, while humans only have access
to to the reflection, to the words that always occur after the fact.


together, there has to be a consensus there.

**** Philosophy of Sensation

** /skinonskinonskin/ (1999)

*** adobe flash

* Works
Barthes, Roland. /Camera Lucida/.

Hartman, Saidiya. "Venus in Two Acts." /Small Axe/, vol. 12 no. 2,
   2008, p. 1-14. Project MUSE muse.jhu.edu/article/241115.

Musser, Amber Jamilla. “Surface-Becoming: Lyle Ashton Harris and Brown
  Jouissance.” /Women & Performance/, vol. 28,. no. 1. February 26, 2018
  https://www.womenandperformance.org/bonus-articles-1/28-1-harris. 

Snorton, C. Riley. /Black on Both Sides/

Spillers, Hortense. "Mama's..."
