** quotes

*** Adair on the "trans anti-archival"

"there’s nothing inherently radical about a preservationist politics,
nothing inherently life-saving about saving files"
- Cassius Adair, "[[http://www.drecollab.org/delete-yr-account-part-i/][Delete Yr Account: Speculations on Trans Digital
Lives and the Anti-Archival, Part I: Are You Sure?]]" 

Talking about the fact that livejournal has disappeared. 

"Perhaps, we can think about self-deletion of a digital archive as
also an act of refusal of the datafied body, the body made digital
target, the data body as extraction site. If this is the case,
deletion isn’t necessarily an eradication. Sometimes, you have to
delete the archive to become a new self."
- Cassius Adair, "[[http://www.drecollab.org/delete-yr-account-part-i/][Delete Yr Account: Speculations on Trans Digital
Lives and the Anti-Archival, Part I: Are You Sure?]]" 

"forgetting and remembering are both time-travelers’ acts... they
invoke both history and future at once, each word conjuring a current
or even future subject who can re-engage the past in their present."
- Cassius Adair, "[[http://www.drecollab.org/delete-yr-account-part-i/][Delete Yr Account: Speculations on Trans Digital
Lives and the Anti-Archival, Part I: Are You Sure?]]" 





** notes

On the material level -- deletion is very difficult: 
The desire for deletion has to vie with the reality of material
permanence. Nothing is ever really deleted, it is just overwritten or
obscured, or even made irrelevant among vast amounts of information.

Disappointment or suprise in the archive (Rusert, Kazanjian) is now
giving way to anxiety and ambivalence about accessing people's past
lives and identities. 
