* Chapter One Brainstorm

** Rough outline for chapter:
- touch as a reading method: making & opening connections
- queerness as untouchable: something we cannot fully grasp
- data as unknowable: something we cannot fully grasp
- abstraction as necessary in order to bring things into relation
- the parallels between DH and Queer theorists, different reading
styles; refocus on touch
- my reading of /voyant-tools/ & /waves/?

*** Pros Description: The first chapter, "Reading: 'Touching without
Touching,'" lays out what Digital Humanities methodologies might learn
from Queer Theory. This chapter looks at specific reading practices by
Eve Kosofsky Sedgwick and Heather Love, which question the proper
relationship of the critic to the object of study. Sedgwick's ideas
about "touching/feeling" and Love's notion of "touching without
touching" pose queer modes of relationality that do not presume full
connections as prerequisite for analysis. This chapter engages these
techniques with various critical methods from the Digital Humanities,
including distant, surface, and post-critical reading, and
deformative, algorithmic, and speculative criticism. I pay particular
attention to how digital formats and interfaces might facilitate queer
critical methods, and I speculate on the intimate process of engaging
with literature on a computer, where users can manipulate and
transform text in virtually infinite and unique ways. Comparing three
very different kinds of digital projects based on text manipulation,
including the text analysis web application /Voyant-Tools/, the text
encoding archive, /Women Writers Online/, and a hypertext novella by
Caitlin Fischer, /These Waves of Girls/, I explain how these tools
work alongside the reader’s intuition, in what Jerome McGann calls a
“prosthetic extension of that demand for critical reflection,” by
which the reader is able to feel her way through the text (18). In
particular, I find that the haptic and exploratory activity of working
with these tools enlivens the reading process by allowing the reader
to play, experiment, and imagine new connections to the textual
object.


** A new way of reading--guided by touch
*** touch, reading: Sedgwick's /Touching Feeling/

Touch is the first site of connection between the queer and the
digital. 

Anzaldua shows how touch is a way of preventing conflict.

Sedgwick shows that touch is a way of multiplying connection. 

** Queerness as untouchable: Resisting overreading
This section explores how reading practices grapple with histories of
queer pain and exclusion to open up new possibilities for
interpretation based on feeling rather than redemption or closure. It
starts to draw out similarities on the ways that queer theorists and
DH practitioners view the objects of their study. 

*** Heather Love's queerness as failure, impossible
Love offers a model of "feeling backward" which is a way for critics
to connect with queer subjects in a way that keeps objects out of the
critic's reach. 

For Love, identification is about finding the moment when the subject
turns away: "Queer history has been an education in absence" (50.)

This moment of turning away characterizes queerness as something raw,
which cannot be captured. 

*** Ann Cvetkovitch's trauma is public, archives are affective. 

Cvetkovitch shows how affirming queer negativity, in trying to
recusitate bad feelings, can actually create more harm. 

She is good at recognizing that some things cannot be figured, while
expanding the archive

Critique: the critic goes too far in making assumptions about the
healing potential of public acts of queer trauma. The critic is not a
psychologist, trauma still kills people, those traumatized need to
seek treatment. 

The point isn't heal or recuperate queer suffering, this can never be
done through abstraction, not by the critic. The point is to examine
the ways that queerness is figured through abstraction--I think? We do
not say whether these things are healing. All we can deal with is the
data that we are given.

** Data as always cooked
*** Johanna Drucker's capta

Shows the reductions of data that are necessary for most graphical
visualizations. Counters these with the concept of "capta" and
graphical expressions that can gesture toward the messiness of
experience. 

*** Ted Underwood on studying models

Ted Underwood puts forth a good understanding on quantification being
no more more objective than words. [insert quote Sinclair that numbers
are strings] Rather than using "distant reading" to ascertain "facts"
about literary history, he's examining what models are really doing by
themselves. His focus on "perspectival modeling" brings the computer
process under scrutiny, as the object of study.

However, there still exists a view that distant reading lacks the
sensitivity of close reading. "Critics who want to sensitively
describe the merits of a single work usually have no need for
statistics" (xxi). 

** Abstraction: for multiplying potential connections
*** Kosofsky Sedgwick's "touching/feeling"
Eve Kosofsky Sedgwick has explained how /reading/ can be either
liberatory or relational. Which is to say it can be a tool for closing
or opening further readings. Sedgwick critiques Michel Foucault for
contributing to a model of "suspicious reading:" an approach that
mines a text for what is hidden, latent, or just beneath the
surface. Foucault's "repressive hypothesis" posits that discourse on
sexuality has been 

"I have tried in this project to explore some of the ways around the
topos of depth or hiddenness, typically followed by a drama of
exposure, that has been such a staple of critical work of the past
four decades" (/Touching Feeling/, 8). 

*** Klein's figuring absence

Lauren Klein finds a way to show what is not there in the data. Is
this the same? 

*** Felski's "post-critical reading"
    
** Digital reading methods (aware of the critic's role):
Digital formats and interfaces facilitate queer encounters methods, an
intimate process of engaging with literature on a computer, where
users can manipulate and transform text.

*** McGann's "prosthetic extension" 
These tools work alongside the reader’s intuition, in what Jerome
McGann calls a “prosthetic extension of that demand for critical
reflection,” by which the reader is able to feel her way through the
text (18).

*** Moretti & Underwood's "distant reading"
*** Ramsay's "algorithmic criticism" 

** Digital projects based on text manipulation: 
I find that the haptic and exploratory activity of working with these
tools enlivens the reading process by allowing the reader to play,
experiment, and imagine new connections to the textual object.

*** /Voyant-Tools/
Jerome McGann "prosthetic extensions"
Potential texts: Woolf's /Orlando/. 

- Interweave a narrative about touch. Taking new materialist ideas but
placing them within context of QPOC critiqe. Anzaldua and Bennet on
touch and severing. Sarah Ahmed too. 

*** /These Waves of Girls/
Following narrative desire. The click of the mouse allows readers to
move with the text, based on their own paths. 

*** what are some print texts that enact these principles of movement?
- Alison Bechdel's "Are You My Mother": where every page is vibrating
with reference. 
