* Chapter One Brainstorm

*** Pros Description: The first chapter, "Reading: 'Touching without
Touching,'" lays out what Digital Humanities methodologies might learn
from Queer Theory. This chapter looks at specific reading practices by
Eve Kosofsky Sedgwick and Heather Love, which question the proper
relationship of the critic to the object of study. Sedgwick's ideas
about "touching/feeling" and Love's notion of "touching without
touching" pose queer modes of relationality that do not presume full
connections as prerequisite for analysis. This chapter engages these
techniques with various critical methods from the Digital Humanities,
including distant, surface, and post-critical reading, and
deformative, algorithmic, and speculative criticism. I pay particular
attention to how digital formats and interfaces might facilitate queer
critical methods, and I speculate on the intimate process of engaging
with literature on a computer, where users can manipulate and
transform text in virtually infinite and unique ways. Comparing three
very different kinds of digital projects based on text manipulation,
including the text analysis web application /Voyant-Tools/, the text
encoding archive, /Women Writers Online/, and a hypertext novella by
Caitlin Fischer, /These Waves of Girls/, I explain how these tools
work alongside the reader’s intuition, in what Jerome McGann calls a
“prosthetic extension of that demand for critical reflection,” by
which the reader is able to feel her way through the text (18). In
particular, I find that the haptic and exploratory activity of working
with these tools enlivens the reading process by allowing the reader
to play, experiment, and imagine new connections to the textual
object.


** Queer modes of relationality (do not presume full connections):
This section explores how reading practices grapple with histories of
queer pain and exclusion to open up new possibilities for
interpretation based on feeling rather than redemption or closure. 

*** Heather Love's "touching without touching"
Identify love's issue with reading: it's about subjects who need their
distance, need their free rein, lest they become part of a narrative
of redemption or resolution. The job of the critic is not to resolve
or redeem their pain. The job of the critic is to identify, but not
fully. To create a play of recognitions.

What does this reading practice look like?


***  Kosofsky Sedgwick's "touching/feeling"
Eve Kosofsky Sedgwick has explained how /reading/ can be either
liberatory or relational. Which is to say it can be a tool for closing
or opening further readings. Sedgwick critiques Michel Foucault for
contributing to a model of "suspicious reading:" an approach that
mines a text for what is hidden, latent, or just beneath the
surface. Foucault's "repressive hypothesis" posits that discourse on
sexuality has been 

"I have tried in this project to explore some of the ways around the
topos of depth or hiddenness, typically followed by a drama of
exposure, that has been such a staple of critical work of the past
four decades" (/Touching Feeling/, 8). 


** Digital reading methods (aware of the critic's role):
Digital formats and interfaces facilitate queer encounters methods, an
intimate process of engaging with literature on a computer, where
users can manipulate and transform text.

*** McGann's "prosthetic extension" 
These tools work alongside the reader’s intuition, in what Jerome
McGann calls a “prosthetic extension of that demand for critical
reflection,” by which the reader is able to feel her way through the
text (18).

*** Moretti & Underwood's "distant reading"
*** Felski's "post-critical reading"

*** Ramsay's "algorithmic criticism" 

*** Drucker's "speculative computing"

** Digital projects based on text manipulation: 
I find that the haptic and exploratory activity of working with these
tools enlivens the reading process by allowing the reader to play,
experiment, and imagine new connections to the textual object.

*** /Voyant-Tools/
Jerome McGann "prosthetic extensions"
Potential texts: Woolf's /Orlando/. 

*** /These Waves of Girls/
Following narrative desire. The click of the mouse allows readers to
move with the text, based on their own paths. 

*** what are some print texts that enact these principles of movement?
- Alison Bechdel's "Are You My Mother": where every page is vibrating
with reference. 
