*** sensual fullness of a lack
- Returning to the question about /Waves/: How does its structure
  relate to queerness? 
- A lack of fulfillment/total understanding draws on this idea that
  queerness strategically lacks a teleology.
    - Insert: /Confessions/ reading?
    - Munoz: queerness is not here. Queerness is a structuring mode of
      desiring. 
    - What does this gain us? A way of reading touch that is more
      concerned with exploring the potential of a touch rather than
      verifiable contact. The sensual fullness of a lack. 

TEXT:

 Clicking
(touching) her way through the narrative, the reader is repeatedly
reminded of her removal from the story, in her inability to grasp the
story. This work thus literalizes the connection between touch, its
frustration, and queer desire.

It is interesting that this medium makes the story accessible through
touch (the “click” on the hyperlinks) while not giving full visual
access to the individual narratives like a traditional print work
(which is a phenomenon exaggerated in the ticker tape). 
*** space break

The performative approach to language--the idea that language can
produce meaning seems to hit its own limit at a specific point in the
novel. At this point, the crisis of signification comes to a climax,
when the biographer increasingly drops his pretension toward accuracy
and boldly speculates:
#+BEGIN_QUOTE
‘Shel, my darling,’ she began again, ‘tell me…’ and so they talked two
hours or more, perhaps about Cape Horn, perhaps not, and really it
would profit little to write down what they said, for they knew each
other so well that they could say anything, which is tantamount to
saying nothing, or saying such stupid, prosy things as how to cook an
omelette, or where to buy the best boots in London, things which have
no lustre taken from their setting, yet are positively of amazing
beauty within it. For it has come about, by the wise economy of
nature, that our modern spirit can almost dispense with language; the
commonest expressions do, since no expressions do; hence the most
ordinary conversation is often the most poetic, and the most poetic is
precisely that which cannot be written down. For which reasons we
leave a great blank here, which must be taken to indicate that the
space is filled to repletion. PAGE NUMBER
#+END_QUOTE
The use of the space break, which is meant to signify everything that
passes between Orlando and Shel and more (“it is filled to repletion”)
functions by signifying nothing. According to critics like Katheryn
N. Benzel, this moment creates literal space for the reader to fill in
with her own interpretation of the scene. The text paradoxes, for the
reader to resolve, such as “the most ordinary conversation is often
the most poetic, and the most poetic is precisely that which cannot be
written down.” As a formal device, the space break, in Smith’s words,
“bemoan[s] the inadequacy of language” (Smith 68).

Here the narrator is saying that language doesn't execute -- it does
not enact. It's pithyness, just four words which begins with the
conditional "since" and the enactive "do," evoke a kind of
programmatic logic. And this programmatic logic hits its own
limitation, it can mean, it can even produce meaning, but it cannot
do. Caughie sums up this intervention, which purposefully precludes a
straightforward understanding of sex and gender, where "sex cannot be
separated from text, the grammatical from the gendered" (Caughie
51). According to Caughie:
#+BEGIN_QUOTE
"Orlando works as a feminist text not because of what it says about
sexual identity but because of what it manages not to say; not because
of what it reveals about the relation between the sexes but because of
what it does to that relation; not because its protagonist is
androgynous but because its discourse is duplicitous" (Caughie 41).
#+END_QUOTE
