* ahem
** 3.27.2024
I'm choosing this method and I'm going to do it slowly. I am choosing
this method and I'm going to do it slowly. My legs are crossed and
they will cramp. I will not write otherwise. I will not write in the
old way, like someone is breathing down my neck. I will not write in
the old way. I will by force if necessary lower my heartrate knowing
that one cannot force relaxation. It is a method of letting go. The
trick then is to note, to notice what I need to let go.

** 5.9.2024
I am not even going to write today. But I'm back inside this document
and that is enough.

** 5.31.2024
And I'm thinking now and again perhaps I ought to write it as a
long-form book. Matt said that one of his regrets was not making
something of the work he did in the dissertation. That now he has that
problem.

I would like to write a book. But I don't know. I don't know. Not like
my dissertation. That feels stuffy. It wasn't fun. The ideas were fun,
but not the academic writing.

Maybe I will try re-writing it now, and see what happens. And I could
also try a draft of a coding tutorial, and see what happens. 
