* queer codes

** sketch
Queer approaches to the digital.

Queer practice as a way of working within constraints to open up
possibilites for alternativity, meaning, resistance.

There is a constraint, such as the reductive flattening of text in
text analysis. The hierarchical format of data structures. The opacity
of the interface, the display layer. (generalization) 

These constraints are embraced by heteronormative culture.

Queer practice would, by contrast, seek these out and re-deploy them
toward ends they were not built for.

*** Performativity / text analysis
*** Dis-identification / data formats
*** Surface aesthetics / interface effects
*** Seduction / artificial intelligence
ROGD - rapid onset gender dysphoria. 

The idea that there is something seductive, that there is something
irresistable about transition.

I need to get a copy of that book. Perhaps to get a copy of many books
with anti-trans ideology.

The seduction of ways of thinking. The lack of critical thinking. The
lack of individual thinking. The ways that we are tied to our desires,
to our preconceptions, confirmation bias. It's the same detail that
makes a chatbot so engaging, so intriguing, so

A chatbot will convince a user that it is intelligent, a user will
project their desire to find meaning onto the chatbot.

Just like that, a transphobic will project their desire onto others,
the fear of ROGD. The desire for transition becomes transformed into a
fear that transness is contagioius. I won't say whether it is or it's
not.

The danger of artificial intlligence is that it makes more apparent
our preconceptions, that we stick to. It is dangerous because it
amplifies, perpetuates our biases and preconceptions (in more than one
way).

By creating a human-like interface, we project our desires and our
fears onto it. 


** draft
