* iteration
Gender is a kind of performance--a series of acts that are repeated,
or /re-iterated/, in the words of Judith Butler, to satisfy social
expectations. The passive voice here is deliberate. The subject,
according to Butler's famous formulation, only comes to exist as a
product of their behavior.[fn:2]

Iteration is one way of understanding gender.[fn:1] Of understanding
gender by how it operates, through the mechanism of
iteration. Iteration is also a way of understanding the computational
manipulation of text, also known as text analysis. The concept known
as the "loop" in programming works by /iterating/ through a series of
items, like a list of words in a novel, and doing something to each
item. For example, we might count the number of times the word "woman"
appears in a text like Virginia Woolf's /Orlando/.[fn:3]

In what follows, I take this similarity between iteration in gender
theory and in programming logics to propose a text analysis method for
analyzing gender in novels.

I take Virginia Woolf's novel, /Orlando/, as my test case, showing how
an /iterative/ text analysis methodology disrupts gender as an innate
or biologically-determined quality.

My reading of Woolf's novel bears out what much of the scholarship on
this has already discovered.

But it does so through a novel method that surfaces new possibilities
for close reading. The methodological intervention here also pertains
to current practices in computational text analysis, a field that can
be referred to as Cultural Analytics. Mostly, my method resists the
more positivistic tendendies and idealistic attitudes toward
computational tools: this work is not interested in unearthing a new
understanding of literary history, isolating a needle in the haystack,
or exploring the permutation of an idea over time or text. Rather, it
is interested how the process of using computational tools can be in
itself generative. The results, and their purported accuracy, are
irrelevant for my purpose.[fn:4]

** TODO start with?

** bank
Iteration, Butler explains, is also a way of /undoing/ gender. It does
so by upending its expectation. By acting in a way that is unexpected,
that goes against the dictates of binary gender systems.

* form

* stack

* intelligence

* Footnotes

[fn:4] I am combining Stephen Ramsay with a feminist critique. Maybe
something to articulate more fully in the body or here in the note. 

[fn:3] Put a description here of Orlando?

[fn:2] Gender performativity is “A process of reiteration by which
both ‘subjects’ and ‘acts’ come to appear at all” (Butler, Bodies
xviii).

[fn:1] Judith Butler, from /Bodies that Matter/: "Performativity is
thus not a singular 'act,' for it is always a reiteration of a norm or
set of norms, and to the extent that it acquires an act-like status in
the present, it conceals or dissimulates the conventions of which it
is a repetition" (12).  
