* what is graduate work?
** info
Panels where students showcase the work they did in the program and
see how their scholarship speaks to others in the department.
- Interested in work outside the traditional academic research paper.
- Interested in how methodologies of scholarship are evolving.

** outline
*** What is graduate work?
- the question of what is english department work today
  - the stakes are misinformation, lack of critical thinking
- my experience navigating a sense of unbelonging, which is dominated
  by feelings of fear. And of turning fear into something productive. 
  
*** sedgwick's provocation:
- sedgwick's question, what does knowledge do. 
  - from paranoid to reparative, from suspicion to imagination
- what does knowledge do?
- how can we draw sustenance from objects meant to oppress or
  subjugate us?

*** my attempt
- using AI to study transphobia in language
  - ROGD
  - fear of transness as contagious, and fear itself being
    contagious
- how fear of ROGD is embedded in language
  - engaging machine learning with trans studies
  - ml:
    - prediction -> appoximation
    - irony? generalization? passing? in language
  - trans studies:
    - vs queer studies
    - difference in affective modes


** sketch
*** april 5
I have some regrets about the way that I did my dissertation. I
foresaw the dissertation being an academic exercise and knew that I
was doing it as a kind of rite of passage. A way of writing, a
practice of weaving together an argument-- it was useful for that. I
did learn how to string many things together, to bring different
frames of thinking into conversation. To do research, to pullee out
pieces, ideas that strike me, to meditate on these with writing, and
string them together. To write!

I think there is something useful about this practice.

But there's a problem with the output: it's not accessible, except
only to a few.

*** april 13
Thank you for having me. I am honored to be here.

I'm going to talk about my experience of doing academic work outside
the traditional research paper. This is something I've been intending
to do as part of my work as a Digital Humanist (a term useful for
labelling, but still doesn't fully describe or encompass the kind of
intervention) Maybe fields--areas of reasearch--ought to be based on
the kind of intervention that you're making.

So I'm going to speak about my experience at the intersection of
language and computation--which is how I describe my positioning
within my interests.

I've always felt outside of traditional English departments, like I
fundamentally didn't belong, despite my primary interest being in
language. I felt more like an outsider so when I started doing
"digital humanities" work.

Traditional English departments - the study of English Language and
Literature -- the study of english letters -- a study of history,
culture, form. But the idea here is that language, and it's ltierary
instances, are the primary object. And to that object, we've appended
multiple assumptions, attributes, like prestige determines quality,
for example. The imbrication of language and nation. Prestige
determines inclusion. This is not new. It's been already argued in
cultural critiques, in the canon wars, I'm not saying anything new. We
know that the discipline (and what of this word, discipline, as a way
of cordoning knowledge?) of English--what we call English--is
structural to reinforce hegemonic ideas about language, prestige--the
imbrications of language and nation--the prioritization of certain
types of writing, from writers in a dominant cultural position. It
emerges in the ways that we organize our study. I'm sure many of you
are already thinking and talking about this. Periodization. The
implication that intellectual interest is organized by the same
motivations / logics as national history, and reinforces the
objectivity of that organization. Remember applying here, how you
chose your specialization from a dropdown?

So what I have been saying isn't new: but what I'm going to say is to
make a proposal for one way of rethinking the work we do in English,
the way that we organize and conceptualize that work.

I am going to start with a question, posed by Eve Sedgwick, about
criticism, and what it /does/.

#+begin_quote
"Moving from the rather fixed question Is a particular piece of
knowlege true, and how can we know? to the further questions: what
does knowledge /do/--the pursuit of it, the having and exposing of
it" (124, /Touching Feeling/)
#+end_quote

Exposure by itself doesn't motivate; because it plays on suspicions.
- The "paranoid trust in exposure seemingly depends... on an infinite
  reservoir of naivete" (141). We assume exposure will "surprise,
  disturb, nevermind motivate" (141).

what does motivate? what does move?
- pleasure
  - Sedgwick explains that "reparative motives" are dismissed because
    they are "about pleasure ('merely aesthetic') and amelioriative
    ('merely reformist')" (144).
- imagination
  - Sedgwick offers instead:
    - "imaginative close reading" - "the devalued and near obsolescent
      critical skill" (/Touching Feeling/ 145).
    - "local theories and nonce taxonomies" (/Touching Feeling/ 145).

A reparative position for reading is
- open to being surprised (whereas paranoia expects to be surprised)
- guided by hope: if we can imagine a different future, we can imagine
  a different past.

#+begin_quote
Hope, often a fracturing, even a traumatic thing to experience, is
among the energies by which the reparatively positioned reader tries
to organize the fragments and part-objects she encounters or
creates. Because the reader has room to realize that the future may be
different from the present, it is also possible for her to entertain
such profoundly painful, profoundly relieving, ethically crucial
possibilities that the past, in turn, could have happened differently
from the way it actually did. (/Touching Feeling/ 146). 
#+end_quote

"Whatever else we know, we know that there isn't time to bullshit"
(149). 

Reparative reading enables us to learn "the ways selves and
communities succeed in extracting sustenance from the objects of a
culture--even of a culture whose avowed desire has often been not to
sustain them" (/Touching Feeling/ 151).

*** april 15 
This notion of close reading. Is this what I want to talk about in my
book?

Reading over my old papers. I don't want to do this kind of work
anymore. I don't want to read piles and piles of criticism with a
larger purpose of making sure I have the authority to speak -- but
rather to read for learning -- how others handle texts, how other are
thinking through their readings -- but from a position of
inferiority. Because no matter what, how much you read and how well
you write, it's never going to be good enough. Now I read those papers
and I think -- this is much better than I thought it was back then. I
remember feeling that it was a big work, a big project. And I remember
the sense of accomplishment at the end, after I'd submitted the
papers. The joy of putting the ideas together throughout the process
too.

But underneath all of that, there was this sense, this dread, this
conviciton that my work wouldn't be good enough. Which is why perhaps
it's taken me a long time to finally reject the academic written
form. I've finally explicitly rejected it. I always knew it was
stifling. Even as I was convinced I'd never be good enough.

I never believed the praise I got from my teachers, never believed
it. Now I believe it.

But that's not what I want to write about. I want to write about close
reading. It's about what Sedgwick says, what does knowledge
/do/. Could this be a way of organizing a discipline? a study of
English? Not what is the truth, what is the content. But maybe. What
kind of action does this study, this criticism, this reading motivate?
What does this kind of reading, this kind of cirtique, actually do in
the physical world?

Maybe I could give an example. My take on this is quite literal. As I
work with digital tools that actually do things, perform computations
upon language. I do a lot of coding that makes transformations of
literary text, like in text analysis, for example, or in marking up
textual changes (like changes in a manuscript) so they can be
represented in digital formats.

My work uses the nuance and complexity of liteary language to test
out the constraints, the limitations, of digital tools. Right now, I'm
working on, perhaps unsurprisingly, large language models.

I'm interested in how the generative capacities of these models, what
some have refered to as "creativity" but what is really just
statistical prediction, can teach us about the assumptions embedded in
language, particularly discriminatory views.

I'm looking at a body of legislative text that limits the rights of
transgender people across the united states. I'm interested in how
these bills are conceptualizing gender. 

*** april 17
I am going to discuss mqy current work, and how it tries to enact what
Sedgwick describes: a kind of imaginative close reading, /which
extracts sustenance from cultural objects not meant to sustain us/.

I'm going to see what we can gain from a technological process (in
this case, having to do with AI) that has the effect of perpetuating
discriminatory and biased views. I'm going to see what we can gain
from studying these kind of constraining systems, which is more than
just an unveiling (as Sedgwick often describes it) of injustice or
oppression.

To start that discussion of movement, of how knowledge work might
/create movement/, move others to action, I'm going to study an
example from our current political moment, just one of the many
authoritarian trends sweeping this country, which is the anti-trans
movement. In particular, I am studying the anti-trans legislation
that's being debated and passed all over the country.

From this legislation, I'm interested in exploring how the rhetoric
reinforces one of the most galvanizing aspects of the movement, a
particular flavor of transphobia: which is the fear that gender
dysphoria can spread from one person to another like a
contagion. Anti-trans folks call this "Rapid Onset Gender Dysphoria,"
or ROGD.

*** april 18
Anti-trans attitudes:

Rapid onset gender dysphoria: this idea that transness can spread from
one person to another, like a contagion. Cassius Adair describes this
kind of threat as a fear of seduction.

This threat is a not only a fear, but a motivating fear. A fear of
seduction. A fear of being moved to action, to transition.

I'm interested in using LLMs to study this fear of seduction. 
- LLMs are really good at generalizing, at making predictions.
  - what is machine learning? Logistic regression: They get enough
    examples of x and y, so they can map the relationship between x
    and y. There's a formula that maps it. Eventually, with enough
    examples, they can get any x and be able to map it pretty well to
    a y.
  - in this mapping, words, language, is given a numerical
    representation, what's technically called a word vector. This
    enables the computer to make mathematical calculations with the
    word, to make predictions.

In a model, words are an approximation. Language is an approximation.

I'm wondering how this approximation in language might allow us to
study more muted, subtle aspects of tone and meaning in language,
specifically of irony. Trans Studies has theorized irony as an
affective mode that distinguishes trans from queer: while queer wants
to rebel, push and cross boundaries, trans, in the words of Andrea
Long Chu, "just wants to pass" (check quote).

I'm interested in exploring how the fear/seduction of ROGD is embedded
in irony.

Here are some examples of irony from a book, which has since been
discredited (check status of this!) that helped to popularize the term
ROGD.

/examples of irony from 'irreversable damage'/

Taking this lens to read the results of the gender generator.

*** Trans Studies notes

**** Adair, Cassius, and Aren Aizura. “‘The Transgender Craze Seducing Our [Sons]’; or, All the Trans Guys Are Just Dating Each Other.” TSQ: Transgender Studies Quarterly, vol. 9, no. 1, Feb. 2022, pp. 44–64. Silverchair, https://doi.org/10.1215/23289252-9475509.

Questions the negative assumptions around the idea of transness being
contagious. What's so bad about it spreading?

Desire as a way of "contagious gendering," which "cis people do it all
the time".

"we see this t4t Daddy/boy as a space of play in which trans masculine
people can re-operationalize gendering and sexualization practices"


**** TODO cardenas, micha, on transness being viral (Adair).

**** Aizura, Aren Z., et al. “Thinking with Trans Now.” Social Text, vol. 38, no. 4 (145), Dec. 2020, pp. 125–47. Silverchair, https://doi.org/10.1215/01642472-8680478.

Marquis Bey: “Where queer theory advanced a sense of antinormativity
as the golden child of its theorization, as it were, trans studies
might (and I mean might) be said to advance a nonnormativity, the
distinction of which from anti-normativity is one in which the
anti-indexes a militant rejection or reactive opposition, whereas the
non-references, for me, a subversion, a decline to state that refuses
the very logics that structure the ability to say yes or no. Trans
studies offers me that, the tinkering and refusal that cares less
about opposing the hegemonic on its own terms and much more about
subverting the hegemonic by way of living life on another terrain."

Eliza Steinbock: “trans analytics have (historically, though not
universally) a different set of primary affects than queer
theory. Both typically take pain as a reference point, but then their
affective interest zags. Queer relishes the joy of subversion. Trans
trades in quotidian boredom. Queer has a celebratory tone. Trans
speaks in sober detail. Perhaps the style of trans studies has been
for the most part realist, but this should not be mistaken for base
materialism. Even speculative thinking requires enough detail to
launch into new realms.”

**** Chu, Andrea Long. “The Right to Change Sex.” Intelligencer, 11 Mar. 2024, https://nymag.com/intelligencer/article/trans-rights-biological-sex-gender-judith-butler.html.

“we have largely failed to form a coherent moral account of *why*
someone’s gender identity should justify the actual biological
interventions that make up gender-affirming care. If gender really
*is* an all-encompassing structure of social norms that produces the
illusion of sex, critics ask, why would the affirmation of someone’s
gender identity entail a change to their biology?”

“This is why the anti-trans movement is so desperate: It is afraid of
what sex might *become.”*

“I am not terribly bothered by saying that the division of sex
determines gender norms, so long as we remember that it never remotely
*finishes* determining them.”

“I am speaking here of a universal birthright: the freedom of
sex. This freedom consists of two principal rights: the right to
change one’s biological sex without appealing to gender and the right
to assume a gender that is not determined by one’s sexual biology.”

“By asserting the freedom of sex, we may stop relying on the
increasingly metaphysical concept of gender identity to justify
sex-changing care, as if such care were only permissible when one’s
biological sex does not match the serial number engraved on one’s
soul… In general, we must rid ourselves of the idea that any necessary
relationship exists between sex and gender; this prepares us to claim
that the freedom to bring sex and gender into whatever relation one
chooses is a basic human right.”

“They do not owe us an explanation. They are busy taking charge of
their own creation. They may not change the world, but they will
certainly change *themselves.”*


** draft
*** thank you
Imposters and Transphobes: The Function of Fear in Grad School

https://bit.ly/gc-english-2024

 Thank you for having me here today. I am honored to have been asked
to come and share my perspective on theme of graduate work, and also
on the question of how our work as students in English might speak to
each other.

 I think this question is a crucial one at this moment in time, when
the public discourse seems to be beyond the reach of (or even desire
for) deep, critical thinking. Right now, we're seeing incredible
amounts of mis-information about what’s happening on college campuses
across the country, and we’re witnessing a kind of fascism that twists
the definitions of tolerance and free expression to serve the
interests of imperialist violence.

 I think students of English have unique tools for thinking through
contemporary issues like mis-information and propaganda.

For this talk, I’m going to organize my comments around the theme of
fear. I’m going to think through the emotion of fear, which is
traditionally seen as a negative emotion, to see how it can become a
productive force that guides reading practices.

I'm going to begin by sharing some of my experience with fear, from
the perspective of a student doing what is considered to be
“non-traditional” work in English departments. Then I’m going to talk
about critical methods that transform negative feelings like fear into
something that is generative and productive. Finally, I’m going to
close by talking about my most recent scholarship, which considers
another kind of fear, that of transphobia, that is currently sweeping
this country in the form of an anti-trans movement.

*** fear

 I'll start with a kind of fear that many of many of you can probably
relate to—that is, impostor syndrome. In my time as a student here, I
felt a strange contradiction—that I didn't really belong in an English
department, but also, that the English department is the only place
where I can do my kind of work. That's because my dissertation is not
really about literature, it’s about software, specifically, software
that handles and transforms language data. My main research question
is how digital tools engage with the semantic and figurative qualities
of language, in how these tools reduce the complexities, ambiguities,
and nuances of language forms into computable text. My goal was to
examine the mechanism of digital tools, to find where they make this
reduction, and then to find ways of re-working the tools to capture
some of the expressivity of language that has been lost. To study this
effect, I used queer literature, a body of literature that is rich in
narrative and figurative forms, as a test case. I experimented with
various digital tools, like text analysis for example, exploring how
these tools manipulate and transform literary language into data.

 In addition to my written dissertation, I ended up coding software
applications, using programming skills that I taught myself
deliberately as part of my graduate training. For my work on text
analysis, for example, I used the Python programming language to
create a simple text analysis application that analyses gender terms
in novels, like Virginia Woolf's Orlando.

[SIMILARITY FOR WOMAN]

 Here's a screenshot of one component of that text analysis
application. It shows a list of words that are computationally
"similar" to the word "woman," in the novel Orlando. The application
determines word similarity through context: it examines a target word,
like “woman,” and the words that surround “woman,” what’s called a
context window, and then it compares those contextual words to other
words and their contexts throughout the novel. It works like almost
every other text analysis task: by counting words and compiling
massive lists of word counts. From these word counts, it then
determines words that tend to have similar contexts. Here, the words
“flight” and “abase” have similar contexts to the word “woman,” and
those words appear next to their probabilities, representing how
closely they relate to “woman”.

 Besides just showing word similarities, my text analysis application
also juxtaposes this so-called "distant reading" view of the words
with "close reading" views of each word in context. The idea is that a
reader might flip between these two views of text, close and distant,
as they explore words in the novel. My goal with the project was to
facilitate a new reading practice where distant reading might seep
into and inform close-reading analysis.

 [SLIDE CUNY ACADEMIC WORKS & GITHUB]

 While my written dissertation is available on CUNY Academic Works, my
coding work is hosted on a website called Github, where a lot of
software (especially DH projects!) is shared and published in a format
that’s open and collaborative. You can see on the right my homepage on
Github, which features my projects or “repositories” that are digital
components to my dissertation (the project title is the text in blue,
with the description right below it).

 I know this kind work might seem impressive now, after I’ve completed
it, but for many years, I really struggled to share it with folks in
English. When I did share it, the most common responses were blank
facial expressions, usually accompanied by the phrase, “Oh, that’s
really interesting. But I don’t know anything about that.” This was
also the response I got, a couple of times, when I asked professors to
be on my committee. I don’t blame them (especially because technology
has a tendency to make people feel flustered or frustrated), but it
was really discouraging, especially early on in the project when I
didn’t have a good sense of where I was going. And I know this is
probably a relatable feeling for many grad students, regardless of the
topic of their research.

 For me, the impostor syndrome manifested most strongly in one
particular form: as an intense fear of public speaking. It began my
first semester of graduate school, when, in the middle of speaking to
my seminar class, my mind went completely blank. I don't know exactly
what caused it, but I know it has something to do with the intensity
of my passion about what I was saying. Something about that intensity
threw me off. For many years afterward, I was afraid of it happening
again, so I avoided going to conferences and from speaking too much in
my seminars. The times that I did speak, I would write down
everything, and I mean everything, even if it was just a two-sentence
comment, that I planned to say before I opened my mouth. Sometimes, I
would also shake while I spoke, in a way that recalls how Helene
Cixous describes the shaking woman in her beautiful essay, “The Laugh
of the Medusa.”

 [CIXOUS QUOTE]

#+begin_quote
Listen to a woman speak at a public gathering (if she hasn’t
painfully lost her wind). She doesn’t ‘speak,’ she throws her
trembling body forward; she lets go of herself, she flies; all of her
passes into her voice, and it’s with her body that she vitally
supports the ‘logic’ of her speech. ("Laugh of the Medusa")
#+end_quote
In the essay, Cixous makes the vital point that expression (both
written and spoken) is an embodied activity—this is what the shaking
signifies precisely. She explains that women can either choose to stay
trapped in their own bodies by a language that does not allow them to
express themselves, or they can use the body as a way to
communicate. (and if you haven’t read the essay, I highly recommend
it)

*** what does knowing do?

 My experience with public speaking, unfortunately, was not as
glorious as Cixous’s rendering of the shaking woman. But it does make
me think about fear, and to wonder how fear might be re-deployed as a
tool for drawing something productive from the repressive structures
that create it in the first place. In re-thinking the function of
fear, I’m inspired by the scholarship of Eve Kosofsky Sedgwick, who as
you may know, is a major figure in Queer Studies, and who also taught
in this department until 2009, when she passed.

   [SEDGWICK’S BOOKS]

Here you can see some of her books, which are among the most famous
books in Queer Studies, and helped to shape the field, like Between
Men, the Epistemology of the Closet, and Touching Feeling.
 
   [SLIDE 5 – SEDGWICK IN ENGLISH LOUNGE]

And here, you’ll see an image of Sedgwick with Robert Reid Pharr, who
also taught in this department, and Samuel Delany, the Science Fiction
writer. The background of the photo should be familiar to all of you.

I’m inspired by the way that Segdwick framed her relationship to
reading practices over her career. Throughout her work, she shifts
from a kind of reading that she calls “paranoid reading” into a new
mode called “reparative reading.” By paranoid reading, Sedgwick means
a critical practice that seek to unveil truth by searching for hidden
meaning in text. In her famous essay on this topic, Sedgwick frames
the difference between paranoid and reparative reading with a question
about truth, and the role of unveiling or exposing truth in critical
analysis:

#+begin_quote
"Moving from the rather fixed question Is a particular piece of
knowledge true, and how can we know? to the further questions: what
does knowledge do–the pursuit of it, the having and exposing of it"
(124, Touching Feeling) 
(123).
#+end_quote

[C1] In this essay, Sedgwick alleges that truth, on its own, does not
motivate action. Merely knowing that something is true, revealing the
presence of systematic oppression, injustice, discrimination, for
example (and here, Sedgwick is theorizing within the context of the
AIDs crisis), is not enough to “enjoin that person to any specific
train of epistemological or narrative consequences”[fn:1]


Truth does not motivate action, because, Sedgwick explains, action is
not the end goal of paranoia. Paranoia is by nature suspicious: it
suspects that there must be something hiding under the
surface. Because of this suspicion, paranoia can never be surprised,
only satisfied, and only temporarily. So when it finally "discovers"
the secret, that discovery only affirms what it has known all
along. One is never “moved,” to to speak.

Paranoid reading practices abound in literary criticism, especially,
as Sedgwick admits, in her own criticism. In her earlier books, in The
Epistemology of the Closet, published in 1990 (and pictured here as
the middle book), for example, she uses paranoid methods to expose
what she calls the unstable binaries between heterosexual and
homosexual categories. Through close-readings of fiction, she exposes
the inherent instability of these binaries — where one term is not
symmetrical or simply subordinated to another, but rather, depends the
other for its meaning through “simultaneous subsumption and exclusion”
(10). Sedgwick explains that such binaries are “sites that are
peculiarly densely charged with lasting potentials for powerful
manipulation” (10).

In her later work, such as that in Touching Feeling, which is the book
on the right, Sedgwick explores other critical reading methods that go
beyond what she calls “the logic of repression” (a logic which she
traces to Foucault) that guides much of paranoid reading, including
her own earlier work. She proposes a mode of “reparative reading,”
which focuses on connection rather than exposure. Reparative reading
“surrender[s] the knowing, anxious paranoid determination that no
horror, however apparently unthinkable, shall ever come to the reader
as new” (146). In a reparative reading practice, a reader allows
herself to be taken by surprise.

She demonstrates reparative reading by analyzing the affect of
shame. What if, Sedgwick asks, we take something that is typically
seen as a negative, structuring force in queer identity, and examine
how it unlocks creativity and productivity? Sedgwick describes shame
as a contagious affect, which may be read as a mobilizing and creative
force in text: she explains that,

   [SLIDE 6: SHAME QUOTES]
   
#+begin_quote
   “Shame—living, as it does, on and in the muscles and capillaries of
   the face—seems to be uniquely contagious from one person to
   another." (63 Touching Feeling).
   
She also describes shame as:

   “not a discrete intrapsychic structure, but a kind of free radical
that (in different people and different cultures) attaches to and
permanently intensifies or alters the meaning of—of almost anything: a
zone of the body, a sensory system, a prohibited or indeed a permitted
behavior, another affect such as anger or arousal, a named identity, a
script for interpreting other people’s behavior toward oneself” (62)
#+end_quote

She demonstrates this reading practice by analyzing metaphors that are
made possible through shame. For example, in the fiction of Henry
James, she connects moments of "blushing" and "flushing" to a fantasy
of the skin being entered. Shame, in this reading, is a way of pulling
other affects and images into relation. This is opposed to paranoid
reading, which might plumb shame for what it reveals about a hidden or
repressed sexuality. She explains that, “When we tune into James’s
language on these frequencies, it is not as superior, privileged
eavesdroppers on a sexual narrative hidden from himself; rather, it is
as an audience offered the privilege of sharing his exhibitionistic
enjoyment and performance of a sexuality organized around shame” (54).

*** my work
I'm interested in this move that Sedgwick makes, of taking what is
typically seen as a negative, repressive affect, like shame, and
seeing how it opens up possibilities for reading new connections in
text.

In my current work, I am exploring how I might enact something similar
with the feeling of fear. In the work I've been doing since the
dissertation, I have been interested in a particular kind of fear, of
transphobia, and how it emerges in our current political moment.

[ROGD PAPER]

For example, one of the things I'm studying is the (now disproved)
clinical phenomenon of so-called "Rapid Onset Gender Dysphoria"
(ROGD), which stipulates that trans-ness can be contagious among
adolescents. The phrase was coined by Dr. Lisa Littman in her study of
parents of transgender youth, published in 2018. In her study, Littman
interviews over 250 parents of transgender children and concludes that
what she calls "peer contagion" of gender dysphoria may be a
contributing factor for adolescents who decide to transition. Almost
immediately following its publication, Littman's study was criticized,
including by the publisher, and its methodology and findings have been
disavowed by every major medical association since then.

Although ROGD is not recognized as a valid diagnosis, it has been used
and is still used as fodder for anti-trans propaganda and
discrimination. It has made its way into the public lexicon, appearing
in books, shows, and most importantly for my project, legislative
bills that are being written, debated, and passed across the United
States. For those who are unfamiliar, this legislation limits trans
peoples' access to basic healthcare, public facilities, legal
recognition, and more.

[ANTI-TRANS LEGISLATION MAP]

Here, you can see a map of where these bills are most concentrated
across the country, and a chart of how many bills are proposed and
passed over the last four years. Notice that this year, though we are
hardly in the fifth month, we’ve almost caught up to the total bills
for last year.

I’m interested in this threat of gender transgression, and
specifically, in the language outlawing gender transgression, of
transitioning from one gender to another, or of opting out of binary
systems of gender. Why is this particular kind of transgression so
controversial among a large part of our population? Why is the fear of
this transgression itself so contagious? I am interested here in two
kinds of fear: in the fear of transness being contagious (in the false
phenomenon of ROGD), and in how this fear of transness itself is
contagious, in the form of transphobia.

To study these phenomena of fear, I apply the same analytical spirit
from my dissertation, where I use close-reading strategies to analyze
aspects of digital tools, to look into their inner mechanisms, toward
tracing their technological processes. For this project, I’ve decided
to study AI tools, known technically as a "large language models" or
LLMs, which include chatbots like ChatGPT. My focus on this project,
for the past several months, has been to understand how these models
are created, how they are "trained," so to speak, so I can trace how
they perpetuate biases, like transphobia, from their training data
into the text that they generate.

I'm going to give a quick overview of how this training process works,
just so we are all on the same page. The training process begins with
the model taking and processing massive amounts of text from the
internet. From processing this training data, word by word, it starts
to compile numerical probabilities for which words tend to surround
other words. It represents these probabilities with numbers, with
actually a very large list of numbers. Here’s an example of what one
of these lists might look like, for the word “protest” (and this is
from a model taken from twitter data)

[PROTEST SLIDE]

Like the first slide that I showed you from the text analysis
application, probability here is important. Words are defined by their
relationship to other words in the database. Here, we see words that
are most closely associated to “protest” in the twitter
database.[fn:2]

You can think of these numbers, or scores, functioning like
definitions, which represent the word's meaning for the computer. To
us, these scores look just like a long list of numbers, but to a
computer, the scores represent a given word's meaning through its
relationship to every other word in the entire dataset of words. A
language model will then generate content by doing math with the
scores attached to each word in its database. And the math that they
use to make generate text is actually math that many of us have heard
of before in math class: things like matrix multiplication and cosine
similarity.

Here is a famous formula that introduced this technology of scoring
words, which is technically called “word vectors” to the world.

[KING - MAN + WOMAN = QUEEN]

The idea is that by taking all the numbers that represent king, then
subtracting the ones that represent man, and adding the ones that
represent woman, you will get queen. I won't get into the sexism of
this formula (what exactly is being subtracted, for example?), but I
want to point out that it has great currency as it is THE formula that
introduced this technology to the world.

[WORD VEC PAPER]

 And here is an image of the original paper itself, “Efficient
Estimation of Word Representations in Vector Space,” which was
published by Google researchers in 2013. Just for some historical
context, in the history of Machine Learning: this paper contributed to
the development of a model architecture, called the “transformer
architecture” in 2017, also by a research team at Google. And that
development, which allowed AI models to take more complex levels of
word contexts into the text generation process, is what led to the
explosion in AI models that we are currently seeing today.
 
 So, to sum up: these tools generalize how language works by studying
examples of language forms. Given how much the training data, and the
specific configurations of words in the training data, affect the
model's text output, I am very interested in using AI tools to study
anti-trans bias, and particularly, the fear of contagion, of ROGD.

 Right now, I am currently the middle of a data gathering and model
training process, to study how models perpetuate this fear from their
training data onto their outputs. I am compiling a dataset of gender
and related terms from these bills. I’m interested specifically in how
these bills, which limit trans peoples’ rights, are framing what it
means to be trans and to receive gender affirming healthcare.

[SLIDES OF DEFS FROM BILLS]

 Here’s some examples of the language that I extracted so far from the
legislation. The dataset is focused on definitions of gender identity
and related terms, like “biological sex” and “gender transition
procedure,” which are underlined here. To get these definitions, I had
to scrape the bill text from congress.gov’s servers. And when I had
the bill text, I wrote a pattern matcher to extract textual patterns
that resemble definitions. (If you’re interested in this process, all
my code is on github).
 
[SOME WORDS IN BLUE]

 Here, the text in blue indicates words and phrases that seem to
suggest underlying assumptions about binary gender and gender
transgression. Right now, I am interested how these assumptions are
being constructed in subtle ways, in seemingly harmless
formulations. For example, I am interested in the word “regardless,”
which appears in many of definitions, and collapses an essentialized
notion of binary gender with biological sex, and contrasts that with
gender as expression.
 
 As I continue to build and clean my dataset (which is a long,
technical process that involves data gathering, processing, and
cleaning), I've also been dabbling with using them to train AI models.

 Leaving aside all the hype about AI, and whether or not it is
“intelligent,” or moving toward what the industry calls “general
intelligence,”[fn:3] AI tools like large language models are really good
at one thing: at making predictions. At generating content that is
plausible. This is a fascinating phenomenon, because it makes them
very good at guessing or improvising, but not at all good at being
creative, at innovating. A language model can only generate what it
has already seen before. Even a phenomenon like “hallucination,” that
a language model spews text that has no bearing in reality, is based
on the tendency of models to repeat what they've already seen. They
hallucinate not because they are creative or random, but because they
are designed from statistical processes to generate what is most
plausible rather than accurate.

This tendency toward plausibility creates an interesting perspective
for me to think through how Trans Studies scholars have characterized
trans affects. Typically, these scholars describe trans affective
modes by distinguishing them from "queer" modes. In a roundtable
called "Thinking with Trans Now" published in Social Text, trans
studies scholar Eliza Steinbock explains,

#+begin_quote “trans analytics have (historically, though not
universally) a different set of primary affects than queer
theory. Both typically take pain as a reference point, but then their
affective interest zags. Queer relishes the joy of subversion. Trans
trades in quotidian boredom. Queer has a celebratory tone. Trans
speaks in sober detail. Perhaps the style of trans studies has been
for the most part realist, but this should not be mistaken for base
materialism. Even speculative thinking requires enough detail to
launch into new realms.”
#+end_quote

Other trans scholars like Marquis Bey and Andrea Long Chu have made
similar points; with Bey making the point that queer's intervention
can be described as "anti" or militant, while trans is "non" or based
in refusal ("Thinking with Trans Now"); and Chu has remarked that
trans studies, rather than resisting norms, "requires that we
understand–as we never have before–what it means to be attached to a
norm, by desire, by habit, by survival" ("After Trans Studies" 108).

 This makes me wonder, could AI-generated text, as a kind of
approximation, a normalization, of its training data, be used to study
the attachments to norms and the quotidian that characterizes trans
affective modes? Could the same processes also be used to study the
attachment to norms that characterizes the opposite movement, in
transphobia, like perspectives driven by the fear of ROGD? What might
outputs from AI text generation suggest about the allure, the threat,
the “seduction,” as Trans Studies scholar Cassius Adair puts it, of
gender transgression?

While this project might sound very ambitious, I'll admit that, so
far, my results are not very encouraging. I need to continue to add
more training data and to tweak my model configuration, probably
numerous times, before I find something really interesting.

Nonetheless, here are some excerpts of my language generated by my
model, which I trained by feeding it some examples of anti-trans
legislation that I have already prepared.

[SLIDE SHOWING THE GENERATED TEXT]

 Here, you can see the prompt text (so, text that I entered as a
prompt to the model, in italics) and the AI model’s responses (where
it provides a continuation of my prompt) in normal, unitalicized text.

 As you can see from skimming the results, the models are showcasing
the tendency toward plausibility, specifically in the tendency to
repeat itself, which is a fascinating concept in machine learning.

 I will close now by coming back to this idea of fear, and
particularly the fear of contagion, which drives some strains of
transphobia. Cassius Adair offers a useful perspective for thinking
through the fear of contagion. In his study of trans erotics, and
specifically “trans for trans” or "t4t erotics," Adair asks, "Why
shouldn't transness be transmissible or contagious? Why can't the
erotic be a site of producing trans identity or practices?" He points
out that, after all, cis people do it all the time: they use sexuality
and sexual encounters as sites of identity formation.

 Here, I see Adair doing for contagion what Sedgwick does for shame:
turning something that is traditionally seen as a negative into
something that may be generative and productive.[fn:4]
 
 It is the same kind of thing I hope to accomplish with this project,
and something that I think is possible by using the tools that we gain
in English departments—that is—by close reading, or what Sedgwick
calls, "imaginative close reading."

 This is a kind of reading that allows one to take what has been a
tool of oppression and turn it into a creative resource. Sedgwick
explains that this kind of reading exposes “the ways selves and
communities succeed in extracting sustenance from the objects of a
culture—even of a culture whose avowed desire has often been not to
sustain them” (Touching Feeling 151).

 Thank you.

* Footnotes
[fn:4] The question is — how to take sustenance from the idea of
transness as contagious. How to celebrate this—this is a controversial
idea! Needs more thought.

[fn:3] There’s another dimension of argument we are entering here, and
probably need more signposting in previous sections (word vectors) to
keep the audience on the same thread: The function of word vectors is
to make generated text plausible. It’s a guess, an approximation,
based on mathematical processes that are “normalizing”

[fn:2] Probably can cut out. Instead, bring us back to the similarity
list for “woman” and build it from there.

[fn:1] This needs to be cut to some extent. The point is about
re-working negative affects into reparative modes, right? Thinking
about what knowledge does is relevant but not necessary.
