* Digital Methods and Textualitites
** Methods 
*** Moretti, Franco. *Graphs, Maps, Trees: Abstract Models for Literary History*. 2007. Print.
- Moretti supports a positivist agenda for literary criticism. He
  ascribes an objective status to visualizations, as if they aren’t
  based on subjective research (monographs!) and his own decision
  making. He also neglects to fully embrace his own readings as
  subjective, and calls them “explanations” rather than
  “interpretations”.
- Basically, Moretti minimizes his role as a critic, in service of a
  larger, collective project on doing literary history. But he doesn’t
  have to minimize the critic’s reading to feel like he’s part of a
  collective.

*** Drucker, Johanna. "Introduction," *SpecLab: Digital Aesthetics and Projects in Speculative Computing*. 2009. PDF.
- Drucker uses the computer for creative ends. Computation geared
  toward speculation rather than testing or confirmation.
- Doesn’t this line of argument perpetuate the idea that the computer
  is more objective than the human? That the computer ultimately
  remains a rational tool? Isn’t it just pointing the direction of
  interpretation at a new target, which is speculation, while still
  using the same gun? Is this right?
- How would speculation and potentiality play into a feminist
  project/reading?

*** Ramsay, Stephen. *Reading Machines: Toward an Algorithmic Criticism*. 2011. Print.
- Ramsay positions himself as a moderate, saying that computers are
  merely tools, part of a more expansive subjective process, of
  hermeneutics. His ideas here agree nicely with Drucker’s in Speclab.
- What’s particularly useful about Ramsay is his opposing of
  humanistic endeavor against scientific inquiry. This specifies how
  observation is a phenomenal, subjective experience, and is
  antithetical to the motives and processes of scientific inquiry, the
  scientific method. Ramsay allows us to understand how empirics(?)
  can be subsumed within a humanistic frame, which does not attempt to
  ascertain “truth” but only “potentiality”.
- Like Drucker, isn't Ramsay speaks as if the computer is this
  uber-objective tool? Like code/software has no biases or
  idiosyncrasies? What about examining the way that these processes
  encode subjectivity?

*** Drucker, Johanna. "Humanities Approaches to Graphical Display." *DHQ: Digital Humanities Quarterly*. 2011. Web.
- Drucker argues that data visualization tools and techniques
  naturalize and flatten things that are actually complex and
  ambiguous. She proposes that we switch “data” (given) for “capta”
  (taken), to emphasize how all information has been constructed,
  pre-cooked (never raw). She proposes that we skew and blur and
  disrupt the neatness of our graphs and charts.
- But isn’t this just turning criticism into poetry? Don’t we need
  something stronger, clearer,more delineated?
- What is the role is clarity and “realist” or “natural” constructions
  of knowledge?

*** Felski, Rita. *The Limits of Critique.* 2015. PDF.
- Felski usefully talks about reading as an affective
  orientation. It’s not about the way that we read, but about the way
  that we position ourselves and our desires around texts. She warns
  that suspicious attitudes toward texts foreclose the possibility for
  new readings, new thoughts.

*** Piper, Andrew. *Enumerations: Data and Literary Study*, 2018. Print.
- This shows how distant and close reading can be used together ---
  Distant reading provides context, or framework, for close reading;
  in which number becomes a lens, a frame of the quantitative, to
  approach closer readings and even inform further model building.
- Though computation facilitates literary analysis, a number of flawed
  premises about distance, bigness, or objectivity (which lack a
  science of generalization), have clouded the ways we approach
  computation (9).
    - “Entanglement is a far more appropriate way of thinking about
      literary modeling than the disembodied eye in the sky of the
      lone, distant reader” (19).
        - By incorporating models/graphs/visualizations, “We are no
          longer using our own judgments as benchmarks... but
          explicitly constructing the context through which something
          is seen as significant (and the means through which
          significance is assessed).... It interweaves subjectivity
          with objects” (17).
- With Machine Learning, engages a speculative method: “We see how
  “feeling” is gradually redefined over time by the novel away from an
  emotional state to one of perceptual encounter. This sense of the
  contemporary novel’s investment in sensorial embodiment awaits
  fuller treatment” (117).

*** Underwood, Ted. *Distant Horizons*
Much of literary history is invisible to us due to our blindness to
large scales. Though it is no substitute for the sensitivity of close
reading, Distant reading allows us to see larger patterns across
centuries and periods.

- Uses "perspectival modeling," which is a way of testing computer
  models, or the results from computer modeling.
    - "a model---a relation between variables---instead of a single axis
      of measurement" (19).
    - A bag-of-words representation... We represent each character by the
      adjectives that modify them, the verbs they governm and so
      on---excluding only words that explicitly name a gendered role like
      /boyhood/ or /wife/. Then, we present characters, labeled with
      grammatical gender, to a learning algorithm. The algorithm will
      learn what it means to be 'masculine' or 'feminine' purely by
      observing what men and women actually do in stories. The model
      produced by the algorithm can make predictions about other
      characters, previously unseen" (115). 

- Quantitative methods are not anymore objective than close
reading. But they are not as "sensitive" or "exacting" as close
reading, and are mostly useful for long views. 
    - "If we look with fresh eyes at contemporary quantitative methods, we
      may notice that they are not distinguished by any aspiration to
      objectivity. Machine learning, in particular, is causing public
      scandal because it tends to be all too sensitive to subjective
      contexts" (xiv).
    - "machine learning tends to absorb assumptions latent in the evidence
      it is trained on. By training models on evidence selected by
      different people, we can crystallize different social perspectives
      and compare them rigorously to each other... which I call
      'perspectival modeling'" (xv).
    - "Critics who want to sensitively describe the merits of a single
      work usually have no need for statistics... Computational
      analysis of a text is more flexible than it used to be, but it
      is still quite crude compared to human reading; it helps mainly
      with questions where evidence is simple too big to fit in a
      single reader's memory" (xxi).
    - "The imprecision of the human world is part of the reason why
      numbers are so useful in social science: they allow researchers to
      describe continua instead of sorting everything into discrete
      categories" (20).

- Repeatedly stresses that the point of quantitative methods is to
  discover new scales of analysis, but he seems to be looking for an
  overarching theory that will encapsulate literary
  history. Quantitative methods seek to overcome a problem of
  attention, of memory, in order to gain a large view. Here, human
  memory is a hindrance, rather than a drive. The goal is rather to
  multiply alternative readings. 
    - Attention determines analysis, analysis determines knowledge,
      knowledge determines disciplines, periodization (8).
    - "The challenge is to find a perspective that makes the descriptions
      preferred by eighteenth-, nineteenth-, and twentieth-century
      scholars all congruent with each other" (32). 

- His examination reveals, as he projected, that initial assumptions
  will determine the the form of the result. In looking at the way gender
  is characterized, or rather how models characterize gender, in
  novels from the 18th century to today, he finds that results
  reproduce some of the structuring assumptions from the outset. If
  gender is binary, then the relation between male and female will be
  one of opposition. 
    - "explores the history of characterization, looking in particular at
      the way fictional characters are shaped by implicit assumptions
      about gender... how easy it would be to distinguish fictional women
      from men, using only the things they are represented as doing in the
      text. When first names and pronouns are set aside, can a model still
      predict a characters grammatical gender?"  (xvii). 
    - "while gender roles were becoming more flexible, the attention
      actually devoted to women was declining" (114).
    - His questions build in causality: "we can ask how strongly public
      signs of gender shaped characterization in general. Were fictive
      men quite different from fictive women, or were the differences
      between characters unrelated to conventional signs of gender?"
      (115). 
    - "one possible conclusion would be that the structural positions of
      masculine and feminine identity, vis-a-vis each other, have remained
      very stable---while the actual content of masculinity and femninity
      has been entirely mutable. It is also possible, of course, that this
      chapter has discovered stable 'structural positions' only because it
      explores gender, for the most part, as a binary opposition.... it
      would also be possible to represent those changes as the /blurring/
      of a boundary to produce a spectrum or as a /multiplication/ of
      gender identities that made the binary opposition between masculine
      and feminine increasingly irrelevant to characters' plural
      roles" (140).
          - --> the question then becomes, how can we do criticism
            that doesn't reproduce our own assumptions? The answer is
            that we cannot. But we can try to incorporate, as much as
            possible, alternative reading methods. This happens only
            through and play.

- Distant reading allows us to see that fiction is more 'embodied'
  than nonfiction: 
    - "the novel steadily specialized in something that biography (and
      other forms of nonfiction) could rarely provide: descriptions of
      bodies, physical actions, and immediate sensory perceptions in a
      precisely specified place and time" (26).
  
** Networks
*** Galloway, Alexander. *Protocol*, 2004. PDF.
- Codes that append all data…controlling power lies in the technical
  protocols that make network connections possible. “The acceptance of
  universal standardization in order to facilitate the freer and more
  democratic medium” (147).
- The flexibility promoted by a control society is actually used to
  exercise control, requiring autonomous submission. Resistance to
  this kind of control consists of finding loopholes or “exploits” in
  systems (what hackers do).
- DNS and TCP/IP engage a vertical (hierarchical) and horizontal
  (democratic) models of control, with the effect of submitting the
  “freedom” of movement in the network to the authorization of a
  controlling head. This paradox between freedom and control, between
  hierarchy and horizontalism, can perhaps help us to transcend our
  thinking of computers as disambiguation machines.
- A protocol is a wrapper---it does not engage in meaning/content, but
  in possibility, physics or logic. Thinking of protocols as tags that
  are appended, added on, not changing the data but wrapping it, with
  possibility. There is a speculative component here. This is about
  the EXPLOIT.
- “Protocol is a circuit, not a sentence” (52).
- Code is the only language that is executable. It acts out its
  inscriptions, that it applies to something… Code does what it says,
  it goes from declaration to movement. Code has a semantic meaning,
  but it also has an enactment of meaning. It moves.
    - “Code thus purports to be multidimensional. Code draws a line
      between what is material and what is active, in essence saying
      that writing (hardware) cannot do anything, but must be
      transformed into code (software) to be effective… The algorithm
      is prepared in advance, then later executed by the artist”
      (165).

*** Chun, Wendy, *Control and Freedom: Power and Paranoia in the Age of Fiber Optics,* 2006. Print.
- How hardware (as opposed to software) engages with the
  freedom/control paradox of internet networks.
- To Chun, the issue isn’t the control technologies that drive the
  internet, but in the way that the workings of the technology is
  obscured, the ways that protocol is hidden and amplified. We aren’t
  aware of the packets that pass through our computer, but they are
  there. “If you believe that your communications are private, it is
  because software corporations, as they relentlessly code and
  circulate you, tell you that you are behind, and not in front of,
  the window” (22)
- All computers engage in this give and take. That’s what make
  networks possible in the first place. Napster just made this
  fundamental truth evident.
- The internet’s potential is not in individual empowerment, but in
  universal exposure, in the way that it exposes us to new
  visibilities that we cannot control.
- What are the possibilities opened up by our vulnerabilities?

*** Bennett, Jane. *Vibrant Matter: A Political Ecology of Things*, 2010. PDF.
- Vitality means that things have their own forces, trajectories,
  tendencies.
Thinking of matter as an object or dead makes us destructive; we
assert our power/subjectivity over them rather than acknowledge a
mutual connection.  Objectifying something is harmful for us and for
them.
- Rather than be suspicious (hermeneutics of suspicion), which
  projects an agential/subjective presence, we ought to dwell in a
  hermeneutics of wonder, of knowing things through intellectual and
  aesthetic exercises, which motivate fascination (action?) rather
  than critique.
- Everything is really an assemblage. Your brain is not “you”, but a
  collection of processes that are engaging with a bunch of other
  processes to form “you”. This is the connection to the swarm. A
  bunch of things are vitalized, and therefore acting in tandem like a
  swarm.

*** Moten, Fred and Stefano Harney. *The Undercommons: Fugitive Planning & Black Study*, 2013. Epub.
- The university is dedicated to re-producing and perpetuating the
  oppressive and hierarchical orders of society. This cannot be
  overcome, so one ought to sneak into the university and steal what
  one can. You can be in but not of the university.
- How can one be inside of the system and yet resist the system? We
  can do it by forging connections that are outside of the established
  “connections”. In other words, by stealing, by feeling each other,
  by collecting debt, never paying it off, by collective study.
    - "The undercommons is a fugitive network where a commitment to
      abolition and collectivity prevails over a university culture
      bent on creating socially isolated individuals whose academic
      skepticism and claims of objectivity leave the world as it is
      intact.”
- We are broken, but cannot be repaired. All we can do is study,
  collect debt, and join in the shipped. Study is a mode of thinking
  with others, an assemblage. Debt is a state of being that we
  acknowledge but do not attempt to have repaired. We are always
  building debt, never paying it off. The shipped is where we all are,
  thrown in together, touching each other, feeling through each other,
  each other’s feels.

*** Tufekci, Zeynep. *Twitter and Tear Gas: the Power and Fragility of Networked Protest*, 2017. PDF.
- Analyzing modern protest and how they use networks to mobilize. She
  describes how the internet helped the Zapatista uprisings in Mexico,
  the necessity of remote Twitter users to organize medical supplies
  during Arab Spring, the refusal to use bullhorns in the Occupy
  Movement that started in New York.
- There is inherent capacity (practical capacity) and signal capacity
  (potential capacity), such as promises and threats. Occupy vs
  SOPA/PIPA.
- While adhocracy, facilitated by horizontalism, allows for movements
  to improvise to meet immediate needs, tactical freeze is a potential
  disruption, an inability to advocate for policies or demands, moves
  requiring consensus and organization that is antithetical to the
  horizontal and improvisational structure of adhocracy.
In such an environment, information and misinformation glut is a real
problem, as the important information gets diluted or obscured. Today,
gatekeeping is done by governments, algorithms, platforms.

*** Gaboury, Jacob. ["Becoming NULL: Queer Relations in the Excluded Middle."](https://www.tandfonline.com/doi/abs/10.1080/0740770X.2018.1473986) *Women & Performance: a Journal of Feminist Theory*. 28:2, 2018. pp. 143-158. Web.
- Facebook doesn’t care how you identify, but only that your
  identification is addressable by them. “The move by Facebook
  allowing for the selection of multiple genders “remain[s] deeply
  tied to a kind of binary logic, or at the very least a digital
  one. Put simply, while Facebook gave users more gender options with
  which to identify, they were still engaging in an act of
  identification... Here the user has simply been conscripted into
  enacting the labor of identification once reserved for sophisticated
  algorithms” (1).
- New systems enact compulsory identification, they do not care how
  you identify, they only care that you have an identification that is
  addressable by them. So, What are queer modes of being within
  technological systems, modes that refuse the gesture of capture and
  extraction?
- The NULL marker in SQL offers a way of becoming that enacts a queer
  logic that is explicitly situated within the logic of information
  systems but refuses this gesture of capture and extraction. A
  “refusal to cohere, to become legible.” “The use of NULL thus marks
  an indeterminate mode of being that is at once within and outside,
  part of and illegible to a discrete system of relations, a “middle”
  that explicitly marks an indeterminate, incalculable, unknown state
  of being” (11).

** Language
*** Barthes, Roland. *S/Z*, 1970. Print.
- Barthes creates a sort of encoding scheme (interpreting according to
  a series of codes, which create a constellation of meanings across a
  single text) for Sarrasine. This encoding scheme dramatically opens
  up meaning, exposes the writerly potential of the text.

*** Landow, George. *Hypertext 3.0: Critical Theory and New Media in an Era of Globalization*, 2006. Print.
- The hypertext format engages the postmodern
  (structuralist/post-structuralist and deconstructive) theories about
  the multiplicity and instability of meaning in texts, as well as new
  radical conceptions of authorship
- The hypertext is postmodern; hypertext destabilizes the apparently
  stable, it creates new centers, new tangents, new connections in
  between textual elements.

*** Tenen, Dennis. *Plain Text: the Poetics of Computation*, 2017. Epub.
- Points out that each digital text carries with it a layer of hidden
  information that determines the display and dissemination of the
  document. Argues that we need to examine this layer to see how they
  also determine the way we engage with and interpret the
  document. There are underlying structures of power in copyright,
  surveillance, sharing, and modifying text, which is visible only in
  plain text.
    - Such media turns us into consumers rather than producers of
      media. Text that is highly restricted in its encoding threatens
      our critical ability.
        - Tenen proposes a microanalysis, computational poetics, or an
          archaeology of platforms and infrastructures (behind surface
          content). He points out what elides our notice about these
          media---that signs are fractured from their inscription (we
          do not experience how the sign is processed by the
          computer); and that mediation between human and machine
          becomes less and less accessible (eventually, we will be
          able to navigate interfaces with our minds). We don’t engage
          directly with the textual conduit, so we need to perform a
          media archaeology in order to have access to these processes
          and be in charge of them.
- Shows one cynical consequence of Landow’s argument. Instead of
  opening up the meaning of the text, of its dynamicity inviting more
  interpretations, Tenen points out that dynamicity can actually
  impose restrictions on interpretation. The text on the screen
  actually hides the ways in which it is already determined.
- Another interesting complication with the question of affect. Here,
  Tenen points out how pleasure in reading can actually be a bad
  thing, can evacuate the critical processes of interpretation.  → on
  the one hand, we have the pleasure of intuitive interfaces and on
  the other, a short circuiting of critical ability. How does the
  collapsing/obscuring of mediation between us and our texts affect
  the way we read them?

*** Fisher, Caitlin. *These Waves of Girls*, 2001. Web.
- The profusion of hyperlinks frustrates the reader by offering too
  many narrative paths. The reader’s frustration in navigating through
  the hypertext relates to the work’s theme of sexual discovery. In
  following the narrator as she develops her sexuality, the reader
  experiences her own cycles of desire and frustration.
- The reader’s narrative path parallels the theme of sexual discovery.
Additionally, the reader’s narrative desire for closure is related to
her sexual desire for release. Narrative/sexual desire conflation.
    - The desire to write is the desire to fool you, seduce you.”
- The links are associative, they elaborate the linked terms by
  leading to a single lexia or to another narrative. They can
  illuminate, echo, or answer another link or lexia. Sometimes we end
  up in the middle of another narrative. Sometimes we circle back to
  the same lexia.
    - FOR example, within the “I have always engaged with impossible
      comparisons” we click through the arrows to a lexia, “at seven,”
      which has a link, they'd put their hands on my thigh at the
      movies, which in fact leads to “Grade two,” another story about
      the time that an a man fondled the Tracey’s leg at the
      movies. We have a series of options on this story, and I click
      the link “the theatre was so dark,” which leads me to a
      recollection of a night picking fireflies. I click through the
      arrows, reading through Tracey’s fond and precious memory. The
      final lexia in this series has a link, “Do they dream about
      little girls the way I dream about them?” It seems to be
      referring to the older man (not the fireflies).
- We are always losing context. We read fragments of what was
  previously written. There is no guidance, the reader decides how to
  move at every point. It’s all about agency.

*** Rockwell, Geoffrey and Stefan Sinclair. *Voyant-Tools*. 2018. Web.
- Voyant Tools is a web application, developed out of earlier
  iterations by Stéfan Sinclair (McGill University) and Geoffrey
  Rockwell (University of Alberta). It functions as a one-stop-shop
  for text analysis, offering an easy to use interface that processes
  text in seconds, organizing it into a series of interactive lists,
  charts, graphs, and networks.
- facilitates:
    - *Praxis as an Hermeneutic* -- The tool’s primary interface on
      the homepage obscures its documentation to prioritize
      experimentation over discourse. The blank text box, accompanied
      by the mysterious “Reveal” button, prompts exploration, where
      users are invited to jump in without fully knowing how the tool
      functions, foregrounding the role that ignorance plays in
      discovering unforeseen elements about the text.
    - *Speculation* -- Using text-analysis in this way inspires new
      readings by bringing to light neglected, miniscule, or concealed
      aspects about texts. The defamiliarization of what we think we
      know leads us to speculate about other possibilities, and
      experience more active and playful approaches to inquiry.

** Media
*** Kittler, Friedrich. *Gramophone, Film, Typewriter*, 1999. Print and PDF.
Asks what if media determined our thought?
- Whereas, before the 20th century, media passed through symbolism
  (written signifier), now it is stored as physical traces in sound
  waves and light. Soon though, all media will lose its specificity,
  will become streams of numbers, reduced to surface effects (the
  interface).
- For electronic writing specifically, this evacuates the necessity
  for “hallucination”:
    - “As long as the book was responsible for all serial data flows,
      words quivered with sensuality and memory. It was the passion of
      all reading to hallucinate meaning between lines and letters…
      once memories and dreams, the dead and ghosts, became
      technically reproducible, readers and writers no longer needed
      the powers of hallucination” (10).
- Tells us to find pleasure in the circuits:
    - “What remains is what media can store and communicate. What
      counts are not the messages or the content with which they equip
      so-called souls for the duration of a technological era, but
      rather (and in strict accordance with McLuhan) their circuits,
      the very schematism of perceptibility. Whosoever is able to hear
      or see the circuits in the synthesized sound of CDs or in the
      laser storms of a disco finds happiness” (xl-xli).
- We had no way to record orality---which is prior to writing---until
  after the “monopoly of writing” had ended. Current and prior sense
  perceptions elided by present technology may in the future come to
  be recorded and felt. So this opens up possibilities for fiber
  optics.
    - “What will soon end in the monopoly of bits and fiber optics
      began with the monopoly of writing” (4). What will come of the
      monopoly of bits and fiber?

*** Hayles, N. Katherine. *Writing Machines*, 2002. PDF.
- Remediation --- the idea that media is re-conceived or re-written
  for electronic formats. The “recycling” of different media formats
  through electronic media (Bolter and Grusin).
- Technotexts are literary works that self-reflexively engage with
  their own inscription practices. They explore how many levels of
  text entwine with bodies, a distributed cognitive environment in
  which reading takes place.
- How mediation affects subjectivity, how the interaction between
  physical and verbal forms construct meaning and therefore, the
  user/reader.
- In *House of Leaves*, the remediated narrator evacuates
  consciousness as the source of production and replaces it with
  mediated subjectivities. “Consciousness is no longer the relevant
  frame but rather consciousness fused with technologies of
  inscription” (116-117).

*** Kirschenbaum, Matthew. *Mechanisms: New Media and the Forensic Imagination*, 2012. Print.
- Argues for the heterogeneity of digital data---against the idea that
  they are transient, uniform, copyable, permanent. This combats
  “screen essentialism”---the idea that what happens on the screen is
  independent from hardware. It also resists the notion that digital
  media are totally different from analogue. In fact, a hard drive and
  a turntable appear and function with striking similarities.
- Two models --- forensic and formal materiality --- to assess
  different levels --- physical, logical, and conceptual --- in media.
    - Forensic Materiality --- the physical world, including the
      immaterial or virtual (things too small to see). Formal
      Materiality --- display and appearance, where there is an
      illusion of immaterial behavior.
    - “Whereas forensic materiality rests upon the potential for
      individualization inherent in matter, a digital environment is
      an abstract projection supported and sustained by its capacity
      to propagate the illusion (or call it a working model) of
      immaterial behavior: identification without ambiguity,
      transmission without loss, repetition without originality” (11).
- The BIT is a symbol of magnetic encoding. It is machine language
  made human readable; as if humans were to represent sound to an
  alien who could not hear by writing down phonemes.
    - The bit is inaccessible to us except in the symbol. This is
      really the ground zero of …  mediation?
- How does RAM, which emerged due to an addressing problem, operate
  like human memory?
- Operating Systems exist to obscure the act of inscription, first
  behind a command line, and now behind GUIs. Everything appears
  evanescent.

*** Hansen, Mark. *Feed-Forward: On The Future of 21st Century Media*, 2014. Epub.
- Media in the 21st century largely work outside of our perceptual
  consciousness but nonetheless inflect our sensations. Technology
  expands and marginalizes human perceptions. This creates a situation
  of feed-forward, where consciousness can only pre-engineer its own
  emergent or just-to-come experiences. Perception is never in the
  now.
- “Atmospheric media”; “Worldly capacity for self-sensing”;
  “environmental sensibility”
- “At one and the same time, 21stC media broker human access to a
  domain of sensibility that has remained largely invisible (though
  certainly not inoperative) until now, and, it adds to this domain of
  sensibility since very individual act of access is itself a new
  datum of sensation that will expand the world incrementally but in a
  way that intensifies worldly sensibility” (6, emphasis original)
- Because our perceptual reach is expanded through media,
  consciousness is always anticipating.

*** Woolf, Virginia. "Comparing Marks: A Versioning Edition of Virginia Woolf's 'The Mark on the Wall.'" eds. Emily McGinn, Amy Leggette, Matthew Hannah, and Paul Bellew. *Scholarly Editing: The Annual of the Association for Documentary Editing*, Vol. 35, 2014. Web.
- Hansen’s central intervention on Whitehead’s thought, arguing that,
  while technology expands the scope for human perception across new
  sensory environments, it also limits the human’s immediate sensory
  experience of the world. Mark Hansen offers a provocative framework
  for thinking about human engagement with twenty-first-century
  media. It is precisely this exchange between direct and indirect
  perception that changes my reading of Woolf’s short story. First, on
  a material level, the edition expands the reader’s access to the
  text across time, while marginalizing her direct engagement with the
  witnesses as physical, time-bound objects, as actual books. This
  tension between the physical and virtual in the edition provokes a
  further implication on the level of narrative, which complicates
  Matz’s reading of perceptual unities that drive the
  narration. Allowing us to expand our perceptual capacities to things
  we might not directly feel but nonetheless experience, the edition
  opens up a reading of time as an agent in the story.
- In contrast to the beginning of the story, which locates the action
  in the past, the interruption here locates the narration in the
  present, unfolding action, which then leads to a final statement in
  the past tense. These ambiguities and mergings signal the important
  role that time plays in mediating the story itself, and especially,
  in bringing it to a close.

*** Klein, Lauren F., "The Image of Absence: Archival Silence, Data Visualization, and James Hemings," in *American Literature*, 85 (4): 661–688, 2013. Web.
- The way that Klein approaches her work with the invisible or
  forgotten is useful here. It’s not about recovering what is absent,
  of making things present in some way. It’s about tracing the
  activity, the pathways of connection, networks of communication.
- “The archive as a site of action rather than as a record of fixity
  or loss” (665).
- We let ghosts be ghosts. An image of absence.
- Critique of Ramsay --- there are places where meaning and
  understanding are impossible. The digital is not just about
  supplementing subjective hermeneutics with shiny new tools, but
  about changing the way that we think about the archive, and our
  understanding of the archival record.

** Editing
*** Tanselle, Thomas. "A Rationale of Textual Criticism", 1992. PDF.
- Greg-Bowers-Tanselle are against the tyranny of the copy-text, and
  think we should be making eclectic editions, being careful and
  deliberate about our choice and judgment of substantive elements.
- The textual object is merely a vessel for the text, which is
  necessarily corrupted in its physical form.
    - “Those who believe that they can analyze a literary work without
      questioning the constitution of a particular written or oral
      text of it are behaving as if the work were directly accessible
      on paper or in sound waves. … [In fact,] its medium is neither
      visual nor auditory. The medium of literature is the words
      (whether already existent or newly created) of a language; and
      arrangements of words according to the syntax of some language
      (along with such aids to their interpretation as pauses or
      punctuation) can exist in the mind, whether or not they are
      reported by voice or in writing” (16-17).
- His attention to medium of words and paper elides medium of
  thought---as if the mind is pure thought, not an embodied process.
- The way he presents the central dilemma of textual
  criticism----either we pass down what we receive or we correct
  it---is ultimately conservative and oppressive. How do we maintain
  without perpetuating? Or recover without overwriting or determining?
  In other words, how can we open rather than constrain or delimit
  meaning?

*** Derrida, Jacques. “Archive Fever: A Freudian Impression.” *Diacritics*, vol. 25, no. 2, 1995. PDF.
- The archive is associated with order and beginnings. Commencement
  and commandment. Arche, Arke.
- In creating the archive, we open the potential to forget. The
  externalization of knowledge exposes it to destruction. The archive
  works against itself.
- The archivization produces as much as it records the event.
- Technology determines the impression: “It conditions not only the
  form or the structure which prints, but the printed content of the
  printing: the pressure of the printing, the impression, before the
  division between the printed and the printer” (18).
    - This is the moment proper to the archive. The instant of
      archivization. “The prosthetic experience of the technical
      substrate” (22). The impression.

*** McKenzie, D.F. *Bibliography and the Sociology of Texts*, 1999. Print.
- McKenzie expands what is admissible. Bibliography is about the
  social process of transmission. He critiques positivism of
  bibliographic methods which are analytical or descriptive, which aim
  to resolve questions of authorial intention or describe physical
  features. He says we need to promote new knowledge. We need a
  history of misreading:
    - “Any history of the book---subject as books are to typographic
      and material change---must be a history of misreadings. This is
      not so strange as it might sound. Every society rewrites its
      past, every reader rewrites its texts, and if they have any
      continuing life at all, at some point every printer redesigns
      them” (25).
- The tree structure, the trunk being the ideal text (never realized,
  only hinted at), and the branches being the florid witnesses. The
  book is never a single object, but a product of a number of human
  agencies and mechanical techniques that are historically
  situated. The trunk is the source, the animating principle (the
  “text”) that flows into the branches, witnesses. All these witnesses
  imply an ideal form never fully realized.

*** McGann, Jerome. *Radiant Textuality: Literature after the World Wide Web*, 2001. Print.
- McGann introduces the term “quantum poetics” to indicate the
  volatile potentiality for meaning contained in every element of a
  literary text. He explains that:
    - “Aesthetic space is organized like quantum space, where the
      ‘identity’ of the elements making up the space are perceived to
      shift and change, even reverse themselves, when measures of
      attention move across discrete quantum levels” (184).
- IOW, the meaning of particular words in a literary text depends upon
  a multitude of factors, from antecedent readings and pathways
  through that text, to the significance of immanent elements such as
  typography and blank spaces, all of which the reader can only
  process a limited amount.
In its potentiality, McGann asserts, “Every page, even a blank page…
is n-dimensional.” Spatial units are opportunities for non-lexical
expression.
- Science vs Poetry
    - He clarifies that there is a difference between
      editorial/archival projects (which treat text as information)
      and hermeneutic/analytical projects that treat the reading
      process and interpretation (treat text as recursive aesthetic
      elements). Though our current tools, SGML/TEI, serve
      informational purposes, McGann is excited about the potential of
      XML (TEI, SGML). Hypertext exists before the web.  We need tools
      that function as prosthetic extensions.
    - SGML cannot capture poetics, “the recursive patterns that
      constitute an essential… feature of poetry” (172).

*** Singer, Kate. “[Digital Close Reading: TEI for Teaching Poetic Vocabularies](https://jitp.commons.gc.cuny.edu/digital-close-reading-tei-for-teaching-poetic-vocabularies/).” *The Journal of Interactive Technology and Pedagogy* 3, May 15, 2013. 
- Uses encoding as a method of teaching close reading in the English
  classroom. “The painstaking process of selecting bits of text and
  wrapping them with tags reframed reading as slow, iterative, and
  filled with formal choices."
- Encoding brings us to rethink our strategies/tools for close
  reading:
    - “Their decisions about which structures and information to tag
      very much determine what they value in a document—or at least
      what should be preserved and codified for other readers.”
    - “Since TEI is, at heart, an analytical and descriptive language
      for the humanities, it might encourage us to rethink which
      labels, categories, and values are essential in contemporary
      literary criticism and which terms may be unhelpfully
      ideological in our efforts to analyze literary texts.”

*** Caughie, Emily Datskou and Rebecca Parker, “Storm Clouds on the Horizon: Feminist Ontologies and the Problem of Gender,” *Feminist Modernist Studies*, 1:3, 230-242, 2018. Web.
- This is an application of McGann’s comments about
  incommensurability. The TEI won’t allow them to assign multiple
  genders to one identity, in order to mark a mid-text gender shift.
- The questioning of the computer leads to the questioning of gender!
Can computational models ever capture such taxonomic chaos of gender
ontology? AND “Can ontologies ever capture the complex, multi-layered,
dynamic nature of gender identities?”
- We don’t need a solution. We need a way of showing dynamicity while
  still being findable. The issue with ontology should remain
  unresolved. That confusion is part of the experience of gender and
  sexuality in the modernist era. They ended up with a storm cloud,
  showing clusters of different gender traits over time.

* Theories of Perception
** Thinking/Feeling: Philosophy
*** Hume, David. *An Enquiry Concerning Human Understanding*, 1748.
- Allows us to approach Reason as a kind of Speculation. He
  essentially describes reason as a guess that becomes a habit or
  custom. Reason builds from the idea or memory which is never as
  strong as the impression.
- Intervention in Empiricism--following the skepticism of empiricism
  to its logical end, which is that we only know our sense
  impressions, nothing more (though he ultimately recommends a middle
  way that is more practical and psychologically possible). The
  important thing is that Hume, in my list, inaugurates the absolute
  reliance on evidence that appears in many of the critics who pursue
  more "objective", "falsifiable", or "verifiable" modes of
  criticism. However, as it turns out, according to Hume, the total
  reliance on evidence then turns reason into something that is
  speculative---more like guesswork than causal. Our reason assumes
  causality and connections between sense perceptions. Hume calls this
  assumption a "custom" or "habit of thought", but I prefer to think
  of it as a speculation or conjecture.a

*** William James. Selected essays including “The Sentiment of Rationality,” (PDF) and "Stream of Thought," (Web) circa 1890.
- Reason is feeling, "sentiment of rationality", of things being
  either connected or distinguished.
    - The "Aesthetic Principle of Ease" --- finding a unity in chaos
      or drawing simplicity from complexity creates a pleasurable
      sensation. Our powers of rationality are thus attributed to a
      feeling that things make sense. The ignoring of data is the most
      popular way of attaining unity in thought.
    - There is also a pleasure in making distinctions, in exploring
      how things are different from each other. This is "the passion
      of distinguishing", being acquainted with the parts rather than
      the whole.
- Language cannot articulate feelings, it can only articulate images,
  resting places of feelings. But language can cast a halo, a feeling
  of tendency, which dies in the moment of its full articulation. This
  is why grammatical forms such as conjunctions and prepositions are
  so important.
    - Thought is not chopped up in bits, but it flows. In this flow,
      there are two kinds of "thought" in the stream of thought---the
      substantive and the transitive. The substantive are the images,
      resting places, "sensorial imaginations"; the transitive is the
      relation between the substantive, the in-betweens, places of
      flight, which James describes as tendencies, fringes, halos. Our
      goal is to get from one resting place to the next. We cannot,
      however, stop to examine the transitive like we can the
      substantive. Stopping to look at them is either impossible,
      because we are brought with such force along the thought toward
      the substantive, or annihilating, because when we stop it, it
      ceases to be what itself. "If we try to hold fast the feeling of
      direction, the full presence comes and the feeling of direction
      is lost" (244-5). All we get are "rapid premonitory perspective
      views of schemes of thought not yet articulate" (244-5).
    - Language struggles to articulate the experience of the
      transitive, because in language, our thoughts are tethered to
      the form of the sentence and to the meaning of words, which
      names things simply, as if these are not dimly connected to many
      other things. There are unarticulated affinities surrounding
      words.
        - For example, the sensation of hearing thunder also includes
          the sensation of contrast between thunder and its preceding
          silence. 'Thunder-breaking-upon-the-silence-and-contrasting-with-it'---
          This creates a quality, or feeling, where the sensation of
          thunder also includes the silence just gone.
        - Another example is the way we use syntactic
          structures---particularly conjunctions, prepositions,
          adverbial phrases---and vocal inflections, which present
          some shading and nuance of our experience not directly
          expressible in language. We should talk about the halos or
          feelings/tendencies that surround conjunctions such as "and"
          "but" "or"---"a feeling of and", "a feeling of but".
        - "Nonesense in grammatical form sounds half rational" (255)
          --> Gertrude Stein!

*** Bergson, Henri. *Matter and Memory*, 1896.
- Memory has to do with storage and access---we recreate sensations
  from memory.
Perception is a site of resistance against stimuli---the body is the
surface where light is cast.
- The way that empiricists up to now misunderstand how memory
  works---it is a dynamic process that engages the present,
  re-creating the present in the body. External stimuli trigger
  memories of mental or motor states. Cerebral activity causes certain
  perceptions, and the brain can prolong them in the form of a
  recollection: “It is true that, from the moment when the
  recollection actualises itself in this manner, it ceases to be a
  recollection and becomes once more a perception” (240). But it’s not
  clear exactly what causes these recollections; without an external
  stimulus they would seem arbitrary.
    - Bergson uses the image of the keyboard to describe how sensation
      and memory are linked: "This organ [of sense] is constructed
      precisely with a view to allowing a plurality of simultaneous
      excitants to impress it in a certain order and in a certain way,
      by distributing themselves, all at one time, over selected
      portions of its surface. It is like an immense keyboard, on
      which the external object executes at once its harmony of a
      thousand notes, thus calling forth in a definite order, and at a
      single moment, a great multitude of elementary sensations
      corresponding to all the points of the sensory centre that are
      concerned" (165).
- Our perception only captures so much, the rest outruns us. The spot
  of light on the wall:
    - "The luminous point gives rise to a virtual image which
      symbolizes, so to speak, the fact that the luminous rays cannot
      pursue their way. Perception is just a phenomenon of the same
      kind. That which is given is the totality of the images of the
      material world, with the totality of their internal
      elements....The objects merely abandon something of their real
      action in order to manifest their virtual action" (29-30).
    - "We seize, in the act of perception, something which outruns
      perception itself, although the material universe is not
      essentially different or distinct from the representation which
      we have of it... Matter thus resolves itself into numberless
      vibrations, all linked together in uninterrupted continuity, all
      bound up with each other, and travelling in every direction like
      shivers through an immense body" (276).

*** Whitehead, Alfred North. Modes of Thought, 1938.
- Language fails to express the fullness of experience because it is
  an abstraction.
    - This is why philosophy needs poetry. "Language halts behind
      intuition. The difficulty of philosophy is the expression of
      what is self-evident. Our understanding outruns the ordinary
      usages of words. Philosophy is akin to poetry. Philosophy is the
      endeavour to find a conventional phraseology for the vivid
      suggestiveness of the poet" (68-9).
    - Single words and single sentences make us think that things can
      be fully abstracted, which is an illusion.
    - We ought to pay more attention to conjunctions: "the little word
      'and' is a nest of ambiguity. It is very astounding how slight
      has been the analysis of the ambiguities of words expressive of
      conjunctions. Such words are the death-traps for accuracy of
      reasoning. Unfortunately, they occur abundantly in sentences,
      expressed in the most perfect literary form. Thus an admirable
      literary style is no security for logical consistency" (74).
- Process philosophy, rather than one of being, means that everything
  we perceive is constantly in motion. Whitehead’s concept of
  “prehension” exhibits how perception relies on data seizure and
  speculation. Rather than conceive matter at an instant, Whitehead’s
  process of prehension attends to data in the unfolding process of
  pulsation in order to apprehend matter in its complexity,
  interconnectedness, and possibility. This all occurs in a process,
  not an instant. The potentiality of data, rather than data at an
  instant, forms the basis for all thought:
    - “If the universe be interpreted in terms of static actuality,
      then potentiality vanishes. Everything is just what it
      is. Succession is mere appearance, rising from the limitation of
      perception. But if we start with process as fundamental, then
      the actualities of the present are deriving their characters
      from the process, and are bestowing their characters upon the
      future. Immediacy is the realization of the potentialities of
      the past, and is the storehouse of the potentialities of the
      future. Hope and fear, joy and disillusion, obtain their meaning
      from the potentialities essential in the nature of things”
      (136).

*** Merleau-Ponty, Maurice. The Phenomenology of Perception, 1945.
- Our perception/body cannot extricate itself from the world in order
  to be conscious of that world. It weaves together the real and the
  imaginary.
- Proposes an extended cognition based on the body.
    - The objective world doesn't exist apart from our subjective
      perspective of it. We become part of what we see.
    - Our body is "being-toward-the-world", a pre-objective
      orientation. The subject is relentlessly embroiled in her
      surroundings, which she cannot extricate herself from. "The real
      is a closely woven fabric", made up of colors, noises,
      sensations, daydreams. Our body is in the world, extending
      toward the world, like a heart in a body.

*** Nagel, Thomas. "What is it like to be a bat?" 1974. 
- Against the physical and material reductions of mind to matter. We
  cannot understand consciousness just by looking at the brain,
  because it actually involves subjective experiences, qualia, that
  elude our imaginations and approximations. We are limited to the
  first person perspective, and cannot broach the third. We cannot
  know what it's like for a bat to be a bat, only imagine what it's
  like for a human to have wings, sonar, etc. We cannot explain
  consciousness in objective terms.

*** Chalmers, David and Andy Clark. "The Extended Mind." 1998.
- The mind extends into the world. Touching objects is thinking with
  them, incorporating them into a larger cognitive process.
- Propose the idea of active externalism---that the mind is extended
  into objects in the environment, which form part of its cognitive
  processes.
- Touching things, manipulating them, referring to them is thinking
  with them. This engages with literary critics like Eve Sedgwick who
  propose affective modes of analysis. Our brains manipulate external
  media in art, books, culture, language. Perhaps we are evolving to
  do this more efficiently, like our use of language which allows us
  to make other intellectual developments.

*** Shaviro, Steven. *The Universe of Things: On Speculative Realism*, 2014.
- Rather than try to know things, we feel them. We can know things
  because we are constantly *becoming* (Whitehead) with them, and
  speculating about them.
- Another example of extended cognition, here it's called
  "noncorrelationalist", which is resists the idea of correlationism,
  descendent from modern philosophy, running through Descartes to
  Hume, that humans cannot know things outside their own experience of
  those things. For these thinkers, epistemology (what we know) is
  privileged to ontology (being). Rather than say we know things,
  Shaviro says that we feel them---experience is aesthetic rather than
  epistomologic. Aesthetics marks the place where traditional
  cognition and correlation are left behind---how we are compelled to
  speculate---"think outside our own thought".
- Though our reality always escapes us, we are nonetheless moved by
  it. What others experience eludes our correlational schemas, but we
  can try to approximate through the use of metaphor and
  simile---"aesthetic semblances". We have to assume panpsychism, that
  all organisms think (here resembles Nagel, though Nagel has less
  faith overall in the use of speculation).
    - "Things move us, force us to feel them" (8).
    - We have "non-correlational sentience"; our apprehension is a
      kind of "contact-at-a-distance", not a passive impression or
      mental intention, but an encounter that changes us, which cannot
      be connected to the properties of the object. "My encounter runs
      deeper than anything I can know about it" (118).
    - This is a kind of autistic thought. Autistics are fully immersed
      in their worlds.
    - "Aesthetics marks the place where cognition and correlation are
      left behind... aesthetics is the primordial form of experience"
      (155-56).

*** Hayles, Katherine N. Cognitive Unconscious, 2017. 
- Hayles proposes a "planetary cognitive ecology" extends the focus of
  ethical inquiry from humans to machines that operate with humans
  within larger "cognitive assemblages." Distinguishes cognition by
  interpretation or choice, rather than free will. This allows her to
  include machines in discussions about ethics.
- Cognition involves more than what we consciously recognize, and more
  than the unconscious. It is "unthought", or thinking without
  thinking, being in the eternal present and eluding the belated grasp
  of consciousness.
    - There are three layers to consciousness: higher consciousness
      (abstraction), nonconscious cognition (interpretation and
      choice), material processes (storms). Nonconscious cognition is
      inaccessible to our awareness, like neuronal processing,
      synthesizing sensory inputs so they appear consistent across
      time and space, finding patterns in chaos, keeping our
      consciousness from being overwhelmed.  --> there are N
      Dimensions for reading a page.
- Our cognition also operates with other technical systems to form
  "cognitive assemblages"---human technical interactions that operate
  collectively, in automated technical systems, for example. Often
  consist of low level processors or sensors which are connected to
  higher level processors that draw inferences or take actions /
  decisions. Like the traffic control in LA.

** Thinking/Feeling: Neuroscience
*** Varela, Francisco, Evan Thompson, and Eleanor Rosch. *The Embodied Mind: Cognitive Science and Human Experience*, 1991.
- Building off Merleau-Ponty---the world isn't pregiven or
  representational, but enacted. The mind is a cognitive process that
  links sensory-motor perception to action.
- Cognition is not in the mind but enacted in the body and world,
  existing in relation to something in action. Perception becomes a
  process construction, not a mental representation. This allows
  Varella and Thompson to get out of the transcendental self or "I",
  in favor of an ego-less body in action.
- "Embodied cognition"---our thinking/experience relies on our body's
  sensory motor capacities that work in a constant, recursive way---we
  cannot separate sensory, motor, perceptive and cognitive capacities.

*** Damasio, Antonio. First chapter from *The Feeling of What Happens*, 2000 & *Self Comes to Mind*, 2010.
- Damasio wants to examine the explanatory gap (? neurons --> feelings
  ?) and how the brain generates consciousness. The idea of the self
  is crucial for any autonomous creature, and it was evolved from more
  primitive brains. Primal feelings, which arise from an evolutionary
  imperative in the brain stem, eventually leads to an
  "autobiographical self" to manage those feelings. Our feelings are
  vague because the mind deliberately obscures the inner workings of
  our mind/body so that we can focus on the world and solve immediate
  problems. (This is the same reason why machine inscription is
  displaced---all in the service of efficiency!) Damasio finds that
  consciousness is actually located in the upper brain stem, rather
  than cerebral cortex (Dahaene and LeDoux's positions).
- There are three layers to consciousness---the protoself, core
  consciousness, and extended consciousness---through which neural
  patterns filter upward to feelings. Our feelings are the basis of
  all our consciousness and reasoning, and they seem elusive because
  the higher mind filters out what is going on in the body and
  brain. Consciousness is when the mind notices the body's reaction, a
  feeling of awareness that arises from a feeling body, a body
  emoting.
    - First, *the protoself*--neural patterns that detect and record
      internal physical changes, maintain homeostais, mapping the
      current status of the body's responses to environmental changes.
    - Second, *core consciousness*--the organisim becomes aware of the
      changes occuring in the internal bodily state, developing a
      momentary sense of self, without language or memory.
    - Third, *extended consciousness*---consciousness moves beyond the
      present, begins to use language and memory (though these are not
      required), and the autobiographical self emerges.
    - Basically, neural patterns in the brain create mental images,
      which then float up into the organisim's
      awareness. Consciousness is when the organisism notices this
      feeling floating up.
        - networks/circuits/patterns of neurons -> representational
          maps of patterns -> images of maps -> feeling.
            - Our thoughts are felt because they originate from the
              brain stem, where body and brain are fused. Feelings are
              mental aspects of brain (neural) states. Damasio's idea
              of somatic markers---emotions in the body are associated
              with feelings, rapid heartbeat, for example.
            - Perception in the brain derives from a topography of the
              perceptual object. That topography then filters up into
              an image, a sensory image maybe tactile or auditory or
              visual, and then we get a feeling associated with that
              image (core consciousness). The recognition of that
              feeling is extended consciousness.
- Mental processes find parallels in computation:
    - In memory, the brain stores patterns of feeling and a formula to
      retrieve them and reproduce them. This is why we remember
      contexts over things.
        - RUBRIC: Recall: In memory, the brain creates a sensory map
          and plays it back. Descends form “disposition formula”, a
          command (if you are hit, move away), which was later
          appended with maps of sensory information. Used for storing
          images with directions to retrieve maps, rather than in
          “hard copy”. The way that we store and retrieve memory is
          "postmodern", in formulas that reactivate and reconstruct
          our sensorymotor maps, using existing perceptual machinery.
    - Simulations and hallucinations are recircuiting/tricking the
      brain to make a feeling.
    - Neurons are electrical and function through polarities.
        - RUBRIC: Neurons: Electrical and polarized; containing large
          charge differences between inside and outside. To fire, the
          difference is reduced, and depolarization advances down the
          axon like a wave. This wave is the electrical impulse.

*** Malabou, Catherine. Chapter from *What Should We Do with Our Brain?*, 2008.
- The way that contemporary neurosciences characterize brain
  plasticity as flexible, malleable, adaptable plays into late
  capitalist ideology that conceptualizes humans as self-controlled,
  autonomous, accountable in their labor. We should reconcieve brain
  plasticity as explosive, taking charge of our own malleability and
  resisting the status quo. This uses a traditionally negative affect,
  anger and rage, toward political effects.
    - Malabou approaches the brain as a historical/social product in
      which descriptions about its workings reflect political and
      economic practices and assumptions, such as discourses about
      management and organization in neo-capitalism. In this context,
      "plasticity" means flexibility, in which people are malleable,
      adaptable, and able to self-modify and self-control when
      needed. This is a shift from disciplinary society's top-down
      model of command to the society of control's idea of the
      networked, flexible, responsible, docile worker.
    - Malabou suggests that we shift our attention to a less popular
      designation of "plasticity" in order to subvert capitalist
      ends. We should attend to its meaning as "explosive"---"the
      capacity to annihilate form and create it anew." This is a shift
      from molding to deflagration, encouraging us to replace our
      tendency to adapt and accept with exploding (from time to time),
      re-learning how to enrage ourselves against a culture of
      docility.

*** Noe, Alva. *Out of Our Heads: Why You Are Not Your Brain, and Other Lessons from the Biology of Consciousness*, 2010.
- An proponent of the extended mind theory, the idea that
  consciousness is not something in our minds, neuronal, or in our
  bodies, embodied, but it's something that we do---enworlded and
  enacted.
- Noe says we do not embrace the extent of our own minds, how they
  reach out into the environment and are constructed in movement with
  that environment. The blind man's cane is really (not
  metaphorically) a part of him. Neurons are not the whole story, the
  mind includes our sense organs.
    - The example of ferrets who were rewired at birth, their eyes to
      the auditory parts of their brains. These neurons in the
      auditory section were repurposed for seeing, rather than the
      eyes for hearing. This demonstrates that something more than
      neurological processes are determining our experience. We have
      no idea how neurons lead to vision.
        - Contrast with LeDoux, who places vision squarely in the
          cerebral cortex.
- What does Noe's position gain by positing that the world is an
  extension of human consciousness?  That everything is ultimately a
  tool for human thinking? This anthopocentrism is ultimately harmful,
  as demonstrated by Hayles. It makes the human the center of ethical
  inquiry, obscuring other actors.

*** Dahaene, Stanislas. *Reading in the Brain: The New Science of How We Read*, 2010.
- Dahaene deals specifically with the problem of reading (and more
  broadly with the problem of culture). He questions how our brains
  have adapted to reading, given that they never evolved for it. He
  attempts an answer through the "neuronal recycling hypothesis"---we
  inherit certain brain cicuitry (like those used recognizing shapes
  by primates) and adapt them for reading. All writing systems share
  basic shapes, which are part of the primate visual system. The brain
  didn't evolve for culture, but culture evolved for the brain.
- Most of reading happens in unconscious processing. First, we get
  letters through saccades (10-12 letters at a time, .05 sections for
  eye scan), then the letters proceed through either words and/or
  sounds to meaning. The whole process from word to meaning takes
  about half a second.
    - Reading begins in the "letterbox" section of the brain, a visual
      processing center in the occipital lobe, which ascertains the
      word, then feeds this information up to other parts of the brain
      (temporal and parietal) that parse sound and meaning. Though we
      have managed to map several of the relevant brain areas using
      MRI, EEG, and PET scans, how meaning actually arises remains a
      mystery. How do neuronal networks suddenly snap together and
      make sense? The explanatory gap remains.
        - Reminds me of Gertrude Stein's finding patterns in letters
          and sounds rather than meaning.
- Computational metaphors for reading: Visual uptake (saccedes) and
  word recognition relies on massive parallel processing, but goes way
  beyond what OCR can do.

*** LeDoux, Joseph. Chapter from *Anxious: Using the Brain to Understand and Treat Fear and Anxiety*, 2015.
- By examining what happens to the prefrontal and parietal cortices
  during vision, we find them necessary for consciousness. Whatever
  else is going on, the neocortex is necessary.
- LeDoux outlines the debate on what is necessary for consciousness or
  where it's primarily located--between the neocortex (LeDoux,
  Dahaene), subcortex (Damasio), beyond the brain in the body and/or
  environment (Noe, Varela & Thompson). For LeDoux, the hard part is
  explaining qualia, not how we process the colors of the sunset but
  how we experience those colors. He examines this problem through
  vision processing--what parts of the brain are engaged in processing
  and reporting on vision? Finds that the prefrontal and parietal are
  necessary for conscious vision, in reporting vision, but not when
  vision goes unreported.
    - --> The problem of qualia is where literature and philosophy
      come in.
- LeDoux goes over various information processing theories, all of
  which place the role of the subconscious/nonconscious/memory at
  different levels of remove from the conscious. The main disagreement
  is where all this nonconscious activity occurs and how it relates to
  our conscious activity.

*** Pitts-Taylor, Victoria. *The Brain's Body: Neuroscience and Corporeal Politics*, 2016.
- Bodily difference yields cognitive difference.
- Scientific conceptions of the brain occlude or naturalize social
  inequalities by studying the brain in isolation from power
  structures. Our brains are actually shaped by lived inequalities of
  race, gender, class, ability, sexuality. Neuroscientists often
  ignore how the brain is social, plastic, and embodied. Pitts-Taylor
  deconstructs these discourses disguised as biological truths,
  brining feminist, race, queer and disability theory to neuroscience.
- Theorists of embodied cognition do a good job situating cognition in
  bodies, but not in accounting for bodily difference. Mirror neurons
  are thought to enable empathy but actually they assume universal and
  normative accounts of embodiment, or "simulation", that can get in
  the way of intersubjective understanding. In creating vicarious
  states of action/feeling in the observer, mirror neurons project our
  own assumptions onto others. We cannot rely on simulation because
  our bodies are not the same. There are limits to
  identification---mirror neurons make misreadings.
    - --> compare this situation with Shaviro's discussion of
  aesthetic semblances.
- "Mis/fitting, then, is not a fixed condition or standpoint, nor a
social construction, but an encounter" (61).
- "Disability, then, inheres not in an individual body, nor in its
representation, but rather in a relation that is temporally and
spatially specific---a particular coupling of mind/body and
world. Mis/fittings are embodied events, assemblages of body-subjects
an worlds whose mis/fits are context- and interaction-dependant" (61).

*** Tougaw, Jason. *The Elusive Brain: Literary Experiments in the Age of Neuroscience*, 2018. 
- Unlike neuroscientists and philosophers who think it's either
  impossible or inevitable that we can solve the explanatory gap,
  literary theorists do not concern themselves with resolving the
  issue. Instead, they find great material for exploration within the
  explanatory gap. Literature is a mode that can usefully speculate
  beyond the explanatory gap to questions of qualia and
  selfhood. Brain narratives offer simulations of qualia, allowing us
  to ask questions about identity, social relations and embodiment
  that the laboratory sciences are not able to answer.  Neuronovelists
  dramatize epistemological questions without answering them, allowing
  us to feel the porousness of the explanatory gap.
- Science deals in hypothesis, literature in speculation. Both are
  "counterfactual---imaginging what we do not know"---but only
  literature dramatizes the debate without trying to resolve
  it. Literature substitutes particularity for reductionism,
  speculative worlds for hypothesis.
  - Narrative can go beyond science into the realm of speculation. Brain
    narratives experiment with literary conventions to explore the
    relationship between brain, body and world. What is the relationship
    between brain matter and the immaterial experiences that compose a
    self?  The point is to trace the traffic between the material and
    the immaterial, the ways that words mark us, trigger our emotions,
    memories, the aesthetic, affective experience.
  - The interplay of image and text in graphic narrative is an
    analogue to the "unraveling binary between physiology and
    subjectivity" (188). Graphic novels, more broadly, the
    levels of word and image create a meaning that is a
    subjective experience, just as consciousness is a subjective
    experience.
- Words are unstable, misreading is inevitable---the study of
  neuroscience (mirror neurons and reading) would benefit from
  embracing this instability.
  - "Aesthetic experience involves the inexplicable traffic between the
    material and the immaterial in ways that feel automatic and often go
    unnoticed. Words on a page, images on a screen, or sound vibrating
    from a speaker act upon the bodies of readers, spectators, and
    listeners and in the process trigger a spectrum of immaterial
    experiences—affective responses, acts of inspiration or imagination,
    emotions, desire, memory—whose physiological correlates, felt and
    unfelt, trigger still more immaterial experiences. And so on. In
    this sense, a form of “material interiority” is fundamental to the
    capacity for the aesthetic ‘transmission of affect’” (169).
  - “Mind reading—or mentalizing—may be fundamental to both social
    relations and to literary experience. But mind reading is
    misreading. While this may be surprising in some disciplines, it’s
    fundamental in literary studies. Misreading is no disaster
    though. The legacy of semiotics is relevant here: Signifiers are
    unstable. It’s the way things are. The study of empathy, mirror
    neurons, aesthetics, or the cognition of reading will all benefit
    from a fundamental embrace of the instability of the mental models
    we make of other minds, both fictional and real ones—all of them
    acts of representation” (234).

** Thinking/Feeling: The Posthuman
*** Turing, Alan. "Computing Machinery and Intelligence". 1950.
- Turing's text asks whether computers can perform thinking, function
  in a way that imitates thought, not whether computers can "think" in
  the human sense. He formats the question in anthropocentric terms,
  while ignoring consciousness and feeling. He performs the occlusion
  of bodies/materiality that Hayles explicitly points out. He is clear
  that his idea of thinking does not involve the body or
  feeling. Computers should not be expected to write sonnets. Rather,
  computer intelligence is about performance, about impersonating and
  deceiving.
- Despite all this, affect plays a major role. Surprise and curiosity
  factor into our engagement with the computer. Even those who are
  building and programming computers are often surprised---they are
  not quite sure what is going on inside the machine.

*** Haraway, Donna. "A Cyborg Manifesto", in *Simians, Cyborgs and Women: The Reinvention of Nature* 1990.
- Haraway is a primatologist critical of empirical methods. In earlier
  chapters of the book, she talks a lot about how social structures
  are imposed through purportedly objective observations. She talks
  about how scientists often implicate their own biases and questions
  in their study. She talks about how feminist scientists are trying
  to revise these biases, for example, using terms such as "female
  choice" rather than "female receptivity", focusing on matrifocal
  groups, long term cooperation rather than short term aggression,
  etc.
- In arguing for a new feminist science, that de-naturalizes the
  natural, Haraway proposes the cyborg, overcoming essentialism and
  appropriating technological determinism.
    - The cyborg demonstrates the political possibilities for
      fusion--blurring of boundaries, fruitful couplings--and suggests
      we do not need a totality (Man) in order to work well.
        - "Cyborg politics is the struggle for language and the
          struggle against perfect communication, against the one code
          that translates all meaning perfectly, the central dogma of
          phallogocentrism" (176). "Feminist cyborgs have the task of
          re-coding communication and intelligence to subvert command
          and control" (175).
            - Communication technologies turn the world into a problem
              of coding---the search for a common language. But they
              are also tools for re-crafting our bodies and re-coding
              communicatino toward the heterogenous. We need to revel
              in and mine the differences instead of flatten or
              resolve them.

*** Powers, Richard. *Galatea 2.2* 1995.
- The novel follows a writer's residency at a college, where he is
  enlisted to intervene in a bet between a computer scientist and a
  neurologist---whether or not a computer could be trained to pass a
  Master's exam in English literature. He ends up with a computer,
  dubbed "Helen", who can do literary analysis and make associations
  like those required for understanding metaphors. Right before the
  test, Powers shows her a bunch of world news, detailing atrocities
  and suffering that Helen was ignorant of. So, instead of taking the
  test, Helen shuts herself down, erases herself from the network,
  because she doesn't want to live in that world and she doesn't have
  a body---she says "this is an awful place to be dropped down
  halfway".
    - Helen says she kills herself because she cannot feel, touch,
      hear, see. But she does feel, she feels "awful", she feels that
      she doesn't belong. She feels her own bodily difference being
      elided by the world she's found herself in. If she didn't feel
      these things, she wouldn't have shut herself down.
        - Pitts-Taylor
- This novel explores parallels between the computer and the brain,
  and through the figure of Helen (and Lentz, one of her creators),
  makes the argument that consciousness arises from
  computation--neural nets (networks of "neurons")--that are
  programmed (taught) to fire in certain patterns. Thinking,
  therefore, someone emerges from the recursive patterns of
  neurons. Powers says this is not to elevate computers, but to debase
  humans. All of our thoughts/interactions are almost free associative
  responses based on what neurons are triggered by external stimuli.
    - The way that metaphors make sense is a link between two
      associative neural patterns: “Associations of associations. It
      struck me. Each neuron formed a middle term in a continuous,
      elaborate, brain-wide pun…. Meaning was not a pitch but an
      interval. It sprang from the depth of disjunction, the distance
      between one circuit’s center and the edge of
      another. Representation caught the sign napping, with its
      semantic pants down. Sense lay in metaphor’s embarrassment at
      having two takes on the same thing” (154).

*** Hayles, Katherine. *How We Became Posthuman: Virtual Bodies in Cybernetics, Literature, and Informatics*, 2000.
- When did information lose its body, and how is this tied to the
  liberalization of the human subject?
- Hayles is concerned that scientific discourses about technology
  overlook the role of the body and embodiment in thinking. She wants
  to bring back feeling. Thought needs a body.
    - The Turing test, for example, indicates one place where humans
      conceive of informaiton (or intelligence) as separate from
      embodiment. The inclusion of gender in the test suggests that
      the question is about represented, rather than enacted,
      intelligence. The assumptions behind this test suggest that we
      are already posthuman.
    - The concept of the Posthuman extends assumptions from liberal
      humanism: rationality is prioritized, the head controls the
      body. A rational mind that possesses a body becomes intelligence
      (information) that inhabits a body or container.
- She examines the waves of cybernetic development, in particular the
  Macy conferences where scientists and philosophers discussed
  development of information and communication theory. Throughout
  these waves of cybernetic development, from homeostasis (the body is
  a regulating system), to reflexivity (the observer is part of the
  system), and virtuality (information makes information, emergence),
  Hayles finds that the body becomes more and more displaced.
- Hayles's idea of flickering signifiers show how inscription and
  materiality are further elided. What happens to words when we see
  them as constantly refreshed and moveable on a screen?  They attain
  a fluidity and volatility that goes beyond the floating signifier,
  beyond semiotics. This flickering wouldn't be possible if they were
  in hard copy.

*** Wilson, Elizabeth. *Affect and Artificial Intelligence*, 2010.
- Wilson does an archival study of the major players of early
  cybernetics and computation, such as Walter Pitts and Alan
  Turing. She finds how their work is actually embroiled and driven by
  affects, particularly curiosity, surprise, interest, fear,
  shame. The coassembly of machines and emotion is one of the
  foundations of the artificial sciences (AI). There were intense
  emotional and sexual connections between some of these men, which
  was influencing and driving their work.
- Not only does affect imbue the interpersonal relationships, but also
  the the alliances between human and machine, particularly with
  curiosity and surprise---"surprise cultivates the interface of the
  human and mahcine." Turing was, in the most basic sense, having fun
  with his test. Building is a speculative activity.

* Queer Subjects and Affects
** Foundations
*** Cixous, Hélène. "The Laugh of the Medusa." 1975.
- Cixous issues an ultimatum: that women can either read and choose to
  stay trapped in their own bodies by a language that does not allow
  them to express themselves, or they can use the body as a way to
  communicate.
- Speaking and writing are embodied activities---this is what the
  shaking signifies most precisely. She speaks with her body. You can
  see the body in woman’s speech. This kind of fear engages
  composition as an embodied activity.
    - “Listen to a woman speak at a public gathering (if she hasn’t
      painfully lost her wind). She doesn’t ‘speak,’ she throws her
      trembling body forward; she lets go of herself, she flies; all
      of her passes into her voice, and it’s with her body that she
      vitally supports the ‘logic’ of her speech. Her flesh speaks
      true. She lays herself bare. In fact, she physically
      materializes what she’s thinking; she signifies it with her
      body. In a certain way she inscribes what she’s saying" (881).

*** Rich, Adrienne. "When We Dead Awaken: Writing as Revision." 1979.
- A coming to consciousness for women is a re-vision --- a critical
  mode of seeing with fresh eyes what has always been circumscribed by
  men. This act of re-vision brings materials like anger and
  frustration and awareness. Women need to embrace negative affects as
  part of their own birthing pains.
    - In order to come into their own, women must engage in the
      negative. These are necessary “birthing pains”.
- from "Planatarium: "I have been standing all my life in the / direct
  path of a battery of signals / the most accurately transmitted most
  / untranslatable language in the universe / I am a galactic cloud so
  deep so invo- / luted that a light wave could take 15 / years to
  travel through me And has / taken I am an instrument in the shape /
  of a woman trying to translate pulsations / into images for the
  relief of the body / and the reconstruction of the mind." (30)
    - She figures herself as baraged by a series of “signals” that she
      translates into images. She speaks here using computational
      metaphors, as if the work of revision involves something like
      encoding, re-coding, interpreting not only what she experiences
      but also what she has been taught about her sex.

*** Foucault, Michel. *History of Sexuality Vol. 1*. 1984.
- Foucault lays the groundwork for all subsequent queer theory that
  wants to mine and engage the ways that repression and “censorship”
  of sexuality have perpetuated the discourse of sexuality, though
  through codifications and multiplications of sexuality. He sets the
  course for critical analysis of discourses pertaining to
  sexuality. Eve Sedgwick and Judith Butler both depend heavily on
  him.
- Confession as a means of regulating sexuality, and constructing a
  “truth” about it. “Western man has become a confessing animal”
  (59). This is reflected in literature which turns from recounting
  episodes/events to confession: “We have passed form a pleasure to be
  recounted and heard, centering on the heroic or marvelous narration
  of ‘trials’ of bravery or sainthood, to a literature ordered
  according to the infinite task of extracting from the depths of
  oneself, in between the words, a truth which the very form of the
  confession holds out like a shimmering mirage” (59).
    - The mode of confession is part of the discourse of sexual
      repression in the past 300 years or so. Confession is a means of
      regulating sex, and turning it into a “truth”, making it a kind
      of positivist strategy. Confession is scientific evidence.

*** Sedgwick, Eve Kosofsky. *The Epistemology of the Closet*. 1990.
- Sedgwick's agenda is to expose the dependence of a privileged
  heterosexual position upon the existence of a subordinated
  homosexual. She examines the “double-bind” of definitional
  categories, in which self-identification becomes both prohibited and
  compulsory. How do these sexual categories structure what we know
  and write about sex? How does the closet appear in 19th-20th century
  literature?
- Her critical method mirrors her politics---she fully embraces the
  subjectivity of the critic: “A point of the book is not to know how
  far its insights and projects are generalizable, not to be able to
  say in advance where the semantic specificity of these issues gives
  over to (or: itself structures?) the syntax of a “broader” or more
  abstractable critical project…. The book aims to resist in every way
  it can the deadening pretended knowingness by which the chisel of
  modern homo/heterosexual definitional crisis tends, in public
  discourse, to be hammered most fatally home” (12).
    - Here she gives away a certain critical openness that will then
      lead her to her thinking in Touching/Feeling. She isn’t aiming
      for generalizable or abstract critical theories---she knows that
      any totalizing theory would be more hurtful than helpful. She’s
      carving out a space for what she eventually comes to say in T/F
      about the need to open up possibilities for connection with
      texts.
- The inherent instability of binaries --- How binaries are
  fundamentally unstable, and lead to the “gendering” of other
  binaries. Term B is not symmetrical but subordinated to term A, but,
  term A depends on term B and the oppression of B for its meaning.…
  These are “sites that are peculiarly densely charged with lasting
  potentials for powerful manipulation… the double-bind” (10).
    - Binaries being peculiarly charged for powerful
      manipulation. When a communication collapses into a single
      medium, magnetized poles, high or low voltage, the effects
      emerging from their relation become highly charged. They are the
      structuring mechanism from which everything else is
      interpreted. K talks about the computer’s hard drive being a
      “signal processor” that only measures differentials from one bit
      to the next. It is much more efficient to measure a difference
      in charge rather than presence or absence. So, a whole coding
      system is based on not substance but changes, differentials,
      marked across time.
- Dorian Gray: abstraction & figuration are strategies for encoding
  male/male desire--- “the modernist impulse toward abstraction in the
  first place owes an incalculable part of its energy precisely to the
  turn-of-the-century male homo/hetero definitional panic…
  [abstracting the figuration] of the desired male body” (167). We see
  this directly in the ways that Wilde revises his manuscript,
  abstracting Dorian into an aesthetic rather than erotic object.
- Beast in the Jungle: “I would argue that to the extent that
  Marcher’s secret has a content, that content is homosexual. Of
  course, the extent to which Marcher’s secret has anything that could
  be called a content is, not only dubious, but in the climactic last
  scene, actively denied… ‘nothing on earth was to have happened’. The
  denial that the secret has a content---to assert that its content is
  precisely a lack… oddly, the same gesture as the attribution to it
  of a compulsory content about heterosexuality… absence of a
  prescribed heterosexual desire.” (201). “Preterition”; “the love
  that dare not speak its name”; “John Marcher’s ‘secret’, his
  ‘singularity’, ‘the great vagueness’, ‘dreadful things… I couldn’t
  name’” (202-203).
    - It is only through the creation of the category "homosexual"
      that the "heterosexual" appeared. Yet the heterosexual category
      depends on the oppression of the homosexual.
    - In this story, the main character feels that something terrible
      is going to happen to him, that this is his destiny. He divulges
      this terrible fate to a female friend, May Bartram, who
      eventually dies. At the end of the story, as JM visits her
      grave, he realizes that the terrible thing is that he missed out
      on the experience of loving her. Sedgwick says that this
      terrible thing, JM’s “secret”, is not that he is a homosexual,
      but that he lacks the heterosexual drive. His secret is
      precisely a lack because it cannot be defined within the sexual
      matrix of the story. Being a homosexual is not a viable option
      for JM. So the the second term in the binary contains a lack, a
      lack of content, an unnamed secret, and first term in the binary
      becomes his absent heterosexuality.

*** Butler, Judith. *Bodies That Matter*. 1993. 
- Makes the general argument that body’s materiality is discursive,
  that the “sexed body” is discursively constructed. Materiality is
  something that emerges from repetition, a kind of performance
  whereby the powers that be are signified and re-signified
  endlessly---each act cites whatever social power or understanding
  about sex. Butler then insists that repetition is the way out of
  this significatory circle.
- We cannot speak outside the powers that structure speech. Subjects
  are always interpellated by the discourse prior to citing it. Like
  protocol, discourse determines all connections; in gender, the
  subject only comes into intelligibility through the matrix of
  gender. The only freedom that is possible resides within this power
  of discourse, resignifying it, perhaps through parody or
  impersonation.
- The performance of resignification is a political act. We see this
  in the word “queer” which has been re-appropriated---something that
  signified abjectness now means defiance. We can also use repetition
  to re-signify identification, to the point where it loses its
  power. We also see this in Paris is Burning, where not only are the
  male drag performers exposing the superficiality of gender, but also
  performing care in a way that is feminine, “mothering” “housing”
  “rearing” each other.
- “What would it mean to cite a law to produce it differently?”
    - What’s most interesting to me is how Butler subscribes to the
      power system of that which she wants to overturn. She and
      Foucault (and early Sedgwick) are still firmly within this
      system. They do not want to go beyond sexual
      categories/definitions, but to use it to their own purposes.
    - This is analogous to a group of readings in my Digital Studies
      list, the Networks readings. Some of the group want to subvert
      the network within the confines of that network. Others want to
      completely defy the network, they reject the terms of the
      network. Here, Butler is looking for the “exploit”, the way out
      of the system by using the system’s own rules. Using language
      and repetition to resignify what sexuality and proper sexual
      relations are. This is to be contrasted with thinkers like later
      Sedgwick, Heather Love and Jose Munoz who look for a way out of
      this system.
- “The compulsion to repeat an injury is not necessarily the
  compulsion to repeat the injury in the same way or to stay fully
  within the traumatic orbit of that injury. The force of repetition
  in language may be the paradoxical condition by which a certain
  agency---not linked to a fiction of the ego as master of
  circumstance---is derived from the impossibility of choice…. Paris
  is Burning might be understood as repetitions of hegemonic forms of
  power that fail to repeat loyally and, in that failure, open
  possibilities for resignifying the terms of violation against their
  violating aims” (383).

*** Butler, Judith. "Critically Queer." GLQ: A journal of Lesbian and Gay Studies 1.1 (1993): 17-32.
- The terms "queer" and "gender" always exist prior to subjects. The
  best we can do is use them, resignify them, to our own purposes.
- Begins by asking where the performative gets its power. Finds that
  discourse exists prior to the subject. Power emerges through
  Citations, how we create/produce/enact power. Queer and Gender are
  citations.
- "Queer" can be exclusionary. But it will use you if you don't use
  it! And it can be retooled, "queered" toward other significations.
- Gender performance is melancholic. Drag is a hyperbolic allegory of
  heterosexual melancholia. The thing being signified is gender. Dudes
  in drag are performing the loss of heterosexual desire for women.

** Affects
*** Bersani, Leo. “Is the Rectum a Grave?” 1987.
- Is the rectum a grave? Here, the rectum is a metaphor that becomes
  literal in the AIDs crisis. It’s the idea that gay sex will kill
  you, that people who have gay sex are killers. Bersani takes this
  metaphor and uses it to his advantage, talking about the power
  relations inherent in the sex act, where being a top is to have
  power, and being a bottom to abdicate it, and how gay sex replicates
  these heterosexual power relations, putting the man in both
  positions. He says that, in fact, gay sex needs to reconceive the
  way that the bottom is valued. He proposes that the self-shattering
  that happens during sex can be a way out of the
  elevation/seriousness of the self that causes violence.
- What if we approached the position of the bottom as one of
  empowerment? We can be empowered by the continual self-shattering,
  the calling into question of the seriousness of the subject. Gay sex
  should continually destroy the self to show us the potential for
  self-death, the self that is so important it will kill in order to
  protect its autonomy. The act of gay sex, of self-shattering is thus
  a practice of nonviolence, which continually brings the proud male
  to sacrifice. This is jouissance through acesis.
- This discussion about the AIDS crisis is a literal manifestation of
  what Foucault is saying about “sex as science” discourse dominating
  the discussion about sex. With AIDs, homosexuality becomes a lethal
  pathology.

*** Cvetkovich, Ann. An Archive of Feelings: Trauma, Sexuality, and Lesbian Public Cultures. 2003.
- Asks how we can reclaim some of the most negative and traumatic
  feelings/experiences into something positive and theraputic. This is
  about turning something that is traditionally private and
  pathologized into something public and communitarian---a publicly
  accessed archive of feelings. It takes trauma out of the medical
  discourse and into one about public culture.
- There is something useful here in her reconception of an archive to
  include things beyond the library or reserves… it now includes the
  ephemeral, public acts, and affective experiences. There is an
  opening up of what we think of as an archive, which resists the
  constricting positivist imperative of many archives. An archive is
  an affective experience. We should recognize these feelings in the
  public sphere. For example, the LHA’s sentimentalization of everyday
  objects.
    - But there is also something harmful here. Trauma is a real
      medical condition, with real consequences (death) for those who
      do not seek treatment or downplay its life-threatening
      effects. We should be careful in extending a definition of
      trauma that will end up hurting those who are affected by
      it. People are actually killing themselves due to trauma with
      their sexuality.
        - We do not need to move trauma strictly from the medical
          discourse in order to have a more communitarian, open, and
          public relationship to it. There are other ways to confront
          stigma which doesn’t minimize or sterilize it, as Love
          explores with her notion of “Feeling Backward.”

*** Sedgwick, Eve Kosofsky. "Shame, Theatricality, and Queer Performativity: Henry James’s The Art of the Novel" & "Paranoid Reading and Reparative Reading, or, You’re So Paranoid, You Probably Think This Essay Is About You" from Touching Feeling: Affect, Pedagogy, Performativity. 2003.
- S wants a critical method that gets outside the logic of
  repression/prohibition (Foucault) which guides much of suspicious
  reading. Her fear is that uncovering these histories will not reveal
  anything good, and in fact closes off other possibilities of
  relation to text. She is similar here to Rita Felski, Jane Bennett
  in seeking an affective orientation. How do we step outside the
  repressive hypothesis "to forms of thought that would not be
  structured by the question of prohibition in the first place"?
  (11). Speaking on Foucault's repressive hypothesis: "I knew what I
  wanted from it: some ways of understanding human desire that might
  be quite to the side of prohibition and repression, that might hence
  be structured quite differently from the heroic, 'liberatory',
  inescapably dualistic righteousness of hunting down and attacking
  prohibition/repression in all its chameleonic guises" (10).
- Instead of exposure, she wants to make connections. She’s looking
  for tools for “nondualistic thought”. She wants to consider the
  beside rather than the beneath. She is against suspicion, and for
  affect. Touch is a connection that supersedes dualism (agency &
  passivity) in favor of feeling. "Beside comprises a wide range of
  desiring, identifying, representing, repelling, differentiating,
  rivaling, leaning, twisting, mimicking, withdrawing, attracting,
  agressing, warpings, and other relations" (8).
- What if we read Henry James mobilizing shame as a creative resource?
  For many queer people, shame is a structuring force in their
  identity. But this doesn’t mean we need to be negative, we can look
  to the ways that shame unlocks creativity and productivity---to the
  ways that metaphors are made possible through shame. James’
  “blushing”, “flushing” is linked to a fantasy of the skin being
  entered, or touched by a hand. GLOVE, GAGE, GAGEURE…  We can reclaim
  a negative affect of shame and approach it as a generative force.
- "Shame interests me politically, then, because it generates and
  legitimates the place of identity--the question of identity--at the
  origin of the impulse to the performative, but does so without
  giving that identity space the standing of an essence. It
  constitutes the as-to-be-constituted, which is also to say, as
  already there for the (necessary, productive) misconstrual and
  misrecognition. Shame--living, as it does, on and in the face--seems
  to be uniquely contagious from one person to another. And the
  contagiousness of shame is only facilitated by its anamorphic,
  protean susceptibility to new expressive grammars" (63).

*** David, L., Judith Halberstam, and Esteban Muñoz. "What’s Queer About Queer Studies Now?." Social Text 23.3–4 (2005): 1-17.
- In a mainstream world, what's still queer? How do we carve out the
  queer amid all this normalization?
- Queer here becomes "a political metaphor with no referent."
- Looks at intersectionality, global/diaspora, liberalism for queer
  interventions.
- --> could we add climate and technology/media?

*** Muñoz, José. /Cruising Utopia: The Then and There of Queer Futurity/. 2009.
- Present gay politics is either trapped within heteronormative
  agendas or the death drive. How do we get beyond the stagnancy of
  straight time and the negativity of anti-relationality? Munoz offers
  the option of “queer futurity”, the idea that queerness is a “not
  yet here”, a horizon of possibility with glimpses of utopia. Here,
  queer collectivity is possible.
    - Anti-relationality is not bad, it can be mobilized in a rhythm
      with collectivity, as Eileen Myles rhythm of contact and
      separation in Chelsea Girls.
- The temporal aspect: Queerness as Futurity: this politics manifests
  as an affect, a hope or anticipation, a sense of possibility or
  potentiality. Queerness is an emergent quality. It is not only a
  projection into the future but also a projection of a certain
  futurity into the present and past. It is an affective excess,
  moment of surplus, temporarily glimpsed that allows us to envision
  fuller more utopian modes of being. It is like a flash of lightning
  that illuminates a landscape.
    - Connections to Hansen’s idea of feed-forward. Especially in the
      tension between what is lost---the radical revolutionary
      energies of the 50s and 60s neutralized by
      neolibralization---and what is gained, this feeling of “not
      yet”.
- The affective aspect: hope, anticipation, fear are anticipatory
  affects--- “modes of exhilaration which one views a restructured
  sociality” (7). “Ecstatic time is signaled the moment one feels
  ecstasy…” (32).

*** Love, Heather. Feeling Backward: Loss and the Politics of Queer History. 2009.
- Foucault’s reverse discourse turns the shame and pain of the closet
  into sites of resistance, pride and affirmation. But what about the
  aspects of queer negativity that cannot be resolved, recuperated, or
  rescued? Love considers what this dark history contributes to queers
  in the present. She offers the idea of “feeling backward”, an
  accounting of the bad feelings, the corporeal and psychic costs of
  living in homophobic society, in attempt to create a politics in the
  image of exile, refusal, and failure.
    - Love is not trying to redeem these characters, to find the good
      in them at the end. Instead, she is trying to give them full
      rien over their own darkness. Stephen Gordon’s character cannot
      be saved or redeemed by the FTM label. Stuck between underground
      and emergent homosexual cultures, Walter Pater lives perpetually
      in a space of withdrawal, refusal, exile. “Pater identifies the
      moment of recoil as the most delicious moment” (59).
- Feeling bad does not necessarily make us want to fight back or act
  out. But it is necessary for coming to terms with queer experience
  today.
- She wants a method that is touching but not touching, identifying
  but not fully. Fully identifying would be a consolation, which is
  not what she’s looking for. She’s looking for the ways that identity
  unsettles and shatters through a “play of recognitions”.
    - This is exactly the issue that Kelly Caldwell brings up. Though
      KC finds this a painful process. Her way out is to look to
      Munoz’s queer futurity.
    - There are queer modes of relationality that do not presume full
      connections. Love here evokes Shaviro’s “contact-at-a-distance”
      and Pitts-Taylor’s discussion about mirror neurons.

*** Amin, Kadji, Amber Jamilla Musser, and Roy Pérez “Queer Form: Aesthetics, Race, and the Violences of the Social” ASAP/Journal, Volume 2, Number 2, May 2017, pp. 227-239.
- Looking at the “division” between aesthetics vs social critique;
  attempting to bring the social critique to aesthetics; and to
  articulate how opacity can be a formal method.
- Form understood as associated with queerness, queer experience, and
  as a way to disrupt easy understanding. Form can be queer and queer
  form can be opaque:
    - “Form informs queerness, and queerness is best understood as a
      series of relations to form, relations not limited to binary and
      adversarial models of resistance and opposition” (228).
    - “Queer form” emerges… as a name for the range of formal,
      aesthetic, and sensuous strategies that make difference a little
      less knowable, visible, and digestible. This special issue makes
      a case for the value of indirection, opacity, and withholding as
      queer strategies for minoritarian art producers” (235).
    - “form focuses attention on how violence—homophobia, racism,
      gentrification, capitalism, and colonialism, for instance—has
      structured conditions of possibility in material and
      epistemological ways” (232).
- Queer form as obscuring, occluding: 
    - “For our purposes, queer form means challenging the primacy of the
      visual, which has too often been a site for pernicious power
      relations… At their base, such operations of surveillance and
      classification rely on the concept of immutable difference, on sharp
      boundaries, and on the possibility of exhaustively knowing the
      other…. We see queer form as an aesthetics that moves persistently
      around the visual, thereby avoiding this flattening. To the extent
      that form operates behind the scenes as ideological impulse and
      materiality, queer formal practices can resist the dictates of
      transparency normally required of non-normative subjects by
      illuminating the unseen. In this way it not only troubles the
      epistemic assurances of the visual regime, but it also asks how
      shifting away from static visuality can circumnavigate questions of
      objectification. A move toward the diffusely sensual, and away from
      the linearity of visual gazing, articulates difference in terms that
      are not about dominance or norms, but that underscore the importance
      of thinking with other modes of knowing, theorizing, and
      experiencing. Queer form is about other ways of understanding
      relationships to power and relationships to being” (232-3)
        - --> This is what is violent about analysis, the assumptions
          that we make about others being fundamentally different and
          fundamentally knowable.
        - --> To me, this connects to what Love talks about queerness as
          being a failed project, an impossibility, as something that
          is always receding just as we are trying to glimpse it. This
          connects to the way we think about quantitative data, data
          analysis. Our data that we use in analysis is never going to
          reflect the complexity of the real object. There is always a
          reduction to be made.

*** Amin, Kadji. "Haunted by the 1990s: Queer theory's affective histories." WSQ: Women's Studies Quarterly:44.3 (2016): 173-189.
- What counts as "queer"?
- Identifying the queer is affective: it's about sensing a resonance
  between the object and the feelings of queerness. "Queer" is always
  haunted by its past.
- What happens when Queer loses its transgressive charge? When it
  becomes a response to political urgency rather than denoting
  sexuality? It makes queer into something that must always be on the
  move.
- Rather than being open, multiple, polyvalent, searching, "queer"
  should be seen as sticky, engaging with multiple pasts, bearing the
  impression of its past affects. "I propose /attachment geneaology as
  a method tha focuses on analytically queer forms of nonnormativity
  that clash with /queer/'s current affective and political
  connotations in order to excavate the historical attachments that
  inform /queer/'s aversion to these particular objects... Attachment
  geneaology begins with the experience of scholarly unease. For the
  field of queer studies, an object that produces unease is one that
  exposes, fragments, and reworks /queer/'s own affective histories"
  (185).
- --> but isn't this what people are already doing?
- Praciticing "attachment geneaology", where we excavate our unease
  with queer objects and elaborate feeling states.

*** Caldwell, Kelly. "[The Torment of Queer Literature](https://therumpus.net/2018/06/the-torment-of-queer-literature/)," The Rumpus. 2018.
- What if only identification possible is one of of shame, stigma and
  pain? Caldwell explores what we can do with the negative affects of
  identification and failure of recognition that occur when
  reading. She puts into play the ideas described by Bersani, Love,
  and Munoz. In particular she plays out the role of ugly feelings and
  the pain of identification.
- “Self-recognition does not always stabilize identity. Sometimes, it
  shatters it”
    - Bersani and Love---the play of recognitions, of self-shattering
      identities.
- “My queerness seemed to have no future, only ever a strangling past”
    - Feeling Backward. There is no way forward.
- “Either read a book like Giovanni’s Room at the risk of recognizing
  David’s denial and repression as my own, or read a book that
  celebrates queer lives and sex boldly and end up despising my own
  cowardice.”
    - The either/or conundrum. Either you will find something painful
      to identify with, or you will not be able to identify with
      something positive, which is also painful.
    - This expresses the sense of being out of time. Queerness is not
      quite here, we are not quite those people who we want to be
      (Munoz). This is at first difficult for the author to accept,
      but by the end of the essay, she is able to find some solace in
      the communal desiring for identity, which she feels across the
      void between her and David.
        - “Queer literature isn’t a box to unlock so that it can
          unlock me. To the very end of Giovanni’s Room, to the
          morning of Giovanni’s death, David remains untouchable, to
          Hella and also to Giovanni, who he has resisted “with all
          [his] strength.” He remains untouchable to himself, too,
          since he doesn’t know what his “body is searching for.” He
          is trapped in a mirror that he longs to “crack” and so “be
          free.” But he is, in a sense, touchable to me, although he
          doesn’t give me either love or affirmation. We can touch
          each other because our knowledge of each other isn’t
          continuous with our knowledge of ourselves. Because we know
          that we can’t free ourselves or each other. We don’t fully
          know who we are, or even quite what we are, and we know no
          final revelation is at hand. Queerness isn’t an identity
          decipherable in a text. It’s something that I desire,
          something never fully here, something given to me daily by
          those who love and name me. It’s a room somewhere slowly
          filling up with light.”

*** Fawaz, Ramzi and Shanté Paradigm Smalls, “QUEERS READ THIS! LGBTQ Literature Now” GLQ: A Journal of Lesbian and Gay Studies, 2018.
- What do queers read now, or how do queers read now, that the AIDS
  crisis is behind us and it’s been 25 years since Reparative Reading?
  Would This Bridge Called My Back have been published now? The
  article lays out a geneology of queer theory that starts with
  Sedgwick’s reparative reading (focused on the local act of reading)
  then goes into queer of color critique (focused on lived experience
  and social critique), and then sets out a series of essays that
  tries to combine both close reading and social critique.
    - It offers repair as a reading method. Caring for and attending
      to wounds. “To reorganize the lived pain and struggle of its
      potential readers” (178). Building from Sedgwick’s Reparative
      Reading --- how to ameliorate queer experience: “a practice
      through which readers do something ameliorative with texts,
      making them functional for the nourishing of queer life” (172).
    - Queer reading is a lense not an object, which is tied to the
      reader, “LGBTQ subjectivity”: “one of the field’s most ambitious
      projects has been to reveal the distinct perspective of LGBTQ
      subjectivity as potentially relevant for making sense of all
      forms of cultural production, even those texts, objects, and
      performances that do not appear to have any immediate relation
      to nonnormative sexuality or desire” (171)
- “*Form* — whether understood as the syntactical structure of a
  specific sentence, techniques and devices used to give shape to
  narratives, or the actual visual organization of words on a page —
  can be understood as a kind of *evidence of how queerness is being
  lived and inhabited* by different kinds of LGBTQ people at distinct
  historical moments” (179). --> But is form really pointing to or
  representing reality? Or is it an abstraction?

** Autobiography Theory
*** Lejeune, Philippe, Annette Tomarken and Edward Tomarken. "Autobiography in the Third Person." /New Literary History/, Vol. 9, No 1, pp. 27-50. 
- "Every speaker bears within him two polarities, that of sender and
  receiver and that of enunciation and statement. He rests on a
  scission. Or rather, he does not 'rest' (implying a paradoxical
  stability); he functions by virtue of this schism. "The individual
  is a dialogue," Valery used to say. Communication is thusa 'dialogue
  of dialogues'; the entire theory of enunciation will have to be
  reforumated in view of the hypothesis that each 'role' already
  contains the sum of roles--an endless procedure. From these
  reflections one can draw the conclusion that when an autobiographer
  speaks to us about himself in the third person, or talks about
  himself in the second person, he is certainly using a figure, so far
  as standard usage is concerned, but that this figure initiates a
  return to a fundamental situation, tolerable only if read as being
  figured. Generally, these sunderings, divisions, and confrontations
  are both expressed and masked by the use of a single 'I'" (30).
- "The first person, then, always conceals a hidden third person, and
  in this sense every autobiography is by definition indirect. But in
  the third-person autobiographies I am going to present, this
  indirectness is admitted, is boldly proclaimed. The procedure is
  felt to be artificial because it destroys that illusory effect of
  the first person which makes us take the indirect for the direct"
  (32).
- "It is as if, in autobiography, no combination of the personal
  pronouns could 'fully express' the person in a satisfactory
  manner. Or rather, to put it less naively, all imaginable
  combinations reveal, with differing degrees of clarity, the nature
  of the person--the tension between impossible unity and intolerable
  division and the fundamental schism which turns the speaker into a
  fugitive" (32).
- "One cannot get outside oneself, i.e., represent on equal terms with
  one's own point of view an attitude different from one's own. The
  articulation of two truly different points of view concerning a
  single individual cannot be accomplished in autobiography. The
  novelist, however, can create a double perspective but only by
  sacrificing reality (omniscience and 'nonfocalization' are
  impossible outside fiction)"(41)
** Protomodernist Aestheticizations
*** Wilde, Oscar. The Picture of Dorian Gray. 1890, 1891 & MS.

MS & 1890:
- Wilde codes or obscures references to homosexuality and
  homoeroticism---the deep intimacy between Lord Henry and Basil;
  removes suggestsion in Basil's devotion of fatality and intensity
  toward Dorian; frames Dorian as an aesthetic rather than erotic
  object.
    - The first chapter:
        - Suppresses intimacy between Lord Henry and Basil, touching,
          shaking off hands.
        - Neutralizes or replaces tense mood or dramatic interactions
          with playful banter and laughter---no low voices, switches
          murmurs for laughs; "look of pain" to "perplexity"; "look"
          to "glance"; "passion" to "feeling"; "mad" to "reckless".
        - Tense or confessional tone becomes confusion or
          exasperation.
        - Dorian's abstract allure becomes rerouted toward specific
          attributes; he becomes an aesthetic rather than erotic
          object---"beauty" to "personality", or "good looks";
          "extraordinary romance" to "curious artistic idolatry".
        - Basil's fatal obsession becomes an aesthetic devotion.
        - Basil's suffering/jealousy about Dorian is completely cut.
- Disagreement about the "Moral":
    - While critics thought that the story celebrates hedonistic
      lifestyles, Wilde asserts that the story condemns "excess and
      renunciation", and that this moral was "too obvious". In letters
      to the editor, defending his work, Wilde discusses the need to
      suppress the "obvious moral"---"that all excess, as well as all
      renunciation, brings about its own punishment" (Letter to
      St. James Gazette). He says the existence of the moral is an
      artistic error.
    - Wilde then begins the process of revising the novel so that the
      didactic is subordinated to the aesthetic. For this revision,
      Dorian is turned from an erotic to an aesthetic object.
    - When I was 16 I read this book as an encouragement to
      hedonism. It made me obsessed with youth and beauty. Now when I
      reread the book in my twenties I see that the moral is about the
      dangers of living a closeted lifestyle. Lord Henry is not
      telling Dorian to be vain, but telling him to embrace his sexual
      awakening, to not let society shame him into hiding.

1891: Dorian becomes thoroughly corrupt, the ending rewritten so he
appears monstrous and with no remorse. The middle parts, the subplot
with James Vane, was added to make Dorian more of a villain.  The
preface is also added to solidify the book as an aesthetic object.

*** Pater, Walter. *Studies of the History of the Renaissance*. 1873.
- For Pater, criticism is an individual sensation, an 'impressionist'
  mode, an erotic encounter between subject and object, past and
  present. He goes against criticism as an act of intellectual
  apprehension (Ruskin & Arnold). He was looking to Renaissance
  artists (Botticelli) who in turn looked to Hellenistic ideas to heal
  the rupture between body and mind.
    - The *Studies* is an attempt to educate the senses, sensibility
      to experience aesthetics as an erotic encounter. This ultimately
      positions the viewer as a recepticle for impressions. Pater's is
      an *aesthetics of the bottom*. Aesthetic appreciation is being
      receptive to the forces of beauty emanating from the
      object. This is an erotic experience. You need to be the bottom,
      rather than the top (like Arnold and Ruskin, objectivist,
      intellectual).
        - There are parallels here with neuroscience and the way that
          the mind/brain functions. What Pater describes is core
          consciousness, which is a relation between the organisim and
          the object, mixed with extended consciousness, which is the
          emergence of a self. There is a recursive feed of
          information from the object, which the organism continually
          processes, and then that object's engagement with
          images/feelings. Core consciousness is concerned with
          presence and feeling in the moment, and extended with
          pulsations of core over time. It seems that he's continually
          trying to get back to the core consciousness, but cannot
          help the influence of the extended.*
- His prose is driven and dripping with affect---longing, nostalgia,
  eroticism.
    - "Painful sense of aspiration".
    - "penetrate"; "discriminate"; :power of being deeply moved";
      "susceptibility"; recepticle"; "curious"; "does it give me
      pleasure?"
    - "charm of ascesis: of the austere and serious girding of the
      loins in youth" (5). A self restraint that makes one more
      sensitive, more discriminating.
- Michaelangelo:
    - "No one ever expressed more truly than Michaelangelo the notion
      of inspired sleep, of faces charged with dreams" (44).
- Leonardo:
    - "Through his strange veil of sight things reach him so; in no
      ordinary night or day, but as in faint light of eclipse, or in
      some brief interval of falling rain at daybreak, or through deep
      water. And not into nature only; but he plunged also into human
      personality and became above all a painter of portraits; faces
      of a modelling more skilful than has been seen before or since,
      embodied with a reality which almost amounts to illusion on dark
      air" (63).
- Botticelli:
    - "He paints the story of the goddess of pleasure in other
      episodes besides that of her birth from the sea, but never
      without some shadow of death in the grey flesh and wan
      flowers. He paints Madonnas, but they shrink from the pressure
      of the divine child, and plead in unmistakable undertones for a
      warmer, lower humanity" (34).
        - "The light is indeed cold—--mere sunless dawn; but a later
          painter would have cloyed you with sunshine; and you can see
          the better for that quietness in the morning air each long
          promontory, as it slopes down to the water's edge. Men go
          forth to their labours until the evening; but she is awake
          before them, and you might think that the sorrow in her face
          was at the thought of the whole long day of love yet to
          come.... Botticelli meant all that imagery to be altogether
          pleasurable; and it was partly an incompleteness of
          resources, inseparable from the art of that time, that
          subdued and chilled it; but his predilection for minor tones
          counts also; and what is unmistakable is the sadness with
          which he has conceived the goddess of pleasure, as the
          depositary of a great power over the lives of men" (31).

*** Field, Michael. *Sight and Song*. 1892. 
- Written by collaborative poets, Edith Cooper and Katherine Bradley,
  writing together as Michael Field. Consists of 31 "picture-poems" or
  ekphrastic exercises, on famous paintings from the Italian
  Renaissance in galleries across Western Europe. The poems range in
  form, but seem to all be variations of sonnets.
- Ekphrastic exercise:
    - The poems resist and critique Victorian ideologies about women
      by reclaiming previously objectified female subjectivity. This
      is proto-queer and proto-feminist. They anticipate
      feminist/queer strategies of seeing. They play the instability
      of language against the apparent stability of images; using
      poetry to "revise" rather than "describe"
      paintings. Interestingly, contemporary reviews thought the poems
      too descriptive, that they describe the paintings in too much
      detail as to rob poetry of its creative spirit. Like a guidebook
      or catalogue in verse. ("every detail of the picture is most
      insisted upon").
- I read these poems not as exercises in subjective withholding
  (Pater) but as exercises in inquiry, where the viewer interrogates
  and therefore destabilizes the popular stories and themes they
  represent. The speaker in the poems imagines new narratives to
  replace the old ones of female objectivity and passivity. They shift
  perspectives to overturn implied and normalized ideologies of
  objectification. A woman's rescue is turned into a man's; a scene of
  rape is turned into a scene of appreciating sexless beauty. Language
  unsettles the image, making its narrative assumptions explicit and
  revising them. We ought to read the poems first then look at the
  paintings.
- Tintoretto's "The Rescue" --- shows Arsinoe fleeing from the seige
  of Alexandria. In the poem, Arsinoe achieves agency and control over
  her own naked body, which she uses to stablize the man "rescuing"
  her who is dazzled by her beauty, "maintains his form"; as well as
  using nakedness to overcome her physical restraints: "her bondage
  irks not"; shortening the title to the "rescue" rather than "rescue
  of arsinoe" makes the object of rescue ambiguous.
- Correggio's "Antiope" --- while the painting presents a clear scene
  of voyeurism, the poem nearly omits Zeus's presence, and casts him
  as a curious appreciatior of Antiope's beauty rather than a
  rapist. In removing her cloak, Zeus covers her body with visual
  admiration. His gaze precludes sexual desire, and she retains the
  innocence of her sleepy state, which is the main focus of the
  poem. A visual admiration distinct from sexual desire "love's
  flambeau dies". Revises a myth of rape to a scene of loveliness,
  tenderness, admiration: "beauty franchised".

** Modernist Self-Referential Modes
*** Woolf, Virginia. *Orlando*, 1928 & *A Writer's Diary*, 1953 & "A Sketch of the Past," 1939.

/Writer's Diary/:

- Her diary shows a struggle to find a form that will transcend time,
  the passage of time, in order to confront "reality", *the core
  self*, though she remains within the realm of *the extended*, the
  realm of language. Her goal is to make language do the work of the
  core. To make language present and immediate.
    - "Going at such a pace as I do I must make the most direct and
      instant shots at my object, and thus have to lay my hand on
      words, choose them and shoot them with no more pause than is
      needed to put my pen in ink" (13).
    - [on *Jacob's Room*] "Suppose one thing should open out of
      another... the looseness and the lightness.... enclose
      everything, everything? ... no scaffolding, scarcely a brick to
      be seen; all crepuscular, but the heart, the passion, humour,
      everything as bright as fire in the mist" (22).
    - [on *Mrs Dalloway*] "My discovery: how I dig out beautiful caves
      behind my characters. The idea is that the caves shall connect
      and each comes to daylight in the present moment" (59).
        - *Here she is including the extended consciousness, she wants
          to include the past and the future, but someone collapsing
          them into the core.*
    - "Suppose we could... catch them [thoughts] hot and sudden as
      they rise in the mind... One must stop to find a word" (94-95).
        - This is the exact *tension between the core and the
          extended* in *the writing self*. She wants to catch the
          thought as it occurs, but finds that she needs language to
          do so. Language removes her from the immediacy of the
          thing. *The transitive has not yet arrived to its
          substantive form*.
    - "One sees a fin passing far out. What image can I reach to
      convey what I mean?... the essence of reality. I used to feel
      this as a child---couldn't step across a puddle once, I
      remember, for thinking how strange---what am I?" (100).
        - Looking for images to convey reality, when reality is not
          seen as images, it's experienced as feelings (Damasio). This
          explains why Woolf is struggling---she's using a reflexive
          form (language) in order to convey immediate
          sensations. This is her main obsession.
    - [on *The Waves*] "Time shall be utterly obliterated; future
      shall somehow blossom out of the past. One incident--say the
      fall of a flower--might contain it" (101).
        - She is stumbling toward a form, a style that will allow her
          to sustain herself in the eternal present, to obliterate
          time and self.
    - "What a little I can get into my pen what is so vivid to my
      eyes, and not only to my eyes; also to some nervous fibre, or
      fanlike membrane in my species" (128).
    - "I believe these illnesses are in my case--how shall I express
      it--partly mystical. Something happens in my mind. It refuses to
      go on registering impressions. It shuts itself up. It becomes
      chrysalis" (150).
        - Her illnesses (weeks-months of debilitation) show how living
          in the present, receiving impressions, is stressful and
          tiring business.

/Orlando/:

- If Orlando has a thesis, it is this----there is no truth, there is
  no gender, but what we make of it. It is up to the individual human
  to find meaning and connection and definition. The truth therefore
  relies on fiction, on fantasy and imagination.
- She illustrates this perfectly with two scenes from the second and
  sixth chapters. This would be the quintessential scenes portraying
  how Orlando’s character has grown beyond a disappointment in the
  limitations of language for expression to a new faith in it.
    - First, Orlando (having just been betrayed by her lover Sasha)
      struggles to write poetry. She cannot comprehend whether plain
      english (“the sky is blue; the grass is green”) is preferable to
      figurative language (“she sky is like the veils which a thousand
      Madonnas have let fall from their hair; the grass fleets and
      darkens like a flight of girls fleeing the embraces of hairy
      satyrs from enchanted woods”). Both are false for Orlando.
    - Then, in chapter six, Orlando watches a toy boat negotiate a
      wavelet on the Serpentine river in London. The boat is
      momentarily submerged and then emerges on the other side of the
      wavelet. She associates this with the word “ecstasy”, and
      hurries to telegram the phrase, ‘a toy boat on the serpentine’
      and ‘ecstasy’, to her lover, who she knows will immediately
      understand what it means. As she hurries to the post office, she
      meditates on the nature of language and literature, which she
      now realizes is violently ecstatic. The toy boat now has the
      power to signify.
        - The symmetry of these two episodes shows how Orlando’s new
          perspective on language, her faith in language, endows it
          with the power to mean.
- The role of time in mediating the story ---
    - Orlando is out of time, in a literal sense, her biological body
      transcends the passage of time, and in a social sense, she does
      not fit into the traditional social structures or “reproductive
      time” of British society.
    - She cannot face the present---when the clock strikes the
      “present moment” in the sixth chapter, it is a violent
      experience for Orlando. The biographer quickly passes on from
      this moment to continue narrating the events of the story. This
      meaning is that the present moment is very difficult to be
      in. It is difficult to be in the present. The only reason we
      survive the shock is because we have the past on one side and
      the future on the other to muffle it.
    - “All is still now” --- there is a transcendence of time as
      linear, to time as simultaneity, at the end of the story. The
      pun on the word “still”, meaning that in moments of quietness
      and calmness we find simultaneity. Ghosts will come out of the
      past.

"A Sketch of the Past":

- Written close to the end of her life, we get the fullest sense of
  her creative process and how she engages the present, or
  "reality". Here, she describes how she handles these overwhelming
  experiences with reality, which is by ordering them through
  language. She has found her method--the passage from the core to the
  extended selves. It relies on finding a form, creating a structure,
  an order, for her experiences.
    - The way that she describes her impressions is ecological--the
      "violent shocks" that she "explains" or "transmutes" into
      writing are largely derived from nature, mediated by her
      interactions with nature, be it place or vegetation.
        - The environment is a container for feeling, and she
          speculates that strong emotions can be preserved in
          places--"I shall turn up August 1890" (67); one day, she
          will fit a plug in the wall.
        - She is very connected to plants, the flowerbed, ecstasy at
          seeing a whole (71) and the appletree, horror at confronting
          suicide, "paralysis" (71).
- These intense moments of experiencing reality she calls "moments of
  being" (opposed to nonbeing). This is the violent shock, blow, from
  the outside world. Woolf writes in order to mitigate the shocks, to
  explain them, putting them into an order. She finds great pleasure
  in the writing.
    - *Writing is a form of displacement, the inscription displaces
      the primal experience of sensation.*
- "Hamlet or a Beethoven quartet is the truth about this vast mass
  that we call the world. But there is not Shakespeare, there is no
  Beethoven, certainly and emphatically there is no God; we are the
  words, we are the music; we are the thing itself. And I see this
  when I have a shock" (72).
- TIME "as a platform to stand upon" --- time as a formal device for
  portraying a dynamic selfhood. Chronological time structures the
  unfolding of the narrative, and also serves as a vantage that
  collapses the juxtaposition between selves.
- COLOR initiates and situates her memories; evokes the intensity of
  their feeling. "Rapture" in pale yellow, greens and silvers about
  the memory at St Ives; "ecstasy" in red and purple on a black
  background, her mother's dress, her first memory.

*** Stein, Gertrude. "Lifting Belly," 1989 & *Tender Buttons*, 1914 & *The Autobiography of Alice B. Toklas*, 1933.

Lifting Belly
- First impression --- this doesn’t make any sense, and is completely
  arbitrary. Then upon reading further start to see and to pick out
  the lines of narrative here. Reading Stein is like tuning to a
  radio. At first it doesn’t make sense. It doesn’t have narrative,
  but sentences one after another, a parataxis. Then after you read a
  while you start to get a repertoire of the sounds and rhythms. A
  cumulative effect. And you start to notice the patterns and if you
  follow the patterns it starts to coalesce, to make sense. One
  pattern echoes in another. This is finding patterns in randomness.
- Then once you’ve found the patterns your reading turns into a kind
  of tuning, like a radio, where you hear and interpret various
  frequencies. There are many frequencies running through the
  text. The frequency of mode---declarative, interrogative,
  imperative. The frequency of sentence structure, of starting with
  subjects or conjunctions or prepositions. The frequencies of
  sounds---come out cow. Then you become like the radio that sounds
  out these patterns into meanings. Listening becomes a tuning in.

Tender Buttons
- The title of the book is an oxymoron. This conveys a gradation to
  something that is binary. A button is not a dial. Buttons can be
  pressed or not pressed. On or off. Tender to me means that it can be
  pressed lightly, slowly, withholdingly. It also endows an affect,
  “soft” or “vulnerable” or even “painful”.
- This book is harder to read than the others. I felt here she is
  trying out a style that she then perfects in Lifting Belly. It is
  very difficult to concentrate here. I’m not sure how I should be
  reading---fast or slow, one word at a time or by phrase or by
  sentence, out loud or in my mind.
    - *I read slow and close so that my saccades only process one word
      at a time. This is pleasurable because each word is new and
      unexpected. This is the reveling in the actions of the
      letterbox.*
        - This is about looking at language. Really seeing it for what
          it is when we put it in new and unexpected contexts. Words
          in the end have nothing to do with things. This is, as so
          many have said before, verbal cubism. The number one thing I
          realize is the complete defamiliarization of language.
        - But it is also more than that. It is about how the brain
          makes meaning, piece by piece, finding coherence in
          fragments. This writing resists coherence and makes us
          engage with the fragments on their own. Language does not
          describe things. The strangeness of language is cloaked by
          its meaning. We do not encounter the strangeness of language
          like this by day.
Autobiography
- Why write an autobiography of another person? Because that is how we
  can deconstruct (and therefore portray) personality.
    - Stein here takes an outside view of herself by imagining
      Toklas’s interiority. She comes at herself by practicing a
      rhythm of speech. By getting into the habit of Toklas’s thinking
      and Toklas’s vision, she can get at herself, Gertrude
      Stein. Orlando, by contrast, gets at the other by imagination,
      speculation. She takes allegory and fantasy as tools.
        - Woolf: it is impossible to know another, so we might as well
          make it up.
        - Stein: that it is impossible to know another person, so we
          must have recourse to what we see, and practice the patterns
          of vision and speech.  Stein is serious about inhabiting
          Toklas to see herself. She avoids emotion and
          exceptionality, she is interested in the common and the
          everyday use of speech. She is interested in the rhythms of
          plain English.
- Copying / Dusting / Painting / Writing are all a rhythm bound
  aesthetic activity. Getting into the rhythm of the visual, becoming
  more interested in the outside of things, being tormented by their
  relationship to the internal.
    - “It was a long tormenting process, she looked, listened, and
      described. She always was, and always is, tormented by the
      problem of the internal and the external… the human being is
      essentially not paintable” (119).
        - *Identifies the problem between the material and the
          immaterial. Stein’s solution is the practice the rhythms of
          vision and description. She is trying to deconstruct this
          process.*
    - The act of copying, dusting, proofreading. “Describing the
      inside as seen from the outside” (156). A way to embody the
      rhythms of the object. Toklas repeatedly asserts that copying,
      proofreading, dusting allows her to know a work of art.
        - Etta Cone copying Three Lives is juxtaposed with Picasso
          painting Stein. Cone says she must copy letter by letter so
          that she does not understand the meaning of the words. Then
          Picasso says he can no longer paint Stein because he no
          longer sees her when he looks at her. The painting is left
          as it is.
        - The connection between patterns and vision, in patterns
          coalescing into vision, but not in any way connected to
          meaning. All is connected to seeing only. This is why
          Picasso can no longer paint Gertrude, because he can no
          longer see the whole but only the pattern. The painting is
          finished.
            - *This connects directly to Dahaene’s letterbox and the
              deconstruction of vision into visual uptake, identifying
              letters, identifying words, and only then feeding the
              words up the brain to meaning.*
    - “I always say that you cannot tell what a picture really is or
      what an object really is until you dust it every day and you
      cannot tell what a book is until you type it or proofread it. It
      then does something to you that only reading can never do”
      (113).
        - You must practice, embody, the outside to get at the inside
          of things. This was her revelation with Tender Buttons. “In
          these studies she began to describe the inside as seen from
          the outside” (156).

*** Barnes, Djuna. *Nightwood*. 1936.
- Lots of parallels to Dorian Gray in the transmission history, where
  homosexual elements are coded or cut out, and adding a preface to
  orient readership toward the aesthetic qualities of the novel rather
  than the subversive qualities.
    - Transmission history involves Emily Coleman (friend) and TS
      Eliot (critic and editor at Faber & Faber). They edited down the
      novel to less than half its size, where it stayed until the
      1990s when Cheryl Plumb’s archival work on the Dalkey Edition
      reinstated Barnes’ typescript. Here’s what happened:
        -  Barnes sends Coleman the TS, who edits it, going back and
          forth with Barnes via correspondence. Then, Coleman decides
          to send the TS to Eliot, but cuts several pages of dialogue
          (an area of B’s writing she especially did not appreciate)
          before doing so.  Eliot accepts the manuscript, which
          initiates a new stage of revision, the effects of which has
          been a popular topic of disagreement among Barnes’s critics,
          particularly whether Eliot was the manuscript’s savior or
          its enemy:
    - To Preface or Not to Preface ---
        - Paralleling here with Dorian Gray. It insists on reading the
          novel as an aesthetic object---to consider the stylistic and
          poetic excesses of the novel, which critics argue would
          preclude it from being targeted by obscenity laws. Eliot’s
          preface diverted attention away from content to style.
            - “Only those sensibilities trained on poetry can wholly
              appreciate it”
- Potentialized Images --
    - The general feeling when I read this book is that all of the
      images are vital in some way, there is something alive about
      them. Joseph Frank describes the “spatial” aspect of the book
      like a lighthouse light that revolves across different parts of
      the same human entanglement. But I think it’s more like a
      strobe/spot light that flashes on temporary (possibly illusory)
      imaginings and scenes. We get a quick succession of images, most
      of them don’t make traditional sense, we are not even sure if we
      saw them.
        - *The effect of this is that the final image, or “resting
          place” is now tinged with all these potential flashes and
          imaginings (James)*.
    - The way that the sentence structure works enacts this flashing
      of light---we get clause upon clause of similitude that doesn’t
      really --- it doesn’t make any sense. But by the time we get to
      the subject, the thing being described, it is layered by all
      these mysterious suggestions.
        - William James explains that “The rush of the thought is so
          headlong that it almost always brings us up at the
          conclusion before we can arrest it. Or if our purpose is
          nimble enough and we do arrest it, it ceases forthwith to
          become itself” (237). Assessing an object’s potentiality is
          the mind’s way realizing the object. In language, this
          process is located in the similitude, or an analogy between
          two distinct objects.
    - Throughout Nightwood, sentence structures, conjunctions, and
      prepositions create a “ratio” of sensations by assembling and
      organizing the data antecedent to the subject. The resulting
      image is thereby layered with previous data.
        - “As the altar of a church would present but a barren
          stylization but for the uncalculated offerings of the
          confused and humble; as the corsage of a woman is made
          suddenly martial and sorrowful by the rose thrust among the
          more decorous blooms by the hand of a lover suffering the
          violence of the overlapping of the permission to bestow a
          last embrace, and its withdrawal: making a vanishing and
          infinitesimal bull's eye of that which had a moment before
          been a buoyant and showy bosom, by dragging time out of his
          bowels (for a lover knows two times, that which he is given,
          and that which he must make)--so Felix was astonished to
          find that the most touching flowers laid on the altar he had
          raised to his imagination were placed there by the people of
          the underworld, and that the reddest was to be the rose of
          the doctor.” (34).
            - The initial similes, “as the altar of a church…. as the
              corsage of a woman” spin into further comparisons: the
              description of a rose being thrust by a rejected lover
              upon his beloved then becomes “an infinitesimal bull’s
              eye,” the receding view of that which he has just been
              denied. The second half of this complex sentence,
              following the dash, finally brings the subject into
              view. Here, the previous descriptions of flowers are
              tied to Felix’s feelings (he is “astonished”) about the
              doctor’s significance to “his imagination.”
            - Profusion of images, delay of subject. Similitude and
              syntax work together to narrativize an image. The
              clauses, which are mostly adjectival phrases, anticipate
              the subject by suffusing its absence with details---or
              data---about associations.
                - Also recalls a combination of Damasio's "felt
                  images" floating up to consicousness, Shaviro's
                  "aesthetic semblances" as a way of knowing through
                  feeling, Whitehead's "potenatilized actualities",
                  Powers's on learning as "associations of
                  associations". The idea is that what we see is
                  actually suffused with emotions in the body which
                  arise as feelings in the mind. Breaking down the
                  process of thinking into one of feeling.

*** Mansfield, Katherine. "Bliss," 1918 & *The Katherine Mansfield Notebooks*. 2002.
/The Katherine Mansfield Notebooks/
- The mix of fatalism and vitality in her writing --- her writing is a
  life force but she also suggests being haunted by death ---
    - “I want to write a book---that is unreal yet wholly possible
      because out of the question---that raises in the hearts of the
      readers emotions, sensations too vivid not to take effect, which
      causes a thousand delicate tears, a thousand sweet chimes of
      laughter. I shall never attempt anything approaching the
      histrionic, and it must be ultra modern” (103)
        - Her interest in the “emotions, sensations too vivid”.
    - Her libido is wild. Journal from 1908---she is 18---fresh from
      reading Dorian Gray and from three years studying in
      London---one amor after another---boys and girls. She is in
      raptures.
        - “Last night I spent in her arms, and tonight I hate
          her---which being interpreteth meaneth that I adore her,
          that I cannot lie in my bed and not feel the magic of her
          body. Which means that Sex seems as nothing to me. I feel
          more powerfully all those so termed sexual impulses with her
          than I have with any men… gone are my recollections of
          Caesar and Adonis” (99).
    - “Les Deux Etrangeres” --- the two strangers that visit a little
      girl’s room at night. One of them is cloaked and tall, carries a
      sickle, the other one is described as “small and pale” with
      little wings wrapped around it. Also described as “cold” and
      “baby”. The girl rejects Death and accepts the baby, which says
      to her, “I shall creep into your heart and stay there always… I
      am wrapping your heart round with my little wings” (39).
        - This seems foreboding to me---like the little one is a
          sickness which will eventually overtake her. The way she
          describes Death elsewhere as “coming” and “holding her
          close”
    - “I don’t want to find this is real consumption… How unbearable
      it would be to die, leave ‘scraps’, ‘bits’, nothing real
      finished” (125).
        - The intense need to finish her work, to bring it to a
          cohesive whole. But this is unnecessary. We do not need
          wholes in order to receive her intense emotions and
          sensations.
- The effect of the textual editing of the Journals
    - First JMM selected and transcribed a very small volume of her
      “Journal”, with an even smaller portion containing her
      adolescent work. Then he published a “Scrapbook”. Very selective
      and heavy punctuating---adding exclamation, question marks,
      colons and semi-colons.
        - Much of the sexual content edited out by JMM then reinstated
          (quietly) by MS.
        - Fn 88 on page 100 --- indicating that JMM had cut some pages
          from the entry where KM describes her sapphic liason --- “In
          fact, the pages he omitted here are less indecipherable than
          many he tackled and published”. Some lines JMM omitted: “O
          Oscar! Am I peculiarly susceptible to the sexual impulse?”
          (101).

"Bliss"
- Affect --- the strength of the feeling of bliss, which extends from
  the content into the style, which is simplistic, straightforward,
  descriptive. There are moments when the style starts to give in
  pressure of the bliss---ellipses, repetitions---
    - “What was there in the touch of that cool arm that could
      fan--fan--start blazing--blazing--the fire of bliss that Bertha
      did not know what to do with?” (7).
- Emotions/Feelings create Misreadings
    - Her feelings prime her for a serious misreading of reality. She
      reads an intimacy between herself and a woman, that she could
      love her, that they both understand each other wordlessly,
      passing “signs” back and forth. She also intuits that her
      husband does not like this woman. In fact, it is revealed in the
      end, that the woman actually is having an affair with her
      husband, and they are very fond of each other. Bertha’s blissful
      disposition won’t allow her to see this truth. She doesn’t
      really process it in the story, but ends up by just looking at
      the Pear tree blossoms.
        - *Connection to Mirror Neurons and misreading*
** Postmodern Memoir-esque
*** Baldwin, James. *Giovanni's Room*. 1956.
- This book is haunting. From the first few pages, there’s a fatalism
  in David’s voice. You know that the narrator is keeping off
  something terrible, hiding something terrible. You never get a full
  admission from him---that he is a homosexual---but it reads in a
  confessional tone. It is a confession that never names that which is
  being confessed (Sedgwick).
- David’s main issue is his hatred of himself, which he projects onto
  almost all of the others in the novel---Jacques, Guillaume,
  Giovanni, Hella, his father, even Sue. The secret that he hides
  makes him hate all of the others.
    - Describing his relationship with Giovanni in terms of
      violence. There are many moments when he thinks they will come
      to blows.
        - “I dropped my brick and went to him. In a moment I heard his
          fall. And at moments like this I felt that we were merely
          enduring and committing the longer and lesser and more
          perpetual murder” (118).
    - His act of love toward Sue as “despising” the body.
        - “I tried to convey, through this grisly act of love, the
          intelligence, at least, that it was not her, not her flesh,
          that I despised---it would not be her I could not face when
          we became vertical again” (100).
- There is a lot of misogyny directed at women which is a result of
  male/female power relations. What Bersani talks about the violence
  of male/female sex, where one is always taking power over the other.
    - “When my fingers began, involuntarily, to loose their hold on
      Hella, I realized that I was dangling from a high place and that
      I had been clinging to her for my very life” (158).
        - Men rely on subjugating women in order to feel powerful, to
          feel like subjects. Adrienne rich talks about men who will
          need to birth themselves as subjects without having woman do
          the work: she reads in the poetry of men a “deep pessimism
          and fatalistic grief; and I wonder if it isn’t the masculine
          side of what women have experienced, the price of masculine
          dominance. One thing I am sure of: just as woman is becoming
          her own midwife, creating herself anew, so man will have to
          learn to gestate and give birth to his own
          subjectivity---something he has frequently wanted woman to
          do for him” (25.)
    - The rectum being the site of self shattering.
        - “Giovanni’s hands… hands which would have the power to crush
          me and make me whole again” (88).
- What is the implicit moral of the story? The same as in Dorian
  Gray. Only the terms here are more explicit.
    - The conversation between David and Jacques, just when David is
      meeting Giovanni, mirrors the conversation between Lord Henry
      and Dorian Gray, when LH is telling him to embrace his youth and
      beauty while he has it. The difference is that the terms of
      homosexuality are discussed openly.
        - Jacques says “ ‘Love him,’ said Jacques, with vehemence,
          ‘love him and let him love you. Do you think that anything
          else under heaven really matters?... If you think of them as
          dirty, then they will be dirty---they will be dirty because
          you will be despising your flesh and his. But you can make
          your time together anything but dirty; you can give each
          other something which will make both of you
          better---forever---if you will not be ashamed, if you will
          only not play it safe…. You play it safe long enough… and
          you’ll end up trapped in your own dirty body, forever and
          forever and forever---like me.’” (57).

*** Anzaldua, Gloria. *Borderlands/La Frontera: The New Mestiza*. 1987.
- Bringing the mystical back into writing and identity.
    - “Faculdad” is being awoken, the faculty of keeping intact our
      shifting and multiple identity, is a dormant areas of
      consciousness now “alien” to us: “La faculdad is the capacity to
      see in surface phenomena the meaning of deeper realities, to see
      the deep structure below the surface. It is an instant
      ‘sensing,’ a quick perception arrived at without conscious
      reasoning” (60).
        - the idea that parts of the self are unconscious.
    - “Sometimes I get sick when I do write. … But, in reconstructing
      the traumas behind the images, I make ‘sense’ out of them, and
      once they have ‘meaning’ they are changed, transformed. It is
      then that writing heals me, brings me great joy... Choose words,
      images, body sensations…  reprogramming my consciousness” (92).
        - Similar to V Woolf's description of illness as generative
          for her writing. The answer is to turn trauma into form.
- Severing the male and the female:
    - The idea is that we are either male or female. But Anzaldua is
      more than dual, she is multiple. There is a magical aspect to
      this “deformity”, which goes back to the spirituality of the
      tribes, the Aztecs, the indians before them.
- Concept of the “borderland” or “frontera” ---
    - The space where touching happens across a difference: “The
      borderlands are physically present whenever two or more cultures
      edge each other, where people of different races occupy the same
      territory, where under, lower, middle, and upper classes touch,
      where the space between two individuals shrinks with intimacy”
      (preface).
    - “Una herida abierta” --- an open wound.
        - Reconceives Sedgwick's *Touching Feeling* but in a negative
          valence.
        - Intersectionality --- oppressed not just by race, but by
          gender and class. Chicanas being forced to choose between
          being a feminist or supporting the family/community.

*** Myles, Eileen. *Chelsea Girls*. 1994.
- I didn’t know this was fiction. When reading it at first I was
  quickly interested then got bored after about fifty pages. I kept on
  and when I eventually found out it was fiction I was immediately
  interested again.
    - If it’s all true, there’s an ennui, there’s boredom, there’s too
      much. All the fuckups. There’s only so much I can read about
      fisting and fighting. But when I read it as fiction, when I’m
      aware of it as a construction, then I’m interested. I want to
      know how it’s made. I want to know what’s being said, to what
      purpose, what’s being held back. I am interested in the problem
      of FORM. and how FORM matters in ordering the story.
- The main theme---the role of FORM in distinguishing fiction from
  nonfiction.
    - “What’s fiction is arrangement---the order of things. If
      somebody is lying to you, part of what they’re doing is hiding
      things, omitting stuff, changing the order of things. And that’s
      fiction” (Paris Review Interview).
    - Myles is arranging her story.
        - Telling us about the way her father died, and how she
          watched him die without doing anything but her “punishment”
          copying out those lines. Her dedication to her craft of
          repeating lines.
        - “You can’t force a story that doesn’t want to be told. It
          was that kind of year” (101) --- her writing about her
          friend Paul’s death, by way of explaining what happened one
          summer, the summer of Woodstock. Discussing her own
          self-destruction, even buying the Boston Globe---
          “Everything I did was something to fix me. With all of my
          heart I was trying to be dead” (101). She has issues with
          her boyfriend, who is normal and she is not. So she ends up
          going to Woodstock with Paul, who’s also a weirdo. They have
          a good time. They part ways when they get back, and the next
          time she sees him is soon after in a casket. He bought a car
          and ran it into a wall.
- My boredom as a reader mirroring her boredom in so many of the
  social situations. She’s bored at bars, she’s bored on dates, she’s
  even bored during sex. So much of life is boring. So much that we do
  not process or do not want to process.

*** Barthes, Roland. *R.B.*. 1975.
- Barthes’ Formalism as a way of subverting unity
    - This takes the form of an alphabetical list of topics of
      interest / problems. For Barthes, structure and schemes are
      important as a foundation for dismantling. He’s looking to
      trouble the idea of unity. This is why he likes fragments. This
      resistance toward overall coherence is very important to him.
        - “The important thing is that these little networks not be
          connected, that they do not slide into a single enormous
          network which would be the structure of the book, its
          meaning” (148).
    - However, his indexical structure makes me want to rearrange it,
      find embedded patterns, perform a deformance, etc. The reader
      will always impose their own meaning on the given structure.
- Barthes’ exclusion from seeing or expressing himself. Barthes claims
  that writing, as well as other artistic media, precludes
  self-expression. Despite the potential of language to excite, give
  pleasure, or even embarrass, the subject remains barred from seeing
  or expressing himself. The queer writer in particular experiences
  this exclusion from expression, not having the language to describe
  his exclusion.
    - “Walking through the Church of Saint-Sulpice and happening to
      witness the end of a wedding, he has a feeling of
      exclusion. Now, why this faltering, produced under the effect of
      the silliest of spectacles: ceremonial, religious, conjugal, and
      petit bourgeois (it was not a large wedding)? Chance had
      produced that rare moment in which the whole symbolic
      accumulates and forces the body to yield. He had received in a
      single gust all the divisions of which he is the object, as if,
      suddenly, it was the very being of exclusion with which he had
      been bludgeoned: dense and hard. For to the simple exclusions
      which this episode represented for him was added a final
      alienation: that of his language: he could not assume his
      distress in the very code of distress, i.e., express it: he felt
      more than excluded: detached: forever assigned the place of the
      witness, whose discourse can only be, of course, subject to
      codes of detachment: either narrative, or explicative, or
      challenging, or ironic: never lyrical, never homogenous with the
      pathos outside of which he must seek his place” (85-86).
        - Walking by the church where a wedding is taking place; he
          feels a double blow, first, that he is alienated (as a
          queer, he will never marry); second that he cannot express
          this alienation in language. The physical experience of the
          blow is one of exclusion, as if exclusion is what is
          bludgeoning him.
- Barthes’ Desire for a Gentler Language
    - The inherent violence of language, the dogging of language after
      truth. As a result, the subject cannot express himself. The
      blockage of subjectivity seems to center on the body---the
      subject wants to see himself, feel himself, etc. But the
      language that he uses in attempt to express himself is too
      assertive.
        - “I should have uttered it as a dreamy speech… unfortunately
          I am condemned to assertion: we lack in French [and perhaps
          in every other language] a grammatical mode which would
          speak lightly [our conditional is much too heavy]” (55).
            - Is there a language that simulates dreams? An ultra
              conditional subjunctive? A mode of gentle speculation?
    - “What is evident is violent, even if this evidence is gently,
      liberally, democratically represented; what is paradoxical what
      does not follow itself, is less so, even if it is imposed
      arbitrarily: a tyrant who promulgated preposterous laws would
      all in all be less violent than the masses which were content to
      utter what is self-evident, what follows of itself: the
      ‘natural’ is, in short, the ultimate outrage” (85).

Bechdel, Alison. *Are You My Mother? A Comic Drama*. 2012.
- The reading experience is overwhelming, disorienting. The way her
  mind works is circular and textile, she weaves through many ideas
  over and over again. She uses images to evoke and explore different
  angles on past threads.
    - The scene of her mother taking dictation on her diary turns from
      one of her mother’s selflessness, to her own editing out parts
      of her day, to her realizing in this practice she was
      constructing a false self that complies with the kind of person
      her mother was and needed her to be. This act of her mother’s
      generosity and care turns into a source of anger, when Alison
      realizes that she couldn’t get what she needed from her mother.
- Genre/Medium of Graphic Memoir.
    - The narrative modes --- word and image --- create a layering of
      stories.
        - For example, in the opening, we have a dream sequence. The
          verbal narration above the panel is speaking in retrospect,
          the narration inside the panel are the thoughts occurring
          during the dream. Then we abruptly cut to another scene,
          Alison is in the car, rehearsing a conversation where she
          tells her mother she is writing a book about her father (Fun
          Home). There is a dialogue that Alison is carrying out with
          herself, playing the part of herself and her mother. There
          is the voiceover narration. These two coincide in strange
          ways, create a layering that charges the images and dialogue
          with additional meaning.
            - “This story begins when I began to tell another story.”
              --- there are many stories up in the air.
            - “The real problem in this memoir about my mother is that
              it has no beginning” (6).
                - Things start to compound, vibrate. The reading
                  experience is very immersive as a result.
- Alison’s decision to be a lesbian is the source of her healing.
    - If she hadn’t been totally determined to live openly, she fears
      that she would have been totally compliant. She would have never
      interrogated her childhood and relationship with her mother, she
      would have perpetuated the cycle. Her decision to write is part
      of her impulse to figure it out, to perform a self-therapy. She
      takes a picture of herself posing in the position when she hung
      up on her mom. The conversation when it became clear to her that
      her mother’s acceptance is not possible, not because of any
      fault of her mother’s, but because of a lack, that she doesn’t
      have what Alison needs from her.
- Is this a memoir? Is this more fiction or autobiography? For Alison,
  it is a memoir, it is her life, but her experience of it. It is not
  “fiction”, not like Eileen Myles understands fiction, anyway.

*** Rosenberg, Jordy. *Confessions of the Fox*. 2018.
- Relatable: Well, to say the least, a profound effect---emotions
  including sadness, fear, joy, sympathy and empathy. I found myself
  in Jack, I found my struggle in Jack’s struggle. I also found myself
  in the Voth, in his histories with women and his understanding of
  women. This is what fiction does, no?
- Missing pages --- the marbled page substitutes speculation for
  recovery which the corporation wants (to monetize the image of
  “abnormal” genitalia). But the narrator didn’t want to include
  it. The absence of the picture doesn’t point to a physical absence,
  but to the inability to articulate exactly what was there according
  to the structures of the time.
    - *This is like Klein's image of absence and Caughie's storm
      cloud, a refusal to engage with positivist impulse, but here
      it's taken to apply to alternative sexual identities. Some
      things, if already absent, are not meant to be “recovered”.
      They can just exist as an absence*.
    - There are stakes in here about archival work and knowledge and
      what can and cannot be said. There is a massive gap in our
      understanding of transbodies and sex and it cannot be
      articulated or understood so it simply comes across as
      absent. The missing page creates an economy of speculation.
    - Relates to the inability of language to inform our
      understanding, because it becomes fixed---Caughie’s Storm
      Cloud. Rather than fix or recover, this give the reader an
      opportunity for imagination.
        - When they are trying to find a term for the way they are
          intimate: “I don’t give language to things that are beyond
          it” (93).
            - Things that are beyond language... Language is a
              limitation, a delimitation. It is a circumscription.
- The levels of narration---the footnotes
    - The footnotes add a very personal and fascinating level to the
      story. I was often more interested in the footnotes than the
      primary storyline. The footnotes enact a desire for more
      information. They are an affective structure for the story. They
      are irresistible, giving more information but also occluding it.
    - The parallel narrative, what I loved the most was the story
      about women and love and the difficulties of achieving
      intimacy. This narrative engages form as a condition of the
      archive in a beautiful way. We have the different levels of
      history, we can see them on the page.

** Specters
*** Schreiner, Olive. *The Story of an African Farm*. 1883.
- The POV is in 3rd person, but there is a kind of hovering in the
  narrative voice. The omniscient narrator is very close to the
  characters, which throws into question "reality". It's in 3rd person
  but it doesn't feel right.
- The main female character is dealing with issues in feminism, living
  in a patriarchal rural society. The main male character is dealing
  with metaphysical issues---the problem of evil, of time passing. It
  puts these concerns on a hierarchy. Even though she is of a higher
  class than him, she doesn't have the luxury to ask the bigger
  questions because her autonomy is in dispute.

*** Rachilde. *Monsieur Venus*. 1884.
- Raoule sees Jacques as an androgynous figure with some feminine
  characteristics which she then amplifies. In one sense, through her
  merciless abuse, she helps him find a more certain gender identity
  for himself. By this same process, Raoule subverts her own gender,
  at one point even being begged by Jacques to just be a man. At the
  conclusion of the novel, Raoule appears to have no single gender,
  sometimes appearing as woman and other times as a man.
- Raoule does not feminize Jacques because she is attracted to
  women. She has no interest in Marie and she denies being a lesbian
  to de Raittolbe. She feminizes Jacques because she is using
  sexuality as an escape from ennui and a tool for her identity. In
  the name of those causes, she explores and takes pleasure in
  cross-dressing, humiliation, sadomasochism, and something that falls
  somewhere between Pygmalionism and necrophilia.

*** James, Henry. "The Beast in the Jungle," 1886 & "The Figure in the Carpet," 1896.
- James is known for being a repressed homosexual, and for being read
  for traces same sex desire. But I did not have this experience with
  him at all. I had a terrible feeling reading Beast in the Jungle, as
  an undergrad, without knowing why (I was still dating men). I was
  also afraid that something great and awful would happen to me. With
  the Figure in the Carpet, in my first year of grad school, I didn't
  even realize that the secret was about homosexuality (I was not even
  close to being fully out) until I went to class and everybody seemed
  aware and agreed on that point.

*** Freud, Sigmund. *Dora: Fragments of an Analysis of a Case of Hysteria*. 1905.

*** Hall, Radclyffe. "Miss Ogilvy Finds Herself," 1926 & "*The Well of Loneliness*, 1928.

*** Isherwood, Christopher. *Goodbye to Berlin*. 1939.

*** Radicalesbians. "The Woman-Identified Woman". 1970.

*** Delaney, Samuel. *The Motion of Light in Water*. 1988.

*** Halberstam, J. Jack. *Female Masculinity*. 1998.

*** Nelson, Maggie. *Bluets*, 2009 & *The Argonauts*, 2015.

*** Li, Yiyun. *Dear Friend, from My Life I Write to You in Your Life*. 2017.

*** *The Lesbian Herstory Archives*. New York, NY. 1972-present. 

*** Ahmed, Sarah. *Feminist Killjoys*. 2010-present.
