* My critical approach

Introduction:
------------

- Deformance and Queer Form


Chapter one:
------------ 

+ Critique of *Distant Reading*, "falsifiable criticism" which is
  "reproducible". And generative reading of DR that attends to the
  ways that computation can access marginalization.

+ Judith Butler's idea of *Gender Performativity* and how it aligns
  with iterativity in Python. Bringing these two together allows us to
  understand how gender theory can open up the way we think about text
  analysis.

- Critique of discursivity from Trans Studies and QOCC. Overlooks
  embodied realities.

Chapter two:
------------

+ Critique of *Textual Editing*, which asserts that the goal of the
  editor is to bring to the surface the intentions of the author. 

+ Critique of *Queer Historiography*, which debates the extent to which
  historians can know or label queerness in the past.

- *Queer Futurity* - The XML format encodes power structures, so how
  do we resist? The critique from QOCC, Munoz, that queerness is not
  yet here.

Chapter three:
--------------

+ *Black Feminist studies* theorizing on the flesh and resisting the
  reduction of the flesh.

- *Media Archaeology* and *Critical code/platform/software studies* on
  the abstraction of the stack, the way formal and forensic engage.  


*** Disability Studies
----------------------

The idea is about how the human interacts with the machine. 

Taking Hayles's idea about a Distributed Cognitive System when a human
interacts with a machine, and engaging it with the idea of
"mis/fitting" from disability studies. 

From Pitts-Taylor, of "misfitting" -- “Mis/fit” --- an encounter --- a
coupling of body and world that are embodied events, assemblages of
bodies and subjects. The features of the environment and variance of
bodies are factors for mis/fitting.

Pitts-Taylor, Victoria. The Brain's Body: Neuroscience and Corporeal
Politics, 2016.

- Our brains do not just respond to positive relationships or
  intentional “brain training,” they are shaped by the lived
  inequalities people experience that arise from race, gender, class,
  abilities, and sexuality. They are social, plastic, and embodied.
- Whereas neuro-philosophers generalize about the embodied brain as if
  we all access and understand the world in a similar manner with
  similarly structured brains (which is akin to a neo-Kantian reaction
  to rationalism), feminist, queer, and disability theorists recognize
  that “Bodily difference yields cognitive difference” (56). When
  neuro-philosophers ignore this, they erase different kinds of bodies
  and obfuscate “epistemic multiplicity” (51).
- Those who promote the idea of embodied cognition do so in a
  universal way. Although they do a good job “situating”
  emotion/thinking in the body and world, which resonates with
  feminist epistemologies, they do not account for difference in
  bodies.
- “I argue for recognition of embodied multiplicity, including
  cognitive and affective ‘misfittings’ of body-minds and worlds”
  (13).
- Pitts-Taylor uses queer theory to re-examine and offer up
  alternative readings of neuroscientific studies of “felt
  orientations of bodies toward each other” (117).


*** Queer Negativity / Futurity
-------------------------------

Writings about trauma, pain, being constitutive of queer
identity. This belongs in the second chapter. There is a connection
between Heather Love and Anzaldua, which allows us to read Wilde.

The discussion is not one of Queer Historiography, but one about Queer
Negativity. 

The answer comes in the form of Munoz. Imagining a future that is not
yet here.  

Gloria Anzaldua
From "/Tlilli, Tlapalli/ / The Path of the Red and Black Ink", page
97:

- "I sit here before my computer, /Amiguita/, my altar on top of the
  monitor with the Virgen de Coatlalopeuh candle and copal incense
  burning. My companion, a wooden serpent staff with feathers, is to
  my right while I ponder the ways metaphor and symbol concretize the
  spirit and etherealize the body. The Writing is my whole life, it is
  my obsession. This vampire which is my talent does not suffer other
  suitors. Daily I court it, offer my neck to its teeth. This is the
  sacrifice that the act of creation requires, a blood sacrifice. For
  only through the body, through the pulling of flesh, can the human
  soul be transformed. And for images, words, stories to have this
  transformative power, they must arise from the human body-flesh and
  bone-and from the Earth's body-stone, sky, liquid, soil. This work,
  these images, piercing tongue or ear lobes with cactus needle, are
  my offerings, are my Aztecan blood sacrifices" (Anzaldua 97).

This is about the pain that is necessary to reconcile in order to
accept gayness. The trauma. 


*** (Black) Trans Thought
-------------------------

The black body (which has been reduced to flesh by the violence of
slavery, Hortense Spillers) is transformed into a site of
possibility. This can be an analogue for thinking through the
transformations of data when it undergoes reduction and therefore
finds new formal constellations.

- Snorton: The reduction of blackness to flesh can be a place of
  possibility, of fugitivity, of escape, for example. Looking at the
  quality that has been used to denigrate as a tool of
  empowerment. /Black on both sides: A racial history of trans
  identity/, Chapter 2: how does this state of gender indefiniteness
  create possibilities of resistance, of escape? The cross dressing of
  runaway slaves. “the black’s figurative capacity to change form as a
  commoditized being engendered flow” (Snorton 59).

- Marquis Bey, "The Trans*-ness of Blackness..." /TSQ/: "/trans*/
  denotes the ubiquity, the transivity, the fundamentality of the
  primordial force of unfixing openness.... Transitivity is the
  beginningness that underlies the (gendered) conditions of
  possibility that allow for distinction" (Bey 284-5). 

  "blackness and trans*-ness are things, discursively marking heir
  thereness and not-thereness, their very linguistic volatility, their
  elusion of syntactical nominatives, which themselves, ultimately,
  are a form of fixing. Ever the artfully escaping air from the
  enframing of life, blackness and trans*-ness embitter the binaristic
  zero-one formulation that is ontology" (Bey 290). 

- Tinsley - Black Atlantic


*** Trans Studies
----------------

The critique of performativity/discursive understandings of gender and
sex by Trans theorists like Jay Prosser. 




*** Giovanni's Room manuscript info: 
Countee Cullen-Harold Jackman Memorial Colection:
http://findingaids.auctr.edu/repositories/2/resources/40

Series 1, Manuscript: Giovanni's Room , circa 1950, Box: 1,
Folder: 36. Countee Cullen-Harold Jackman memorial collection,
0000-0000-0000-0034. Robert W. Woodruff Library of the Atlanta
University Center,
Inc. . http://findingaids.auctr.edu/repositories/2/archival_objects/50402
Accessed March 23, 2022.

Manuscript page:
https://radar.auctr.edu/islandora/object/auc.034%3A0038

